//! Network protocol state machine for fuzzing (`rustre-fuzz-net`).
//!
//! Models a network protocol as a finite state machine.  Each state has
//! transitions (guarded, with actions) and message templates.  The
//! [`StateMachineFuzzer`] drives the machine while mutating message fields.

pub use std::collections::HashMap;
use std::fmt;

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

/// States of a generic TCP/application-layer protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProtocolState {
    Initial,
    Connected,
    Authenticated,
    DataTransfer,
    Closing,
    Error,
    Closed,
}

impl ProtocolState {
    /// Returns `true` if this is a terminal state.
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(self, Self::Closed | Self::Error)
    }
}

impl fmt::Display for ProtocolState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Self::Initial => "Initial",
            Self::Connected => "Connected",
            Self::Authenticated => "Authenticated",
            Self::DataTransfer => "DataTransfer",
            Self::Closing => "Closing",
            Self::Error => "Error",
            Self::Closed => "Closed",
        };
        write!(f, "{s}")
    }
}

// ---------------------------------------------------------------------------
// User-defined State (for custom protocols)
// ---------------------------------------------------------------------------

/// A user-defined state for protocols with more than the built-in states.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CustomState {
    pub id: u32,
    pub name: String,
    pub is_terminal: bool,
}

impl CustomState {
    #[must_use]
    pub fn new(id: u32, name: impl Into<String>) -> Self {
        Self {
            id,
            name: name.into(),
            is_terminal: false,
        }
    }

    #[must_use]
    pub const fn terminal(mut self) -> Self {
        self.is_terminal = true;
        self
    }
}

/// A state node in the FSM (either built-in or custom).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum State {
    Builtin(ProtocolState),
    Custom(CustomState),
}

impl State {
    #[must_use]
    pub const fn is_terminal(&self) -> bool {
        match self {
            Self::Builtin(s) => s.is_terminal(),
            Self::Custom(s) => s.is_terminal,
        }
    }

    #[must_use]
    pub fn name(&self) -> String {
        match self {
            Self::Builtin(s) => s.to_string(),
            Self::Custom(s) => s.name.clone(),
        }
    }
}

impl fmt::Display for State {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}

// ---------------------------------------------------------------------------
// MessageTemplate
// ---------------------------------------------------------------------------

/// Field type in a message template.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum FieldType {
    FixedBytes(Vec<u8>),
    RandomBytes { min_len: usize, max_len: usize },
    U8(u8),
    U16Le(u16),
    U32Le(u32),
    U64Le(u64),
    AsciiString(String),
    LengthPrefixed { inner: Box<Self> },
}

impl FieldType {
    /// Generate bytes from this field, using `rng` for random fields.
    #[must_use]
    pub fn generate(&self, rng: &mut SimpleRng) -> Vec<u8> {
        match self {
            Self::FixedBytes(b) => b.clone(),
            Self::RandomBytes { min_len, max_len } => {
                let len = min_len + rng.next_range(max_len - min_len + 1);
                (0..len).map(|_| rng.next_byte()).collect()
            }
            Self::U8(v) => vec![*v],
            Self::U16Le(v) => v.to_le_bytes().to_vec(),
            Self::U32Le(v) => v.to_le_bytes().to_vec(),
            Self::U64Le(v) => v.to_le_bytes().to_vec(),
            Self::AsciiString(s) => s.as_bytes().to_vec(),
            Self::LengthPrefixed { inner } => {
                let data = inner.generate(rng);
                let mut out = vec![data.len() as u8];
                out.extend(data);
                out
            }
        }
    }

    /// Mutate the generated bytes.
    pub fn mutate(&mut self, rng: &mut SimpleRng) {
        match self {
            Self::FixedBytes(b) if !b.is_empty() => {
                let idx = rng.next_range(b.len());
                b[idx] ^= rng.next_byte();
            }
            Self::U8(v) => *v = rng.next_byte(),
            Self::U16Le(v) => *v = rng.next_u16(),
            Self::U32Le(v) => *v = rng.next_u32(),
            Self::AsciiString(s) if !s.is_empty() => {
                let idx = rng.next_range(s.len());
                let mut chars: Vec<char> = s.chars().collect();
                chars[idx] = (rng.next_range(26) as u8 + b'a') as char;
                *s = chars.into_iter().collect();
            }
            _ => {}
        }
    }
}

/// A message template consists of ordered fields.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageTemplate {
    pub name: String,
    pub fields: Vec<FieldType>,
    /// Whether this message is fuzz-able (mutated during fuzzing).
    pub fuzzable: bool,
}

impl MessageTemplate {
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            fields: Vec::new(),
            fuzzable: true,
        }
    }

    pub fn add_field(&mut self, field: FieldType) {
        self.fields.push(field);
    }

    /// Generate message bytes.
    #[must_use]
    pub fn generate(&self, rng: &mut SimpleRng) -> Vec<u8> {
        self.fields.iter().flat_map(|f| f.generate(rng)).collect()
    }

    /// Generate a mutated version of the message.
    #[must_use]
    pub fn generate_mutated(&self, rng: &mut SimpleRng) -> Vec<u8> {
        if !self.fuzzable {
            return self.generate(rng);
        }
        let mut template = self.clone();
        // Mutate a random field.
        if !template.fields.is_empty() {
            let idx = rng.next_range(template.fields.len());
            template.fields[idx].mutate(rng);
        }
        template.generate(rng)
    }
}

// ---------------------------------------------------------------------------
// Transition
// ---------------------------------------------------------------------------

/// A guard function: `fn(state, message) -> bool`.
pub type GuardFn = Box<dyn Fn(&State, &[u8]) -> bool + Send + Sync>;

/// An action function: `fn(message) -> Option<response>`.
pub type ActionFn = Box<dyn Fn(&[u8]) -> Option<Vec<u8>> + Send + Sync>;

/// A state machine transition.
pub struct Transition {
    /// Source state.
    pub from: State,
    /// Destination state.
    pub to: State,
    /// Human-readable label.
    pub label: String,
    /// Message template to send when taking this transition.
    pub message: MessageTemplate,
    /// Guard: if `Some`, must return `true` for the transition to be taken.
    pub guard: Option<GuardFn>,
    /// Action executed when the transition is taken.
    pub action: Option<ActionFn>,
}

impl Transition {
    /// Create a simple transition with no guard or action.
    #[must_use]
    pub fn new(from: State, to: State, label: impl Into<String>, message: MessageTemplate) -> Self {
        Self {
            from,
            to,
            label: label.into(),
            message,
            guard: None,
            action: None,
        }
    }

    /// Check if the guard allows this transition (always true if no guard).
    #[must_use]
    pub fn check_guard(&self, current: &State, msg: &[u8]) -> bool {
        self.guard.as_ref().is_none_or(|g| g(current, msg))
    }

    /// Execute the action and return an optional response.
    #[must_use]
    pub fn execute_action(&self, msg: &[u8]) -> Option<Vec<u8>> {
        self.action.as_ref().and_then(|a| a(msg))
    }
}

impl fmt::Debug for Transition {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Transition({} → {} [{}])",
            self.from, self.to, self.label
        )
    }
}

// ---------------------------------------------------------------------------
// NetworkStateMachine
// ---------------------------------------------------------------------------

/// A finite state machine representing a network protocol.
pub struct NetworkStateMachine {
    pub current_state: State,
    pub initial_state: State,
    pub transitions: Vec<Transition>,
    /// History of visited states.
    pub history: Vec<State>,
    /// Messages sent in this session.
    pub sent_messages: Vec<Vec<u8>>,
}

impl NetworkStateMachine {
    /// Create an FSM starting in `initial_state`.
    #[must_use]
    pub fn new(initial_state: State) -> Self {
        Self {
            current_state: initial_state.clone(),
            initial_state,
            transitions: Vec::new(),
            history: Vec::new(),
            sent_messages: Vec::new(),
        }
    }

    /// Add a transition.
    pub fn add_transition(&mut self, transition: Transition) {
        self.transitions.push(transition);
    }

    /// Find all transitions from the current state.
    #[must_use]
    pub fn available_transitions(&self) -> Vec<&Transition> {
        self.transitions
            .iter()
            .filter(|t| t.from == self.current_state)
            .collect()
    }

    /// Take a random transition from the current state using `rng`.
    ///
    /// Returns the message bytes sent, or `None` if no transition is available.
    pub fn step(&mut self, rng: &mut SimpleRng) -> Option<Vec<u8>> {
        let available: Vec<usize> = self
            .transitions
            .iter()
            .enumerate()
            .filter(|(_, t)| t.from == self.current_state)
            .map(|(i, _)| i)
            .collect();

        if available.is_empty() {
            return None;
        }
        let idx = available[rng.next_range(available.len())];

        let msg = self.transitions[idx].message.generate_mutated(rng);
        if self.transitions[idx].check_guard(&self.current_state, &msg) {
            self.history.push(self.current_state.clone());
            let next = self.transitions[idx].to.clone();
            self.sent_messages.push(msg.clone());
            self.current_state = next;
            Some(msg)
        } else {
            Some(msg) // guard failed, still return msg but don't advance
        }
    }

    /// Reset to the initial state.
    pub fn reset(&mut self) {
        self.current_state = self.initial_state.clone();
        self.history.clear();
        self.sent_messages.clear();
    }

    /// Whether we are in a terminal state.
    #[must_use]
    pub const fn is_terminal(&self) -> bool {
        self.current_state.is_terminal()
    }
}

// ---------------------------------------------------------------------------
// StateExplorer
// ---------------------------------------------------------------------------

/// Explores the state machine graph by BFS/DFS to find all reachable states.
#[derive(Debug, Default)]
pub struct StateExplorer {
    pub visited_states: Vec<State>,
    pub edges: Vec<(State, State, String)>,
}

impl StateExplorer {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// BFS exploration of the FSM graph.
    pub fn explore_bfs(&mut self, fsm: &NetworkStateMachine) {
        use std::collections::{HashSet, VecDeque};
        let mut visited: HashSet<String> = HashSet::new();
        let mut queue: VecDeque<State> = VecDeque::new();

        queue.push_back(fsm.initial_state.clone());
        visited.insert(fsm.initial_state.name());

        while let Some(state) = queue.pop_front() {
            self.visited_states.push(state.clone());
            for t in &fsm.transitions {
                if t.from == state && !visited.contains(&t.to.name()) {
                    visited.insert(t.to.name());
                    self.edges
                        .push((state.clone(), t.to.clone(), t.label.clone()));
                    queue.push_back(t.to.clone());
                }
            }
        }
    }

    /// Return all unique state names found.
    #[must_use]
    pub fn state_names(&self) -> Vec<String> {
        self.visited_states.iter().map(State::name).collect()
    }

    /// Number of distinct edges discovered.
    #[must_use]
    pub const fn edge_count(&self) -> usize {
        self.edges.len()
    }
}

// ---------------------------------------------------------------------------
// StateMachineFuzzer
// ---------------------------------------------------------------------------

/// Drives the FSM through random transitions, collecting generated messages
/// as fuzzer inputs.
pub struct StateMachineFuzzer {
    pub fsm: NetworkStateMachine,
    pub rng: SimpleRng,
    /// Maximum steps per session.
    pub max_steps: usize,
    /// Collected inputs (sessions × messages).
    pub corpus: Vec<Vec<Vec<u8>>>,
}

impl StateMachineFuzzer {
    #[must_use]
    pub const fn new(fsm: NetworkStateMachine, seed: u64) -> Self {
        Self {
            fsm,
            rng: SimpleRng::new(seed),
            max_steps: 64,
            corpus: Vec::new(),
        }
    }

    /// Run one fuzzing session: drive the FSM for up to `max_steps` steps.
    /// Returns the messages generated.
    #[must_use]
    pub fn run_session(&mut self) -> Vec<Vec<u8>> {
        self.fsm.reset();
        let mut session = Vec::new();
        for _ in 0..self.max_steps {
            if self.fsm.is_terminal() {
                break;
            }
            if let Some(msg) = self.fsm.step(&mut self.rng) {
                session.push(msg);
            } else {
                break;
            }
        }
        self.corpus.push(session.clone());
        session
    }

    /// Run `n` sessions and return the total number of messages generated.
    pub fn run_sessions(&mut self, n: usize) -> usize {
        (0..n).map(|_| self.run_session().len()).sum()
    }

    /// Return all unique messages across all sessions.
    #[must_use]
    pub fn unique_messages(&self) -> Vec<&Vec<u8>> {
        let mut seen = std::collections::HashSet::new();
        let mut out = Vec::new();
        for session in &self.corpus {
            for msg in session {
                if seen.insert(msg.as_slice()) {
                    out.push(msg);
                }
            }
        }
        out
    }
}

// ---------------------------------------------------------------------------
// SimpleRng
// ---------------------------------------------------------------------------

/// Fast xorshift64 PRNG.
#[derive(Debug, Clone)]
pub struct SimpleRng(u64);

impl SimpleRng {
    #[must_use]
    pub const fn new(seed: u64) -> Self {
        Self(if seed == 0 { 1 } else { seed })
    }

    pub const fn next_u64(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }

    pub const fn next_byte(&mut self) -> u8 {
        self.next_u64() as u8
    }

    pub const fn next_u16(&mut self) -> u16 {
        self.next_u64() as u16
    }

    pub const fn next_u32(&mut self) -> u32 {
        self.next_u64() as u32
    }

    pub const fn next_range(&mut self, n: usize) -> usize {
        if n == 0 {
            return 0;
        }
        (self.next_u64() as usize) % n
    }
}

// ---------------------------------------------------------------------------
// Helpers: pre-built HTTP-like state machine
// ---------------------------------------------------------------------------

/// Build a simple HTTP-like state machine for testing.
#[must_use]
pub fn http_like_state_machine() -> NetworkStateMachine {
    let initial = State::Builtin(ProtocolState::Initial);
    let connected = State::Builtin(ProtocolState::Connected);
    let data = State::Builtin(ProtocolState::DataTransfer);
    let closing = State::Builtin(ProtocolState::Closing);
    let closed = State::Builtin(ProtocolState::Closed);

    let mut fsm = NetworkStateMachine::new(initial.clone());

    // SYN
    let mut syn = MessageTemplate::new("TCP_SYN");
    syn.add_field(FieldType::FixedBytes(b"SYN".to_vec()));
    fsm.add_transition(Transition::new(initial, connected.clone(), "connect", syn));

    // HTTP GET
    let mut get = MessageTemplate::new("HTTP_GET");
    get.add_field(FieldType::AsciiString(
        "GET /fuzz HTTP/1.1\r\n\r\n".to_string(),
    ));
    fsm.add_transition(Transition::new(connected, data.clone(), "request", get));

    // Data post
    let mut post = MessageTemplate::new("HTTP_POST");
    post.add_field(FieldType::RandomBytes {
        min_len: 4,
        max_len: 256,
    });
    fsm.add_transition(Transition::new(
        data.clone(),
        data.clone(),
        "transfer",
        post,
    ));

    // Close
    let mut fin = MessageTemplate::new("TCP_FIN");
    fin.add_field(FieldType::FixedBytes(b"FIN".to_vec()));
    fsm.add_transition(Transition::new(data, closing.clone(), "close", fin));

    let mut ack = MessageTemplate::new("TCP_ACK");
    ack.add_field(FieldType::FixedBytes(b"ACK".to_vec()));
    fsm.add_transition(Transition::new(closing, closed, "ack_close", ack));

    fsm
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_rng() -> SimpleRng {
        SimpleRng::new(0xDEAD_BEEF)
    }

    // ── ProtocolState ──────────────────────────────────────────────────────

    #[test]
    fn protocol_state_terminal() {
        assert!(ProtocolState::Closed.is_terminal());
        assert!(ProtocolState::Error.is_terminal());
        assert!(!ProtocolState::Connected.is_terminal());
    }

    #[test]
    fn protocol_state_display() {
        assert_eq!(ProtocolState::DataTransfer.to_string(), "DataTransfer");
    }

    // ── State ─────────────────────────────────────────────────────────────

    #[test]
    fn state_builtin_name() {
        let s = State::Builtin(ProtocolState::Authenticated);
        assert_eq!(s.name(), "Authenticated");
    }

    #[test]
    fn state_custom_name() {
        let s = State::Custom(CustomState::new(1, "MyState"));
        assert_eq!(s.name(), "MyState");
    }

    #[test]
    fn state_custom_terminal() {
        let s = State::Custom(CustomState::new(1, "Done").terminal());
        assert!(s.is_terminal());
    }

    // ── FieldType ─────────────────────────────────────────────────────────

    #[test]
    fn field_fixed_bytes() {
        let mut rng = make_rng();
        let f = FieldType::FixedBytes(vec![0xDE, 0xAD]);
        assert_eq!(f.generate(&mut rng), vec![0xDE, 0xAD]);
    }

    #[test]
    fn field_u8() {
        let mut rng = make_rng();
        assert_eq!(FieldType::U8(42).generate(&mut rng), vec![42]);
    }

    #[test]
    fn field_u16le() {
        let mut rng = make_rng();
        let bytes = FieldType::U16Le(0x0102).generate(&mut rng);
        assert_eq!(bytes, vec![0x02, 0x01]);
    }

    #[test]
    fn field_u32le() {
        let mut rng = make_rng();
        let bytes = FieldType::U32Le(0x01020304).generate(&mut rng);
        assert_eq!(u32::from_le_bytes(bytes.try_into().unwrap()), 0x01020304);
    }

    #[test]
    fn field_random_bytes_len_in_range() {
        let mut rng = make_rng();
        let f = FieldType::RandomBytes {
            min_len: 4,
            max_len: 8,
        };
        for _ in 0..20 {
            let out = f.generate(&mut rng);
            assert!(out.len() >= 4 && out.len() <= 8);
        }
    }

    #[test]
    fn field_length_prefixed() {
        let mut rng = make_rng();
        let f = FieldType::LengthPrefixed {
            inner: Box::new(FieldType::FixedBytes(vec![1, 2, 3])),
        };
        let out = f.generate(&mut rng);
        assert_eq!(out[0], 3);
        assert_eq!(&out[1..], &[1, 2, 3]);
    }

    #[test]
    fn field_mutate_changes_value() {
        let mut rng = make_rng();
        let mut f = FieldType::U8(0x55);
        // Mutate enough times that the value changes with overwhelming probability.
        for _ in 0..100 {
            f.mutate(&mut rng);
        }
        if let FieldType::U8(v) = f {
            let _ = v; // just ensure no panic
        }
    }

    // ── MessageTemplate ───────────────────────────────────────────────────

    #[test]
    fn message_template_generate() {
        let mut rng = make_rng();
        let mut t = MessageTemplate::new("hello");
        t.add_field(FieldType::FixedBytes(b"HELLO".to_vec()));
        let out = t.generate(&mut rng);
        assert_eq!(out, b"HELLO");
    }

    #[test]
    fn message_template_generate_mutated_not_panic() {
        let mut rng = make_rng();
        let mut t = MessageTemplate::new("m");
        t.add_field(FieldType::U32Le(0xDEADBEEF));
        for _ in 0..20 {
            let out = t.generate_mutated(&mut rng);
            assert_eq!(out.len(), 4);
        }
    }

    // ── NetworkStateMachine ────────────────────────────────────────────────

    #[test]
    fn fsm_http_like_connects() {
        let mut fsm = http_like_state_machine();
        let mut rng = make_rng();
        // First step should take us to Connected.
        let msg = fsm.step(&mut rng);
        assert!(msg.is_some());
        assert_eq!(fsm.current_state, State::Builtin(ProtocolState::Connected));
    }

    #[test]
    fn fsm_reset() {
        let mut fsm = http_like_state_machine();
        let mut rng = make_rng();
        fsm.step(&mut rng);
        fsm.reset();
        assert_eq!(fsm.current_state, State::Builtin(ProtocolState::Initial));
        assert!(fsm.history.is_empty());
    }

    #[test]
    fn fsm_available_transitions_initial() {
        let fsm = http_like_state_machine();
        let avail = fsm.available_transitions();
        assert_eq!(avail.len(), 1);
        assert_eq!(avail[0].label, "connect");
    }

    #[test]
    fn fsm_no_available_transitions_in_closed() {
        let fsm = NetworkStateMachine::new(State::Builtin(ProtocolState::Closed));
        assert!(fsm.available_transitions().is_empty());
    }

    #[test]
    fn fsm_is_terminal() {
        let fsm = NetworkStateMachine::new(State::Builtin(ProtocolState::Closed));
        assert!(fsm.is_terminal());
    }

    // ── StateExplorer ─────────────────────────────────────────────────────

    #[test]
    fn state_explorer_bfs() {
        let fsm = http_like_state_machine();
        let mut explorer = StateExplorer::new();
        explorer.explore_bfs(&fsm);
        let names = explorer.state_names();
        assert!(names.contains(&"Initial".to_string()));
        assert!(names.contains(&"Connected".to_string()));
    }

    #[test]
    fn state_explorer_edge_count() {
        let fsm = http_like_state_machine();
        let mut explorer = StateExplorer::new();
        explorer.explore_bfs(&fsm);
        assert!(explorer.edge_count() >= 3);
    }

    // ── StateMachineFuzzer ─────────────────────────────────────────────────

    #[test]
    fn fuzzer_run_session_produces_messages() {
        let fsm = http_like_state_machine();
        let mut fuzzer = StateMachineFuzzer::new(fsm, 42);
        let session = fuzzer.run_session();
        assert!(!session.is_empty());
    }

    #[test]
    fn fuzzer_run_sessions_count() {
        let fsm = http_like_state_machine();
        let mut fuzzer = StateMachineFuzzer::new(fsm, 99);
        let total = fuzzer.run_sessions(5);
        assert!(total > 0);
    }

    #[test]
    fn fuzzer_corpus_grows() {
        let fsm = http_like_state_machine();
        let mut fuzzer = StateMachineFuzzer::new(fsm, 1);
        fuzzer.run_sessions(3);
        assert_eq!(fuzzer.corpus.len(), 3);
    }

    #[test]
    fn fuzzer_unique_messages() {
        let fsm = http_like_state_machine();
        let mut fuzzer = StateMachineFuzzer::new(fsm, 7);
        fuzzer.run_sessions(3);
        assert!(!fuzzer.unique_messages().is_empty());
    }

    // ── SimpleRng ─────────────────────────────────────────────────────────

    #[test]
    fn rng_range() {
        let mut rng = make_rng();
        for _ in 0..100 {
            assert!(rng.next_range(8) < 8);
        }
    }

    #[test]
    fn rng_zero_range() {
        let mut rng = make_rng();
        assert_eq!(rng.next_range(0), 0);
    }

    #[test]
    fn rng_not_constant() {
        let mut rng = make_rng();
        let a = rng.next_u64();
        let b = rng.next_u64();
        assert_ne!(a, b);
    }
}
