[package]
license.workspace = true
name = "rustre-cli"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[[bin]]
name = "rustre-cli"
path = "src/main.rs"

[lib]
name = "rustre_cli"
path = "src/lib.rs"

[dependencies]
rustre-core = { path = "../rustre-core" }
rustre-project = { path = "../rustre-project" }
rustre-patch = { path = "../rustre-patch" }
rustre-fuzz-cov = { path = "../rustre-fuzz-cov" }
rustre-fuzz-sanitizers = { path = "../rustre-fuzz-sanitizers" }
rustre-net = { path = "../rustre-net" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[lints]
workspace = true
