[package]
license.workspace = true
name = "rustre-symbols-pdb"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-symbols = { path = "../rustre-symbols" }
rustre-pe-tools = { path = "../rustre-pe-tools" }
rustre-demangle  = { path = "../rustre-demangle" }
thiserror = { workspace = true }
serde = { workspace = true }
bitflags = "2.6"

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
