[package]
name = "rustre-analysis-string"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rustre-analysis = { path = "../rustre-analysis" }
rustre-core = { path = "../rustre-core" }
rustre-il-llil = { path = "../rustre-il-llil" }
ahash = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
