[package]
license.workspace = true
name = "rustre-plugin-loader"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-plugin-api = { path = "../rustre-plugin-api" }

[lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
