[package]
license.workspace = true
name = "rustre-arch-arm"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-core = { path = "../rustre-core" }
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
