[package]
license.workspace = true
name = "rustre-symbols-dwarf"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-symbols = { path = "../rustre-symbols" }
thiserror = { workspace = true }
serde = { workspace = true }
gimli = { workspace = true }
object = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
