//! MCP wrappers for the rustre-adf crate.
//! Extracted from `wire_tools.rs` by `workflow_split_wire_tools`.

use rustre_mcp_server::{McpError, ToolDefinition, ToolHandler, ToolResult};
use serde_json::{json, Value};
use async_trait::async_trait;

pub struct AdfLatticeValueMeetTopTool;
impl AdfLatticeValueMeetTopTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_lattice_value_meet_top".to_string(), description: "LatticeValue::meet(Top, Const(x)).".to_string(), input_schema: json!({"type":"object","properties":{"x":{"type":"integer"}},"required":["x"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfLatticeValueMeetTopTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let x = args.get("x").and_then(Value::as_i64).ok_or_else(|| McpError::InvalidParams("missing 'x'".into()))?; let r = rustre_analysis_dataflow::LatticeValue::meet(&rustre_analysis_dataflow::LatticeValue::Top, &rustre_analysis_dataflow::LatticeValue::Const(x)); let (kind, val) = match r { rustre_analysis_dataflow::LatticeValue::Top => ("top", None), rustre_analysis_dataflow::LatticeValue::Const(c) => ("const", Some(c)), rustre_analysis_dataflow::LatticeValue::Bottom => ("bottom", None) }; Ok(ToolResult::text(json!({"kind":kind,"value":val,"source":"rustre_analysis_dataflow::LatticeValue::meet"}).to_string())) } }

pub struct AdfLatticeValueMeetEqualTool;
impl AdfLatticeValueMeetEqualTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_lattice_value_meet_equal".to_string(), description: "meet(Const(a), Const(a)).".to_string(), input_schema: json!({"type":"object","properties":{"a":{"type":"integer"}},"required":["a"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfLatticeValueMeetEqualTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = args.get("a").and_then(Value::as_i64).ok_or_else(|| McpError::InvalidParams("missing 'a'".into()))?; let r = rustre_analysis_dataflow::LatticeValue::meet(&rustre_analysis_dataflow::LatticeValue::Const(a), &rustre_analysis_dataflow::LatticeValue::Const(a)); let (kind, val) = match r { rustre_analysis_dataflow::LatticeValue::Top => ("top", None), rustre_analysis_dataflow::LatticeValue::Const(c) => ("const", Some(c)), rustre_analysis_dataflow::LatticeValue::Bottom => ("bottom", None) }; Ok(ToolResult::text(json!({"kind":kind,"value":val,"source":"rustre_analysis_dataflow::LatticeValue::meet"}).to_string())) } }

pub struct AdfLatticeValueMeetDifferentTool;
impl AdfLatticeValueMeetDifferentTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_lattice_value_meet_different".to_string(), description: "meet(Const(a), Const(b)) with a!=b.".to_string(), input_schema: json!({"type":"object","properties":{"a":{"type":"integer"},"b":{"type":"integer"}},"required":["a","b"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfLatticeValueMeetDifferentTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = args.get("a").and_then(Value::as_i64).ok_or_else(|| McpError::InvalidParams("missing 'a'".into()))?; let b = args.get("b").and_then(Value::as_i64).ok_or_else(|| McpError::InvalidParams("missing 'b'".into()))?; let r = rustre_analysis_dataflow::LatticeValue::meet(&rustre_analysis_dataflow::LatticeValue::Const(a), &rustre_analysis_dataflow::LatticeValue::Const(b)); let is_bottom = matches!(r, rustre_analysis_dataflow::LatticeValue::Bottom); Ok(ToolResult::text(json!({"is_bottom":is_bottom,"source":"rustre_analysis_dataflow::LatticeValue::meet"}).to_string())) } }

pub struct AdfStatementNewTool;
impl AdfStatementNewTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_statement_new".to_string(), description: "Statement::new.".to_string(), input_schema: json!({"type":"object","properties":{"id":{"type":"integer"},"def":{"type":"string"},"uses":{"type":"array","items":{"type":"string"}}},"required":["id"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfStatementNewTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let id = args.get("id").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'id'".into()))? as usize; let def_s = args.get("def").and_then(Value::as_str); let uses: Vec<String> = args.get("uses").and_then(Value::as_array).map(|a| a.iter().filter_map(|v| v.as_str().map(str::to_string)).collect()).unwrap_or_default(); let uses_ref: Vec<&str> = uses.iter().map(String::as_str).collect(); let s = rustre_analysis_dataflow::Statement::new(id, def_s, uses_ref); Ok(ToolResult::text(json!({"id":s.id,"def":s.def,"uses":s.uses,"expr":s.expr,"source":"rustre_analysis_dataflow::Statement::new"}).to_string())) } }

pub struct AdfStatementWithExprTool;
impl AdfStatementWithExprTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_statement_with_expr".to_string(), description: "Statement::with_expr.".to_string(), input_schema: json!({"type":"object","properties":{"id":{"type":"integer"},"expr":{"type":"string"}},"required":["id","expr"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfStatementWithExprTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let id = args.get("id").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'id'".into()))? as usize; let expr = args.get("expr").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'expr'".into()))?; let s = rustre_analysis_dataflow::Statement::new(id, None, vec![]).with_expr(expr); Ok(ToolResult::text(json!({"id":s.id,"expr":s.expr,"source":"rustre_analysis_dataflow::Statement::with_expr"}).to_string())) } }

pub struct AdfLinearCfgNodeCountTool;
impl AdfLinearCfgNodeCountTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_linear_cfg_node_count".to_string(), description: "linear_cfg + Cfg::node_count.".to_string(), input_schema: json!({"type":"object","properties":{"n":{"type":"integer"}},"required":["n"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfLinearCfgNodeCountTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let n = args.get("n").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n'".into()))? as usize; let stmts: Vec<rustre_analysis_dataflow::Statement> = (0..n).map(|i| rustre_analysis_dataflow::Statement::new(i, None, vec![])).collect(); let cfg = rustre_analysis_dataflow::linear_cfg(stmts); Ok(ToolResult::text(json!({"node_count":cfg.node_count(),"entry":cfg.entry,"exit":cfg.exit,"source":"rustre_analysis_dataflow::linear_cfg"}).to_string())) } }

pub struct AdfComputeDominatorsChainTool;
impl AdfComputeDominatorsChainTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_compute_dominators_chain".to_string(), description: "compute_dominators over a linear chain.".to_string(), input_schema: json!({"type":"object","properties":{"n":{"type":"integer"}},"required":["n"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfComputeDominatorsChainTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let n = args.get("n").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n'".into()))? as usize; if n == 0 { return Err(McpError::InvalidParams("n must be > 0".into())); } let successors: Vec<Vec<usize>> = (0..n).map(|i| if i + 1 < n { vec![i + 1] } else { vec![] }).collect(); let idom = rustre_analysis_dataflow::compute_dominators(n, &successors, 0); Ok(ToolResult::text(json!({"idom":idom,"n":n,"source":"rustre_analysis_dataflow::compute_dominators"}).to_string())) } }

pub struct AdfPostorderChainTool;
impl AdfPostorderChainTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_postorder_chain".to_string(), description: "postorder of a linear chain.".to_string(), input_schema: json!({"type":"object","properties":{"n":{"type":"integer"}},"required":["n"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfPostorderChainTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let n = args.get("n").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n'".into()))? as usize; if n == 0 { return Err(McpError::InvalidParams("n must be > 0".into())); } let succ: Vec<Vec<usize>> = (0..n).map(|i| if i + 1 < n { vec![i + 1] } else { vec![] }).collect(); let po = rustre_analysis_dataflow::postorder(n, &succ, 0); Ok(ToolResult::text(json!({"postorder":po,"len":n,"source":"rustre_analysis_dataflow::postorder"}).to_string())) } }

pub struct AdfDominatorsFromEdgesTool;
impl AdfDominatorsFromEdgesTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_dominators_from_edges".to_string(), description: "compute_dominators_from_edges.".to_string(), input_schema: json!({"type":"object","properties":{"n":{"type":"integer"},"edges":{"type":"array"},"entry":{"type":"integer"}},"required":["n","edges"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfDominatorsFromEdgesTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let n = args.get("n").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n'".into()))? as usize; let entry = args.get("entry").and_then(Value::as_u64).unwrap_or(0) as usize; let edges_arr = args.get("edges").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'edges'".into()))?; let edges: Vec<[usize; 2]> = edges_arr.iter().filter_map(|v| { let a = v.as_array()?; Some([a.first()?.as_u64()? as usize, a.get(1)?.as_u64()? as usize]) }).collect(); let idom = rustre_analysis_dataflow::compute_dominators_from_edges(n, &edges, entry); Ok(ToolResult::text(json!({"idom":idom,"n":n,"source":"rustre_analysis_dataflow::compute_dominators_from_edges"}).to_string())) } }

pub struct AdfTraceCallersBackwardSimpleTool;
impl AdfTraceCallersBackwardSimpleTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_trace_callers_backward_simple".to_string(), description: "trace_callers_backward.".to_string(), input_schema: json!({"type":"object","properties":{"addr":{"type":"integer"},"hops":{"type":"integer"},"edges":{"type":"array"}},"required":["addr","edges"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfTraceCallersBackwardSimpleTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let hops = args.get("hops").and_then(Value::as_u64).unwrap_or(4) as usize; let edges_arr = args.get("edges").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'edges'".into()))?; let edges: Vec<(u64, u64)> = edges_arr.iter().filter_map(|v| { let a = v.as_array()?; Some((a.first()?.as_u64()?, a.get(1)?.as_u64()?)) }).collect(); let t = rustre_analysis_dataflow::trace_callers_backward(addr, hops, &edges); Ok(ToolResult::text(json!({"target":addr,"hops":hops,"node_count":t.total,"source":"rustre_analysis_dataflow::trace_callers_backward"}).to_string())) } }

pub struct AdfTraceCalleesForwardSimpleTool;
impl AdfTraceCalleesForwardSimpleTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "adf_trace_callees_forward_simple".to_string(), description: "trace_callees_forward.".to_string(), input_schema: json!({"type":"object","properties":{"addr":{"type":"integer"},"hops":{"type":"integer"},"edges":{"type":"array"}},"required":["addr","edges"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for AdfTraceCalleesForwardSimpleTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let hops = args.get("hops").and_then(Value::as_u64).unwrap_or(4) as usize; let edges_arr = args.get("edges").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'edges'".into()))?; let edges: Vec<(u64, u64)> = edges_arr.iter().filter_map(|v| { let a = v.as_array()?; Some((a.first()?.as_u64()?, a.get(1)?.as_u64()?)) }).collect(); let t = rustre_analysis_dataflow::trace_callees_forward(addr, hops, &edges); Ok(ToolResult::text(json!({"source_addr":addr,"hops":hops,"node_count":t.total,"source":"rustre_analysis_dataflow::trace_callees_forward"}).to_string())) } }

pub fn handlers() -> Vec<(ToolDefinition, Box<dyn ToolHandler>)> {
    vec![
        (AdfLatticeValueMeetTopTool::definition(), Box::new(AdfLatticeValueMeetTopTool)),
        (AdfLatticeValueMeetEqualTool::definition(), Box::new(AdfLatticeValueMeetEqualTool)),
        (AdfLatticeValueMeetDifferentTool::definition(), Box::new(AdfLatticeValueMeetDifferentTool)),
        (AdfStatementNewTool::definition(), Box::new(AdfStatementNewTool)),
        (AdfStatementWithExprTool::definition(), Box::new(AdfStatementWithExprTool)),
        (AdfLinearCfgNodeCountTool::definition(), Box::new(AdfLinearCfgNodeCountTool)),
        (AdfComputeDominatorsChainTool::definition(), Box::new(AdfComputeDominatorsChainTool)),
        (AdfPostorderChainTool::definition(), Box::new(AdfPostorderChainTool)),
        (AdfDominatorsFromEdgesTool::definition(), Box::new(AdfDominatorsFromEdgesTool)),
        (AdfTraceCallersBackwardSimpleTool::definition(), Box::new(AdfTraceCallersBackwardSimpleTool)),
        (AdfTraceCalleesForwardSimpleTool::definition(), Box::new(AdfTraceCalleesForwardSimpleTool)),
    ]
}
