//! MCP wrappers for the rustre-debug_macos crate.
//! Extracted from wire_tools.rs by workflow_split_wire_tools.

use rustre_mcp_server::{McpError, ToolDefinition, ToolHandler, ToolResult};
use serde_json::{json, Value};
use async_trait::async_trait;
use crate::{args_to_bytes};

pub struct DebugMacosBreakpointManagerBuildTool;

pub struct DebugMacosProcessDescribeTool;

pub struct DebugMacosX86RegisterIndexTool;
impl DebugMacosX86RegisterIndexTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_x86_register_index".to_string(), description: "x86_64 thread-state index via rustre_debug_macos::MacosRegisterSet::x86_64_index.".to_string(), input_schema: json!({ "type": "object", "properties": { "name": {"type": "string"} }, "required": ["name"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosX86RegisterIndexTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?; Ok(ToolResult::text(json!({ "name": name, "index": rustre_debug_macos::MacosRegisterSet::x86_64_index(name), "source": "rustre_debug_macos::MacosRegisterSet::x86_64_index" }).to_string())) } }

pub struct DebugMacosArm64RegisterIndexTool;
impl DebugMacosArm64RegisterIndexTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_arm64_register_index".to_string(), description: "ARM_THREAD_STATE64 index via rustre_debug_macos::MacosRegisterSet::arm64_index.".to_string(), input_schema: json!({ "type": "object", "properties": { "name": {"type": "string"} }, "required": ["name"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosArm64RegisterIndexTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?; Ok(ToolResult::text(json!({ "name": name, "index": rustre_debug_macos::MacosRegisterSet::arm64_index(name), "source": "rustre_debug_macos::MacosRegisterSet::arm64_index" }).to_string())) } }

pub struct DebugMacosMachoHeaderParseTool;
impl DebugMacosMachoHeaderParseTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_macho_header_parse".to_string(), description: "Parse Mach-O header via rustre_debug_macos::MachoHeader::parse.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type": "string"}, "bytes": {"type":"array"} } }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachoHeaderParseTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; let h = rustre_debug_macos::MachoHeader::parse(&data); let out = h.as_ref().map(|h| json!({ "magic": h.magic, "cpu_type": h.cpu_type.name(), "cpu_subtype": h.cpu_subtype, "file_type": h.file_type.name(), "n_cmds": h.n_cmds, "size_of_cmds": h.size_of_cmds, "flags": h.flags, "is_64": h.is_64, "is_pie": h.is_pie(), "is_stripped": h.is_stripped() })); Ok(ToolResult::text(json!({ "header": out, "source": "rustre_debug_macos::MachoHeader::parse" }).to_string())) } }

pub struct DebugMacosCpuTypeFromU32Tool;
impl DebugMacosCpuTypeFromU32Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_cpu_type_from_u32".to_string(), description: "Decode Mach-O cpu_type_t via rustre_debug_macos::CpuType::from_u32.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type": "integer"} }, "required": ["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosCpuTypeFromU32Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let ct = rustre_debug_macos::CpuType::from_u32(v); Ok(ToolResult::text(json!({ "value": v, "name": ct.name(), "source": "rustre_debug_macos::CpuType::from_u32" }).to_string())) } }

pub struct DebugMacosMachoFileTypeFromU32Tool;
impl DebugMacosMachoFileTypeFromU32Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_macho_file_type_from_u32".to_string(), description: "Decode Mach-O filetype via rustre_debug_macos::MachoFileType::from_u32.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type": "integer"} }, "required": ["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachoFileTypeFromU32Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let ft = rustre_debug_macos::MachoFileType::from_u32(v); Ok(ToolResult::text(json!({ "value": v, "name": ft.name(), "source": "rustre_debug_macos::MachoFileType::from_u32" }).to_string())) } }

pub struct DebugMacosFormatMachoVersionTool;
impl DebugMacosFormatMachoVersionTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_format_macho_version".to_string(), description: "Format packed Mach-O version via rustre_debug_macos::format_macho_version.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type": "integer"} }, "required": ["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosFormatMachoVersionTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; Ok(ToolResult::text(json!({ "value": v, "formatted": rustre_debug_macos::format_macho_version(v), "source": "rustre_debug_macos::format_macho_version" }).to_string())) } }

pub struct DebugMacosFormatUuidTool;
impl DebugMacosFormatUuidTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_format_uuid".to_string(), description: "Format 16-byte Mach-O UUID via rustre_debug_macos::format_uuid.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type": "string"}, "bytes": {"type":"array"} } }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosFormatUuidTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; if data.len() != 16 { return Err(McpError::InvalidParams(format!("expected 16 bytes, got {}", data.len()))); } let mut uuid = [0u8; 16]; uuid.copy_from_slice(&data); Ok(ToolResult::text(json!({ "uuid": rustre_debug_macos::format_uuid(&uuid), "source": "rustre_debug_macos::format_uuid" }).to_string())) } }

pub struct DebugMacosMachExceptionFromU32Tool;
impl DebugMacosMachExceptionFromU32Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_exception_from_u32".to_string(), description: "Decode Mach exception number via rustre_debug_macos::MachException.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type": "integer"} }, "required": ["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachExceptionFromU32Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let e = rustre_debug_macos::MachException::from_u32(v); Ok(ToolResult::text(json!({ "value": v, "name": e.name(), "signal": e.to_signal(), "source": "rustre_debug_macos::MachException::from_u32" }).to_string())) } }

pub struct DebugMacosVmProtDecodeTool;
impl DebugMacosVmProtDecodeTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_vm_prot_decode".to_string(), description: "Decode raw vm_prot_t via rustre_debug_macos::VmProt.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type": "integer"} }, "required": ["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosVmProtDecodeTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let p = rustre_debug_macos::VmProt::from_raw(v); Ok(ToolResult::text(json!({ "value": v, "readable": p.readable(), "writable": p.writable(), "executable": p.executable(), "as_str": p.as_str(), "source": "rustre_debug_macos::VmProt::from_raw" }).to_string())) } }

pub struct DebugMacosMachVmProtectionDecodeTool;
impl DebugMacosMachVmProtectionDecodeTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_vm_protection_decode".to_string(), description: "Decode Mach VM protection bits via rustre_debug_macos::MachVmProtection.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type": "integer"} }, "required": ["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachVmProtectionDecodeTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let p = rustre_debug_macos::MachVmProtection::from_raw(v); Ok(ToolResult::text(json!({ "value": v, "read": p.read, "write": p.write, "execute": p.execute, "unix_str": p.to_unix_str(), "as_raw": p.as_raw(), "source": "rustre_debug_macos::MachVmProtection::from_raw" }).to_string())) } }

pub struct DebugMacosSimulateX8664RegistersTool;
impl DebugMacosSimulateX8664RegistersTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_simulate_x86_64_registers".to_string(), description: "Build x86_64 RegisterSet via rustre_debug_macos::simulate_x86_64_register_set.".to_string(), input_schema: json!({ "type": "object", "properties": { "rip":{"type":"integer"},"rsp":{"type":"integer"},"rbp":{"type":"integer"},"rax":{"type":"integer"},"rbx":{"type":"integer"} }, "required":["rip","rsp","rbp","rax","rbx"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosSimulateX8664RegistersTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let g = |k: &str| args.get(k).and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams(format!("missing '{k}'"))); let rs = rustre_debug_macos::simulate_x86_64_register_set(g("rip")?, g("rsp")?, g("rbp")?, g("rax")?, g("rbx")?); Ok(ToolResult::text(json!({ "pc": rs.pc, "sp": rs.sp, "fp": rs.fp, "rax": rs.get("rax"), "rbx": rs.get("rbx"), "source": "rustre_debug_macos::simulate_x86_64_register_set" }).to_string())) } }

pub struct DebugMacosSimulateArm64RegistersTool;
impl DebugMacosSimulateArm64RegistersTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_simulate_arm64_registers".to_string(), description: "Build arm64 RegisterSet via rustre_debug_macos::simulate_arm64_register_set.".to_string(), input_schema: json!({ "type": "object", "properties": { "pc":{"type":"integer"},"sp":{"type":"integer"},"fp":{"type":"integer"},"lr":{"type":"integer"},"x0":{"type":"integer"} }, "required":["pc","sp","fp","lr","x0"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosSimulateArm64RegistersTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let g = |k: &str| args.get(k).and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams(format!("missing '{k}'"))); let rs = rustre_debug_macos::simulate_arm64_register_set(g("pc")?, g("sp")?, g("fp")?, g("lr")?, g("x0")?); Ok(ToolResult::text(json!({ "pc": rs.pc, "sp": rs.sp, "fp": rs.fp, "lr": rs.lr, "x0": rs.get("x0"), "source": "rustre_debug_macos::simulate_arm64_register_set" }).to_string())) } }

pub struct DebugMacosDyldImageRebasedTool;
impl DebugMacosDyldImageRebasedTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_dyld_image_rebased".to_string(), description: "Rebased address for a dyld image via rustre_debug_macos::DyldImage::rebased.".to_string(), input_schema: json!({ "type": "object", "properties": { "load_address":{"type":"integer"},"path":{"type":"string"},"slide":{"type":"integer"},"offset":{"type":"integer"} }, "required":["load_address","path","slide","offset"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosDyldImageRebasedTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let load_address = args.get("load_address").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'load_address'".into()))?; let path = args.get("path").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'path'".into()))?.to_string(); let slide = args.get("slide").and_then(Value::as_i64).ok_or_else(|| McpError::InvalidParams("missing 'slide'".into()))?; let offset = args.get("offset").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'offset'".into()))?; let img = rustre_debug_macos::DyldImage { load_address, path, slide }; Ok(ToolResult::text(json!({ "rebased": img.rebased(offset), "name": img.name(), "source": "rustre_debug_macos::DyldImage::rebased" }).to_string())) } }

pub struct DebugMacosMachoSectionQualifiedNameTool;
impl DebugMacosMachoSectionQualifiedNameTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_macho_section_qualified_name".to_string(), description: "'segment.section' and is_code flag via rustre_debug_macos::MachoSection.".to_string(), input_schema: json!({ "type": "object", "properties": { "segment":{"type":"string"},"section":{"type":"string"},"addr":{"type":"integer"},"size":{"type":"integer"},"offset":{"type":"integer"},"flags":{"type":"integer"} }, "required":["segment","section"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachoSectionQualifiedNameTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let segment = args.get("segment").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'segment'".into()))?.to_string(); let section = args.get("section").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'section'".into()))?.to_string(); let s = rustre_debug_macos::MachoSection { segment, section, addr: args.get("addr").and_then(Value::as_u64).unwrap_or(0), size: args.get("size").and_then(Value::as_u64).unwrap_or(0), offset: args.get("offset").and_then(Value::as_u64).unwrap_or(0) as u32, flags: args.get("flags").and_then(Value::as_u64).unwrap_or(0) as u32 }; Ok(ToolResult::text(json!({ "qualified_name": s.qualified_name(), "is_code": s.is_code(), "source": "rustre_debug_macos::MachoSection" }).to_string())) } }

pub struct DebugMacosFatHeaderParseTool;
impl DebugMacosFatHeaderParseTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_fat_header_parse".to_string(), description: "Parse a Mach-O universal (FAT) header via rustre_debug_macos::FatHeader::parse.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type":"string"}, "bytes": {"type":"array"} } }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosFatHeaderParseTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; let h = rustre_debug_macos::FatHeader::parse(&data); let arches: Vec<_> = h.as_ref().map(|h| h.arches.iter().map(|a| json!({ "cpu_type": a.cpu_type.name(), "cpu_subtype": a.cpu_subtype, "offset": a.offset, "size": a.size, "align": a.align })).collect()).unwrap_or_default(); Ok(ToolResult::text(json!({ "parsed": h.is_some(), "arches": arches, "source": "rustre_debug_macos::FatHeader::parse" }).to_string())) } }

pub struct DebugMacosParseLoadCommandsTool;
impl DebugMacosParseLoadCommandsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_parse_load_commands".to_string(), description: "Parse Mach-O load commands via rustre_debug_macos::parse_load_commands.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type":"string"}, "bytes": {"type":"array"}, "n_cmds": {"type":"integer"}, "is_64": {"type":"boolean"} }, "required": ["n_cmds"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosParseLoadCommandsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; let n = args.get("n_cmds").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n_cmds'".into()))? as u32; let is_64 = args.get("is_64").and_then(Value::as_bool).unwrap_or(true); let cmds = rustre_debug_macos::parse_load_commands(&data, n, is_64); let list: Vec<_> = cmds.iter().map(|c| json!({ "cmd_num": c.cmd_num(), "segment_name": c.segment_name() })).collect(); Ok(ToolResult::text(json!({ "count": cmds.len(), "commands": list, "source": "rustre_debug_macos::parse_load_commands" }).to_string())) } }

pub struct DebugMacosExtractDylibsTool;
impl DebugMacosExtractDylibsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_extract_dylibs".to_string(), description: "Extract LC_LOAD_DYLIB entries via rustre_debug_macos::extract_dylibs.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type":"string"}, "bytes": {"type":"array"}, "n_cmds": {"type":"integer"}, "is_64": {"type":"boolean"} }, "required": ["n_cmds"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosExtractDylibsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; let n = args.get("n_cmds").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n_cmds'".into()))? as u32; let is_64 = args.get("is_64").and_then(Value::as_bool).unwrap_or(true); let cmds = rustre_debug_macos::parse_load_commands(&data, n, is_64); let dylibs = rustre_debug_macos::extract_dylibs(&cmds); let list: Vec<_> = dylibs.iter().map(|d| json!({ "path": d.path, "compat": d.compat_version, "current": d.current_version })).collect(); Ok(ToolResult::text(json!({ "count": dylibs.len(), "dylibs": list, "source": "rustre_debug_macos::extract_dylibs" }).to_string())) } }

pub struct DebugMacosExtractUuidTool;
impl DebugMacosExtractUuidTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_extract_uuid".to_string(), description: "Extract LC_UUID via rustre_debug_macos::extract_uuid and format via format_uuid.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type":"string"}, "bytes": {"type":"array"}, "n_cmds": {"type":"integer"}, "is_64": {"type":"boolean"} }, "required": ["n_cmds"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosExtractUuidTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; let n = args.get("n_cmds").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n_cmds'".into()))? as u32; let is_64 = args.get("is_64").and_then(Value::as_bool).unwrap_or(true); let cmds = rustre_debug_macos::parse_load_commands(&data, n, is_64); let uuid = rustre_debug_macos::extract_uuid(&cmds); let formatted = uuid.as_ref().map(rustre_debug_macos::format_uuid); Ok(ToolResult::text(json!({ "found": uuid.is_some(), "uuid": formatted, "source": "rustre_debug_macos::extract_uuid" }).to_string())) } }

pub struct DebugMacosMachExceptionToSignalTool;
impl DebugMacosMachExceptionToSignalTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_exception_to_signal".to_string(), description: "Map Mach exception number to POSIX signal via rustre_debug_macos::MachException::to_signal.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type":"integer"} }, "required": ["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachExceptionToSignalTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let e = rustre_debug_macos::MachException::from_u32(v); Ok(ToolResult::text(json!({ "value": v, "name": e.name(), "signal": e.to_signal(), "source": "rustre_debug_macos::MachException::to_signal" }).to_string())) } }

pub struct DebugMacosVmRegionDescribeTool;
impl DebugMacosVmRegionDescribeTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_vm_region_describe".to_string(), description: "Build a VmRegion and report bounds/permissions via rustre_debug_macos::VmRegion.".to_string(), input_schema: json!({ "type": "object", "properties": { "address": {"type":"integer"}, "size": {"type":"integer"}, "prot": {"type":"integer"} }, "required": ["address","size","prot"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosVmRegionDescribeTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("address").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'address'".into()))?; let size = args.get("size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'size'".into()))?; let prot = args.get("prot").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'prot'".into()))? as u32; let r = rustre_debug_macos::VmRegion::new(addr, size, rustre_debug_macos::VmProt::from_raw(prot)); let mm = r.to_memory_map(); Ok(ToolResult::text(json!({ "address": r.address, "size": r.size, "readable": mm.readable, "writable": mm.writable, "executable": mm.executable, "prot_str": r.prot.as_str(), "source": "rustre_debug_macos::VmRegion" }).to_string())) } }

pub struct DebugMacosVmRegionContainsTool;
impl DebugMacosVmRegionContainsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_vm_region_contains".to_string(), description: "Test whether an address falls inside a VmRegion via rustre_debug_macos::VmRegion::contains.".to_string(), input_schema: json!({ "type": "object", "properties": { "address": {"type":"integer"}, "size": {"type":"integer"}, "query": {"type":"integer"} }, "required": ["address","size","query"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosVmRegionContainsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("address").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'address'".into()))?; let size = args.get("size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'size'".into()))?; let q = args.get("query").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'query'".into()))?; let r = rustre_debug_macos::VmRegion::new(addr, size, rustre_debug_macos::VmProt::from_raw(0)); Ok(ToolResult::text(json!({ "query": q, "contains": r.contains(q), "source": "rustre_debug_macos::VmRegion::contains" }).to_string())) } }

pub struct DebugMacosBreakpointManagerRoundTripTool;
impl DebugMacosBreakpointManagerRoundTripTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_breakpoint_manager_round_trip".to_string(), description: "Insert then remove an address via rustre_debug_macos::BreakpointManager to verify round-trip.".to_string(), input_schema: json!({ "type": "object", "properties": { "address": {"type":"integer"}, "original_byte": {"type":"integer"} }, "required": ["address","original_byte"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosBreakpointManagerRoundTripTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("address").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'address'".into()))?; let byte = args.get("original_byte").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'original_byte'".into()))? as u8; let mut mgr = rustre_debug_macos::BreakpointManager::new(); mgr.insert(addr, byte); let contained = mgr.contains(addr); let removed = mgr.remove(addr); let after = mgr.contains(addr); Ok(ToolResult::text(json!({ "address": addr, "inserted_byte": byte, "contained": contained, "removed": removed, "contained_after_remove": after, "source": "rustre_debug_macos::BreakpointManager" }).to_string())) } }

pub struct DebugMacosMachExceptionTypeAsU32Tool;
impl DebugMacosMachExceptionTypeAsU32Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_exception_type_as_u32".to_string(), description: "Round-trip a MachExceptionType through from_u32/as_u32.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type":"integer"} }, "required":["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachExceptionTypeAsU32Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let t = rustre_debug_macos::MachExceptionType::from_u32(v); Ok(ToolResult::text(json!({ "value": v, "name": t.name(), "as_u32": t.as_u32(), "is_typically_fatal": t.is_typically_fatal(), "source": "rustre_debug_macos::MachExceptionType::as_u32" }).to_string())) } }

pub struct DebugMacosMachVmProtectionToUnixStrTool;
impl DebugMacosMachVmProtectionToUnixStrTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_vm_protection_to_unix_str".to_string(), description: "Encode MachVmProtection bits to rwx string via to_unix_str.".to_string(), input_schema: json!({ "type": "object", "properties": { "bits": {"type":"integer"} }, "required":["bits"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachVmProtectionToUnixStrTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let b = args.get("bits").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'bits'".into()))? as u32; let p = rustre_debug_macos::MachVmProtection::from_raw(b); Ok(ToolResult::text(json!({ "bits": b, "unix_str": p.to_unix_str(), "as_raw": p.as_raw(), "source": "rustre_debug_macos::MachVmProtection::to_unix_str" }).to_string())) } }

pub struct DebugMacosMachVmRegionIsWritableTool;
impl DebugMacosMachVmRegionIsWritableTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_vm_region_is_writable".to_string(), description: "Report writable/executable flags of a MachVmRegion.".to_string(), input_schema: json!({ "type": "object", "properties": { "address": {"type":"integer"}, "size": {"type":"integer"}, "prot": {"type":"integer"} }, "required":["address","size","prot"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachVmRegionIsWritableTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("address").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'address'".into()))?; let size = args.get("size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'size'".into()))?; let prot = args.get("prot").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'prot'".into()))? as u32; let r = rustre_debug_macos::MachVmRegion { address: addr, size, protection: rustre_debug_macos::MachVmProtection::from_raw(prot), max_protection: rustre_debug_macos::MachVmProtection::from_raw(prot), name: String::new() }; Ok(ToolResult::text(json!({ "address": r.address, "end": r.end(), "is_writable": r.is_writable(), "is_executable": r.is_executable(), "source": "rustre_debug_macos::MachVmRegion::is_writable" }).to_string())) } }

pub struct DebugMacosVmRegionMapOpsTool;
impl DebugMacosVmRegionMapOpsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_vm_region_map_ops".to_string(), description: "Build a VmRegionMap from regions and report len/is_empty/total_size and lookup.".to_string(), input_schema: json!({ "type": "object", "properties": { "regions": {"type":"array"}, "query": {"type":"integer"} }, "required":["regions"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosVmRegionMapOpsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("regions").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'regions'".into()))?; let mut map = rustre_debug_macos::VmRegionMap::new(); for r in arr { let addr = r.get("address").and_then(Value::as_u64).unwrap_or(0); let size = r.get("size").and_then(Value::as_u64).unwrap_or(0); let prot = r.get("prot").and_then(Value::as_u64).unwrap_or(0) as u32; map.add(rustre_debug_macos::MachVmRegion { address: addr, size, protection: rustre_debug_macos::MachVmProtection::from_raw(prot), max_protection: rustre_debug_macos::MachVmProtection::from_raw(prot), name: String::new() }); } let q = args.get("query").and_then(Value::as_u64); let found = q.and_then(|q| map.find(q).map(|r| r.address)); Ok(ToolResult::text(json!({ "len": map.len(), "is_empty": map.is_empty(), "total_size": map.total_size(), "executable_count": map.executable_regions().len(), "writable_count": map.writable_regions().len(), "query": q, "found_address": found, "source": "rustre_debug_macos::VmRegionMap" }).to_string())) } }

pub struct DebugMacosDyldImageListFindTool;
impl DebugMacosDyldImageListFindTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_dyld_image_list_find".to_string(), description: "Populate a DyldImageList and query find_by_name/image_at.".to_string(), input_schema: json!({ "type": "object", "properties": { "images": {"type":"array"}, "name": {"type":"string"}, "addr": {"type":"integer"} } }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosDyldImageListFindTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("images").and_then(Value::as_array).cloned().unwrap_or_default(); let mut list = rustre_debug_macos::DyldImageList::default(); for i in arr { let load = i.get("load_address").and_then(Value::as_u64).unwrap_or(0); let path = i.get("path").and_then(Value::as_str).unwrap_or("").to_string(); let slide = i.get("slide").and_then(Value::as_i64).unwrap_or(0); list.images.push(rustre_debug_macos::DyldImage { load_address: load, path, slide }); } let name = args.get("name").and_then(Value::as_str); let addr = args.get("addr").and_then(Value::as_u64); let by_name = name.and_then(|n| list.find_by_name(n).map(|i| i.path.clone())); let at_addr = addr.and_then(|a| list.image_at(a).map(|i| i.path.clone())); Ok(ToolResult::text(json!({ "len": list.len(), "is_empty": list.is_empty(), "find_by_name": by_name, "image_at": at_addr, "source": "rustre_debug_macos::DyldImageList" }).to_string())) } }

pub struct DebugMacosMachoSectionContainsTool;
impl DebugMacosMachoSectionContainsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_macho_section_contains".to_string(), description: "Test whether an address falls inside a MachoSection via contains.".to_string(), input_schema: json!({ "type": "object", "properties": { "segment": {"type":"string"}, "section": {"type":"string"}, "addr": {"type":"integer"}, "size": {"type":"integer"}, "query": {"type":"integer"} }, "required":["segment","section","addr","size","query"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachoSectionContainsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let seg = args.get("segment").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'segment'".into()))?.to_string(); let sec = args.get("section").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'section'".into()))?.to_string(); let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let size = args.get("size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'size'".into()))?; let q = args.get("query").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'query'".into()))?; let s = rustre_debug_macos::MachoSection { segment: seg, section: sec, addr, size, offset: 0, flags: 0 }; Ok(ToolResult::text(json!({ "query": q, "contains": s.contains(q), "qualified_name": s.qualified_name(), "source": "rustre_debug_macos::MachoSection::contains" }).to_string())) } }

pub struct DebugMacosStopReasonAddressTool;
impl DebugMacosStopReasonAddressTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_stop_reason_address".to_string(), description: "Report MacosStopReason::address for a synthesized breakpoint/single-step/exception.".to_string(), input_schema: json!({ "type": "object", "properties": { "kind": {"type":"string"}, "address": {"type":"integer"}, "code": {"type":"integer"} }, "required":["kind"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosStopReasonAddressTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let kind = args.get("kind").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'kind'".into()))?; let addr = args.get("address").and_then(Value::as_u64).unwrap_or(0); let code = args.get("code").and_then(Value::as_u64).unwrap_or(0); let reason = match kind { "breakpoint" => rustre_debug_macos::MacosStopReason::Breakpoint { address: addr }, "single_step" => rustre_debug_macos::MacosStopReason::SingleStep { address: addr }, "exception" => rustre_debug_macos::MacosStopReason::Exception { exc_type: rustre_debug_macos::MachExceptionType::from_u32(1), code, subcode: 0 }, "exited" => rustre_debug_macos::MacosStopReason::Exited { exit_code: 0 }, _ => return Err(McpError::InvalidParams(format!("unknown kind '{kind}'"))) }; Ok(ToolResult::text(json!({ "kind": kind, "address": reason.address(), "is_exit": reason.is_exit(), "source": "rustre_debug_macos::MacosStopReason::address" }).to_string())) } }

pub struct DebugMacosProcessTableEnumerateTool;
impl DebugMacosProcessTableEnumerateTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_process_table_enumerate".to_string(), description: "Build a MacOsProcessEnumerator, add simulated entries, then enumerate/filter/lookup.".to_string(), input_schema: json!({ "type": "object", "properties": { "entries": {"type":"array"}, "filter": {"type":"string"}, "find_pid": {"type":"integer"}, "find_name": {"type":"string"} }, "required":["entries"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosProcessTableEnumerateTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("entries").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'entries'".into()))?; let mut e = rustre_debug_macos::MacOsProcessEnumerator::new(); for p in arr { let pid = p.get("pid").and_then(Value::as_u64).unwrap_or(0) as u32; let ppid = p.get("ppid").and_then(Value::as_u64).unwrap_or(0) as u32; let name = p.get("name").and_then(Value::as_str).unwrap_or("").to_string(); e.add_simulated(rustre_debug_macos::MacOsProcessEntry::new(pid, ppid, name)); } let all = e.enumerate(); let filt = args.get("filter").and_then(Value::as_str).map(|f| e.enumerate_filtered(f).len()); let by_pid = args.get("find_pid").and_then(Value::as_u64).and_then(|p| e.find_by_pid(p as u32).map(|x| x.name)); let by_name = args.get("find_name").and_then(Value::as_str).and_then(|n| e.find_by_name(n).map(|x| x.pid)); Ok(ToolResult::text(json!({ "count": all.len(), "filtered_count": filt, "find_by_pid_name": by_pid, "find_by_name_pid": by_name, "source": "rustre_debug_macos::MacOsProcessEnumerator" }).to_string())) } }

pub struct DebugMacosFatHeaderSliceForTool;
impl DebugMacosFatHeaderSliceForTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_fat_header_slice_for".to_string(), description: "Parse a FAT header then select a slice via FatHeader::slice_for.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type":"string"}, "bytes": {"type":"array"}, "cpu_type": {"type":"integer"} }, "required":["cpu_type"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosFatHeaderSliceForTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; let cpu_raw = args.get("cpu_type").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'cpu_type'".into()))? as u32; let cpu = rustre_debug_macos::CpuType::from_u32(cpu_raw); let h = rustre_debug_macos::FatHeader::parse(&data); let slice = h.as_ref().and_then(|h| h.slice_for(cpu)).map(|a| json!({ "cpu_type": a.cpu_type.name(), "offset": a.offset, "size": a.size, "align": a.align })); Ok(ToolResult::text(json!({ "parsed": h.is_some(), "cpu_type_query": cpu.name(), "slice": slice, "source": "rustre_debug_macos::FatHeader::slice_for" }).to_string())) } }

pub struct DebugMacosThreadListOpsTool;
impl DebugMacosThreadListOpsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_thread_list_ops".to_string(), description: "Populate a MacosThreadList and query len/is_empty/find/stopped_tids.".to_string(), input_schema: json!({ "type": "object", "properties": { "threads": {"type":"array"}, "find_tid": {"type":"integer"} }, "required":["threads"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosThreadListOpsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("threads").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'threads'".into()))?; let mut list = rustre_debug_macos::MacosThreadList::new(); for t in arr { let tid = t.get("tid").and_then(Value::as_u64).unwrap_or(0) as u32; let port = t.get("port").and_then(Value::as_u64).unwrap_or(0) as u32; let is_stopped = t.get("is_stopped").and_then(Value::as_bool).unwrap_or(false); let name = t.get("name").and_then(Value::as_str).map(String::from); list.add(rustre_debug_macos::MacosThreadInfo { tid, port, is_stopped, name }); } let find = args.get("find_tid").and_then(Value::as_u64).and_then(|t| list.find(t as u32).map(|i| i.port)); Ok(ToolResult::text(json!({ "len": list.len(), "is_empty": list.is_empty(), "stopped_tids": list.stopped_tids(), "found_port": find, "source": "rustre_debug_macos::MacosThreadList" }).to_string())) } }

pub struct DebugMacosMachExceptionTypeFromU32Tool;
impl DebugMacosMachExceptionTypeFromU32Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_exception_type_from_u32".to_string(), description: "Decode via rustre_debug_macos::MachExceptionType::from_u32.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type":"integer"} }, "required":["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachExceptionTypeFromU32Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let t = rustre_debug_macos::MachExceptionType::from_u32(v); Ok(ToolResult::text(json!({ "value": v, "name": t.name(), "as_u32": t.as_u32(), "is_typically_fatal": t.is_typically_fatal(), "source": "rustre_debug_macos::MachExceptionType::from_u32" }).to_string())) } }

pub struct DebugMacosMachExceptionTypeIsFatalTool;
impl DebugMacosMachExceptionTypeIsFatalTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_exception_type_is_fatal".to_string(), description: "rustre_debug_macos::MachExceptionType::is_typically_fatal.".to_string(), input_schema: json!({ "type": "object", "properties": { "value": {"type":"integer"} }, "required":["value"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachExceptionTypeIsFatalTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("value").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'value'".into()))? as u32; let t = rustre_debug_macos::MachExceptionType::from_u32(v); Ok(ToolResult::text(json!({ "value": v, "is_typically_fatal": t.is_typically_fatal(), "source": "rustre_debug_macos::MachExceptionType::is_typically_fatal" }).to_string())) } }

pub struct DebugMacosMachVmProtectionAsRawTool;
impl DebugMacosMachVmProtectionAsRawTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_vm_protection_as_raw".to_string(), description: "Encode read/write/execute bools to raw bits via rustre_debug_macos::MachVmProtection::as_raw.".to_string(), input_schema: json!({ "type": "object", "properties": { "read": {"type":"boolean"}, "write": {"type":"boolean"}, "execute": {"type":"boolean"} } }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachVmProtectionAsRawTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let r = args.get("read").and_then(Value::as_bool).unwrap_or(false); let w = args.get("write").and_then(Value::as_bool).unwrap_or(false); let x = args.get("execute").and_then(Value::as_bool).unwrap_or(false); let p = rustre_debug_macos::MachVmProtection { read: r, write: w, execute: x }; Ok(ToolResult::text(json!({ "raw": p.as_raw(), "unix": p.to_unix_str(), "source": "rustre_debug_macos::MachVmProtection::as_raw" }).to_string())) } }

pub struct DebugMacosMachVmRegionEndTool;
impl DebugMacosMachVmRegionEndTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mach_vm_region_end".to_string(), description: "End address of a Mach VM region via rustre_debug_macos::MachVmRegion::end.".to_string(), input_schema: json!({ "type": "object", "properties": { "address": {"type":"integer"}, "size": {"type":"integer"} }, "required":["address","size"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachVmRegionEndTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = args.get("address").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'address'".into()))?; let s = args.get("size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'size'".into()))?; let r = rustre_debug_macos::MachVmRegion { address: a, size: s, protection: rustre_debug_macos::MachVmProtection::default(), max_protection: rustre_debug_macos::MachVmProtection::default(), name: String::new() }; Ok(ToolResult::text(json!({ "address": a, "size": s, "end": r.end(), "is_writable": r.is_writable(), "is_executable": r.is_executable(), "source": "rustre_debug_macos::MachVmRegion::end" }).to_string())) } }

pub struct DebugMacosDyldImageNameTool;
impl DebugMacosDyldImageNameTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_dyld_image_name".to_string(), description: "Basename of a DyldImage via rustre_debug_macos::DyldImage::name.".to_string(), input_schema: json!({ "type": "object", "properties": { "path": {"type":"string"}, "load_address": {"type":"integer"}, "slide": {"type":"integer"} }, "required":["path"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosDyldImageNameTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let path = args.get("path").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'path'".into()))?.to_string(); let load_address = args.get("load_address").and_then(Value::as_u64).unwrap_or(0); let slide = args.get("slide").and_then(Value::as_i64).unwrap_or(0); let img = rustre_debug_macos::DyldImage { load_address, path: path.clone(), slide }; Ok(ToolResult::text(json!({ "path": path, "name": img.name(), "source": "rustre_debug_macos::DyldImage::name" }).to_string())) } }

pub struct DebugMacosMachoSectionIsCodeTool;
impl DebugMacosMachoSectionIsCodeTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_macho_section_is_code".to_string(), description: "Detect the __TEXT.__text section via rustre_debug_macos::MachoSection::is_code.".to_string(), input_schema: json!({ "type": "object", "properties": { "segment": {"type":"string"}, "section": {"type":"string"}, "addr": {"type":"integer"}, "size": {"type":"integer"} }, "required":["segment","section"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMachoSectionIsCodeTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let segment = args.get("segment").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'segment'".into()))?.to_string(); let section = args.get("section").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'section'".into()))?.to_string(); let addr = args.get("addr").and_then(Value::as_u64).unwrap_or(0); let size = args.get("size").and_then(Value::as_u64).unwrap_or(0); let s = rustre_debug_macos::MachoSection { segment: segment.clone(), section: section.clone(), addr, size, offset: 0, flags: 0 }; Ok(ToolResult::text(json!({ "qualified_name": s.qualified_name(), "is_code": s.is_code(), "source": "rustre_debug_macos::MachoSection::is_code" }).to_string())) } }

pub struct DebugMacosTaskInfoResidentRatioTool;
impl DebugMacosTaskInfoResidentRatioTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_task_info_resident_ratio".to_string(), description: "Compute rustre_debug_macos::TaskInfo::resident_ratio.".to_string(), input_schema: json!({ "type": "object", "properties": { "virtual_size": {"type":"integer"}, "resident_size": {"type":"integer"} }, "required":["virtual_size","resident_size"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosTaskInfoResidentRatioTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let v = args.get("virtual_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'virtual_size'".into()))?; let r = args.get("resident_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'resident_size'".into()))?; let ti = rustre_debug_macos::TaskInfo { virtual_size: v, resident_size: r, ..Default::default() }; Ok(ToolResult::text(json!({ "virtual_size": v, "resident_size": r, "ratio": ti.resident_ratio(), "source": "rustre_debug_macos::TaskInfo::resident_ratio" }).to_string())) } }

pub struct DebugMacosStopReasonIsExitTool;
impl DebugMacosStopReasonIsExitTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_stop_reason_is_exit".to_string(), description: "Classify a synthetic MacosStopReason via rustre_debug_macos::MacosStopReason.".to_string(), input_schema: json!({ "type": "object", "properties": { "kind": {"type":"string"}, "value": {"type":"integer"} }, "required":["kind"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosStopReasonIsExitTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let kind = args.get("kind").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'kind'".into()))?; let v = args.get("value").and_then(Value::as_i64).unwrap_or(0); let r = match kind { "exited" => rustre_debug_macos::MacosStopReason::Exited { exit_code: v as i32 }, "single_step" => rustre_debug_macos::MacosStopReason::SingleStep { address: v as u64 }, "breakpoint" => rustre_debug_macos::MacosStopReason::Breakpoint { address: v as u64 }, "signal" => rustre_debug_macos::MacosStopReason::Signal { signal: v as i32 }, other => return Err(McpError::InvalidParams(format!("unknown kind: {other}"))) }; Ok(ToolResult::text(json!({ "kind": kind, "is_exit": r.is_exit(), "address": r.address(), "source": "rustre_debug_macos::MacosStopReason" }).to_string())) } }

pub struct DebugMacosArm64HwBpEncodeTool;
impl DebugMacosArm64HwBpEncodeTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_arm64_hw_bp_encode".to_string(), description: "Encode ARM64 hardware breakpoint via rustre_debug_macos::ArmDebugState64::enable_breakpoint.".to_string(), input_schema: json!({ "type": "object", "properties": { "slot": {"type":"integer"}, "address": {"type":"integer"} }, "required":["slot","address"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosArm64HwBpEncodeTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let slot = args.get("slot").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'slot'".into()))? as usize; if slot >= rustre_debug_macos::ARM64_HW_BP_MAX { return Err(McpError::InvalidParams(format!("slot {slot} >= ARM64_HW_BP_MAX"))); } let address = args.get("address").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'address'".into()))?; let mut s = rustre_debug_macos::ArmDebugState64::default(); s.enable_breakpoint(slot, address); Ok(ToolResult::text(json!({ "slot": slot, "bvr": s.bvr[slot], "bcr": s.bcr[slot], "enabled": s.is_breakpoint_enabled(slot), "source": "rustre_debug_macos::ArmDebugState64::enable_breakpoint" }).to_string())) } }

pub struct DebugMacosDsymLocatorNameForTool;
impl DebugMacosDsymLocatorNameForTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_dsym_locator_name_for".to_string(), description: "Derive the .dSYM bundle name via rustre_debug_macos::DsymLocator::dsym_name_for.".to_string(), input_schema: json!({ "type": "object", "properties": { "executable": {"type":"string"} }, "required":["executable"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosDsymLocatorNameForTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let exe = args.get("executable").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'executable'".into()))?; Ok(ToolResult::text(json!({ "executable": exe, "dsym_name": rustre_debug_macos::DsymLocator::dsym_name_for(exe), "source": "rustre_debug_macos::DsymLocator::dsym_name_for" }).to_string())) } }

pub struct DebugMacosDsymLocatorCandidatesTool;
impl DebugMacosDsymLocatorCandidatesTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_dsym_locator_candidates".to_string(), description: "Enumerate candidate .dSYM paths via rustre_debug_macos::DsymLocator::candidates.".to_string(), input_schema: json!({ "type": "object", "properties": { "executable": {"type":"string"}, "search_paths": {"type":"array"} }, "required":["executable"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosDsymLocatorCandidatesTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let exe = args.get("executable").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'executable'".into()))?.to_string(); let paths: Vec<String> = args.get("search_paths").and_then(Value::as_array).map(|arr| arr.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect()).unwrap_or_default(); let mut loc = rustre_debug_macos::DsymLocator::new(); for p in &paths { loc.add_search_path(p.clone()); } let cands = loc.candidates(&exe); Ok(ToolResult::text(json!({ "executable": exe, "candidates": cands, "source": "rustre_debug_macos::DsymLocator::candidates" }).to_string())) } }

pub struct DebugMacosMacMemPermFromUnixStrTool;
impl DebugMacosMacMemPermFromUnixStrTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_mac_mem_perm_from_unix_str".to_string(), description: "Parse rwx permissions via rustre_debug_macos::MacMemoryPermissions::from_unix_str.".to_string(), input_schema: json!({ "type": "object", "properties": { "s": {"type":"string"} }, "required":["s"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosMacMemPermFromUnixStrTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let s = args.get("s").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 's'".into()))?; let p = rustre_debug_macos::MacMemoryPermissions::from_unix_str(s); Ok(ToolResult::text(json!({ "s": s, "parsed": p.map(|p| json!({ "readable": p.readable, "writable": p.writable, "executable": p.executable, "roundtrip": p.to_unix_str() })), "source": "rustre_debug_macos::MacMemoryPermissions::from_unix_str" }).to_string())) } }

pub struct DebugMacosUuidRecordCanonicalTool;
impl DebugMacosUuidRecordCanonicalTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_uuid_record_canonical".to_string(), description: "Format a 16-byte UUID via rustre_debug_macos::UuidRecord::to_string_canonical.".to_string(), input_schema: json!({ "type": "object", "properties": { "hex": {"type":"string"}, "bytes": {"type":"array"} } }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosUuidRecordCanonicalTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let data = args_to_bytes(&args)?; if data.len() != 16 { return Err(McpError::InvalidParams(format!("expected 16 bytes, got {}", data.len()))); } let mut b = [0u8; 16]; b.copy_from_slice(&data); let u = rustre_debug_macos::UuidRecord::from_bytes(b); Ok(ToolResult::text(json!({ "canonical": u.to_string_canonical(), "is_zero": u.is_zero(), "source": "rustre_debug_macos::UuidRecord::to_string_canonical" }).to_string())) } }

pub struct DebugMacosThreadListStoppedTidsTool;
impl DebugMacosThreadListStoppedTidsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_thread_list_stopped_tids".to_string(), description: "Filter stopped tids via rustre_debug_macos::MacosThreadList::stopped_tids.".to_string(), input_schema: json!({ "type": "object", "properties": { "threads": {"type":"array"} }, "required":["threads"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosThreadListStoppedTidsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("threads").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'threads'".into()))?; let mut list = rustre_debug_macos::MacosThreadList::new(); for v in arr { let tid = v.get("tid").and_then(Value::as_u64).unwrap_or(0) as u32; let port = v.get("port").and_then(Value::as_u64).unwrap_or(0) as u32; let is_stopped = v.get("is_stopped").and_then(Value::as_bool).unwrap_or(false); let name = v.get("name").and_then(Value::as_str).map(|s| s.to_string()); list.add(rustre_debug_macos::MacosThreadInfo { tid, port, is_stopped, name }); } Ok(ToolResult::text(json!({ "len": list.len(), "stopped_tids": list.stopped_tids(), "source": "rustre_debug_macos::MacosThreadList::stopped_tids" }).to_string())) } }

pub struct DebugMacosVmRegionMapTotalsTool;
impl DebugMacosVmRegionMapTotalsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "debug_macos_vm_region_map_totals".to_string(), description: "Aggregate stats via rustre_debug_macos::VmRegionMap.".to_string(), input_schema: json!({ "type": "object", "properties": { "regions": {"type":"array"} }, "required":["regions"] }), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DebugMacosVmRegionMapTotalsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("regions").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'regions'".into()))?; let mut m = rustre_debug_macos::VmRegionMap::new(); for v in arr { let address = v.get("address").and_then(Value::as_u64).unwrap_or(0); let size = v.get("size").and_then(Value::as_u64).unwrap_or(0); let prot_bits = v.get("prot").and_then(Value::as_u64).unwrap_or(0) as u32; let prot = rustre_debug_macos::MachVmProtection::from_raw(prot_bits); m.add(rustre_debug_macos::MachVmRegion { address, size, protection: prot, max_protection: prot, name: String::new() }); } Ok(ToolResult::text(json!({ "len": m.len(), "total_size": m.total_size(), "executable_count": m.executable_regions().len(), "writable_count": m.writable_regions().len(), "source": "rustre_debug_macos::VmRegionMap" }).to_string())) } }

pub fn handlers() -> Vec<(ToolDefinition, Box<dyn ToolHandler>)> {
    vec![
        (DebugMacosBreakpointManagerBuildTool::definition(), Box::new(DebugMacosBreakpointManagerBuildTool)),
        (DebugMacosProcessDescribeTool::definition(), Box::new(DebugMacosProcessDescribeTool)),
        (DebugMacosX86RegisterIndexTool::definition(), Box::new(DebugMacosX86RegisterIndexTool)),
        (DebugMacosArm64RegisterIndexTool::definition(), Box::new(DebugMacosArm64RegisterIndexTool)),
        (DebugMacosMachoHeaderParseTool::definition(), Box::new(DebugMacosMachoHeaderParseTool)),
        (DebugMacosCpuTypeFromU32Tool::definition(), Box::new(DebugMacosCpuTypeFromU32Tool)),
        (DebugMacosMachoFileTypeFromU32Tool::definition(), Box::new(DebugMacosMachoFileTypeFromU32Tool)),
        (DebugMacosFormatMachoVersionTool::definition(), Box::new(DebugMacosFormatMachoVersionTool)),
        (DebugMacosFormatUuidTool::definition(), Box::new(DebugMacosFormatUuidTool)),
        (DebugMacosMachExceptionFromU32Tool::definition(), Box::new(DebugMacosMachExceptionFromU32Tool)),
        (DebugMacosVmProtDecodeTool::definition(), Box::new(DebugMacosVmProtDecodeTool)),
        (DebugMacosMachVmProtectionDecodeTool::definition(), Box::new(DebugMacosMachVmProtectionDecodeTool)),
        (DebugMacosSimulateX8664RegistersTool::definition(), Box::new(DebugMacosSimulateX8664RegistersTool)),
        (DebugMacosSimulateArm64RegistersTool::definition(), Box::new(DebugMacosSimulateArm64RegistersTool)),
        (DebugMacosDyldImageRebasedTool::definition(), Box::new(DebugMacosDyldImageRebasedTool)),
        (DebugMacosMachoSectionQualifiedNameTool::definition(), Box::new(DebugMacosMachoSectionQualifiedNameTool)),
        (DebugMacosFatHeaderParseTool::definition(), Box::new(DebugMacosFatHeaderParseTool)),
        (DebugMacosParseLoadCommandsTool::definition(), Box::new(DebugMacosParseLoadCommandsTool)),
        (DebugMacosExtractDylibsTool::definition(), Box::new(DebugMacosExtractDylibsTool)),
        (DebugMacosExtractUuidTool::definition(), Box::new(DebugMacosExtractUuidTool)),
        (DebugMacosMachExceptionToSignalTool::definition(), Box::new(DebugMacosMachExceptionToSignalTool)),
        (DebugMacosVmRegionDescribeTool::definition(), Box::new(DebugMacosVmRegionDescribeTool)),
        (DebugMacosVmRegionContainsTool::definition(), Box::new(DebugMacosVmRegionContainsTool)),
        (DebugMacosBreakpointManagerRoundTripTool::definition(), Box::new(DebugMacosBreakpointManagerRoundTripTool)),
        (DebugMacosMachExceptionTypeAsU32Tool::definition(), Box::new(DebugMacosMachExceptionTypeAsU32Tool)),
        (DebugMacosMachVmProtectionToUnixStrTool::definition(), Box::new(DebugMacosMachVmProtectionToUnixStrTool)),
        (DebugMacosMachVmRegionIsWritableTool::definition(), Box::new(DebugMacosMachVmRegionIsWritableTool)),
        (DebugMacosVmRegionMapOpsTool::definition(), Box::new(DebugMacosVmRegionMapOpsTool)),
        (DebugMacosDyldImageListFindTool::definition(), Box::new(DebugMacosDyldImageListFindTool)),
        (DebugMacosMachoSectionContainsTool::definition(), Box::new(DebugMacosMachoSectionContainsTool)),
        (DebugMacosStopReasonAddressTool::definition(), Box::new(DebugMacosStopReasonAddressTool)),
        (DebugMacosProcessTableEnumerateTool::definition(), Box::new(DebugMacosProcessTableEnumerateTool)),
        (DebugMacosFatHeaderSliceForTool::definition(), Box::new(DebugMacosFatHeaderSliceForTool)),
        (DebugMacosThreadListOpsTool::definition(), Box::new(DebugMacosThreadListOpsTool)),
        (DebugMacosMachExceptionTypeFromU32Tool::definition(), Box::new(DebugMacosMachExceptionTypeFromU32Tool)),
        (DebugMacosMachExceptionTypeIsFatalTool::definition(), Box::new(DebugMacosMachExceptionTypeIsFatalTool)),
        (DebugMacosMachVmProtectionAsRawTool::definition(), Box::new(DebugMacosMachVmProtectionAsRawTool)),
        (DebugMacosMachVmRegionEndTool::definition(), Box::new(DebugMacosMachVmRegionEndTool)),
        (DebugMacosDyldImageNameTool::definition(), Box::new(DebugMacosDyldImageNameTool)),
        (DebugMacosMachoSectionIsCodeTool::definition(), Box::new(DebugMacosMachoSectionIsCodeTool)),
        (DebugMacosTaskInfoResidentRatioTool::definition(), Box::new(DebugMacosTaskInfoResidentRatioTool)),
        (DebugMacosStopReasonIsExitTool::definition(), Box::new(DebugMacosStopReasonIsExitTool)),
        (DebugMacosArm64HwBpEncodeTool::definition(), Box::new(DebugMacosArm64HwBpEncodeTool)),
        (DebugMacosDsymLocatorNameForTool::definition(), Box::new(DebugMacosDsymLocatorNameForTool)),
        (DebugMacosDsymLocatorCandidatesTool::definition(), Box::new(DebugMacosDsymLocatorCandidatesTool)),
        (DebugMacosMacMemPermFromUnixStrTool::definition(), Box::new(DebugMacosMacMemPermFromUnixStrTool)),
        (DebugMacosUuidRecordCanonicalTool::definition(), Box::new(DebugMacosUuidRecordCanonicalTool)),
        (DebugMacosThreadListStoppedTidsTool::definition(), Box::new(DebugMacosThreadListStoppedTidsTool)),
        (DebugMacosVmRegionMapTotalsTool::definition(), Box::new(DebugMacosVmRegionMapTotalsTool)),
    ]
}
