//! MCP wrappers for the rustre-dt crate.
//! Extracted from `wire_tools.rs` by `workflow_split_wire_tools`.

use rustre_mcp_server::{McpError, ToolDefinition, ToolHandler, ToolResult};
use serde_json::{json, Value};
use async_trait::async_trait;
use crate::wire_tools::{__decomp_parse_int_width};

pub struct DtIsPointerVoidTool;
impl DtIsPointerVoidTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_is_pointer_void_n2".to_string(), description: "Check is_pointer() on DecompType::Ptr(void).".to_string(), input_schema: json!({"type":"object","properties":{}}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtIsPointerVoidTool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { let t = rustre_decompiler_type::DecompType::Ptr(Box::new(rustre_decompiler_type::DecompType::Void)); Ok(ToolResult::text(json!({"is_pointer": t.is_pointer(), "source":"rustre_decompiler_type::DecompType::is_pointer"}).to_string())) } }

pub struct DtPointeeCnameTool;
impl DtPointeeCnameTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_pointee_c_name_n2".to_string(), description: "Return pointee c_name for Ptr(Int(width)).".to_string(), input_schema: json!({"type":"object","properties":{"width":{"type":"string"}},"required":["width"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtPointeeCnameTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ws = args.get("width").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'width'".into()))?; let w = __decomp_parse_int_width(ws).ok_or_else(|| McpError::InvalidParams("bad width".into()))?; let t = rustre_decompiler_type::DecompType::Ptr(Box::new(rustre_decompiler_type::DecompType::Int(w))); let p = t.pointee().map(|x| x.c_name()); Ok(ToolResult::text(json!({"pointee_c_name": p, "source":"rustre_decompiler_type::DecompType::pointee"}).to_string())) } }

pub struct DtNamePrefixIntTool;
impl DtNamePrefixIntTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_name_prefix_int_n2".to_string(), description: "Return name_prefix() for Int(width).".to_string(), input_schema: json!({"type":"object","properties":{"width":{"type":"string"}},"required":["width"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtNamePrefixIntTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ws = args.get("width").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'width'".into()))?; let w = __decomp_parse_int_width(ws).ok_or_else(|| McpError::InvalidParams("bad width".into()))?; let t = rustre_decompiler_type::DecompType::Int(w); Ok(ToolResult::text(json!({"prefix": t.name_prefix(), "source":"rustre_decompiler_type::DecompType::name_prefix"}).to_string())) } }

pub struct DtStructFieldExactTool;
impl DtStructFieldExactTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_struct_field_exact_n2".to_string(), description: "Build a struct with two int fields and query field_exact(offset).".to_string(), input_schema: json!({"type":"object","properties":{"offset":{"type":"integer"}},"required":["offset"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtStructFieldExactTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let off = args.get("offset").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'offset'".into()))?; use rustre_decompiler_type::{StructField, StructType, DecompType}; use rustre_decompiler_expr::IntWidth; let st = StructType::new("S", vec![StructField::new(0,"a",DecompType::Int(IntWidth::I32)), StructField::new(4,"b",DecompType::Int(IntWidth::I32))], 8); Ok(ToolResult::text(json!({"field_exact": st.field_exact(off).map(|f| f.name.clone()), "source":"rustre_decompiler_type::StructType::field_exact"}).to_string())) } }

pub struct DtFunctionArityTool;
impl DtFunctionArityTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_function_arity_n2".to_string(), description: "Return arity of a FunctionType with N int params.".to_string(), input_schema: json!({"type":"object","properties":{"n":{"type":"integer"}},"required":["n"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtFunctionArityTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let n = args.get("n").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'n'".into()))? as usize; use rustre_decompiler_type::{FunctionType, DecompType}; use rustre_decompiler_expr::IntWidth; let mut f = FunctionType::new("fn0", DecompType::Void); for i in 0..n { f.add_param(format!("p{i}"), DecompType::Int(IntWidth::I32)); } Ok(ToolResult::text(json!({"arity": f.arity(), "prototype": f.c_prototype(), "source":"rustre_decompiler_type::FunctionType::arity"}).to_string())) } }

pub struct DtQualifierStringTool;
impl DtQualifierStringTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_qualifier_string_n2".to_string(), description: "Compose TypeQualifier flags and return qualifier_string().".to_string(), input_schema: json!({"type":"object","properties":{"const_":{"type":"boolean"},"volatile":{"type":"boolean"},"restrict":{"type":"boolean"}}}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtQualifierStringTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let mut q = rustre_decompiler_type::TypeQualifier::NONE; if args.get("const_").and_then(Value::as_bool).unwrap_or(false) { q = q.with_const(); } if args.get("volatile").and_then(Value::as_bool).unwrap_or(false) { q = q.with_volatile(); } if args.get("restrict").and_then(Value::as_bool).unwrap_or(false) { q = q.with_restrict(); } Ok(ToolResult::text(json!({"qualifier": q.qualifier_string(), "is_const": q.is_const(), "is_volatile": q.is_volatile(), "is_restrict": q.is_restrict(), "source":"rustre_decompiler_type::TypeQualifier::qualifier_string"}).to_string())) } }

pub struct DtQualifiedTypeCnameTool;
impl DtQualifiedTypeCnameTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_qualified_c_name_n2".to_string(), description: "QualifiedType::new(Int(width)).with_qualifiers(CONST).c_name().".to_string(), input_schema: json!({"type":"object","properties":{"width":{"type":"string"}},"required":["width"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtQualifiedTypeCnameTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ws = args.get("width").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'width'".into()))?; let w = __decomp_parse_int_width(ws).ok_or_else(|| McpError::InvalidParams("bad width".into()))?; let qt = rustre_decompiler_type::QualifiedType::new(rustre_decompiler_type::DecompType::Int(w)).with_qualifiers(rustre_decompiler_type::TypeQualifier::NONE.with_const()); Ok(ToolResult::text(json!({"c_name": qt.c_name(), "source":"rustre_decompiler_type::QualifiedType::c_name"}).to_string())) } }

pub struct DtTypeLayoutForStructTool;
impl DtTypeLayoutForStructTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_layout_for_struct_n2".to_string(), description: "Compute TypeLayout::for_struct on a simple 2-int struct and return size/alignment/padded_size.".to_string(), input_schema: json!({"type":"object","properties":{"total_size":{"type":"integer"}},"required":["total_size"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtTypeLayoutForStructTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ts = args.get("total_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'total_size'".into()))?; use rustre_decompiler_type::{StructField, StructType, DecompType, TypeLayout}; use rustre_decompiler_expr::IntWidth; let st = StructType::new("S", vec![StructField::new(0,"a",DecompType::Int(IntWidth::I32)), StructField::new(4,"b",DecompType::Int(IntWidth::I32))], ts); let l = TypeLayout::for_struct(&st); Ok(ToolResult::text(json!({"size": l.size, "alignment": l.alignment, "padded_size": l.padded_size(), "source":"rustre_decompiler_type::TypeLayout::for_struct"}).to_string())) } }

pub struct DtUnionMemberNamedTool;
impl DtUnionMemberNamedTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_union_member_named_n2".to_string(), description: "UnionType lookup member by name; returns member offset if found.".to_string(), input_schema: json!({"type":"object","properties":{"member":{"type":"string"}},"required":["member"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtUnionMemberNamedTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("member").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'member'".into()))?; use rustre_decompiler_type::{StructField, UnionType, DecompType}; use rustre_decompiler_expr::IntWidth; let u = UnionType::new("U", vec![StructField::new(0,"a",DecompType::Int(IntWidth::I32)), StructField::new(0,"b",DecompType::Int(IntWidth::I64))]); Ok(ToolResult::text(json!({"found": u.member_named(name).map(|f| f.offset), "source":"rustre_decompiler_type::UnionType::member_named"}).to_string())) } }

pub struct DtTypeDatabaseResolveTypedefTool;
impl DtTypeDatabaseResolveTypedefTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_database_resolve_typedef_n2".to_string(), description: "TypeDatabase: add_typedef then resolve_typedef; returns c_name of resolved type.".to_string(), input_schema: json!({"type":"object","properties":{"alias":{"type":"string"},"width":{"type":"string"}},"required":["alias","width"]}), parameters: Value::Null } } }
#[async_trait]
impl ToolHandler for DtTypeDatabaseResolveTypedefTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let alias = args.get("alias").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'alias'".into()))?.to_string(); let ws = args.get("width").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'width'".into()))?; let w = __decomp_parse_int_width(ws).ok_or_else(|| McpError::InvalidParams("bad width".into()))?; let mut db = rustre_decompiler_type::TypeDatabase::new(); db.add_typedef(alias.clone(), rustre_decompiler_type::DecompType::Int(w)); Ok(ToolResult::text(json!({"resolved_c_name": db.resolve_typedef(&alias).map(|t| t.c_name()), "typedef_count": db.typedef_count(), "source":"rustre_decompiler_type::TypeDatabase::resolve_typedef"}).to_string())) } }

pub struct DtZ1ResolveStructTool;
impl DtZ1ResolveStructTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_env_resolve_struct_z1".to_string(), description: "TypeEnvironment: add_struct then resolve_struct on a named-struct type.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1ResolveStructTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?.to_string(); use rustre_decompiler_type::{StructField, StructType, DecompType, TypeEnvironment}; use rustre_decompiler_expr::IntWidth; let st = StructType::new(name.clone(), vec![StructField::new(0, "a", DecompType::Int(IntWidth::I32))], 4); let mut env = TypeEnvironment::new(); env.add_struct(st.clone()); let ty = DecompType::Struct(Box::new(st)); let resolved = env.resolve_struct(&ty).map(|s| s.name.clone()); let by_name = env.struct_named(&name).map(|s| s.total_size); Ok(ToolResult::text(json!({"name": name, "resolved": resolved, "size": by_name, "source":"rustre_decompiler_type::TypeEnvironment::resolve_struct"}).to_string())) } }

pub struct DtZ1TypeDatabaseGetStructTool;
impl DtZ1TypeDatabaseGetStructTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_database_get_struct_z1".to_string(), description: "TypeDatabase::add_struct then get_struct.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1TypeDatabaseGetStructTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?.to_string(); use rustre_decompiler_type::{StructField, StructType, DecompType, TypeDatabase}; use rustre_decompiler_expr::IntWidth; let st = StructType::new(name.clone(), vec![StructField::new(0, "f0", DecompType::Int(IntWidth::I32))], 4); let mut db = TypeDatabase::new(); db.add_struct(st); let got = db.get_struct(&name).map(|s| s.total_size); Ok(ToolResult::text(json!({"name": name, "size": got, "count": db.struct_count(), "source":"rustre_decompiler_type::TypeDatabase::get_struct"}).to_string())) } }

pub struct DtZ1TypeDatabaseGetUnionTool;
impl DtZ1TypeDatabaseGetUnionTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_database_get_union_z1".to_string(), description: "TypeDatabase::add_union then get_union.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1TypeDatabaseGetUnionTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?.to_string(); use rustre_decompiler_type::{StructField, UnionType, DecompType, TypeDatabase}; use rustre_decompiler_expr::IntWidth; let u = UnionType::new(name.clone(), vec![StructField::new(0, "a", DecompType::Int(IntWidth::I32)), StructField::new(0, "b", DecompType::Int(IntWidth::I64))]); let mut db = TypeDatabase::new(); db.add_union(u); let got = db.get_union(&name).map(|x| x.total_size); Ok(ToolResult::text(json!({"name": name, "total_size": got, "count": db.union_count(), "source":"rustre_decompiler_type::TypeDatabase::get_union"}).to_string())) } }

pub struct DtZ1TypeDatabaseGetFunctionTool;
impl DtZ1TypeDatabaseGetFunctionTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_database_get_function_z1".to_string(), description: "TypeDatabase::add_function then get_function; returns c_prototype.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1TypeDatabaseGetFunctionTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?.to_string(); use rustre_decompiler_type::{FunctionType, DecompType, TypeDatabase}; use rustre_decompiler_expr::IntWidth; let mut f = FunctionType::new(name.clone(), DecompType::Int(IntWidth::I32)); f.add_param("x", DecompType::Int(IntWidth::I32)); let mut db = TypeDatabase::new(); db.add_function(f); let proto = db.get_function(&name).map(|x| x.c_prototype()); Ok(ToolResult::text(json!({"name": name, "prototype": proto, "count": db.function_count(), "source":"rustre_decompiler_type::TypeDatabase::get_function"}).to_string())) } }

pub struct DtZ1CtypeEmitStructTool;
impl DtZ1CtypeEmitStructTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_ctype_emit_struct_z1".to_string(), description: "CTypeEmitter::emit_struct on a simple 2-field struct.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1CtypeEmitStructTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?.to_string(); use rustre_decompiler_type::{StructField, StructType, DecompType, CTypeEmitter}; use rustre_decompiler_expr::IntWidth; let st = StructType::new(name, vec![StructField::new(0, "a", DecompType::Int(IntWidth::I32)), StructField::new(4, "b", DecompType::Int(IntWidth::I32))], 8); let em = CTypeEmitter::new(); Ok(ToolResult::text(json!({"code": em.emit_struct(&st), "source":"rustre_decompiler_type::CTypeEmitter::emit_struct"}).to_string())) } }

pub struct DtZ1CtypeEmitUnionTool;
impl DtZ1CtypeEmitUnionTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_ctype_emit_union_z1".to_string(), description: "CTypeEmitter::emit_union on a simple union.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1CtypeEmitUnionTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?.to_string(); use rustre_decompiler_type::{StructField, UnionType, DecompType, CTypeEmitter}; use rustre_decompiler_expr::IntWidth; let u = UnionType::new(name, vec![StructField::new(0, "a", DecompType::Int(IntWidth::I32)), StructField::new(0, "b", DecompType::Int(IntWidth::I64))]); let em = CTypeEmitter::new(); Ok(ToolResult::text(json!({"code": em.emit_union(&u), "source":"rustre_decompiler_type::CTypeEmitter::emit_union"}).to_string())) } }

pub struct DtZ1CtypeEmitFunctionTool;
impl DtZ1CtypeEmitFunctionTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_ctype_emit_function_z1".to_string(), description: "CTypeEmitter::emit_function on a simple int func(int).".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1CtypeEmitFunctionTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'name'".into()))?.to_string(); use rustre_decompiler_type::{FunctionType, DecompType, CTypeEmitter}; use rustre_decompiler_expr::IntWidth; let mut f = FunctionType::new(name, DecompType::Int(IntWidth::I32)); f.add_param("x", DecompType::Int(IntWidth::I32)); let em = CTypeEmitter::new(); Ok(ToolResult::text(json!({"code": em.emit_function(&f), "source":"rustre_decompiler_type::CTypeEmitter::emit_function"}).to_string())) } }

pub struct DtZ1UnifierSameClassTool;
impl DtZ1UnifierSameClassTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_unifier_same_class_z1".to_string(), description: "TypeUnifier: add constraint then check same_class(a,b).".to_string(), input_schema: json!({"type":"object","properties":{"a":{"type":"string"},"b":{"type":"string"}},"required":["a","b"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1UnifierSameClassTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = args.get("a").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a'".into()))?.to_string(); let b = args.get("b").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b'".into()))?.to_string(); let mut s = rustre_decompiler_type::ConstraintSolver::new(); s.add(rustre_decompiler_type::Constraint::Equal(a.clone(), b.clone())); let _ = s.solve(); let same = s.same_class(&a, &b); Ok(ToolResult::text(json!({"a": a, "b": b, "same_class": same, "conflicts": s.conflicts().len(), "source":"rustre_decompiler_type::ConstraintSolver::same_class"}).to_string())) } }

pub struct DtZ1InferencePointerDerefTool;
impl DtZ1InferencePointerDerefTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_inference_pointer_deref_z1".to_string(), description: "TypeInference: set_type on ptr, then infer_pointer_deref; returns result c_name.".to_string(), input_schema: json!({"type":"object","properties":{"ptr":{"type":"string"},"result":{"type":"string"},"width":{"type":"string"}},"required":["ptr","result","width"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1InferencePointerDerefTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ptr = args.get("ptr").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'ptr'".into()))?.to_string(); let result = args.get("result").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'result'".into()))?.to_string(); let w = __decomp_parse_int_width(args.get("width").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'width'".into()))?).ok_or_else(|| McpError::InvalidParams("bad width".into()))?; use rustre_decompiler_type::{DecompType, TypeInference}; let mut ti = TypeInference::new(); ti.set_type(ptr.clone(), DecompType::Ptr(Box::new(DecompType::Int(w)))); ti.infer_pointer_deref(&ptr, &result); let got = ti.get_type(&result).map(|t| t.c_name()); Ok(ToolResult::text(json!({"ptr": ptr, "result": result, "c_name": got, "type_count": ti.type_count(), "source":"rustre_decompiler_type::TypeInference::infer_pointer_deref"}).to_string())) } }

pub struct DtZ1PropagatorBinopTool;
impl DtZ1PropagatorBinopTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "decompiler_type_propagator_binop_z1".to_string(), description: "TypePropagator: seed(lhs) then propagate_through_binop(result, lhs, rhs); returns result c_name.".to_string(), input_schema: json!({"type":"object","properties":{"lhs":{"type":"string"},"rhs":{"type":"string"},"result":{"type":"string"},"width":{"type":"string"}},"required":["lhs","rhs","result","width"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for DtZ1PropagatorBinopTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let lhs = args.get("lhs").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'lhs'".into()))?.to_string(); let rhs = args.get("rhs").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'rhs'".into()))?.to_string(); let result = args.get("result").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'result'".into()))?.to_string(); let w = __decomp_parse_int_width(args.get("width").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'width'".into()))?).ok_or_else(|| McpError::InvalidParams("bad width".into()))?; use rustre_decompiler_type::{DecompType, TypePropagator}; let mut tp = TypePropagator::new(); tp.seed(lhs.clone(), DecompType::Int(w)); tp.propagate_through_binop(&result, &lhs, &rhs); let got = tp.get(&result).map(|t| t.c_name()); Ok(ToolResult::text(json!({"result": result, "c_name": got, "source":"rustre_decompiler_type::TypePropagator::propagate_through_binop"}).to_string())) } }

pub fn handlers() -> Vec<(ToolDefinition, Box<dyn ToolHandler>)> {
    vec![
        (DtIsPointerVoidTool::definition(), Box::new(DtIsPointerVoidTool)),
        (DtPointeeCnameTool::definition(), Box::new(DtPointeeCnameTool)),
        (DtNamePrefixIntTool::definition(), Box::new(DtNamePrefixIntTool)),
        (DtStructFieldExactTool::definition(), Box::new(DtStructFieldExactTool)),
        (DtFunctionArityTool::definition(), Box::new(DtFunctionArityTool)),
        (DtQualifierStringTool::definition(), Box::new(DtQualifierStringTool)),
        (DtQualifiedTypeCnameTool::definition(), Box::new(DtQualifiedTypeCnameTool)),
        (DtTypeLayoutForStructTool::definition(), Box::new(DtTypeLayoutForStructTool)),
        (DtUnionMemberNamedTool::definition(), Box::new(DtUnionMemberNamedTool)),
        (DtTypeDatabaseResolveTypedefTool::definition(), Box::new(DtTypeDatabaseResolveTypedefTool)),
        (DtZ1ResolveStructTool::definition(), Box::new(DtZ1ResolveStructTool)),
        (DtZ1TypeDatabaseGetStructTool::definition(), Box::new(DtZ1TypeDatabaseGetStructTool)),
        (DtZ1TypeDatabaseGetUnionTool::definition(), Box::new(DtZ1TypeDatabaseGetUnionTool)),
        (DtZ1TypeDatabaseGetFunctionTool::definition(), Box::new(DtZ1TypeDatabaseGetFunctionTool)),
        (DtZ1CtypeEmitStructTool::definition(), Box::new(DtZ1CtypeEmitStructTool)),
        (DtZ1CtypeEmitUnionTool::definition(), Box::new(DtZ1CtypeEmitUnionTool)),
        (DtZ1CtypeEmitFunctionTool::definition(), Box::new(DtZ1CtypeEmitFunctionTool)),
        (DtZ1UnifierSameClassTool::definition(), Box::new(DtZ1UnifierSameClassTool)),
        (DtZ1InferencePointerDerefTool::definition(), Box::new(DtZ1InferencePointerDerefTool)),
        (DtZ1PropagatorBinopTool::definition(), Box::new(DtZ1PropagatorBinopTool)),
    ]
}
