//! MCP wrappers for the rustre-mem_kx7 crate.
//! Extracted from `wire_tools.rs` by `workflow_split_wire_tools`.

use rustre_mcp_server::{McpError, ToolDefinition, ToolHandler, ToolResult};
use serde_json::{json, Value};
use async_trait::async_trait;
use crate::wire_tools::{__mem_hex_decode_v2, __mem_kx7_addr, __mem_kx7_check_page};

pub struct MemKx7ShannonEntropyHexTool;
impl MemKx7ShannonEntropyHexTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_shannon_entropy_hex".to_string(), description: "rustre_mem::shannon_entropy on hex-decoded bytes.".to_string(), input_schema: json!({"type":"object","required":["hex"],"properties":{"hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7ShannonEntropyHexTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let hex = args.get("hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'hex'".into()))?; let d = __mem_hex_decode_v2(hex)?; Ok(ToolResult::text(json!({"entropy":rustre_mem::shannon_entropy(&d),"source":"rustre_mem::shannon_entropy"}).to_string())) } }

pub struct MemKx7ShannonEntropyLenTool;
impl MemKx7ShannonEntropyLenTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_shannon_entropy_len".to_string(), description: "rustre_mem::shannon_entropy plus decoded length.".to_string(), input_schema: json!({"type":"object","required":["hex"],"properties":{"hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7ShannonEntropyLenTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let hex = args.get("hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'hex'".into()))?; let d = __mem_hex_decode_v2(hex)?; Ok(ToolResult::text(json!({"len":d.len(),"entropy":rustre_mem::shannon_entropy(&d),"source":"rustre_mem::shannon_entropy"}).to_string())) } }

pub struct MemKx7EntropyWindowsMaxTool;
impl MemKx7EntropyWindowsMaxTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_entropy_windows_max".to_string(), description: "Maximum shannon_entropy over non-overlapping windows.".to_string(), input_schema: json!({"type":"object","required":["hex","window"],"properties":{"hex":{"type":"string"},"window":{"type":"integer","minimum":1}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7EntropyWindowsMaxTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let d = __mem_hex_decode_v2(args.get("hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'hex'".into()))?)?; let w = args.get("window").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'window'".into()))? as usize; if w == 0 { return Err(McpError::InternalError("'window' must be > 0".into())); } let mut max_e: f64 = 0.0; let mut count = 0usize; let mut i = 0; while i < d.len() { let end = (i + w).min(d.len()); let e = rustre_mem::shannon_entropy(&d[i..end]); if e > max_e { max_e = e; } count += 1; i = end; } Ok(ToolResult::text(json!({"max_entropy":max_e,"windows":count,"source":"rustre_mem::shannon_entropy"}).to_string())) } }

pub struct MemKx7EntropyWindowsAvgTool;
impl MemKx7EntropyWindowsAvgTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_entropy_windows_avg".to_string(), description: "Average shannon_entropy across non-overlapping windows.".to_string(), input_schema: json!({"type":"object","required":["hex","window"],"properties":{"hex":{"type":"string"},"window":{"type":"integer","minimum":1}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7EntropyWindowsAvgTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let d = __mem_hex_decode_v2(args.get("hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'hex'".into()))?)?; let w = args.get("window").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'window'".into()))? as usize; if w == 0 { return Err(McpError::InternalError("'window' must be > 0".into())); } let mut sum = 0.0f64; let mut count = 0usize; let mut i = 0; while i < d.len() { let end = (i + w).min(d.len()); sum += rustre_mem::shannon_entropy(&d[i..end]); count += 1; i = end; } let avg = if count > 0 { sum / count as f64 } else { 0.0 }; Ok(ToolResult::text(json!({"avg_entropy":avg,"windows":count,"source":"rustre_mem::shannon_entropy"}).to_string())) } }

pub struct MemKx7EntropyWindowsAboveTool;
impl MemKx7EntropyWindowsAboveTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_entropy_windows_above".to_string(), description: "Number of windows whose shannon_entropy is >= threshold.".to_string(), input_schema: json!({"type":"object","required":["hex","window","threshold"],"properties":{"hex":{"type":"string"},"window":{"type":"integer","minimum":1},"threshold":{"type":"number"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7EntropyWindowsAboveTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let d = __mem_hex_decode_v2(args.get("hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'hex'".into()))?)?; let w = args.get("window").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'window'".into()))? as usize; let th = args.get("threshold").and_then(Value::as_f64).ok_or_else(|| McpError::InvalidParams("missing 'threshold'".into()))?; if w == 0 { return Err(McpError::InternalError("'window' must be > 0".into())); } let mut hits = 0usize; let mut count = 0usize; let mut i = 0; while i < d.len() { let end = (i + w).min(d.len()); if rustre_mem::shannon_entropy(&d[i..end]) >= th { hits += 1; } count += 1; i = end; } Ok(ToolResult::text(json!({"hits":hits,"windows":count,"threshold":th,"source":"rustre_mem::shannon_entropy"}).to_string())) } }

pub struct MemKx7EntropySliceTool;
impl MemKx7EntropySliceTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_entropy_slice".to_string(), description: "shannon_entropy over hex[offset..offset+len].".to_string(), input_schema: json!({"type":"object","required":["hex","offset","len"],"properties":{"hex":{"type":"string"},"offset":{"type":"integer"},"len":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7EntropySliceTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let d = __mem_hex_decode_v2(args.get("hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'hex'".into()))?)?; let off = args.get("offset").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'offset'".into()))? as usize; let len = args.get("len").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'len'".into()))? as usize; if off > d.len() { return Err(McpError::InternalError("offset out of bounds".into())); } let end = (off + len).min(d.len()); let e = rustre_mem::shannon_entropy(&d[off..end]); Ok(ToolResult::text(json!({"entropy":e,"actual_len":end-off,"source":"rustre_mem::shannon_entropy"}).to_string())) } }

pub struct MemKx7DiffMemoryRegionsTool;
impl MemKx7DiffMemoryRegionsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_memory_regions".to_string(), description: "rustre_mem::diff_memory region_count on equal-length hex buffers.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffMemoryRegionsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(base)); Ok(ToolResult::text(json!({"region_count":d.region_count(),"source":"rustre_mem::diff_memory"}).to_string())) } }

pub struct MemKx7DiffMemoryChangedBytesTool;
impl MemKx7DiffMemoryChangedBytesTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_memory_changed_bytes".to_string(), description: "rustre_mem::diff_memory changed_byte_count on equal-length hex buffers.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffMemoryChangedBytesTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(base)); Ok(ToolResult::text(json!({"changed_bytes":d.changed_byte_count(),"source":"rustre_mem::diff_memory"}).to_string())) } }

pub struct MemKx7DiffMemoryFirstAddrTool;
impl MemKx7DiffMemoryFirstAddrTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_memory_first_addr".to_string(), description: "Address of the first differing region, or -1 if identical.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffMemoryFirstAddrTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(base)); let first: i128 = d.changes.first().map_or(-1, |c| c.addr.as_u64() as i128); Ok(ToolResult::text(json!({"first_addr":first,"source":"rustre_mem::diff_memory"}).to_string())) } }

pub struct MemKx7DiffMemoryLastEndTool;
impl MemKx7DiffMemoryLastEndTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_memory_last_end".to_string(), description: "End address of the last differing region, or -1 if identical.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffMemoryLastEndTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(base)); let last: i128 = d.changes.last().map_or(-1, |c| c.end_addr().as_u64() as i128); Ok(ToolResult::text(json!({"last_end":last,"source":"rustre_mem::MemoryChange::end_addr"}).to_string())) } }

pub struct MemKx7DiffMemoryIsIdenticalTool;
impl MemKx7DiffMemoryIsIdenticalTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_memory_is_identical".to_string(), description: "rustre_mem::SnapshotDiff::is_identical on equal-length hex buffers.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffMemoryIsIdenticalTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(0)); Ok(ToolResult::text(json!({"is_identical":d.is_identical(),"source":"rustre_mem::SnapshotDiff::is_identical"}).to_string())) } }

pub struct MemKx7DiffMemoryLenientRegionsTool;
impl MemKx7DiffMemoryLenientRegionsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_memory_lenient_regions".to_string(), description: "rustre_mem::diff_memory_lenient region_count.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffMemoryLenientRegionsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let d = rustre_mem::diff_memory_lenient(&a, &b, __mem_kx7_addr(base)); Ok(ToolResult::text(json!({"region_count":d.region_count(),"common_len":a.len().min(b.len()),"source":"rustre_mem::diff_memory_lenient"}).to_string())) } }

pub struct MemKx7DiffMemoryLenientChangedTool;
impl MemKx7DiffMemoryLenientChangedTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_memory_lenient_changed".to_string(), description: "rustre_mem::diff_memory_lenient changed_byte_count.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffMemoryLenientChangedTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let d = rustre_mem::diff_memory_lenient(&a, &b, __mem_kx7_addr(base)); Ok(ToolResult::text(json!({"changed_bytes":d.changed_byte_count(),"source":"rustre_mem::diff_memory_lenient"}).to_string())) } }

pub struct MemKx7DiffBytesSpanCountTool;
impl MemKx7DiffBytesSpanCountTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_bytes_span_count".to_string(), description: "rustre_mem::diff::diff_bytes span count.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffBytesSpanCountTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let s = rustre_mem::diff::diff_bytes(__mem_kx7_addr(base), &a, &b); Ok(ToolResult::text(json!({"span_count":s.len(),"source":"rustre_mem::diff::diff_bytes"}).to_string())) } }

pub struct MemKx7DiffBytesFirstLenTool;
impl MemKx7DiffBytesFirstLenTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_bytes_first_len".to_string(), description: "Length of first diff span, or 0.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffBytesFirstLenTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; let s = rustre_mem::diff::diff_bytes(__mem_kx7_addr(0), &a, &b); let first = s.first().map_or(0, rustre_mem::DiffSpan::len); Ok(ToolResult::text(json!({"first_len":first,"source":"rustre_mem::DiffSpan::len"}).to_string())) } }

pub struct MemKx7DiffBytesTotalLenTool;
impl MemKx7DiffBytesTotalLenTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_bytes_total_len".to_string(), description: "Sum of lengths across all diff spans.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffBytesTotalLenTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; let s = rustre_mem::diff::diff_bytes(__mem_kx7_addr(0), &a, &b); let total: usize = s.iter().map(rustre_mem::DiffSpan::len).sum(); Ok(ToolResult::text(json!({"total_len":total,"spans":s.len(),"source":"rustre_mem::diff::diff_bytes"}).to_string())) } }

pub struct MemKx7DiffBytesLastEndTool;
impl MemKx7DiffBytesLastEndTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_bytes_last_end".to_string(), description: "End address of last diff span, or -1.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"},"base":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffBytesLastEndTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let s = rustre_mem::diff::diff_bytes(__mem_kx7_addr(base), &a, &b); let last: i128 = s.last().map_or(-1, |x| x.range.end.as_u64() as i128); Ok(ToolResult::text(json!({"last_end":last,"source":"rustre_mem::diff::diff_bytes"}).to_string())) } }

pub struct MemKx7DiffBytesChangeRatioTool;
impl MemKx7DiffBytesChangeRatioTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_diff_bytes_change_ratio".to_string(), description: "Changed bytes / min(a,b) length ratio.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7DiffBytesChangeRatioTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; let s = rustre_mem::diff::diff_bytes(__mem_kx7_addr(0), &a, &b); let total: usize = s.iter().map(rustre_mem::DiffSpan::len).sum(); let denom = a.len().min(b.len()); let ratio = if denom > 0 { total as f64 / denom as f64 } else { 0.0 }; Ok(ToolResult::text(json!({"ratio":ratio,"changed":total,"denom":denom,"source":"rustre_mem::diff::diff_bytes"}).to_string())) } }

pub struct MemKx7SnapshotDiffApplyTool;
impl MemKx7SnapshotDiffApplyTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_snapshotdiff_apply".to_string(), description: "diff_memory(a,b) then apply_to a buffer of len=a.len(); reports success.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7SnapshotDiffApplyTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(0)); let mut buf = a; let ok = d.apply_to(&mut buf, __mem_kx7_addr(0)).is_ok(); let matches = ok && buf == b; Ok(ToolResult::text(json!({"apply_ok":ok,"buffer_equals_b":matches,"buffer_len":buf.len(),"source":"rustre_mem::SnapshotDiff::apply_to"}).to_string())) } }

pub struct MemKx7SnapshotDiffInvertTool;
impl MemKx7SnapshotDiffInvertTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_snapshotdiff_invert".to_string(), description: "diff_memory then invert(); reports region counts before/after.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7SnapshotDiffInvertTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(0)); let inv = d.invert(); Ok(ToolResult::text(json!({"regions":d.region_count(),"invert_regions":inv.region_count(),"source":"rustre_mem::SnapshotDiff::invert"}).to_string())) } }

pub struct MemKx7SnapshotDiffJsonRoundtripTool;
impl MemKx7SnapshotDiffJsonRoundtripTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_snapshotdiff_json_roundtrip".to_string(), description: "diff_memory then to_json / from_json roundtrip.".to_string(), input_schema: json!({"type":"object","required":["a_hex","b_hex"],"properties":{"a_hex":{"type":"string"},"b_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7SnapshotDiffJsonRoundtripTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = __mem_hex_decode_v2(args.get("a_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'a_hex'".into()))?)?; let b = __mem_hex_decode_v2(args.get("b_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'b_hex'".into()))?)?; if a.len() != b.len() { return Err(McpError::InternalError("a and b must have equal length".into())); } let d = rustre_mem::diff_memory(&a, &b, __mem_kx7_addr(0)); let js = d.to_json().map_err(|e| McpError::InternalError(e.to_string()))?; let parsed = rustre_mem::SnapshotDiff::from_json(&js).map_err(|e| McpError::InternalError(e.to_string()))?; Ok(ToolResult::text(json!({"regions":d.region_count(),"roundtrip_regions":parsed.region_count(),"json_len":js.len(),"source":"rustre_mem::SnapshotDiff::to_json"}).to_string())) } }

pub struct MemKx7PageAlignUpTool;
impl MemKx7PageAlignUpTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_align_up".to_string(), description: "rustre_mem::region::page_align_up (page_size must be power of two).".to_string(), input_schema: json!({"type":"object","required":["addr","page_size"],"properties":{"addr":{"type":"integer"},"page_size":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageAlignUpTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; __mem_kx7_check_page(page)?; let r = rustre_mem::region::page_align_up(__mem_kx7_addr(addr), page); Ok(ToolResult::text(json!({"aligned":r.as_u64(),"source":"rustre_mem::region::page_align_up"}).to_string())) } }

pub struct MemKx7PageAlignDownTool;
impl MemKx7PageAlignDownTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_align_down".to_string(), description: "rustre_mem::region::page_align_down (page_size must be power of two).".to_string(), input_schema: json!({"type":"object","required":["addr","page_size"],"properties":{"addr":{"type":"integer"},"page_size":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageAlignDownTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; __mem_kx7_check_page(page)?; let r = rustre_mem::region::page_align_down(__mem_kx7_addr(addr), page); Ok(ToolResult::text(json!({"aligned":r.as_u64(),"source":"rustre_mem::region::page_align_down"}).to_string())) } }

pub struct MemKx7PageIndexTool;
impl MemKx7PageIndexTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_index".to_string(), description: "rustre_mem::region::page_index for addr under page_size.".to_string(), input_schema: json!({"type":"object","required":["addr","page_size"],"properties":{"addr":{"type":"integer"},"page_size":{"type":"integer","minimum":1}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageIndexTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; if page == 0 { return Err(McpError::InternalError("page_size must be > 0".into())); } let idx = rustre_mem::region::page_index(__mem_kx7_addr(addr), page); Ok(ToolResult::text(json!({"page_index":idx,"source":"rustre_mem::region::page_index"}).to_string())) } }

pub struct MemKx7PageRangeIndicesTool;
impl MemKx7PageRangeIndicesTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_range_indices".to_string(), description: "rustre_mem::region::page_range_indices for [start,end).".to_string(), input_schema: json!({"type":"object","required":["start","end","page_size"],"properties":{"start":{"type":"integer"},"end":{"type":"integer"},"page_size":{"type":"integer","minimum":1}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageRangeIndicesTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let start = args.get("start").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'start'".into()))?; let end = args.get("end").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'end'".into()))?; let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; if page == 0 { return Err(McpError::InternalError("page_size must be > 0".into())); } if end < start { return Err(McpError::InternalError("end must be >= start".into())); } let r = rustre_core::address::AddressRange::new(__mem_kx7_addr(start), __mem_kx7_addr(end)); let (first, last) = rustre_mem::region::page_range_indices(&r, page); Ok(ToolResult::text(json!({"first":first,"last":last,"source":"rustre_mem::region::page_range_indices"}).to_string())) } }

pub struct MemKx7PageContainingTool;
impl MemKx7PageContainingTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_containing".to_string(), description: "rustre_mem::region::page_containing to (start,end).".to_string(), input_schema: json!({"type":"object","required":["addr","page_size"],"properties":{"addr":{"type":"integer"},"page_size":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageContainingTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; __mem_kx7_check_page(page)?; let r = rustre_mem::region::page_containing(__mem_kx7_addr(addr), page); Ok(ToolResult::text(json!({"start":r.start.as_u64(),"end":r.end.as_u64(),"source":"rustre_mem::region::page_containing"}).to_string())) } }

pub struct MemKx7PageAlignRoundtripTool;
impl MemKx7PageAlignRoundtripTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_align_roundtrip".to_string(), description: "align_up(addr) then align_down(that); expect equality.".to_string(), input_schema: json!({"type":"object","required":["addr","page_size"],"properties":{"addr":{"type":"integer"},"page_size":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageAlignRoundtripTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; __mem_kx7_check_page(page)?; let up = rustre_mem::region::page_align_up(__mem_kx7_addr(addr), page); let down = rustre_mem::region::page_align_down(up, page); Ok(ToolResult::text(json!({"up":up.as_u64(),"down":down.as_u64(),"equal":up.as_u64()==down.as_u64(),"source":"rustre_mem::region::page_align_up"}).to_string())) } }

pub struct MemKx7PageSpanCountTool;
impl MemKx7PageSpanCountTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_span_count".to_string(), description: "Number of pages spanned by [start,end) via page_range_indices.".to_string(), input_schema: json!({"type":"object","required":["start","end","page_size"],"properties":{"start":{"type":"integer"},"end":{"type":"integer"},"page_size":{"type":"integer","minimum":1}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageSpanCountTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let start = args.get("start").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'start'".into()))?; let end = args.get("end").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'end'".into()))?; let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; if page == 0 { return Err(McpError::InternalError("page_size must be > 0".into())); } if end <= start { return Ok(ToolResult::text(json!({"pages":0,"source":"rustre_mem::region::page_range_indices"}).to_string())); } let r = rustre_core::address::AddressRange::new(__mem_kx7_addr(start), __mem_kx7_addr(end)); let (first, last) = rustre_mem::region::page_range_indices(&r, page); Ok(ToolResult::text(json!({"pages":last - first + 1,"source":"rustre_mem::region::page_range_indices"}).to_string())) } }

pub struct MemKx7PageAlignUpBatchTool;
impl MemKx7PageAlignUpBatchTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_page_align_up_batch".to_string(), description: "Apply rustre_mem::region::page_align_up to a list of addrs.".to_string(), input_schema: json!({"type":"object","required":["addrs","page_size"],"properties":{"addrs":{"type":"array","items":{"type":"integer"}},"page_size":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7PageAlignUpBatchTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let page = args.get("page_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'page_size'".into()))?; __mem_kx7_check_page(page)?; let addrs: Vec<u64> = args.get("addrs").and_then(Value::as_array).map(|a| a.iter().filter_map(Value::as_u64).collect()).unwrap_or_default(); let out: Vec<u64> = addrs.iter().map(|a| rustre_mem::region::page_align_up(__mem_kx7_addr(*a), page).as_u64()).collect(); Ok(ToolResult::text(json!({"count":out.len(),"aligned":out,"source":"rustre_mem::region::page_align_up"}).to_string())) } }

pub struct MemKx7BytePatternParseLenTool;
impl MemKx7BytePatternParseLenTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_bytepattern_parse_len".to_string(), description: "rustre_mem::BytePattern::parse then .len() / .is_all_wild().".to_string(), input_schema: json!({"type":"object","required":["pattern"],"properties":{"pattern":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7BytePatternParseLenTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let p = args.get("pattern").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'pattern'".into()))?; let bp = rustre_mem::BytePattern::parse(p).map_err(McpError::InternalError)?; Ok(ToolResult::text(json!({"len":bp.len(),"all_wild":bp.is_all_wild(),"source":"rustre_mem::BytePattern::parse"}).to_string())) } }

pub struct MemKx7BytePatternMatchesAtTool;
impl MemKx7BytePatternMatchesAtTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_bytepattern_matches_at".to_string(), description: "rustre_mem::BytePattern::matches_at against hex data.".to_string(), input_schema: json!({"type":"object","required":["pattern","hex"],"properties":{"pattern":{"type":"string"},"hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7BytePatternMatchesAtTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let p = args.get("pattern").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'pattern'".into()))?; let data = __mem_hex_decode_v2(args.get("hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'hex'".into()))?)?; let bp = rustre_mem::BytePattern::parse(p).map_err(McpError::InternalError)?; if data.len() < bp.len() { return Ok(ToolResult::text(json!({"matches":false,"reason":"data shorter than pattern","source":"rustre_mem::BytePattern::matches_at"}).to_string())); } Ok(ToolResult::text(json!({"matches":bp.matches_at(&data),"source":"rustre_mem::BytePattern::matches_at"}).to_string())) } }

pub struct MemKx7BytePatternValidTool;
impl MemKx7BytePatternValidTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_kx7_bytepattern_valid".to_string(), description: "Check whether rustre_mem::BytePattern::parse accepts a string.".to_string(), input_schema: json!({"type":"object","required":["pattern"],"properties":{"pattern":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemKx7BytePatternValidTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let p = args.get("pattern").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing 'pattern'".into()))?; let r = rustre_mem::BytePattern::parse(p); Ok(ToolResult::text(json!({"valid":r.is_ok(),"error":r.as_ref().err().cloned(),"source":"rustre_mem::BytePattern::parse"}).to_string())) } }

#[must_use]
pub fn handlers() -> Vec<(ToolDefinition, Box<dyn ToolHandler>)> {
    vec![
        (MemKx7ShannonEntropyHexTool::definition(), Box::new(MemKx7ShannonEntropyHexTool)),
        (MemKx7ShannonEntropyLenTool::definition(), Box::new(MemKx7ShannonEntropyLenTool)),
        (MemKx7EntropyWindowsMaxTool::definition(), Box::new(MemKx7EntropyWindowsMaxTool)),
        (MemKx7EntropyWindowsAvgTool::definition(), Box::new(MemKx7EntropyWindowsAvgTool)),
        (MemKx7EntropyWindowsAboveTool::definition(), Box::new(MemKx7EntropyWindowsAboveTool)),
        (MemKx7EntropySliceTool::definition(), Box::new(MemKx7EntropySliceTool)),
        (MemKx7DiffMemoryRegionsTool::definition(), Box::new(MemKx7DiffMemoryRegionsTool)),
        (MemKx7DiffMemoryChangedBytesTool::definition(), Box::new(MemKx7DiffMemoryChangedBytesTool)),
        (MemKx7DiffMemoryFirstAddrTool::definition(), Box::new(MemKx7DiffMemoryFirstAddrTool)),
        (MemKx7DiffMemoryLastEndTool::definition(), Box::new(MemKx7DiffMemoryLastEndTool)),
        (MemKx7DiffMemoryIsIdenticalTool::definition(), Box::new(MemKx7DiffMemoryIsIdenticalTool)),
        (MemKx7DiffMemoryLenientRegionsTool::definition(), Box::new(MemKx7DiffMemoryLenientRegionsTool)),
        (MemKx7DiffMemoryLenientChangedTool::definition(), Box::new(MemKx7DiffMemoryLenientChangedTool)),
        (MemKx7DiffBytesSpanCountTool::definition(), Box::new(MemKx7DiffBytesSpanCountTool)),
        (MemKx7DiffBytesFirstLenTool::definition(), Box::new(MemKx7DiffBytesFirstLenTool)),
        (MemKx7DiffBytesTotalLenTool::definition(), Box::new(MemKx7DiffBytesTotalLenTool)),
        (MemKx7DiffBytesLastEndTool::definition(), Box::new(MemKx7DiffBytesLastEndTool)),
        (MemKx7DiffBytesChangeRatioTool::definition(), Box::new(MemKx7DiffBytesChangeRatioTool)),
        (MemKx7SnapshotDiffApplyTool::definition(), Box::new(MemKx7SnapshotDiffApplyTool)),
        (MemKx7SnapshotDiffInvertTool::definition(), Box::new(MemKx7SnapshotDiffInvertTool)),
        (MemKx7SnapshotDiffJsonRoundtripTool::definition(), Box::new(MemKx7SnapshotDiffJsonRoundtripTool)),
        (MemKx7PageAlignUpTool::definition(), Box::new(MemKx7PageAlignUpTool)),
        (MemKx7PageAlignDownTool::definition(), Box::new(MemKx7PageAlignDownTool)),
        (MemKx7PageIndexTool::definition(), Box::new(MemKx7PageIndexTool)),
        (MemKx7PageRangeIndicesTool::definition(), Box::new(MemKx7PageRangeIndicesTool)),
        (MemKx7PageContainingTool::definition(), Box::new(MemKx7PageContainingTool)),
        (MemKx7PageAlignRoundtripTool::definition(), Box::new(MemKx7PageAlignRoundtripTool)),
        (MemKx7PageSpanCountTool::definition(), Box::new(MemKx7PageSpanCountTool)),
        (MemKx7PageAlignUpBatchTool::definition(), Box::new(MemKx7PageAlignUpBatchTool)),
        (MemKx7BytePatternParseLenTool::definition(), Box::new(MemKx7BytePatternParseLenTool)),
        (MemKx7BytePatternMatchesAtTool::definition(), Box::new(MemKx7BytePatternMatchesAtTool)),
        (MemKx7BytePatternValidTool::definition(), Box::new(MemKx7BytePatternValidTool)),
    ]
}
