//! MCP wrappers for the rustre-mem_ma crate.
//! Extracted from wire_tools.rs by workflow_split_wire_tools.

use rustre_mcp_server::{McpError, ToolDefinition, ToolHandler, ToolResult};
use serde_json::{json, Value};
use async_trait::async_trait;
use crate::{args_to_bytes, hex_encode};

pub struct MemMaShannonEntropyBytesV4Tool;
impl MemMaShannonEntropyBytesV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_shannon_entropy_bytes_v4".to_string(), description: "Shannon entropy of a hex/byte buffer via rustre_mem::memory_analysis::shannon_entropy_bytes.".to_string(), input_schema: json!({"type":"object","properties":{"hex":{"type":"string"},"bytes":{"type":"array","items":{"type":"integer"}}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaShannonEntropyBytesV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let b = args_to_bytes(&args)?; let e = rustre_mem::memory_analysis::shannon_entropy_bytes(&b); Ok(ToolResult::text(json!({"len":b.len(),"entropy":e,"source":"rustre_mem::memory_analysis::shannon_entropy_bytes"}).to_string())) } }

pub struct MemMaEntropyRegionNewV4Tool;
impl MemMaEntropyRegionNewV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_entropy_region_new_v4".to_string(), description: "Build rustre_mem::memory_analysis::EntropyRegion::new(base, bytes).".to_string(), input_schema: json!({"type":"object","required":["base"],"properties":{"base":{"type":"integer"},"hex":{"type":"string"},"bytes":{"type":"array","items":{"type":"integer"}}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaEntropyRegionNewV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let base = args.get("base").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing base".into()))?; let b = args_to_bytes(&args)?; let r = rustre_mem::memory_analysis::EntropyRegion::new(rustre_mem::memory_analysis::Va(base), &b); Ok(ToolResult::text(json!({"address":r.address.0,"size":r.size,"entropy":r.entropy,"is_suspicious":r.is_suspicious,"source":"rustre_mem::memory_analysis::EntropyRegion::new"}).to_string())) } }

pub struct MemMaEntropyRegionSuspiciousThresholdV4Tool;
impl MemMaEntropyRegionSuspiciousThresholdV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_entropy_region_suspicious_threshold_v4".to_string(), description: "Return EntropyRegion::SUSPICIOUS_THRESHOLD.".to_string(), input_schema: json!({"type":"object","properties":{}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaEntropyRegionSuspiciousThresholdV4Tool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { let t = rustre_mem::memory_analysis::EntropyRegion::SUSPICIOUS_THRESHOLD; Ok(ToolResult::text(json!({"threshold":t,"source":"rustre_mem::memory_analysis::EntropyRegion::SUSPICIOUS_THRESHOLD"}).to_string())) } }

pub struct MemMaDiffRegionsHexV4Tool;
impl MemMaDiffRegionsHexV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_diff_regions_hex_v4".to_string(), description: "Diff two equal-length hex buffers via memory_analysis::diff_regions.".to_string(), input_schema: json!({"type":"object","required":["base","before_hex","after_hex"],"properties":{"base":{"type":"integer"},"before_hex":{"type":"string"},"after_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaDiffRegionsHexV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let base = args.get("base").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing base".into()))?; let bh = args.get("before_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing before_hex".into()))?; let ah = args.get("after_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing after_hex".into()))?; let b = crate::hex_decode(bh)?; let a = crate::hex_decode(ah)?; if a.len() != b.len() { return Err(McpError::InvalidParams("before/after must be equal length".into())); } let spans = rustre_mem::memory_analysis::diff_regions(rustre_mem::memory_analysis::Va(base), &b, &a); let out: Vec<_> = spans.iter().map(|s| json!({"start":s.start.0,"len":s.len(),"old_hex":hex_encode(&s.old_bytes),"new_hex":hex_encode(&s.new_bytes)})).collect(); Ok(ToolResult::text(json!({"span_count":out.len(),"spans":out,"source":"rustre_mem::memory_analysis::diff_regions"}).to_string())) } }

pub struct MemMaDiffSpanLenV4Tool;
impl MemMaDiffSpanLenV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_diff_span_len_v4".to_string(), description: "Construct memory_analysis::DiffSpan and report len/is_empty.".to_string(), input_schema: json!({"type":"object","required":["start","old_hex","new_hex"],"properties":{"start":{"type":"integer"},"old_hex":{"type":"string"},"new_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaDiffSpanLenV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let start = args.get("start").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing start".into()))?; let oh = args.get("old_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing old_hex".into()))?; let nh = args.get("new_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing new_hex".into()))?; let old_bytes = crate::hex_decode(oh)?; let new_bytes = crate::hex_decode(nh)?; let s = rustre_mem::memory_analysis::DiffSpan { start: rustre_mem::memory_analysis::Va(start), old_bytes, new_bytes }; Ok(ToolResult::text(json!({"start":s.start.0,"len":s.len(),"is_empty":s.is_empty(),"source":"rustre_mem::memory_analysis::DiffSpan::len"}).to_string())) } }

pub struct MemMaMemoryStatisticsComputeV4Tool;
impl MemMaMemoryStatisticsComputeV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_memory_statistics_compute_v4".to_string(), description: "MemoryStatistics::compute(base, data, block_size).".to_string(), input_schema: json!({"type":"object","required":["base","block_size"],"properties":{"base":{"type":"integer"},"block_size":{"type":"integer","minimum":1},"hex":{"type":"string"},"bytes":{"type":"array","items":{"type":"integer"}}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaMemoryStatisticsComputeV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let base = args.get("base").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing base".into()))?; let bs = args.get("block_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing block_size".into()))? as usize; if bs == 0 { return Err(McpError::InvalidParams("block_size must be > 0".into())); } let data = args_to_bytes(&args)?; let s = rustre_mem::memory_analysis::MemoryStatistics::compute(rustre_mem::memory_analysis::Va(base), &data, bs); Ok(ToolResult::text(json!({"total_bytes":s.total_bytes,"zero_bytes":s.zero_bytes,"non_zero_bytes":s.non_zero_bytes,"min_entropy":s.min_entropy,"max_entropy":s.max_entropy,"min_addr":s.min_entropy_block_addr.map(|v| v.0),"max_addr":s.max_entropy_block_addr.map(|v| v.0),"source":"rustre_mem::memory_analysis::MemoryStatistics::compute"}).to_string())) } }

pub struct MemMaMemoryStatisticsFractionsV4Tool;
impl MemMaMemoryStatisticsFractionsV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_memory_statistics_fractions_v4".to_string(), description: "Report non_zero_fraction/zero_fraction from MemoryStatistics::compute.".to_string(), input_schema: json!({"type":"object","required":["block_size"],"properties":{"base":{"type":"integer"},"block_size":{"type":"integer","minimum":1},"hex":{"type":"string"},"bytes":{"type":"array","items":{"type":"integer"}}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaMemoryStatisticsFractionsV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let base = args.get("base").and_then(Value::as_u64).unwrap_or(0); let bs = args.get("block_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing block_size".into()))? as usize; if bs == 0 { return Err(McpError::InvalidParams("block_size must be > 0".into())); } let data = args_to_bytes(&args)?; let s = rustre_mem::memory_analysis::MemoryStatistics::compute(rustre_mem::memory_analysis::Va(base), &data, bs); Ok(ToolResult::text(json!({"non_zero_fraction":s.non_zero_fraction(),"zero_fraction":s.zero_fraction(),"total_bytes":s.total_bytes,"source":"rustre_mem::memory_analysis::MemoryStatistics::non_zero_fraction"}).to_string())) } }

pub struct MemMaBytePatternFromHexStrV4Tool;
impl MemMaBytePatternFromHexStrV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_byte_pattern_from_hex_str_v4".to_string(), description: "BytePattern::from_hex_str.".to_string(), input_schema: json!({"type":"object","required":["pattern"],"properties":{"pattern":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaBytePatternFromHexStrV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let s = args.get("pattern").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing pattern".into()))?; let p = rustre_mem::memory_analysis::BytePattern::from_hex_str(s); Ok(ToolResult::text(json!({"len":p.len(),"is_empty":p.is_empty(),"bytes":p.bytes,"mask":p.mask,"source":"rustre_mem::memory_analysis::BytePattern::from_hex_str"}).to_string())) } }

pub struct MemMaBytePatternMatchesAtV4Tool;
impl MemMaBytePatternMatchesAtV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_byte_pattern_matches_at_v4".to_string(), description: "BytePattern::from_hex_str(pattern).matches_at(data_hex).".to_string(), input_schema: json!({"type":"object","required":["pattern","data_hex"],"properties":{"pattern":{"type":"string"},"data_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaBytePatternMatchesAtV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ps = args.get("pattern").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing pattern".into()))?; let ds = args.get("data_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing data_hex".into()))?; let p = rustre_mem::memory_analysis::BytePattern::from_hex_str(ps); let d = crate::hex_decode(ds)?; Ok(ToolResult::text(json!({"matches":p.matches_at(&d),"pattern_len":p.len(),"data_len":d.len(),"source":"rustre_mem::memory_analysis::BytePattern::matches_at"}).to_string())) } }

pub struct MemMaBytePatternExactV4Tool;
impl MemMaBytePatternExactV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_byte_pattern_exact_v4".to_string(), description: "BytePattern::exact(hex).matches_at(data_hex).".to_string(), input_schema: json!({"type":"object","required":["pattern_hex","data_hex"],"properties":{"pattern_hex":{"type":"string"},"data_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaBytePatternExactV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ph = args.get("pattern_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing pattern_hex".into()))?; let dh = args.get("data_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing data_hex".into()))?; let pb = crate::hex_decode(ph)?; let db = crate::hex_decode(dh)?; let p = rustre_mem::memory_analysis::BytePattern::exact(pb); Ok(ToolResult::text(json!({"len":p.len(),"is_empty":p.is_empty(),"matches":p.matches_at(&db),"source":"rustre_mem::memory_analysis::BytePattern::exact"}).to_string())) } }

pub struct MemMaBytePatternMatcherFindAllV4Tool;
impl MemMaBytePatternMatcherFindAllV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_byte_pattern_matcher_find_all_v4".to_string(), description: "BytePatternMatcher::parse(pattern).find_all(data_hex).".to_string(), input_schema: json!({"type":"object","required":["pattern","data_hex"],"properties":{"pattern":{"type":"string"},"data_hex":{"type":"string"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaBytePatternMatcherFindAllV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let ps = args.get("pattern").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing pattern".into()))?; let ds = args.get("data_hex").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("missing data_hex".into()))?; let m = rustre_mem::memory_analysis::BytePatternMatcher::parse(ps); let d = crate::hex_decode(ds)?; let hits = m.find_all(&d); Ok(ToolResult::text(json!({"pattern_len":m.len(),"is_empty":m.is_empty(),"hit_count":hits.len(),"offsets":hits,"source":"rustre_mem::memory_analysis::BytePatternMatcher::find_all"}).to_string())) } }

pub struct MemMaScanEntropyV4Tool;
impl MemMaScanEntropyV4Tool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "mem_ma_scan_entropy_v4".to_string(), description: "memory_analysis::scan_entropy(base, data, block_size).".to_string(), input_schema: json!({"type":"object","required":["base","block_size"],"properties":{"base":{"type":"integer"},"block_size":{"type":"integer","minimum":1},"hex":{"type":"string"},"bytes":{"type":"array","items":{"type":"integer"}}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for MemMaScanEntropyV4Tool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let base = args.get("base").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing base".into()))?; let bs = args.get("block_size").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing block_size".into()))? as usize; if bs == 0 { return Err(McpError::InvalidParams("block_size must be > 0".into())); } let d = args_to_bytes(&args)?; let regs = rustre_mem::memory_analysis::scan_entropy(rustre_mem::memory_analysis::Va(base), &d, bs); let items: Vec<_> = regs.iter().map(|r| json!({"address":r.address.0,"size":r.size,"entropy":r.entropy,"is_suspicious":r.is_suspicious})).collect(); Ok(ToolResult::text(json!({"count":items.len(),"regions":items,"source":"rustre_mem::memory_analysis::scan_entropy"}).to_string())) } }

pub fn handlers() -> Vec<(ToolDefinition, Box<dyn ToolHandler>)> {
    vec![
        (MemMaShannonEntropyBytesV4Tool::definition(), Box::new(MemMaShannonEntropyBytesV4Tool)),
        (MemMaEntropyRegionNewV4Tool::definition(), Box::new(MemMaEntropyRegionNewV4Tool)),
        (MemMaEntropyRegionSuspiciousThresholdV4Tool::definition(), Box::new(MemMaEntropyRegionSuspiciousThresholdV4Tool)),
        (MemMaDiffRegionsHexV4Tool::definition(), Box::new(MemMaDiffRegionsHexV4Tool)),
        (MemMaDiffSpanLenV4Tool::definition(), Box::new(MemMaDiffSpanLenV4Tool)),
        (MemMaMemoryStatisticsComputeV4Tool::definition(), Box::new(MemMaMemoryStatisticsComputeV4Tool)),
        (MemMaMemoryStatisticsFractionsV4Tool::definition(), Box::new(MemMaMemoryStatisticsFractionsV4Tool)),
        (MemMaBytePatternFromHexStrV4Tool::definition(), Box::new(MemMaBytePatternFromHexStrV4Tool)),
        (MemMaBytePatternMatchesAtV4Tool::definition(), Box::new(MemMaBytePatternMatchesAtV4Tool)),
        (MemMaBytePatternExactV4Tool::definition(), Box::new(MemMaBytePatternExactV4Tool)),
        (MemMaBytePatternMatcherFindAllV4Tool::definition(), Box::new(MemMaBytePatternMatcherFindAllV4Tool)),
        (MemMaScanEntropyV4Tool::definition(), Box::new(MemMaScanEntropyV4Tool)),
    ]
}
