//! MCP wrappers for the rustre-symbols_v7 crate.
//! Extracted from wire_tools.rs by workflow_split_wire_tools.

use rustre_mcp_server::{McpError, ToolDefinition, ToolHandler, ToolResult};
use serde_json::{json, Value};
use async_trait::async_trait;

pub struct SymbolsV7SymbolNewDisplayTool;
impl SymbolsV7SymbolNewDisplayTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_symbol_new_display".to_string(), description: "Symbol::new + display_name/is_function/is_data/end_address.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"},"addr":{"type":"integer"},"size":{"type":"integer"},"demangled":{"type":"string"}},"required":["name","addr"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SymbolNewDisplayTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("name".into()))?; let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("addr".into()))?; let mut s = rustre_symbols::Symbol::new(name.to_string(), addr, rustre_symbols::SymKind::Function); s.size = args.get("size").and_then(Value::as_u64); if let Some(d) = args.get("demangled").and_then(Value::as_str) { s.set_demangled(d.to_string()); } Ok(ToolResult::text(json!({"display":s.display_name(),"is_function":s.is_function(),"is_data":s.is_data(),"end":s.end_address(),"source":"rustre_symbols::Symbol"}).to_string())) } }

pub struct SymbolsV7SymbolContainsTool;
impl SymbolsV7SymbolContainsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_symbol_contains".to_string(), description: "Symbol::contains(probe) with optional size.".to_string(), input_schema: json!({"type":"object","properties":{"addr":{"type":"integer"},"size":{"type":"integer"},"probe":{"type":"integer"}},"required":["addr","probe"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SymbolContainsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("addr".into()))?; let p = args.get("probe").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("probe".into()))?; let mut s = rustre_symbols::Symbol::new("s".into(), a, rustre_symbols::SymKind::Function); s.size = args.get("size").and_then(Value::as_u64); Ok(ToolResult::text(json!({"contains":s.contains(p),"end":s.end_address(),"source":"rustre_symbols::Symbol::contains"}).to_string())) } }

pub struct SymbolsV7BindingDisplayTool;
impl SymbolsV7BindingDisplayTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_binding_display".to_string(), description: "SymbolBinding all variants Display.".to_string(), input_schema: json!({"type":"object"}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7BindingDisplayTool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { use rustre_symbols::SymbolBinding as B; let v: Vec<String> = [B::Local, B::Global, B::Weak, B::GnuUnique].iter().map(std::string::ToString::to_string).collect(); Ok(ToolResult::text(json!({"variants":v,"source":"rustre_symbols::SymbolBinding"}).to_string())) } }

pub struct SymbolsV7VisibilityDisplayTool;
impl SymbolsV7VisibilityDisplayTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_visibility_display".to_string(), description: "SymbolVisibility all variants Display.".to_string(), input_schema: json!({"type":"object"}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7VisibilityDisplayTool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { use rustre_symbols::SymbolVisibility as V; let v: Vec<String> = [V::Default, V::Hidden, V::Protected, V::Internal].iter().map(std::string::ToString::to_string).collect(); Ok(ToolResult::text(json!({"variants":v,"source":"rustre_symbols::SymbolVisibility"}).to_string())) } }

pub struct SymbolsV7LegacySourceDisplayTool;
impl SymbolsV7LegacySourceDisplayTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_legacy_source_display".to_string(), description: "LegacySymbolSource all variants Display.".to_string(), input_schema: json!({"type":"object"}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7LegacySourceDisplayTool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { use rustre_symbols::LegacySymbolSource as L; let v: Vec<String> = [L::Export, L::Import, L::Debug, L::Synthetic, L::User].iter().map(std::string::ToString::to_string).collect(); Ok(ToolResult::text(json!({"variants":v,"source":"rustre_symbols::LegacySymbolSource"}).to_string())) } }

pub struct SymbolsV7SymKindClassifyTool;
impl SymbolsV7SymKindClassifyTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_symkind_classify".to_string(), description: "Enumerate SymKind Display + is_function/is_data flags via Symbol.".to_string(), input_schema: json!({"type":"object"}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SymKindClassifyTool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { use rustre_symbols::SymKind as K; let all = [K::Function, K::Data, K::Label, K::Section, K::File, K::Type, K::Namespace, K::TLS, K::IFunc, K::Common, K::Unknown]; let v: Vec<(String, bool, bool)> = all.iter().map(|k| { let s = rustre_symbols::Symbol::new("x".into(), 0, *k); (k.to_string(), s.is_function(), s.is_data()) }).collect(); Ok(ToolResult::text(json!({"kinds":v,"source":"rustre_symbols::SymKind"}).to_string())) } }

pub struct SymbolsV7SymbolCacheLruTool;
impl SymbolsV7SymbolCacheLruTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_symbol_cache_lru".to_string(), description: "SymbolCache new/insert/get/len/capacity round-trip.".to_string(), input_schema: json!({"type":"object","properties":{"cap":{"type":"integer"},"addrs":{"type":"array","items":{"type":"integer"}},"probe":{"type":"integer"}},"required":["cap","addrs","probe"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SymbolCacheLruTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let cap = args.get("cap").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("cap".into()))? as usize; let addrs = args.get("addrs").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("addrs".into()))?; let probe = args.get("probe").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("probe".into()))?; let mut c = rustre_symbols::SymbolCache::new(cap); for v in addrs { if let Some(a) = v.as_u64() { c.insert(a, rustre_symbols::Symbol::new(format!("f_{a:x}"), a, rustre_symbols::SymKind::Function)); } } let hit = c.get(probe).map(|s| s.name); Ok(ToolResult::text(json!({"len":c.len(),"capacity":c.capacity(),"hit":hit,"source":"rustre_symbols::SymbolCache"}).to_string())) } }

pub struct SymbolsV7SymbolStatsFromNamesTool;
impl SymbolsV7SymbolStatsFromNamesTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_symbol_stats_from_names".to_string(), description: "SymbolStats::from_symbols with function/data/label mix.".to_string(), input_schema: json!({"type":"object","properties":{"funcs":{"type":"integer"},"data":{"type":"integer"},"labels":{"type":"integer"}}}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SymbolStatsFromNamesTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let f = args.get("funcs").and_then(Value::as_u64).unwrap_or(2); let d = args.get("data").and_then(Value::as_u64).unwrap_or(1); let l = args.get("labels").and_then(Value::as_u64).unwrap_or(1); let mut v: Vec<rustre_symbols::Symbol> = Vec::new(); for i in 0..f { v.push(rustre_symbols::Symbol::new(format!("fn_{i}"), 0x1000 + i, rustre_symbols::SymKind::Function)); } for i in 0..d { v.push(rustre_symbols::Symbol::new(format!("d_{i}"), 0x2000 + i, rustre_symbols::SymKind::Data)); } for i in 0..l { v.push(rustre_symbols::Symbol::new(format!("l_{i}"), 0x3000 + i, rustre_symbols::SymKind::Label)); } let s = rustre_symbols::SymbolStats::from_symbols(&v); Ok(ToolResult::text(json!({"total":s.total,"functions":s.functions,"data":s.data,"labels":s.labels,"display":s.to_string(),"source":"rustre_symbols::SymbolStats"}).to_string())) } }

pub struct SymbolsV7SymbolStoreOpsTool;
impl SymbolsV7SymbolStoreOpsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_symbol_store_ops".to_string(), description: "SymbolStore upsert/find_by_name/find_by_prefix/rename/len.".to_string(), input_schema: json!({"type":"object","properties":{"entries":{"type":"array","items":{"type":"object"}},"prefix":{"type":"string"},"rename_from":{"type":"string"},"rename_to":{"type":"string"},"rename_addr":{"type":"integer"}},"required":["entries"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SymbolStoreOpsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("entries").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("entries".into()))?; let mut st = rustre_symbols::SymbolStore::new(); for e in arr { let n = e.get("name").and_then(Value::as_str).unwrap_or("s").to_string(); let a = e.get("addr").and_then(Value::as_u64).unwrap_or(0); st.upsert(rustre_symbols::Symbol::new(n, a, rustre_symbols::SymKind::Function)); } let pfx = args.get("prefix").and_then(Value::as_str).unwrap_or(""); let by_prefix = st.find_by_prefix(pfx).len(); let mut renamed = false; if let (Some(f), Some(t), Some(a)) = (args.get("rename_from").and_then(Value::as_str), args.get("rename_to").and_then(Value::as_str), args.get("rename_addr").and_then(Value::as_u64)) { renamed = st.rename(a, f, t); } let stats = st.stats(); Ok(ToolResult::text(json!({"len":st.len(),"by_prefix":by_prefix,"renamed":renamed,"stats_total":stats.total,"source":"rustre_symbols::SymbolStore"}).to_string())) } }

pub struct SymbolsV7DebugMergerFinishTool;
impl SymbolsV7DebugMergerFinishTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_debug_merger_finish".to_string(), description: "DebugSymbolMerger merge two sets and finish sorted.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}}},"required":["names"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7DebugMergerFinishTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("names".into()))?; let mut m = rustre_symbols::DebugSymbolMerger::new(); let syms: Vec<rustre_symbols::Symbol> = names.iter().enumerate().filter_map(|(i, v)| v.as_str().map(|s| rustre_symbols::Symbol::new(s.to_string(), (i as u64) * 0x10 + 0x1000, rustre_symbols::SymKind::Function))).collect(); m.merge(syms.clone()); m.merge(syms); let ln = m.len(); let out = m.finish(); Ok(ToolResult::text(json!({"len":ln,"finished":out.len(),"first":out.first().map(|s| s.name.clone()),"source":"rustre_symbols::DebugSymbolMerger"}).to_string())) } }

pub struct SymbolsV7ExportTableLookupTool;
impl SymbolsV7ExportTableLookupTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_export_table_lookup".to_string(), description: "ExportTable from_symbols + by_name + by_ordinal + len.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"},"ordinal":{"type":"integer"}},"required":["name","ordinal"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7ExportTableLookupTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("name".into()))?; let ord = args.get("ordinal").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("ordinal".into()))? as u32; let mut s = rustre_symbols::Symbol::new(name.to_string(), 0x1000, rustre_symbols::SymKind::Function); s.source = rustre_symbols::LegacySymbolSource::Export; s.ordinal = Some(ord); let t = rustre_symbols::ExportTable::from_symbols(&[s]); let by_name = t.by_name(name).map(|x| x.name.clone()); let by_ord = t.by_ordinal(ord).map(|x| x.name.clone()); Ok(ToolResult::text(json!({"len":t.len(),"by_name":by_name,"by_ordinal":by_ord,"source":"rustre_symbols::ExportTable"}).to_string())) } }

pub struct SymbolsV7ImportTableGroupTool;
impl SymbolsV7ImportTableGroupTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_import_table_group".to_string(), description: "ImportTable from_symbols + by_name + grouped_by_module.".to_string(), input_schema: json!({"type":"object","properties":{"entries":{"type":"array","items":{"type":"object"}},"probe":{"type":"string"}},"required":["entries","probe"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7ImportTableGroupTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("entries").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("entries".into()))?; let probe = args.get("probe").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("probe".into()))?; let syms: Vec<rustre_symbols::Symbol> = arr.iter().enumerate().map(|(i, e)| { let n = e.get("name").and_then(Value::as_str).unwrap_or("imp").to_string(); let m = e.get("module").and_then(Value::as_str).map(std::string::ToString::to_string); let mut s = rustre_symbols::Symbol::new(n, 0x1000 + i as u64, rustre_symbols::SymKind::Function); s.source = rustre_symbols::LegacySymbolSource::Import; s.source_file = m; s }).collect(); let t = rustre_symbols::ImportTable::from_symbols(&syms); let modules = t.grouped_by_module().len(); let hit = t.by_name(probe).map(|x| x.name.clone()); Ok(ToolResult::text(json!({"len":t.len(),"modules":modules,"by_name":hit,"source":"rustre_symbols::ImportTable"}).to_string())) } }

pub struct SymbolsV7SectionSymbolsCountTool;
impl SymbolsV7SectionSymbolsCountTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_section_symbols_count".to_string(), description: "SectionSymbols::from_symbols + section_count + in_section.".to_string(), input_schema: json!({"type":"object","properties":{"sections":{"type":"array","items":{"type":"integer"}},"probe":{"type":"integer"}},"required":["sections","probe"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SectionSymbolsCountTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("sections").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("sections".into()))?; let probe = args.get("probe").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("probe".into()))? as u16; let syms: Vec<rustre_symbols::Symbol> = arr.iter().enumerate().filter_map(|(i, v)| v.as_u64().map(|sec| { let mut s = rustre_symbols::Symbol::new(format!("s_{i}"), 0x1000 + i as u64, rustre_symbols::SymKind::Function); s.section_index = Some(sec as u16); s })).collect(); let ss = rustre_symbols::SectionSymbols::from_symbols(&syms); Ok(ToolResult::text(json!({"section_count":ss.section_count(),"in_probe":ss.in_section(probe).len(),"source":"rustre_symbols::SectionSymbols"}).to_string())) } }

pub struct SymbolsV7ConflictStrategiesAllTool;
impl SymbolsV7ConflictStrategiesAllTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_conflict_strategies_all".to_string(), description: "Run SymbolConflictResolver with each ConflictStrategy over the same input.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}},"addr":{"type":"integer"}},"required":["names","addr"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7ConflictStrategiesAllTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("names".into()))?; let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("addr".into()))?; use rustre_symbols::ConflictStrategy as C; let strategies = [C::PreferDebug, C::PreferExport, C::KeepFirst, C::KeepLast, C::KeepAll]; let syms: Vec<rustre_symbols::Symbol> = names.iter().filter_map(|v| v.as_str()).map(|n| rustre_symbols::Symbol::new(n.to_string(), addr, rustre_symbols::SymKind::Function)).collect(); let results: Vec<(String, usize)> = strategies.iter().map(|s| (format!("{s:?}"), rustre_symbols::SymbolConflictResolver::new(*s).resolve(syms.clone()).len())).collect(); Ok(ToolResult::text(json!({"results":results,"source":"rustre_symbols::SymbolConflictResolver"}).to_string())) } }

pub struct SymbolsV7SymbolExporterAllTool;
impl SymbolsV7SymbolExporterAllTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_symbol_exporter_all".to_string(), description: "SymbolExporter::to_json/to_csv/to_idc/to_map output sizes.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}}},"required":["names"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7SymbolExporterAllTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("names".into()))?; let syms: Vec<rustre_symbols::Symbol> = names.iter().enumerate().filter_map(|(i, v)| v.as_str().map(|n| rustre_symbols::Symbol::new(n.to_string(), 0x1000 + i as u64, rustre_symbols::SymKind::Function))).collect(); let json_out = rustre_symbols::SymbolExporter::to_json(&syms).map_err(|e| McpError::InternalError(e.to_string()))?; let csv = rustre_symbols::SymbolExporter::to_csv(&syms); let idc = rustre_symbols::SymbolExporter::to_idc(&syms); let map = rustre_symbols::SymbolExporter::to_map(&syms); Ok(ToolResult::text(json!({"json_len":json_out.len(),"csv_len":csv.len(),"idc_len":idc.len(),"map_len":map.len(),"source":"rustre_symbols::SymbolExporter"}).to_string())) } }

pub struct SymbolsV7PdbServerMsdlTool;
impl SymbolsV7PdbServerMsdlTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_pdb_server_msdl".to_string(), description: "PdbSymbolServer::msdl base_url + pdb_url.".to_string(), input_schema: json!({"type":"object","properties":{"pdb":{"type":"string"},"guid":{"type":"string"},"age":{"type":"integer"}},"required":["pdb","guid","age"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7PdbServerMsdlTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let pdb = args.get("pdb").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("pdb".into()))?; let guid = args.get("guid").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("guid".into()))?; let age = args.get("age").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("age".into()))? as u32; let s = rustre_symbols::PdbSymbolServer::msdl(); Ok(ToolResult::text(json!({"base":s.base_url,"url":s.pdb_url(pdb,guid,age),"source":"rustre_symbols::PdbSymbolServer::msdl"}).to_string())) } }

pub struct SymbolsV7XrefIndexOpsTool;
impl SymbolsV7XrefIndexOpsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_xref_index_ops".to_string(), description: "CrossReferenceIndex add/refs_to/refs_from/ref_count_to/clear.".to_string(), input_schema: json!({"type":"object","properties":{"edges":{"type":"array","items":{"type":"object"}},"target":{"type":"integer"}},"required":["edges","target"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7XrefIndexOpsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let edges = args.get("edges").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("edges".into()))?; let target = args.get("target").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("target".into()))?; let mut x = rustre_symbols::CrossReferenceIndex::new(); for e in edges { let f = e.get("from").and_then(Value::as_u64).unwrap_or(0); let t = e.get("to").and_then(Value::as_u64).unwrap_or(0); x.add_xref(f, t); } let to = x.refs_to(target); let from = x.refs_from(target); let cnt = x.ref_count_to(target); x.clear(); Ok(ToolResult::text(json!({"refs_to":to,"refs_from":from,"ref_count_to":cnt,"cleared_count":x.ref_count_to(target),"source":"rustre_symbols::CrossReferenceIndex"}).to_string())) } }

pub struct SymbolsV7UnifiedSymbolDisplayTool;
impl SymbolsV7UnifiedSymbolDisplayTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_unified_symbol_display".to_string(), description: "UnifiedSymbol::new + display_name + end_address + Display.".to_string(), input_schema: json!({"type":"object","properties":{"name":{"type":"string"},"addr":{"type":"integer"},"size":{"type":"integer"}},"required":["name","addr"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7UnifiedSymbolDisplayTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let name = args.get("name").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("name".into()))?; let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("addr".into()))?; let mut s = rustre_symbols::UnifiedSymbol::new(name.to_string(), addr, rustre_symbols::SymbolKind::Function, rustre_symbols::SymbolSource::Pdb); s.size = args.get("size").and_then(Value::as_u64); Ok(ToolResult::text(json!({"display":s.display_name(),"end":s.end_address(),"full":s.to_string(),"source":"rustre_symbols::UnifiedSymbol"}).to_string())) } }

pub struct SymbolsV7DemanglerPipelineOrderTool;
impl SymbolsV7DemanglerPipelineOrderTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_demangler_pipeline_order".to_string(), description: "DemanglerPipeline set_order + demangle each name.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}}},"required":["names"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7DemanglerPipelineOrderTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("names".into()))?; use rustre_symbols::DemangleStrategy as S; let mut p = rustre_symbols::DemanglerPipeline::new(); p.set_order(vec![S::Rust, S::Msvc, S::Itanium]); let results: Vec<(String, Option<String>)> = names.iter().filter_map(|v| v.as_str().map(|n| (n.to_string(), p.demangle(n)))).collect(); p.clear_cache(); Ok(ToolResult::text(json!({"results":results,"source":"rustre_symbols::DemanglerPipeline"}).to_string())) } }

pub struct SymbolsV7InMemoryProviderOpsTool;
impl SymbolsV7InMemoryProviderOpsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v7_in_memory_provider_ops".to_string(), description: "InMemorySymbolProvider add/sort/remove/rename + SymbolProvider trait lookups.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}},"probe":{"type":"string"},"remove":{"type":"string"}},"required":["names","probe"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV7InMemoryProviderOpsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { use rustre_symbols::SymbolProvider; let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("names".into()))?; let probe = args.get("probe").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("probe".into()))?; let mut p = rustre_symbols::InMemorySymbolProvider::new(); for (i, v) in names.iter().enumerate() { if let Some(n) = v.as_str() { p.add(rustre_symbols::Symbol::new(n.to_string(), 0x1000 + (i as u64) * 0x10, rustre_symbols::SymKind::Function)); } } p.sort_by_address(); let hit = p.lookup_name(probe).map(|s| s.address); let mut removed = false; if let Some(r) = args.get("remove").and_then(Value::as_str) { removed = p.remove_by_name(r); } Ok(ToolResult::text(json!({"len":p.len(),"is_empty":p.is_empty(),"lookup_name":hit,"removed":removed,"all_count":p.all_symbols().len(),"source":"rustre_symbols::InMemorySymbolProvider"}).to_string())) } }

pub fn handlers() -> Vec<(ToolDefinition, Box<dyn ToolHandler>)> {
    vec![
        (SymbolsV7SymbolNewDisplayTool::definition(), Box::new(SymbolsV7SymbolNewDisplayTool)),
        (SymbolsV7SymbolContainsTool::definition(), Box::new(SymbolsV7SymbolContainsTool)),
        (SymbolsV7BindingDisplayTool::definition(), Box::new(SymbolsV7BindingDisplayTool)),
        (SymbolsV7VisibilityDisplayTool::definition(), Box::new(SymbolsV7VisibilityDisplayTool)),
        (SymbolsV7LegacySourceDisplayTool::definition(), Box::new(SymbolsV7LegacySourceDisplayTool)),
        (SymbolsV7SymKindClassifyTool::definition(), Box::new(SymbolsV7SymKindClassifyTool)),
        (SymbolsV7SymbolCacheLruTool::definition(), Box::new(SymbolsV7SymbolCacheLruTool)),
        (SymbolsV7SymbolStatsFromNamesTool::definition(), Box::new(SymbolsV7SymbolStatsFromNamesTool)),
        (SymbolsV7SymbolStoreOpsTool::definition(), Box::new(SymbolsV7SymbolStoreOpsTool)),
        (SymbolsV7DebugMergerFinishTool::definition(), Box::new(SymbolsV7DebugMergerFinishTool)),
        (SymbolsV7ExportTableLookupTool::definition(), Box::new(SymbolsV7ExportTableLookupTool)),
        (SymbolsV7ImportTableGroupTool::definition(), Box::new(SymbolsV7ImportTableGroupTool)),
        (SymbolsV7SectionSymbolsCountTool::definition(), Box::new(SymbolsV7SectionSymbolsCountTool)),
        (SymbolsV7ConflictStrategiesAllTool::definition(), Box::new(SymbolsV7ConflictStrategiesAllTool)),
        (SymbolsV7SymbolExporterAllTool::definition(), Box::new(SymbolsV7SymbolExporterAllTool)),
        (SymbolsV7PdbServerMsdlTool::definition(), Box::new(SymbolsV7PdbServerMsdlTool)),
        (SymbolsV7XrefIndexOpsTool::definition(), Box::new(SymbolsV7XrefIndexOpsTool)),
        (SymbolsV7UnifiedSymbolDisplayTool::definition(), Box::new(SymbolsV7UnifiedSymbolDisplayTool)),
        (SymbolsV7DemanglerPipelineOrderTool::definition(), Box::new(SymbolsV7DemanglerPipelineOrderTool)),
        (SymbolsV7InMemoryProviderOpsTool::definition(), Box::new(SymbolsV7InMemoryProviderOpsTool)),
    ]
}
