//! MCP wrappers for the rustre-symbols_v6 crate.
//! Extracted from `wire_tools.rs` by `workflow_split_wire_tools`.

use rustre_mcp_server::{McpError, ToolDefinition, ToolHandler, ToolResult};
use serde_json::{json, Value};
use async_trait::async_trait;

pub struct SymbolsV6SourcePriorityAllTool;
impl SymbolsV6SourcePriorityAllTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_source_priority_all".to_string(), description: "Return SymbolSource::priority() for all variants.".to_string(), input_schema: json!({"type":"object"}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6SourcePriorityAllTool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { use rustre_symbols::SymbolSource as S; let all = [S::Pdb, S::Dwarf, S::CodeView, S::Stabs, S::Flirt, S::Manual, S::Inferred, S::Import, S::Export, S::Elf, S::Pe, S::Ai]; let v: Vec<(String, u8)> = all.iter().map(|s| (s.to_string(), s.priority())).collect(); Ok(ToolResult::text(json!({"priorities": v, "source":"rustre_symbols::SymbolSource::priority"}).to_string())) } }

pub struct SymbolsV6SynthNamesAllTool;
impl SymbolsV6SynthNamesAllTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_synthetic_names_all".to_string(), description: "Generate function/data/label/dword/qword synthetic names for addr.".to_string(), input_schema: json!({"type":"object","properties":{"addr":{"type":"integer"}},"required":["addr"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6SynthNamesAllTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let a = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("missing 'addr'".into()))?; use rustre_symbols::SyntheticSymbolGen as G; Ok(ToolResult::text(json!({"function":G::function_name(a),"data":G::data_name(a),"label":G::label_name(a),"dword":G::dword_name(a),"qword":G::qword_name(a),"source":"rustre_symbols::SyntheticSymbolGen"}).to_string())) } }

pub struct SymbolsV6TryDemangleBatchTool;
impl SymbolsV6TryDemangleBatchTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_try_demangle_batch".to_string(), description: "Apply rustre_symbols::try_demangle to a batch of names.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}}},"required":["names"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6TryDemangleBatchTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'names'".into()))?; let results: Vec<(String, Option<String>)> = names.iter().filter_map(|v| v.as_str().map(|s| (s.to_string(), rustre_symbols::try_demangle(s)))).collect(); let cnt = results.len(); Ok(ToolResult::text(json!({"results": results, "count": cnt, "source":"rustre_symbols::try_demangle"}).to_string())) } }

pub struct SymbolsV6FunctionBoundaryOpsTool;
impl SymbolsV6FunctionBoundaryOpsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_function_boundary_ops".to_string(), description: "FunctionBoundary::new/size/contains/overlaps.".to_string(), input_schema: json!({"type":"object","properties":{"start":{"type":"integer"},"end":{"type":"integer"},"probe":{"type":"integer"},"o_start":{"type":"integer"},"o_end":{"type":"integer"}},"required":["start","end","probe","o_start","o_end"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6FunctionBoundaryOpsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let s = args.get("start").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("start".into()))?; let e = args.get("end").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("end".into()))?; let p = args.get("probe").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("probe".into()))?; let os = args.get("o_start").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("o_start".into()))?; let oe = args.get("o_end").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("o_end".into()))?; let a = rustre_symbols::FunctionBoundary::new(s, e, "a".into()); let b = rustre_symbols::FunctionBoundary::new(os, oe, "b".into()); Ok(ToolResult::text(json!({"size_a":a.size(),"contains_probe":a.contains(p),"overlaps_ab":a.overlaps(&b),"display_a":a.to_string(),"source":"rustre_symbols::FunctionBoundary"}).to_string())) } }

pub struct SymbolsV6PdbUrlBuildTool;
impl SymbolsV6PdbUrlBuildTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_pdb_url_build".to_string(), description: "Build PDB symbol server URL via PdbSymbolServer::pdb_url.".to_string(), input_schema: json!({"type":"object","properties":{"base":{"type":"string"},"pdb":{"type":"string"},"guid":{"type":"string"},"age":{"type":"integer"}},"required":["pdb","guid","age"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6PdbUrlBuildTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let pdb = args.get("pdb").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("pdb".into()))?; let guid = args.get("guid").and_then(Value::as_str).ok_or_else(|| McpError::InvalidParams("guid".into()))?; let age = args.get("age").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("age".into()))? as u32; let s = if let Some(b) = args.get("base").and_then(Value::as_str) { rustre_symbols::PdbSymbolServer::new(b) } else { rustre_symbols::PdbSymbolServer::msdl() }; let url = s.pdb_url(pdb, guid, age); Ok(ToolResult::text(json!({"url": url, "base": s.base_url, "source":"rustre_symbols::PdbSymbolServer::pdb_url"}).to_string())) } }

pub struct SymbolsV6SymKindDisplayAllTool;
impl SymbolsV6SymKindDisplayAllTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_symkind_display_all".to_string(), description: "Enumerate SymKind Display strings.".to_string(), input_schema: json!({"type":"object"}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6SymKindDisplayAllTool { async fn call(&self, _args: Value) -> Result<ToolResult, McpError> { use rustre_symbols::SymKind as K; let all = [K::Function, K::Data, K::Label, K::Section, K::File, K::Type, K::Namespace, K::TLS, K::IFunc, K::Common, K::Unknown]; let v: Vec<String> = all.iter().map(|k| k.to_string()).collect(); Ok(ToolResult::text(json!({"kinds": v, "source":"rustre_symbols::SymKind"}).to_string())) } }

pub struct SymbolsV6AddrMapLookupTool;
impl SymbolsV6AddrMapLookupTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_addr_map_lookup".to_string(), description: "AddressToSymbolMap::from_symbols + lookup_exact + lookup_floor.".to_string(), input_schema: json!({"type":"object","properties":{"addrs":{"type":"array","items":{"type":"integer"}},"probe":{"type":"integer"}},"required":["addrs","probe"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6AddrMapLookupTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let arr = args.get("addrs").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("addrs".into()))?; let probe = args.get("probe").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("probe".into()))?; let syms: Vec<rustre_symbols::Symbol> = arr.iter().filter_map(|v| v.as_u64()).map(|a| rustre_symbols::Symbol::new(format!("f_{a:x}"), a, rustre_symbols::SymKind::Function)).collect(); let m = rustre_symbols::AddressToSymbolMap::from_symbols(&syms); let exact = m.lookup_exact(probe).map(|s| s.name.clone()); let floor = m.lookup_floor(probe).map(|s| s.name.clone()); Ok(ToolResult::text(json!({"len":m.len(),"exact":exact,"floor":floor,"source":"rustre_symbols::AddressToSymbolMap"}).to_string())) } }

pub struct SymbolsV6ConflictResolveTool;
impl SymbolsV6ConflictResolveTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_conflict_resolve".to_string(), description: "Resolve conflicting symbols via SymbolConflictResolver::KeepFirst.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}},"addr":{"type":"integer"}},"required":["names","addr"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6ConflictResolveTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("names".into()))?; let addr = args.get("addr").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("addr".into()))?; let syms: Vec<rustre_symbols::Symbol> = names.iter().filter_map(|v| v.as_str()).map(|n| rustre_symbols::Symbol::new(n.to_string(), addr, rustre_symbols::SymKind::Function)).collect(); let r = rustre_symbols::SymbolConflictResolver::new(rustre_symbols::ConflictStrategy::KeepFirst).resolve(syms); let out_names: Vec<String> = r.iter().map(|s| s.name.clone()).collect(); let cnt = r.len(); Ok(ToolResult::text(json!({"kept": out_names, "count": cnt, "source":"rustre_symbols::SymbolConflictResolver"}).to_string())) } }

pub struct SymbolsV6UnifiedTableOpsTool;
impl SymbolsV6UnifiedTableOpsTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_unified_table_ops".to_string(), description: "UnifiedSymbolTable add/lookup_name/nearest_below/len.".to_string(), input_schema: json!({"type":"object","properties":{"entries":{"type":"array","items":{"type":"object"}},"probe":{"type":"integer"},"name_q":{"type":"string"}},"required":["entries","probe"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6UnifiedTableOpsTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let entries = args.get("entries").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("entries".into()))?; let probe = args.get("probe").and_then(Value::as_u64).ok_or_else(|| McpError::InvalidParams("probe".into()))?; let mut t = rustre_symbols::UnifiedSymbolTable::new(); for e in entries { let name = e.get("name").and_then(Value::as_str).unwrap_or("s").to_string(); let addr = e.get("addr").and_then(Value::as_u64).unwrap_or(0); t.add(rustre_symbols::UnifiedSymbol::new(name, addr, rustre_symbols::SymbolKind::Function, rustre_symbols::SymbolSource::Manual)); } let nb = t.nearest_below(probe).map(|s| s.name.clone()); let name_q = args.get("name_q").and_then(Value::as_str).unwrap_or(""); let by_name = t.lookup_name(name_q).len(); Ok(ToolResult::text(json!({"len":t.len(),"nearest_below":nb,"by_name_count":by_name,"source":"rustre_symbols::UnifiedSymbolTable"}).to_string())) } }

pub struct SymbolsV6DemangleAllTableTool;
impl SymbolsV6DemangleAllTableTool { #[must_use] pub fn definition() -> ToolDefinition { ToolDefinition { name: "symbols_v6_demangle_all_table".to_string(), description: "Apply demangle_all to a UnifiedSymbolTable built from names.".to_string(), input_schema: json!({"type":"object","properties":{"names":{"type":"array","items":{"type":"string"}}},"required":["names"]}), parameters: Value::Null } } }
#[async_trait] impl ToolHandler for SymbolsV6DemangleAllTableTool { async fn call(&self, args: Value) -> Result<ToolResult, McpError> { let names = args.get("names").and_then(Value::as_array).ok_or_else(|| McpError::InvalidParams("missing 'names'".into()))?; let mut t = rustre_symbols::UnifiedSymbolTable::new(); for (i, v) in names.iter().enumerate() { if let Some(n) = v.as_str() { t.add(rustre_symbols::UnifiedSymbol::new(n.to_string(), (i as u64) * 0x10 + 0x1000, rustre_symbols::SymbolKind::Function, rustre_symbols::SymbolSource::Elf)); } } rustre_symbols::demangle_all(&mut t); let demangled: Vec<(String, Option<String>)> = t.iter_by_address().map(|s| (s.name.clone(), s.demangled_name.clone())).collect(); let ln = t.len(); Ok(ToolResult::text(json!({"results": demangled, "len": ln, "source":"rustre_symbols::demangle_all"}).to_string())) } }

#[must_use]
pub fn handlers() -> Vec<(ToolDefinition, Box<dyn ToolHandler>)> {
    vec![
        (SymbolsV6SourcePriorityAllTool::definition(), Box::new(SymbolsV6SourcePriorityAllTool)),
        (SymbolsV6SynthNamesAllTool::definition(), Box::new(SymbolsV6SynthNamesAllTool)),
        (SymbolsV6TryDemangleBatchTool::definition(), Box::new(SymbolsV6TryDemangleBatchTool)),
        (SymbolsV6FunctionBoundaryOpsTool::definition(), Box::new(SymbolsV6FunctionBoundaryOpsTool)),
        (SymbolsV6PdbUrlBuildTool::definition(), Box::new(SymbolsV6PdbUrlBuildTool)),
        (SymbolsV6SymKindDisplayAllTool::definition(), Box::new(SymbolsV6SymKindDisplayAllTool)),
        (SymbolsV6AddrMapLookupTool::definition(), Box::new(SymbolsV6AddrMapLookupTool)),
        (SymbolsV6ConflictResolveTool::definition(), Box::new(SymbolsV6ConflictResolveTool)),
        (SymbolsV6UnifiedTableOpsTool::definition(), Box::new(SymbolsV6UnifiedTableOpsTool)),
        (SymbolsV6DemangleAllTableTool::definition(), Box::new(SymbolsV6DemangleAllTableTool)),
    ]
}
