[package]
license.workspace = true
name = "rustre-il-llil"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-il = { path = "../rustre-il" }
rustre-core = { path = "../rustre-core" }
rustre-il-lift = { path = "../rustre-il-lift" }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
petgraph = { workspace = true }
bitflags = { workspace = true }
ahash = { workspace = true }

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
