[package]
license.workspace = true
name = "rustre-diff-bindiff"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-diff = { path = "../rustre-diff" }
rustre-core = { path = "../rustre-core" }
petgraph = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
