//! Algebraic properties of the type unifier (T25).
//!
//! # Why properties and not examples
//!
//! The existing tests check specific constraint sets against specific expected
//! types. That catches a wrong answer on the cases someone thought of; it does
//! not catch an equivalence relation that is subtly *not* an equivalence
//! relation.
//!
//! Union-find only means what it is supposed to mean if unification is
//! **reflexive**, **symmetric** and **transitive**, and if solving is
//! **order-independent**. Break any one and the solver still produces answers —
//! just different ones depending on the order constraints happened to arrive in,
//! which is the worst kind of bug: reproducible only sometimes.
//!
//! Order-independence matters concretely here. Constraints are generated by
//! walking instructions, so their order follows the disassembly. Two passes over
//! the same function that reorder anything — a `HashMap` iteration, a parallel
//! chunk — must still produce the same types, or `scan_function_to_engine`'s
//! cross-function merging silently depends on scheduling.

use rustre_analysis_typerecov::type_constraint_generator::{ConstraintKind, TypeConstraint, Provenance};
use rustre_analysis_typerecov::type_unifier::TypeUnifier;
use rustre_analysis_typerecov::{RecoveredType, TypeVar};

fn v(i: u32) -> TypeVar {
    TypeVar::new(i)
}

fn c(id: u32, kind: ConstraintKind) -> TypeConstraint {
    TypeConstraint {
        id,
        kind,
        provenance: Provenance::new(0, "test"),
        confidence: 1.0,
    }
}

fn eq(id: u32, a: u32, b: u32) -> TypeConstraint {
    c(id, ConstraintKind::Equal { lhs: v(a), rhs: v(b) })
}

fn has(id: u32, var: u32, ty: RecoveredType) -> TypeConstraint {
    c(id, ConstraintKind::HasType { var: v(var), ty })
}

fn int(width: u8, signed: bool) -> RecoveredType {
    RecoveredType::Int { width, signed }
}

/// Solve and return the resolved type of each variable, or `None` on error.
fn solve(var_count: u32, constraints: &[TypeConstraint]) -> Option<Vec<RecoveredType>> {
    let mut u = TypeUnifier::new(var_count);
    let res = u.solve(constraints).ok()?;
    Some((0..var_count).map(|i| res.get(v(i)).clone()).collect())
}

// ─── equivalence-relation properties ─────────────────────────────────────────

#[test]
fn unifying_a_variable_with_itself_changes_nothing() {
    // Reflexivity. A self-edge must not corrupt the class or loop forever.
    let base = solve(3, &[has(0, 0, int(4, true))]).expect("solve");
    let with_self = solve(
        3,
        &[has(0, 0, int(4, true)), eq(1, 0, 0), eq(2, 1, 1), eq(3, 2, 2)],
    )
    .expect("solve");
    assert_eq!(base, with_self, "un vincolo riflessivo ha cambiato il risultato");
}

#[test]
fn unification_is_symmetric() {
    // `a = b` and `b = a` must give the same answer. If they differ, the
    // relation is directed and "equal" does not mean equal.
    let ab = solve(2, &[has(0, 0, int(8, false)), eq(1, 0, 1)]).expect("solve");
    let ba = solve(2, &[has(0, 0, int(8, false)), eq(1, 1, 0)]).expect("solve");
    assert_eq!(ab, ba, "a=b e b=a producono risultati diversi");
}

#[test]
fn unification_is_transitive() {
    // a=b, b=c must propagate a's type all the way to c.
    let r = solve(
        3,
        &[has(0, 0, int(4, true)), eq(1, 0, 1), eq(2, 1, 2)],
    )
    .expect("solve");
    assert_eq!(r[0], r[1], "a e b devono condividere il tipo");
    assert_eq!(r[1], r[2], "la transitività non propaga fino a c");
    assert_eq!(r[0], int(4, true));
}

#[test]
fn a_long_chain_propagates_end_to_end() {
    // Transitivity at depth: a 200-link chain must still carry the type, and
    // must not blow the stack — path compression is what makes this cheap.
    const N: u32 = 200;
    let mut cs = vec![has(0, 0, int(2, false))];
    for i in 0..N - 1 {
        cs.push(eq(i + 1, i, i + 1));
    }
    let r = solve(N, &cs).expect("solve");
    assert_eq!(r[(N - 1) as usize], int(2, false), "il tipo non arriva in fondo");
}

// ─── order independence ──────────────────────────────────────────────────────

#[test]
fn the_result_does_not_depend_on_constraint_order() {
    // Constraints are produced by walking instructions; any reordering — a
    // `HashMap`, a parallel chunk — must not change the answer.
    let base = vec![
        has(0, 0, int(4, true)),
        eq(1, 0, 1),
        eq(2, 2, 3),
        eq(3, 1, 2),
        has(4, 4, RecoveredType::Float { width: 8 }),
        eq(5, 4, 5),
    ];
    let expected = solve(6, &base).expect("solve");

    // Deterministic rotations: every cyclic shift of the same set.
    for shift in 1..base.len() {
        let mut rotated = base.clone();
        rotated.rotate_left(shift);
        let got = solve(6, &rotated).expect("solve");
        assert_eq!(
            got, expected,
            "ruotando i vincoli di {shift} il risultato cambia: \
             l'unificazione dipende dall'ordine"
        );
    }

    // And the exact reverse.
    let mut reversed = base.clone();
    reversed.reverse();
    assert_eq!(solve(6, &reversed).expect("solve"), expected);
}

#[test]
fn duplicate_constraints_are_idempotent() {
    // The generator can emit the same fact twice (two instructions, one truth).
    // Applying it twice must equal applying it once.
    let once = solve(2, &[has(0, 0, int(4, false)), eq(1, 0, 1)]).expect("solve");
    let twice = solve(
        2,
        &[
            has(0, 0, int(4, false)),
            has(1, 0, int(4, false)),
            eq(2, 0, 1),
            eq(3, 0, 1),
            eq(4, 1, 0),
        ],
    )
    .expect("solve");
    assert_eq!(once, twice, "ripetere lo stesso vincolo cambia il risultato");
}

// ─── termination and bounds ──────────────────────────────────────────────────

#[test]
fn a_cycle_terminates() {
    // a=b, b=c, c=a. A naive implementation loops forever here; this asserts it
    // returns at all, and that the whole cycle shares one type.
    let r = solve(
        3,
        &[has(0, 0, int(8, true)), eq(1, 0, 1), eq(2, 1, 2), eq(3, 2, 0)],
    )
    .expect("un ciclo deve terminare");
    assert_eq!(r[0], r[1]);
    assert_eq!(r[1], r[2]);
}

#[test]
fn an_empty_constraint_set_resolves_everything_to_unknown() {
    // No information in, no information out — and specifically not a crash or a
    // fabricated type.
    let r = solve(4, &[]).expect("solve");
    for (i, t) in r.iter().enumerate() {
        assert_eq!(*t, RecoveredType::Unknown, "var {i} inventata senza vincoli");
    }
}

#[test]
fn variables_outside_the_declared_range_do_not_panic() {
    // A constraint referencing a var beyond `var_count` is malformed input from
    // the generator's point of view. It must be rejected or ignored, never
    // panic: the generator runs on types recovered from untrusted binaries.
    let mut u = TypeUnifier::new(2);
    let _ = u.solve(&[eq(0, 0, 99), has(1, 50, int(4, true))]);
}

#[test]
fn class_count_never_exceeds_variable_count() {
    // A sanity invariant: merging can only reduce the number of classes.
    let mut u = TypeUnifier::new(6);
    let res = u
        .solve(&[eq(0, 0, 1), eq(1, 2, 3), eq(2, 4, 5)])
        .expect("solve");
    assert!(
        res.class_count <= 6,
        "class_count {} supera il numero di variabili",
        res.class_count
    );
    assert!(res.class_count >= 1, "almeno una classe deve esistere");
}
