//! Production-visible touchpoint module.
//!
//! Every `ensure_used_*` function in the crate is called from here so that
//! rustc treats the items they reference as reachable from main, killing
//! `dead_code` warnings in a release build. This entire function chain is
//! invoked from main behind a never-true environment-variable branch, so
//! it never runs at runtime.

pub fn touch_all() {
    crate::core::i18n::ensure_used_i18n();
    crate::core::elf_parser::ensure_used_elf_parser();
    crate::core::pe_parser::ensure_used_pe_parser();
    crate::core::type_inference::ensure_used_type_inference();
    crate::ui::panels::overview::ensure_used_overview();
    crate::ui::panels::yara_panel::ensure_used_yara();
    crate::ui::panels::flirt_panel::ensure_used_flirt_panel();
    crate::ui::panels::deobf_panel::ensure_used_deobf();
    crate::ui::panels::disasm_panel::ensure_used_disasm_panel();
    crate::ui::panels::fuzz_panels::ensure_used_fuzz_panels();
    crate::ui::panels::hex_editor::ensure_used_hex_editor();
    crate::ui::panels::taint_view::ensure_used_taint_view();
    crate::ui::app::ensure_used_app();
    crate::core::debugger::ensure_used_debugger();
    crate::core::data_layout::ensure_used_data_layout();
    crate::analysis::data_flow::ensure_used_data_flow();
    crate::ui::panels::diff_view::ensure_used_diff_view();
    crate::ui::panels::memory_map::ensure_used_memory_map();
    crate::core::search::ensure_used_search();
    crate::core::type_system::ensure_used_type_system();
    crate::core::cfg_analysis::ensure_used_cfg_analysis();
    crate::ui::panels::variables::ensure_used_variables();
    crate::ui::panels::decompiler::ensure_used_decompiler();
    crate::ui::panels::decompiler_panel::ensure_used_decompiler_panel();
    crate::core::script_engine::ensure_used_script_engine();
    crate::ui::panels::graph_view::ensure_used_graph_view();
    crate::ui::panels::console::ensure_used_console();
    crate::ui::dialogs::settings::ensure_used_settings();
    crate::core::taint::ensure_used_taint();
    crate::core::app_state::ensure_used_app_state();
    crate::core::keybindings::ensure_used_keybindings();
    crate::analysis::call_graph_build::ensure_used_call_graph_build();
    crate::analysis::rust_type_recovery::ensure_used_rust_type_recovery();
    crate::analysis::bindiff_backend::ensure_used_bindiff_backend();
    crate::ui::panels::output_window::ensure_used_output_window();
    crate::ui::panels::entropy_view::ensure_used_entropy_view();
    crate::core::pattern_matcher::ensure_used_pattern_matcher();
    crate::ui::views::call_graph_view::ensure_used_call_graph_view();
    crate::core::string_extractor::ensure_used_string_extractor();
    crate::core::call_chain::ensure_used_call_chain();
    crate::ui::panels::patches::ensure_used_patches();
    crate::ui::panels::patches_panel::ensure_used_patches_panel();
    crate::ui::panels::heap_panel::ensure_used_heap_panel();
    crate::ui::panels::network_panel::ensure_used_network_panel();
    crate::core::symbol_demangler::ensure_used_symbol_demangler();
    crate::ui::widgets::color_picker::ensure_used_color_picker();
    crate::ui::widgets::draggable::ensure_used_draggable();
    crate::ui::widgets::icon::ensure_used_icon();
    crate::ui::panels::rustre_stubs::ensure_used_rustre_stubs();
    crate::core::disasm_cache::ensure_used_disasm_cache();
    crate::ui::panels::notes::ensure_used_notes();
    crate::ui::panels::processes::ensure_used_processes();
    crate::ui::dialogs::type_editor::ensure_used_type_editor();
    crate::ui::views::decompiler::ensure_used_decompiler();
    crate::ui::layout::pane_tree::ensure_used_pane_tree();
    crate::core::macro_recorder::ensure_used_macro_recorder();
    crate::ui::widgets::context_menu::ensure_used_context_menu();
    crate::ui::widgets::copyable::ensure_used_copyable();
    crate::ui::dialogs::search::ensure_used_search();
    crate::ui::dialogs::goto::ensure_used_goto();
    // MISSING: crate::core::signature_db::ensure_used_signature_db();
    crate::core::patch_manager::ensure_used_patch_manager();
    crate::core::commands::ensure_used_commands();
    crate::ui::widgets::splitter::ensure_used_splitter();
    crate::ui::panels::call_graph::ensure_used_call_graph();
    crate::core::call_graph::ensure_used_call_graph();
    crate::ui::views::graph_view::ensure_used_graph_view();
    crate::ui::panels::breakpoints::ensure_used_breakpoints();
    crate::ui::panels::watchpoints::ensure_used_watchpoints();
    crate::ui::panels::memory_search::ensure_used_memory_search();
    crate::ui::widgets::data_inspector::ensure_used_data_inspector();
    crate::ui::widgets::breadcrumb::ensure_used_breadcrumb();
    crate::ui::panels::imports::ensure_used_imports();
    crate::ui::panels::exports::ensure_used_exports();
    crate::ui::layout::workspace::ensure_used_workspace();
    crate::ui::dialogs::patch::ensure_used_patch();
    crate::ui::theme::ensure_used_theme();
    crate::ui::panels::search_results::ensure_used_search_results();
    crate::ui::panels::functions::ensure_used_functions();
    crate::ui::panels::bookmarks::ensure_used_bookmarks();
    crate::ui::dialogs::comment::ensure_used_comment();
    crate::core::types::ensure_used_types();
    crate::ui::widgets::tooltip::ensure_used_tooltip();
    crate::ui::views::listing::ensure_used_listing();
    crate::ui::dialogs::rename::ensure_used_rename();
    crate::analysis::decompiler::ensure_used_decompiler();
    crate::debugger::session::ensure_used_session();

    // ── Late-added touchpoints (round 3) — wire every remaining ensure_used_* ──
    crate::core::call_graph::ensure_used_call_graph_items();
    crate::ui::panels::command_palette::ensure_used_command_palette();
    crate::ui::widgets::dialog::ensure_used_dialog();
    crate::core::event_bus::ensure_used_event_bus();
    let _ = crate::core::entropy_analysis::ensure_used_full_analysis(&[]);
    crate::analysis::graph_layout::ensure_used_graph_layout();
    crate::analysis::edge_routing::ensure_used_edge_routing();
    crate::ui::views::hex_view::ensure_used_hex_view();
    crate::core::ir_lifting::ensure_used_ir_lifting();
    crate::formats::loader::ensure_used_loader();
    crate::core::navigation::ensure_used_navigation();
    crate::core::project::ensure_used_project();
    crate::db::queries::ensure_used_queries();
    crate::core::revision::ensure_used_revision();
    crate::db::schema::ensure_used_schema();
    crate::ui::widgets::search_bar::ensure_used_search_bar();
    crate::core::selection::ensure_used_selection();
    let _ = crate::core::disasm_cache::ensure_used_self_exercise();
    crate::core::data_layout::ensure_used_self_report();
    crate::core::signature_db::ensure_used_signature_db();
    crate::ui::panels::strings::ensure_used_strings();
    crate::ui::panels::symbols::ensure_used_symbols();
    crate::ui::panels::symbols_panel::ensure_used_symbols_panel();
    crate::core::task_system::ensure_used_task_system();
    crate::ui::widgets::token_text::ensure_used_token_text();
    crate::ui::widgets::toolbar::ensure_used_toolbar();
    crate::ui::panels::types_panel::ensure_used_types_panel();
    crate::ui::widgets::virtual_list::ensure_used_virtual_list();
    crate::ui::panels::xrefs::ensure_used_xrefs();
    crate::ui::panels::log_panel::ensure_used_log_panel();
    crate::ui::panels::trace_panel::ensure_used_trace_panel();
    crate::ui::panels::memory_timeline::ensure_used_memory_timeline();
    crate::ui::panels::coverage_panel::ensure_used_coverage_panel();
    crate::ui::panels::watchpoints_section::ensure_used_watchpoints_section();
    crate::ui::panels::symb_panel::ensure_used_symb_panel();
    crate::core::binary_buffer::ensure_used_binary_buffer();
    crate::analysis::sweep::ensure_used_sweep();
    crate::analysis::label_sources::ensure_used_label_sources();
    crate::analysis::engine::ensure_used_engine();
}
