[package]
license.workspace = true
name = "rustre-plugin-native"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
parking_lot = { workspace = true }
libloading = { workspace = true }

[lints.rust]
unsafe_code = "allow"
unused_must_use = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
