[package]
license.workspace = true
name = "rustre-mobile-jadx"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
bitflags = { workspace = true }
petgraph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tempfile = "3"
zip = "2"
rustre-mobile-smali = { path = "../rustre-mobile-smali" }

[lints]
workspace = true
