//! `rustre-arch-x86`
//!
//! Production-quality x86/x64 disassembler built on top of `iced-x86`.
//!
//! Supports 16-bit, 32-bit, and 64-bit modes via [`X86Arch`].
//! Exposes an [`Iterator`]-based [`LinearDisassembler`] for streaming decoding
//! across arbitrary byte slices.

pub mod branch;
pub mod fpu_lifter;
pub mod render;
pub use render::{render_instruction, render_instruction_with_syntax, Syntax};
pub mod length;
pub mod lift;
pub use lift::iced_bytes;
pub mod modrm;
pub mod prefix;
pub mod simd_lifter;
pub mod sse;
pub mod string_ops_lifter;
pub mod system_insn_lifter;
pub mod tables;
pub mod x87;

// Shared re-export stub for the category-lifter sub-modules.
// lift_control_system and lift_fpu_simd are generated by the enterprise
// workflow; we guard their inclusion so the crate compiles even when those
// files are absent.
pub mod lift_data_arith;

/// Complete x86-64 opcode decode lookup table: X86DecodeTable, OpcodeEntry,
/// OpcodeGroup, InstrFormat, PrefixHandler, Escape0F, Escape0F38, Escape0F3A.
pub mod x86_decode_table;

/// Complete x86-64 instruction database: X86InstructionDatabase, FlagEffects,
/// InstrCategory, MemAccess, OpType, OperandConstraint.
pub mod x86_instruction_database;

/// SIMD/AVX decoder: X86SimdDecoder, SimdInsn, SimdGroup, decode_simd().
pub mod x86_simd_decoder;

/// Prefix analyzer: X86PrefixAnalyzer, Prefix, PrefixGroup, parse_prefix_byte().
pub mod x86_prefix_analyzer;

/// CFG builder: X86ControlFlowGraph, X86Block, X86Edge, build_cfg().
pub mod x86_control_flow_graph;

pub use lift::X86Lifter;


use iced_x86::{
    Decoder, DecoderOptions, FlowControl, Formatter, GasFormatter, Instruction as IcedInstruction,
    InstructionInfoFactory, MemorySize, OpAccess, OpKind,
};
use rustre_core::address::Address;
use rustre_core::arch::{
    Architecture, BranchCondition, BranchInfo, CallingConvention, InstrFlags, Instruction,
    LiftContext, LlilOp, RegisterInfo, RegisterKind,
};
use rustre_core::endian::Endian;
use rustre_core::errors::CoreError;

// ---------------------------------------------------------------------------
// FormatterOutput implementation
// ---------------------------------------------------------------------------

/// A thin wrapper around [`String`] that implements [`iced_x86::FormatterOutput`]
/// so we can capture formatted disassembly text.
struct StringOutput(String);

impl StringOutput {
    fn new() -> Self {
        Self(String::with_capacity(64))
    }
}

impl iced_x86::FormatterOutput for StringOutput {
    fn write(&mut self, text: &str, _kind: iced_x86::FormatterTextKind) {
        self.0.push_str(text);
    }
}

// ---------------------------------------------------------------------------
// X86Arch
// ---------------------------------------------------------------------------

/// The primary architecture descriptor.
///
/// Construct with [`X86Arch::new_16bit`], [`X86Arch::new_32bit`], or
/// [`X86Arch::new_64bit`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct X86Arch {
    bits: u32,
}

impl Default for X86Arch {
    fn default() -> Self {
        Self::new_64bit()
    }
}

impl X86Arch {
    /// Create a 16-bit (real-mode / 8086) architecture descriptor.
    #[must_use]
    pub const fn new_16bit() -> Self {
        Self { bits: 16 }
    }

    /// Create a 32-bit (IA-32 / i386) architecture descriptor.
    #[must_use]
    pub const fn new_32bit() -> Self {
        Self { bits: 32 }
    }

    /// Create a 64-bit (AMD64 / x86-64) architecture descriptor.
    #[must_use]
    pub const fn new_64bit() -> Self {
        Self { bits: 64 }
    }

    /// The bitness value (16, 32, or 64).
    #[must_use]
    pub const fn bits(&self) -> u32 {
        self.bits
    }

    /// Decode one instruction at `address` and lift it to a sequence of LLIL
    /// instructions.
    ///
    /// Returns the lifted [`lift::X86Lifter`] output together with the decoded
    /// instruction's byte length. This is the high-level entry point that ties
    /// decoding and lifting together.
    pub fn lift(
        &self,
        address: Address,
        bytes: &[u8],
    ) -> Result<(Vec<rustre_il_llil::LlilAnnotatedInstr>, usize), CoreError> {
        let (iced, len) = self.decode_one(address, bytes)?;
        let mut lifter = lift::X86Lifter::new(self.bits);
        let lifted = lifter.lift(&iced, address, len);
        Ok((lifted, len))
    }

    // ------------------------------------------------------------------
    // Internal helpers
    // ------------------------------------------------------------------

    /// Decode **one** instruction at `address` from `bytes` using iced-x86.
    fn decode_one(
        &self,
        address: Address,
        bytes: &[u8],
    ) -> Result<(IcedInstruction, usize), CoreError> {
        if bytes.is_empty() {
            return Err(CoreError::PluginError {
                plugin: "x86".into(),
                message: "No bytes to disassemble".into(),
            });
        }

        let mut decoder = Decoder::with_ip(self.bits, bytes, address.0, DecoderOptions::NONE);

        let iced = decoder.decode();

        if iced.is_invalid() {
            return Err(CoreError::PluginError {
                plugin: "x86".into(),
                message: format!("Invalid instruction at 0x{:x}", address.0),
            });
        }

        let len = iced.len();
        Ok((iced, len))
    }

    /// Build the GAS (AT&T) formatter used by [`Self::convert`]. Callers that
    /// convert many instructions should build it once and reuse it via
    /// [`Self::convert_with`].
    fn make_formatter() -> GasFormatter {
        let mut formatter = GasFormatter::new();
        formatter
            .options_mut()
            .set_space_after_operand_separator(true);
        formatter.options_mut().set_rip_relative_addresses(true);
        formatter
    }

    /// Convert an [`IcedInstruction`] to our [`Instruction`] type.
    fn convert(&self, address: Address, iced: &IcedInstruction, raw_bytes: &[u8]) -> Instruction {
        let mut formatter = Self::make_formatter();
        self.convert_with(&mut formatter, address, iced, raw_bytes)
    }

    /// Like [`Self::convert`], but reuses a caller-owned formatter (one string
    /// buffer allocation instead of a formatter + buffer per instruction).
    fn convert_with(
        &self,
        formatter: &mut GasFormatter,
        address: Address,
        iced: &IcedInstruction,
        raw_bytes: &[u8],
    ) -> Instruction {
        let len = iced.len();

        let mut output = StringOutput::new();
        formatter.format(iced, &mut output);
        let full_text = output.0;

        // Split on first whitespace: everything before is the mnemonic,
        // everything after is operands.
        let (mnemonic, operands) = split_mnemonic_operands(&full_text);

        let flags = flow_control_to_flags(iced);

        {
            let mut instr = Instruction::new(address, len, mnemonic, raw_bytes[..len].to_vec());
            instr.operands = operands;
            instr.flags = flags;
            instr
        }
    }
}

/// Split a full formatted instruction string into `(mnemonic, operands)`.
/// e.g. `"movq %rax, %rbx"` → `("movq", "%rax, %rbx")`.
fn split_mnemonic_operands(text: &str) -> (String, String) {
    let text = text.trim();
    if let Some(pos) = text.find(|c: char| c.is_whitespace()) {
        let mnemonic = text[..pos].trim().to_string();
        let operands = text[pos..].trim().to_string();
        (mnemonic, operands)
    } else {
        (text.to_string(), String::new())
    }
}

/// Map iced-x86 [`FlowControl`] (plus memory-access information) to our
/// [`InstrFlags`] bit set.
fn flow_control_to_flags(iced: &IcedInstruction) -> InstrFlags {
    let mut flags = InstrFlags::NONE;

    match iced.flow_control() {
        FlowControl::Next => {}
        FlowControl::UnconditionalBranch => {
            flags |= InstrFlags::BRANCH;
        }
        FlowControl::ConditionalBranch => {
            flags |= InstrFlags::BRANCH | InstrFlags::CONDITIONAL;
        }
        FlowControl::Call => {
            flags |= InstrFlags::BRANCH | InstrFlags::CALL;
        }
        FlowControl::Return => {
            flags |= InstrFlags::RET;
        }
        FlowControl::IndirectBranch => {
            flags |= InstrFlags::BRANCH | InstrFlags::INDIRECT;
        }
        FlowControl::IndirectCall => {
            flags |= InstrFlags::BRANCH | InstrFlags::CALL | InstrFlags::INDIRECT;
        }
        FlowControl::XbeginXabortXend => {
            flags |= InstrFlags::BRANCH | InstrFlags::CONDITIONAL;
        }
        FlowControl::Exception => {
            flags |= InstrFlags::BARRIER;
        }
        FlowControl::Interrupt => {
            flags |= InstrFlags::BARRIER;
        }
    }

    // Determine memory-access flags via InstructionInfoFactory.
    let mut factory = InstructionInfoFactory::new();
    let info = factory.info(iced);

    let has_mem_read = info.used_memory().iter().any(|m| {
        matches!(
            m.access(),
            OpAccess::Read | OpAccess::CondRead | OpAccess::ReadWrite | OpAccess::ReadCondWrite
        )
    });
    let has_mem_write = info.used_memory().iter().any(|m| {
        matches!(
            m.access(),
            OpAccess::Write | OpAccess::CondWrite | OpAccess::ReadWrite | OpAccess::ReadCondWrite
        )
    });

    // Fall back to opkind heuristic when InstructionInfoFactory finds nothing
    // (e.g. push/pop on some microarchitectures).
    let memory_operand_present = (0..iced.op_count()).any(|i| {
        iced.op_kind(i) == OpKind::Memory
            || iced.op_kind(i) == OpKind::MemorySegSI
            || iced.op_kind(i) == OpKind::MemorySegESI
            || iced.op_kind(i) == OpKind::MemorySegRSI
            || iced.op_kind(i) == OpKind::MemorySegDI
            || iced.op_kind(i) == OpKind::MemorySegEDI
            || iced.op_kind(i) == OpKind::MemorySegRDI
            || iced.op_kind(i) == OpKind::MemoryESDI
            || iced.op_kind(i) == OpKind::MemoryESEDI
            || iced.op_kind(i) == OpKind::MemoryESRDI
    });

    if has_mem_read {
        flags |= InstrFlags::READ_MEM;
    }
    if has_mem_write {
        flags |= InstrFlags::WRITE_MEM;
    }
    // Fallback: InstructionInfoFactory found no memory accesses but a memory
    // operand is present. We cannot reliably determine directionality without
    // inspecting the mnemonic, so we conservatively set only READ_MEM to avoid
    // falsely marking write-only instructions (e.g. MOV [mem], reg) as readers.
    if !has_mem_read && !has_mem_write && memory_operand_present && iced.memory_size() != MemorySize::Unknown {
        flags |= InstrFlags::READ_MEM;
    }

    flags
}

/// Extract branch targets from a decoded iced instruction.
/// Returns a list of [`BranchInfo`] entries (may be empty for non-branches).
fn extract_branches(iced: &IcedInstruction) -> Vec<BranchInfo> {
    let mut out = Vec::new();

    match iced.flow_control() {
        FlowControl::UnconditionalBranch => {
            let target = iced.near_branch_target();
            if target != 0 {
                out.push(BranchInfo::unconditional_jump(target));
            }
        }
        FlowControl::ConditionalBranch => {
            let target = iced.near_branch_target();
            if target != 0 {
                out.push(BranchInfo::conditional_jump(
                    target,
                    BranchCondition::Custom(0),
                ));
            }
        }
        FlowControl::Call => {
            let target = iced.near_branch_target();
            if target != 0 {
                out.push(BranchInfo::call(target));
            }
        }
        FlowControl::XbeginXabortXend => {
            let target = iced.near_branch_target();
            if target != 0 {
                out.push(BranchInfo::conditional_jump(
                    target,
                    BranchCondition::Custom(0),
                ));
            }
        }
        // Indirect / Return / Exception / Next → no static target
        _ => {}
    }

    out
}

// ---------------------------------------------------------------------------
// Architecture impl
// ---------------------------------------------------------------------------

impl Architecture for X86Arch {
    fn name(&self) -> &str {
        match self.bits {
            16 => "x86_16",
            32 => "x86_32",
            64 => "x86_64",
            _ => "x86_unknown",
        }
    }

    fn pointer_size(&self) -> usize {
        match self.bits {
            16 => 2,
            32 => 4,
            64 => 8,
            _ => 8,
        }
    }

    fn endian(&self) -> Endian {
        Endian::Little
    }

    fn disassemble(&self, address: Address, bytes: &[u8]) -> Result<Instruction, CoreError> {
        let (iced, _len) = self.decode_one(address, bytes)?;
        Ok(self.convert(address, &iced, bytes))
    }

    fn get_branches(&self, instr: &Instruction) -> Vec<BranchInfo> {
        // Re-decode the instruction so we can call extract_branches on the
        // iced type.  The raw bytes are stored in the Instruction itself.
        if instr.bytes.is_empty() {
            return vec![];
        }
        match self.decode_one(instr.address, &instr.bytes) {
            Ok((iced, _)) => extract_branches(&iced),
            Err(_) => {
                // Graceful degradation: if re-decode somehow fails, fall back
                // to parsing the operands string that the old stub used.
                fallback_branches(instr)
            }
        }
    }

    fn registers(&self) -> Vec<RegisterInfo> {
        match self.bits {
            16 => registers_16bit(),
            32 => registers_32bit(),
            64 => registers_64bit(),
            _ => registers_64bit(),
        }
    }

    fn calling_conventions(&self) -> Vec<CallingConvention> {
        match self.bits {
            16 => vec![],
            32 => calling_conventions_32bit(),
            64 => calling_conventions_64bit(),
            _ => calling_conventions_64bit(),
        }
    }

    /// Lift a single instruction to LLIL operations via [`X86LiftAdapter`].
    ///
    /// This is the primary cross-crate integration point: it re-decodes the
    /// raw instruction bytes stored in `instr.bytes` with iced-x86, then
    /// dispatches to [`X86LiftAdapter::adapt_iced_to_llil`] which converts the
    /// iced representation to the [`LlilOp`] / [`IrExpr`] types from
    /// `rustre-core`.  The resulting ops are deposited into `ctx` so that
    /// callers can accumulate multiple instructions in one pass.
    ///
    /// # Errors
    ///
    /// Returns [`CoreError::PluginError`] if the bytes cannot be decoded by
    /// iced-x86.
    fn lift(&self, instr: &Instruction, ctx: &mut LiftContext) -> Result<Vec<LlilOp>, CoreError> {
        if instr.bytes.is_empty() {
            return Err(CoreError::PluginError {
                plugin: "x86".into(),
                message: "lift: instruction has no bytes".into(),
            });
        }

        // Re-decode with iced-x86 at the instruction's virtual address.
        let iced = X86LiftAdapter::decode_one_iced(self.bits, &instr.bytes, instr.address.0)
            .ok_or_else(|| CoreError::PluginError {
                plugin: "x86".into(),
                message: format!(
                    "lift: iced-x86 could not decode bytes at {:#x}",
                    instr.address.0
                ),
            })?;

        // Translate to LlilOp via the adapter.
        let ops = X86LiftAdapter::adapt_iced_to_llil(&iced, ctx);

        // Deposit each op into the context so label resolution works across
        // multiple calls.
        for op in &ops {
            ctx.emit(op.clone());
        }

        Ok(ops)
    }
}

// ---------------------------------------------------------------------------
// X86LiftAdapter
// ---------------------------------------------------------------------------

/// Bridges the gap between the `rustre-arch-x86` [`Instruction`] type (which
/// stores raw bytes) and the flat [`LlilOp`] / [`LiftContext`] types from
/// `rustre-core`.
///
/// The adapter re-decodes the raw instruction bytes with `iced-x86`, then
/// translates the result to the flat `rustre-core` [`LlilOp`] representation
/// (using `GetReg(u32)` / `SetReg(u32)` / `Jump(u64)` / etc.) and deposits
/// the ops into the caller-supplied [`LiftContext`].
///
/// # Register ID scheme
///
/// | Hardware register group | IDs   |
/// |-------------------------|-------|
/// | RAX / EAX / AX / AL    | 0–3   |
/// | RBX / EBX / BX / BL    | 4–7   |
/// | RCX / ECX / CX / CL    | 8–11  |
/// | RDX / EDX / DX / DL    | 12–15 |
/// | RSI / ESI / SI / SIL   | 16–19 |
/// | RDI / EDI / DI / DIL   | 20–23 |
/// | RSP (all aliases)       | 24    |
/// | RBP (all aliases)       | 25    |
/// | R8–R15 (all aliases)    | 26–33 |
/// | RIP / EIP               | 34    |
/// | RFLAGS / EFLAGS / FLAGS | 35    | (reserved; iced-x86 exposes no flags Register variant) |
/// | XMM0–XMM15              | 36–51 |
/// | YMM0–YMM15              | 52–67 |
pub struct X86LiftAdapter {
    bits: u32,
}

impl X86LiftAdapter {
    /// Create an adapter for the given bitness (16, 32, or 64).
    #[must_use]
    pub const fn new(bits: u32) -> Self {
        Self { bits }
    }

    /// The bitness (16, 32, or 64) this adapter was constructed for.
    #[must_use]
    pub const fn bits(&self) -> u32 {
        self.bits
    }

    /// Decode one iced-x86 instruction from `bytes` at virtual address `ip`.
    ///
    /// Returns `None` if the bytes are empty or the decode produces an invalid
    /// instruction.
    #[must_use]
    pub fn decode_one_iced(bits: u32, bytes: &[u8], ip: u64) -> Option<IcedInstruction> {
        if bytes.is_empty() {
            return None;
        }
        let mut decoder = Decoder::with_ip(bits, bytes, ip, DecoderOptions::NONE);
        if !decoder.can_decode() {
            return None;
        }
        let iced = decoder.decode();
        if iced.is_invalid() { None } else { Some(iced) }
    }

    /// Map an iced-x86 register to a canonical `u32` register identifier.
    ///
    /// Returns [`u32::MAX`] for registers not covered by the scheme (segment
    /// registers, FPU stack, MMX, ZMM, debug and control registers).
    #[must_use]
    pub const fn reg_id(reg: iced_x86::Register) -> u32 {
        use iced_x86::Register as R;
        match reg {
            // ── RAX family ──────────────────────────────────────────────────
            R::RAX => 0,
            R::EAX => 1,
            R::AX => 2,
            R::AL => 3,
            // AH accesses bits 8-15 of AX — distinct from AL (bits 0-7); unique ID 68
            R::AH => 68,
            // ── RBX family ──────────────────────────────────────────────────
            R::RBX => 4,
            R::EBX => 5,
            R::BX => 6,
            R::BL => 7,
            // BH accesses bits 8-15 of BX — distinct from BL; unique ID 69
            R::BH => 69,
            // ── RCX family ──────────────────────────────────────────────────
            R::RCX => 8,
            R::ECX => 9,
            R::CX => 10,
            R::CL => 11,
            // CH accesses bits 8-15 of CX — distinct from CL; unique ID 70
            R::CH => 70,
            // ── RDX family ──────────────────────────────────────────────────
            R::RDX => 12,
            R::EDX => 13,
            R::DX => 14,
            R::DL => 15,
            // DH accesses bits 8-15 of DX — distinct from DL; unique ID 71
            R::DH => 71,
            // ── RSI family ──────────────────────────────────────────────────
            R::RSI => 16,
            R::ESI => 17,
            R::SI => 18,
            R::SIL => 19,
            // ── RDI family ──────────────────────────────────────────────────
            R::RDI => 20,
            R::EDI => 21,
            R::DI => 22,
            R::DIL => 23,
            // ── RSP — all size aliases share id 24 ──────────────────────────
            R::RSP | R::ESP | R::SP | R::SPL => 24,
            // ── RBP — all size aliases share id 25 ──────────────────────────
            R::RBP | R::EBP | R::BP | R::BPL => 25,
            // ── R8–R15 ──────────────────────────────────────────────────────
            R::R8 | R::R8D | R::R8W | R::R8L => 26,
            R::R9 | R::R9D | R::R9W | R::R9L => 27,
            R::R10 | R::R10D | R::R10W | R::R10L => 28,
            R::R11 | R::R11D | R::R11W | R::R11L => 29,
            R::R12 | R::R12D | R::R12W | R::R12L => 30,
            R::R13 | R::R13D | R::R13W | R::R13L => 31,
            R::R14 | R::R14D | R::R14W | R::R14L => 32,
            R::R15 | R::R15D | R::R15W | R::R15L => 33,
            // ── RIP / EIP ───────────────────────────────────────────────────
            R::RIP | R::EIP => 34,
            // ── RFLAGS / EFLAGS / FLAGS — ID 35 reserved ────────────────────
            // iced-x86 does not expose RFLAGS/EFLAGS/FLAGS as Register variants;
            // they are tracked implicitly via InstructionInfoFactory. ID 35 is
            // reserved in the scheme for future use when an explicit flags
            // register becomes available.
            // ── XMM0–XMM15 ──────────────────────────────────────────────────
            R::XMM0 => 36,
            R::XMM1 => 37,
            R::XMM2 => 38,
            R::XMM3 => 39,
            R::XMM4 => 40,
            R::XMM5 => 41,
            R::XMM6 => 42,
            R::XMM7 => 43,
            R::XMM8 => 44,
            R::XMM9 => 45,
            R::XMM10 => 46,
            R::XMM11 => 47,
            R::XMM12 => 48,
            R::XMM13 => 49,
            R::XMM14 => 50,
            R::XMM15 => 51,
            // ── YMM0–YMM15 ──────────────────────────────────────────────────
            R::YMM0 => 52,
            R::YMM1 => 53,
            R::YMM2 => 54,
            R::YMM3 => 55,
            R::YMM4 => 56,
            R::YMM5 => 57,
            R::YMM6 => 58,
            R::YMM7 => 59,
            R::YMM8 => 60,
            R::YMM9 => 61,
            R::YMM10 => 62,
            R::YMM11 => 63,
            R::YMM12 => 64,
            R::YMM13 => 65,
            R::YMM14 => 66,
            R::YMM15 => 67,
            // ── Everything else ─────────────────────────────────────────────
            _ => u32::MAX,
        }
    }

    /// Adapt a decoded `iced-x86` instruction to a `Vec<LlilOp>` using the
    /// flat `rustre-core` [`LlilOp`] representation.
    ///
    /// This is the central bridging function between the two crates.  The flat
    /// representation uses `GetReg(id)` / `SetReg(id)` pairs and constant
    /// instruction variants rather than expression trees, keeping the output
    /// compatible with `rustre-core`'s consumer interfaces.
    #[must_use]
    pub fn adapt_iced_to_llil(iced_instr: &IcedInstruction, _ctx: &mut LiftContext) -> Vec<LlilOp> {
        use iced_x86::Mnemonic as M;

        /// Emit `GetReg(id)` for the register at operand `n`, or a `Const(0)` for
        /// an immediate zero / unresolvable operand.
        fn src_reg(instr: &IcedInstruction, n: u32) -> LlilOp {
            match instr.op_kind(n) {
                OpKind::Register => {
                    LlilOp::GetReg(X86LiftAdapter::reg_id(instr.op_register(n)))
                }
                // A memory source is an honest memory read in the flat IR,
                // not a garbage constant (`immediate()` on a memory operand
                // returns 0/meaningless data).
                OpKind::Memory => LlilOp::Load,
                _ => LlilOp::Const(i128::from(instr.immediate(n))),
            }
        }

        /// Register id for operand `n`.
        fn reg_id_n(instr: &IcedInstruction, n: u32) -> u32 {
            if instr.op_kind(n) == OpKind::Register {
                X86LiftAdapter::reg_id(instr.op_register(n))
            } else {
                u32::MAX
            }
        }

        match iced_instr.mnemonic() {
            // ── data movement ──────────────────────────────────────────────
            M::Mov | M::Movsx | M::Movsxd | M::Movzx => {
                // dst = src : emit GetReg(src) followed by SetReg(dst)
                let src = src_reg(iced_instr, 1);
                let dst_id = reg_id_n(iced_instr, 0);
                if dst_id == u32::MAX {
                    // Memory destination: model as a Store
                    vec![src, LlilOp::Store]
                } else {
                    vec![src, LlilOp::SetReg(dst_id)]
                }
            }
            M::Lea => {
                // LEA dst, [mem]: for the flat IR we emit a Const(0) and SetReg.
                // A richer analysis pass resolves the effective address separately.
                let dst_id = reg_id_n(iced_instr, 0);
                vec![LlilOp::Const(0), LlilOp::SetReg(dst_id)]
            }
            M::Xchg => {
                let id0 = reg_id_n(iced_instr, 0);
                let id1 = reg_id_n(iced_instr, 1);
                // Correct swap using the flat stack IR:
                //   Push id1's original value first, then id0's original.
                //   SetReg(id1) pops id0's value → id1 now holds id0's original.
                //   SetReg(id0) pops id1's value → id0 now holds id1's original.
                // Both originals are read before any register is written,
                // avoiding the bug where GetReg(id1) after SetReg(id1) would
                // return the already-overwritten value.
                vec![
                    LlilOp::GetReg(id1),
                    LlilOp::GetReg(id0),
                    LlilOp::SetReg(id1),
                    LlilOp::SetReg(id0),
                ]
            }
            M::Push => {
                // RSP -= size; [RSP] = src
                let src = src_reg(iced_instr, 0);
                vec![
                    LlilOp::GetReg(24),
                    LlilOp::Sub,
                    LlilOp::SetReg(24),
                    src,
                    LlilOp::Store,
                ]
            }
            M::Pop => {
                // dst = [RSP]; RSP += size
                let dst_id = reg_id_n(iced_instr, 0);
                vec![
                    LlilOp::Load,
                    LlilOp::SetReg(dst_id),
                    LlilOp::GetReg(24),
                    LlilOp::Add,
                    LlilOp::SetReg(24),
                ]
            }
            // ── arithmetic ─────────────────────────────────────────────────
            M::Add | M::Adc => {
                let dst_id = reg_id_n(iced_instr, 0);
                let src = src_reg(iced_instr, 1);
                vec![
                    LlilOp::GetReg(dst_id),
                    src,
                    LlilOp::Add,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Sub | M::Sbb => {
                let dst_id = reg_id_n(iced_instr, 0);
                let src = src_reg(iced_instr, 1);
                vec![
                    LlilOp::GetReg(dst_id),
                    src,
                    LlilOp::Sub,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Inc => {
                let dst_id = reg_id_n(iced_instr, 0);
                vec![
                    LlilOp::GetReg(dst_id),
                    LlilOp::Const(1),
                    LlilOp::Add,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Dec => {
                let dst_id = reg_id_n(iced_instr, 0);
                vec![
                    LlilOp::GetReg(dst_id),
                    LlilOp::Const(1),
                    LlilOp::Sub,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Neg => {
                let dst_id = reg_id_n(iced_instr, 0);
                vec![
                    LlilOp::Const(0),
                    LlilOp::GetReg(dst_id),
                    LlilOp::Sub,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Mul | M::Imul => {
                // One-operand form: RAX = RAX * src (high half in RDX not
                // representable in the flat IR — quotient-register write is
                // the honest single-destination approximation). Two/three
                // operand IMUL keeps its explicit destination.
                if iced_instr.op_count() == 1 {
                    let rax = X86LiftAdapter::reg_id(iced_x86::Register::RAX);
                    vec![
                        LlilOp::GetReg(rax),
                        src_reg(iced_instr, 0),
                        LlilOp::Mul,
                        LlilOp::SetReg(rax),
                    ]
                } else {
                    let dst_id = reg_id_n(iced_instr, 0);
                    let (a, b) = if iced_instr.op_count() >= 3 {
                        (src_reg(iced_instr, 1), src_reg(iced_instr, 2))
                    } else {
                        (LlilOp::GetReg(dst_id), src_reg(iced_instr, 1))
                    };
                    vec![a, b, LlilOp::Mul, LlilOp::SetReg(dst_id)]
                }
            }
            M::Div | M::Idiv => {
                // Always one-operand: RAX = RAX / src (remainder in RDX not
                // representable in the flat IR).
                let rax = X86LiftAdapter::reg_id(iced_x86::Register::RAX);
                vec![
                    LlilOp::GetReg(rax),
                    src_reg(iced_instr, 0),
                    LlilOp::Div,
                    LlilOp::SetReg(rax),
                ]
            }
            // ── logic ──────────────────────────────────────────────────────
            M::And => {
                let dst_id = reg_id_n(iced_instr, 0);
                let src = src_reg(iced_instr, 1);
                vec![
                    LlilOp::GetReg(dst_id),
                    src,
                    LlilOp::And,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Or => {
                let dst_id = reg_id_n(iced_instr, 0);
                let src = src_reg(iced_instr, 1);
                vec![
                    LlilOp::GetReg(dst_id),
                    src,
                    LlilOp::Or,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Xor => {
                let dst_id = reg_id_n(iced_instr, 0);
                // xor reg, reg → zero
                if iced_instr.op0_register() == iced_instr.op1_register() {
                    vec![LlilOp::Const(0), LlilOp::SetReg(dst_id)]
                } else {
                    let src = src_reg(iced_instr, 1);
                    vec![
                        LlilOp::GetReg(dst_id),
                        src,
                        LlilOp::Xor,
                        LlilOp::SetReg(dst_id),
                    ]
                }
            }
            M::Not => {
                let dst_id = reg_id_n(iced_instr, 0);
                vec![LlilOp::GetReg(dst_id), LlilOp::Not, LlilOp::SetReg(dst_id)]
            }
            M::Cmp | M::Test => {
                // These only set flags; no register is written in the flat IR.
                let id0 = reg_id_n(iced_instr, 0);
                let src = src_reg(iced_instr, 1);
                vec![LlilOp::GetReg(id0), src, LlilOp::Sub]
            }
            // ── shifts ─────────────────────────────────────────────────────
            M::Shl | M::Sal => {
                let dst_id = reg_id_n(iced_instr, 0);
                let count = if iced_instr.op_count() > 1 {
                    src_reg(iced_instr, 1)
                } else {
                    LlilOp::Const(1)
                };
                vec![
                    LlilOp::GetReg(dst_id),
                    count,
                    LlilOp::Lsl,
                    LlilOp::SetReg(dst_id),
                ]
            }
            M::Shr | M::Sar => {
                let dst_id = reg_id_n(iced_instr, 0);
                let count = if iced_instr.op_count() > 1 {
                    src_reg(iced_instr, 1)
                } else {
                    LlilOp::Const(1)
                };
                // SAR is sign-preserving — lifting it as Lsr corrupts every
                // negative value; use the dedicated Asr op.
                let shift = if iced_instr.mnemonic() == M::Sar {
                    LlilOp::Asr
                } else {
                    LlilOp::Lsr
                };
                vec![
                    LlilOp::GetReg(dst_id),
                    count,
                    shift,
                    LlilOp::SetReg(dst_id),
                ]
            }
            // ── control flow ───────────────────────────────────────────────
            M::Jmp => {
                let target = iced_instr.near_branch64();
                vec![LlilOp::Jump(target)]
            }
            M::Call => {
                let target = iced_instr.near_branch64();
                vec![LlilOp::Call(target)]
            }
            M::Ret | M::Retf => {
                vec![LlilOp::Return]
            }
            // ── conditional branches (Jcc) — all map to a generic Jump ─────
            M::Je
            | M::Jne
            | M::Jb
            | M::Jae
            | M::Jbe
            | M::Ja
            | M::Js
            | M::Jns
            | M::Jp
            | M::Jnp
            | M::Jl
            | M::Jge
            | M::Jle
            | M::Jg
            | M::Jo
            | M::Jno
            | M::Jcxz
            | M::Jecxz
            | M::Jrcxz => {
                vec![LlilOp::Jump(iced_instr.near_branch64())]
            }
            // ── system ─────────────────────────────────────────────────────
            M::Syscall | M::Sysenter => {
                vec![LlilOp::Syscall]
            }
            M::Nop | M::Fnop | M::Pause => {
                vec![LlilOp::Nop]
            }
            // ── fallback ───────────────────────────────────────────────────
            // The flat LlilOp stub has no Unknown/Intrinsic variant, so
            // unlisted mnemonics necessarily degrade to Nop. This adapter is
            // a coarse rustre-core bridge; the full-fidelity lifter is
            // `lift.rs` (LlilExpr trees), which dispatches every mnemonic.
            _ => vec![LlilOp::Nop],
        }
    }
}

/// Last-resort branch extraction from formatted operands string.
fn fallback_branches(instr: &Instruction) -> Vec<BranchInfo> {
    if !instr.flags.contains(InstrFlags::BRANCH) {
        return vec![];
    }
    // Try to parse "0x<hex>" or plain hex address from operands.
    let operands = instr.operands.trim();
    let hex_str = operands
        .strip_prefix("0x")
        .or_else(|| operands.strip_prefix("0X"))
        .unwrap_or(operands);
    if let Ok(addr_val) = u64::from_str_radix(hex_str, 16) {
        let bi = if instr.flags.contains(InstrFlags::CALL) {
            BranchInfo::call(addr_val)
        } else if instr.flags.contains(InstrFlags::CONDITIONAL) {
            BranchInfo::conditional_jump(addr_val, BranchCondition::Custom(0))
        } else {
            BranchInfo::unconditional_jump(addr_val)
        };
        vec![bi]
    } else {
        vec![]
    }
}

// ---------------------------------------------------------------------------
// Register tables
// ---------------------------------------------------------------------------

fn reg(name: &str, size: usize, id: u32) -> RegisterInfo {
    RegisterInfo::new(name, id, size, RegisterKind::General)
}

/// Full x86-16 register list.
fn registers_16bit() -> Vec<RegisterInfo> {
    vec![
        reg("ax", 2, 0),
        reg("bx", 2, 1),
        reg("cx", 2, 2),
        reg("dx", 2, 3),
        reg("si", 2, 4),
        reg("di", 2, 5),
        reg("bp", 2, 6),
        reg("sp", 2, 7),
        reg("ip", 2, 8),
        reg("flags", 2, 9),
        reg("al", 1, 10),
        reg("ah", 1, 11),
        reg("bl", 1, 12),
        reg("bh", 1, 13),
        reg("cl", 1, 14),
        reg("ch", 1, 15),
        reg("dl", 1, 16),
        reg("dh", 1, 17),
        reg("cs", 2, 18),
        reg("ds", 2, 19),
        reg("es", 2, 20),
        reg("fs", 2, 21),
        reg("gs", 2, 22),
        reg("ss", 2, 23),
        reg("st0", 10, 24),
        reg("st1", 10, 25),
        reg("st2", 10, 26),
        reg("st3", 10, 27),
        reg("st4", 10, 28),
        reg("st5", 10, 29),
        reg("st6", 10, 30),
        reg("st7", 10, 31),
    ]
}

/// Full x86-32 register list.
fn registers_32bit() -> Vec<RegisterInfo> {
    let mut regs = vec![
        // General-purpose 32-bit
        reg("eax", 4, 0),
        reg("ebx", 4, 1),
        reg("ecx", 4, 2),
        reg("edx", 4, 3),
        reg("esi", 4, 4),
        reg("edi", 4, 5),
        reg("ebp", 4, 6),
        reg("esp", 4, 7),
        reg("eip", 4, 8),
        reg("eflags", 4, 9),
        // 16-bit sub-registers
        reg("ax", 2, 10),
        reg("bx", 2, 11),
        reg("cx", 2, 12),
        reg("dx", 2, 13),
        reg("si", 2, 14),
        reg("di", 2, 15),
        reg("bp", 2, 16),
        reg("sp", 2, 17),
        // 8-bit sub-registers
        reg("al", 1, 18),
        reg("ah", 1, 19),
        reg("bl", 1, 20),
        reg("bh", 1, 21),
        reg("cl", 1, 22),
        reg("ch", 1, 23),
        reg("dl", 1, 24),
        reg("dh", 1, 25),
        // Segment registers
        reg("cs", 2, 26),
        reg("ds", 2, 27),
        reg("es", 2, 28),
        reg("fs", 2, 29),
        reg("gs", 2, 30),
        reg("ss", 2, 31),
        // Control registers
        reg("cr0", 4, 32),
        reg("cr2", 4, 33),
        reg("cr3", 4, 34),
        reg("cr4", 4, 35),
        // Debug registers
        reg("dr0", 4, 36),
        reg("dr1", 4, 37),
        reg("dr2", 4, 38),
        reg("dr3", 4, 39),
        reg("dr6", 4, 40),
        reg("dr7", 4, 41),
        // x87 FPU
        reg("st0", 10, 42),
        reg("st1", 10, 43),
        reg("st2", 10, 44),
        reg("st3", 10, 45),
        reg("st4", 10, 46),
        reg("st5", 10, 47),
        reg("st6", 10, 48),
        reg("st7", 10, 49),
    ];
    // MMX
    for i in 0u32..8 {
        regs.push(reg(&format!("mm{i}"), 8, 50 + i));
    }
    // XMM (SSE)
    for i in 0u32..8 {
        regs.push(reg(&format!("xmm{i}"), 16, 58 + i));
    }
    regs
}

/// Full x86-64 register list (GPR, segment, control, debug, FPU, MMX,
/// SSE/AVX/AVX-512, MPX, opmask).
#[must_use]
pub fn registers_64bit() -> Vec<RegisterInfo> {
    let mut regs = Vec::with_capacity(256);
    let mut id = 0u32;

    // --- 64-bit GPRs ---
    for name in &[
        "rax", "rbx", "rcx", "rdx", "rsi", "rdi", "rsp", "rbp", "r8", "r9", "r10", "r11", "r12",
        "r13", "r14", "r15", "rip", "rflags",
    ] {
        regs.push(reg(name, 8, id));
        id += 1;
    }

    // --- 32-bit sub-registers ---
    for name in &[
        "eax", "ebx", "ecx", "edx", "esi", "edi", "esp", "ebp", "r8d", "r9d", "r10d", "r11d",
        "r12d", "r13d", "r14d", "r15d", "eip", "eflags",
    ] {
        regs.push(reg(name, 4, id));
        id += 1;
    }

    // --- 16-bit sub-registers ---
    for name in &[
        "ax", "bx", "cx", "dx", "si", "di", "sp", "bp", "r8w", "r9w", "r10w", "r11w", "r12w",
        "r13w", "r14w", "r15w",
    ] {
        regs.push(reg(name, 2, id));
        id += 1;
    }

    // --- 8-bit sub-registers ---
    for name in &[
        "al", "ah", "bl", "bh", "cl", "ch", "dl", "dh", "sil", "dil", "spl", "bpl", "r8b", "r9b",
        "r10b", "r11b", "r12b", "r13b", "r14b", "r15b",
    ] {
        regs.push(reg(name, 1, id));
        id += 1;
    }

    // --- Segment registers ---
    for name in &["cs", "ds", "es", "fs", "gs", "ss"] {
        regs.push(reg(name, 2, id));
        id += 1;
    }

    // --- Control registers ---
    for name in &["cr0", "cr2", "cr3", "cr4", "cr8"] {
        regs.push(reg(name, 8, id));
        id += 1;
    }

    // --- Debug registers ---
    for name in &["dr0", "dr1", "dr2", "dr3", "dr6", "dr7"] {
        regs.push(reg(name, 8, id));
        id += 1;
    }

    // --- x87 FPU stack ---
    for i in 0u32..8 {
        regs.push(reg(&format!("st{i}"), 10, id));
        id += 1;
    }

    // --- MMX ---
    for i in 0u32..8 {
        regs.push(reg(&format!("mm{i}"), 8, id));
        id += 1;
    }

    // --- XMM (SSE / SSE2) ---
    for i in 0u32..16 {
        regs.push(reg(&format!("xmm{i}"), 16, id));
        id += 1;
    }

    // --- YMM (AVX) ---
    for i in 0u32..16 {
        regs.push(reg(&format!("ymm{i}"), 32, id));
        id += 1;
    }

    // --- ZMM (AVX-512) ---
    for i in 0u32..32 {
        regs.push(reg(&format!("zmm{i}"), 64, id));
        id += 1;
    }

    // --- AVX-512 opmask registers ---
    for i in 0u32..8 {
        regs.push(reg(&format!("k{i}"), 8, id));
        id += 1;
    }

    // --- MPX bound registers ---
    for i in 0u32..4 {
        regs.push(reg(&format!("bnd{i}"), 16, id));
        id += 1;
    }

    regs
}

// ---------------------------------------------------------------------------
// Calling conventions
// ---------------------------------------------------------------------------

fn calling_conventions_32bit() -> Vec<CallingConvention> {
    vec![
        // cdecl: caller cleans the stack
        CallingConvention::new("cdecl")
            .with_int_args(vec![])
            .with_return_regs(vec!["eax".to_string(), "edx".to_string()]),
        // stdcall: callee cleans the stack
        {
            let mut cc = CallingConvention::new("stdcall")
                .with_int_args(vec![])
                .with_return_regs(vec!["eax".to_string()]);
            cc.caller_cleans_stack = false;
            cc
        },
        // fastcall: first two args in ECX, EDX; rest on stack
        {
            let mut cc = CallingConvention::new("fastcall")
                .with_int_args(vec!["ecx".to_string(), "edx".to_string()])
                .with_return_regs(vec!["eax".to_string()]);
            cc.caller_cleans_stack = false;
            cc
        },
        // thiscall (MSVC): this pointer in ECX
        {
            let mut cc = CallingConvention::new("thiscall")
                .with_int_args(vec!["ecx".to_string()])
                .with_return_regs(vec!["eax".to_string()]);
            cc.caller_cleans_stack = false;
            cc
        },
    ]
}

fn calling_conventions_64bit() -> Vec<CallingConvention> {
    vec![
        // System V AMD64 ABI (Linux, macOS, BSD)
        CallingConvention::new("sysv_amd64")
            .with_int_args(vec![
                "rdi".to_string(),
                "rsi".to_string(),
                "rdx".to_string(),
                "rcx".to_string(),
                "r8".to_string(),
                "r9".to_string(),
            ])
            .with_return_regs(vec!["rax".to_string(), "rdx".to_string()]),
        // Microsoft x64 ABI (Windows)
        CallingConvention::new("ms_x64")
            .with_int_args(vec![
                "rcx".to_string(),
                "rdx".to_string(),
                "r8".to_string(),
                "r9".to_string(),
            ])
            .with_return_regs(vec!["rax".to_string()]),
        // Syscall (Linux kernel interface)
        CallingConvention::new("syscall")
            .with_int_args(vec![
                "rdi".to_string(),
                "rsi".to_string(),
                "rdx".to_string(),
                "r10".to_string(),
                "r8".to_string(),
                "r9".to_string(),
            ])
            .with_return_regs(vec!["rax".to_string()]),
    ]
}

// ---------------------------------------------------------------------------
// LinearDisassembler
// ---------------------------------------------------------------------------

/// Streaming, iterator-based linear disassembler.
///
/// Decodes instructions sequentially from a byte slice, advancing by the
/// length of each successfully decoded instruction.  On decode error the
/// iterator yields `Err(CoreError)` and halts (does not advance past the
/// bad byte).
///
/// # Example
/// ```no_run
/// use rustre_arch_x86::{X86Arch, LinearDisassembler};
/// use rustre_core::address::Address;
///
/// let code: &[u8] = &[0x55, 0x48, 0x89, 0xe5, 0x90, 0xc3];
/// let arch = X86Arch::new_64bit();
/// let base = Address::new(0x1000);
/// for result in LinearDisassembler::new(&arch, code, base) {
///     let instr = result.unwrap();
///     println!("{:?}", instr);
/// }
/// ```
pub struct LinearDisassembler<'a> {
    arch: &'a X86Arch,
    bytes: &'a [u8],
    base_addr: Address,
    offset: usize,
    formatter: GasFormatter,
}

impl<'a> LinearDisassembler<'a> {
    /// Create a new linear disassembler.
    #[must_use]
    pub fn new(arch: &'a X86Arch, bytes: &'a [u8], base_addr: Address) -> Self {
        Self {
            arch,
            bytes,
            base_addr,
            offset: 0,
            formatter: X86Arch::make_formatter(),
        }
    }

    /// Return the current byte offset within the provided slice.
    #[must_use]
    pub const fn offset(&self) -> usize {
        self.offset
    }

    /// Return the current virtual address (base + offset).
    #[must_use]
    pub const fn current_address(&self) -> Address {
        Address::new(self.base_addr.0.wrapping_add(self.offset as u64))
    }

    /// Return `true` if there are no more bytes to decode.
    #[must_use]
    pub const fn is_done(&self) -> bool {
        self.offset >= self.bytes.len()
    }
}

impl Iterator for LinearDisassembler<'_> {
    type Item = Result<Instruction, CoreError>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.offset >= self.bytes.len() {
            return None;
        }

        let remaining = &self.bytes[self.offset..];
        let cur_addr = Address::new(self.base_addr.0.wrapping_add(self.offset as u64));

        match self.arch.decode_one(cur_addr, remaining) {
            Ok((ref iced, len)) => {
                let instr =
                    self.arch
                        .convert_with(&mut self.formatter, cur_addr, iced, remaining);
                self.offset += len;
                Some(Ok(instr))
            }
            Err(e) => {
                // Do not advance — let the caller decide what to do.
                Some(Err(e))
            }
        }
    }
}

// ---------------------------------------------------------------------------
// New top-level lifter API (wires lift_data_arith / lift_control_system /
// lift_fpu_simd dispatch together into a single entry point).
// ---------------------------------------------------------------------------

/// Lift a single decoded `iced-x86` instruction via the main `X86Lifter`.
///
/// Returns a `Vec<LlilAnnotatedInstr>`. Delegates to the fully-implemented
/// [`lift::X86Lifter`]; the category sub-modules
/// (`lift_data_arith` / `lift_control_system` / `lift_fpu_simd`) are filled in
/// incrementally by the enterprise workflow.
#[must_use]
pub fn lift_to_llil(instr: &iced_x86::Instruction) -> Vec<rustre_il_llil::LlilAnnotatedInstr> {
    // Infer the bitness from the decoded instruction so 16/32-bit code is not
    // lifted with 64-bit pointer/stack widths. `CodeSize::Unknown` (e.g. an
    // `Instruction` built by hand rather than by a `Decoder`) falls back to 64.
    let bits = match instr.code_size() {
        iced_x86::CodeSize::Code16 => 16,
        iced_x86::CodeSize::Code32 => 32,
        _ => 64,
    };
    lift_to_llil_with_bits(instr, bits)
}

/// Like [`lift_to_llil`] but with an explicit target bitness (16, 32, or 64).
#[must_use]
pub fn lift_to_llil_with_bits(
    instr: &iced_x86::Instruction,
    bits: u32,
) -> Vec<rustre_il_llil::LlilAnnotatedInstr> {
    let mut lifter = X86Lifter::new(bits);
    lifter.lift(instr, Address::new(instr.ip()), instr.len())
}

/// Come [`lift_to_llil_with_bits`], ma i temporanei partono da `base` e la funzione
/// restituisce anche **quanti** ne ha allocati, cosi' che il chiamante possa filare la
/// numerazione all'istruzione successiva (#4400: senza questo, ogni istruzione riparte
/// da `Temporary(0)` e i nomi `tmp{n}` collidono).
///
/// `base` viene passato come **parametro**, non letto dall'ambiente: la logica resta
/// testabile senza variabili globali.
#[must_use]
pub fn lift_to_llil_from_base(
    instr: &iced_x86::Instruction,
    bits: u32,
    base: u32,
) -> (Vec<rustre_il_llil::LlilAnnotatedInstr>, u32) {
    let mut lifter = X86Lifter::with_temp_base(bits, base);
    let ops = lifter.lift(instr, Address::new(instr.ip()), instr.len());
    (ops, lifter.temp_count())
}

/// High-level architecture-aware lifter struct.
///
/// Wraps `lift_to_llil` and carries the target bitness so that callers can
/// query architecture metadata alongside lifting.
pub struct ArchX86Lifter {
    pub bits: u8,
}

impl ArchX86Lifter {
    /// Create a new lifter for the given bitness (16, 32, or 64).
    #[must_use]
    pub const fn new(bits: u8) -> Self {
        Self { bits }
    }

    /// Lift a single decoded instruction.
    #[must_use]
    pub fn lift_instruction(
        &self,
        instr: &iced_x86::Instruction,
    ) -> Vec<rustre_il_llil::LlilAnnotatedInstr> {
        lift_to_llil_with_bits(instr, u32::from(self.bits))
    }

    /// Returns the canonical architecture name for the configured bitness.
    #[must_use]
    pub const fn arch_name(&self) -> &str {
        match self.bits {
            64 => "x86_64",
            32 => "x86",
            16 => "x86_16",
            _ => "x86",
        }
    }
}

/// Decode and lift every instruction in `bytes` starting at virtual address
/// `ip` in `bits`-bit mode.
///
/// Returns a `Vec` of `(instruction_ip, Vec<LlilOp>)` pairs, one entry per
/// successfully decoded instruction.  Stops at the first invalid encoding.
#[must_use]
pub fn disassemble_and_lift(
    bytes: &[u8],
    ip: u64,
    bits: u8,
) -> Vec<(u64, Vec<rustre_il_llil::LlilAnnotatedInstr>)> {
    use iced_x86::{Decoder, DecoderOptions};
    let mut decoder = Decoder::with_ip(u32::from(bits), bytes, ip, DecoderOptions::NONE);
    let mut results = Vec::new();
    // Gate OPT-IN `RUSTRE_X86_TMPUNIQ` (#4400/#4410): quando acceso, la numerazione dei
    // temporanei prosegue da un'istruzione alla successiva invece di ripartire da 0,
    // eliminando la collisione dei nomi `tmp{n}`. Default SPENTO: accenderlo cambia
    // l'emissione di ENTRAMBI i path, quindi la decisione non e' automatica.
    let uniq = matches!(
        std::env::var("RUSTRE_X86_TMPUNIQ").as_deref(),
        Ok("1" | "true")
    );
    let mut base = 0u32;
    while decoder.can_decode() {
        let instr = decoder.decode();
        if instr.is_invalid() {
            break;
        }
        let ops = if uniq {
            let (ops, next) = lift_to_llil_from_base(&instr, u32::from(bits), base);
            base = next;
            ops
        } else {
            lift_to_llil_with_bits(&instr, u32::from(bits))
        };
        results.push((instr.ip(), ops));
    }
    results
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // Convenience helper
    fn x64() -> X86Arch {
        X86Arch::new_64bit()
    }
    fn x32() -> X86Arch {
        X86Arch::new_32bit()
    }

    // ------------------------------------------------------------------
    // Flat adapter (adapt_iced_to_llil) regressions
    // ------------------------------------------------------------------

    fn adapt(bytes: &[u8]) -> Vec<LlilOp> {
        let iced = X86LiftAdapter::decode_one_iced(64, bytes, 0x1000).unwrap();
        let mut ctx = LiftContext::new(Address(0x1000), "x86_64");
        X86LiftAdapter::adapt_iced_to_llil(&iced, &mut ctx)
    }

    #[test]
    fn test_adapter_sar_uses_asr_not_lsr() {
        // 48 d1 f8 — sar rax, 1
        let ops = adapt(&[0x48, 0xD1, 0xF8]);
        assert!(ops.contains(&LlilOp::Asr), "SAR must lift to Asr: {ops:?}");
        assert!(!ops.contains(&LlilOp::Lsr));
        // 48 d1 e8 — shr rax, 1 stays logical
        let ops = adapt(&[0x48, 0xD1, 0xE8]);
        assert!(ops.contains(&LlilOp::Lsr));
    }

    #[test]
    fn test_adapter_memory_source_is_load_not_const() {
        // 48 03 03 — add rax, [rbx]
        let ops = adapt(&[0x48, 0x03, 0x03]);
        assert!(ops.contains(&LlilOp::Load), "memory src must be Load: {ops:?}");
        assert!(
            !ops.iter().any(|o| matches!(o, LlilOp::Const(_))),
            "memory src must not become a garbage constant"
        );
    }

    #[test]
    fn test_adapter_one_operand_mul_div_use_accumulator() {
        let rax = X86LiftAdapter::reg_id(iced_x86::Register::RAX);
        // 48 f7 e3 — mul rbx (one-operand: rax = rax * rbx)
        let ops = adapt(&[0x48, 0xF7, 0xE3]);
        assert!(ops.contains(&LlilOp::GetReg(rax)), "mul reads rax: {ops:?}");
        assert!(ops.contains(&LlilOp::SetReg(rax)), "mul writes rax: {ops:?}");
        // 48 f7 f3 — div rbx
        let ops = adapt(&[0x48, 0xF7, 0xF3]);
        assert!(ops.contains(&LlilOp::GetReg(rax)));
        assert!(ops.contains(&LlilOp::SetReg(rax)));
        assert!(ops.contains(&LlilOp::Div));
    }

    // ------------------------------------------------------------------
    // Basic architecture properties
    // ------------------------------------------------------------------

    #[test]
    fn test_64bit_pointer_size() {
        assert_eq!(x64().pointer_size(), 8);
    }

    #[test]
    fn test_32bit_pointer_size() {
        assert_eq!(x32().pointer_size(), 4);
    }

    #[test]
    fn test_16bit_pointer_size() {
        assert_eq!(X86Arch::new_16bit().pointer_size(), 2);
    }

    #[test]
    fn test_endianness() {
        assert_eq!(x64().endian(), Endian::Little);
        assert_eq!(x32().endian(), Endian::Little);
    }

    #[test]
    fn test_names() {
        assert_eq!(X86Arch::new_16bit().name(), "x86_16");
        assert_eq!(X86Arch::new_32bit().name(), "x86_32");
        assert_eq!(X86Arch::new_64bit().name(), "x86_64");
    }

    // ------------------------------------------------------------------
    // NOP  (0x90)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_nop() {
        let arch = x64();
        let instr = arch.disassemble(Address::new(0x1000), &[0x90]).unwrap();
        assert_eq!(instr.mnemonic, "nop", "mnemonic should be nop");
        assert_eq!(instr.size, 1);
        assert_eq!(instr.address.0, 0x1000);
        assert_eq!(instr.bytes, vec![0x90u8]);
        assert_eq!(instr.flags & InstrFlags::BRANCH, InstrFlags::NONE);
        assert_eq!(instr.flags & InstrFlags::RET, InstrFlags::NONE);
    }

    // ------------------------------------------------------------------
    // RET  (0xC3)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_ret() {
        let arch = x64();
        let instr = arch.disassemble(Address::new(0x1001), &[0xc3]).unwrap();
        assert_eq!(instr.mnemonic, "ret");
        assert_eq!(instr.size, 1);
        assert!(
            instr.flags.contains(InstrFlags::RET),
            "ret must have RETURN flag"
        );
        assert!(
            !instr.flags.contains(InstrFlags::BRANCH),
            "ret must NOT have BRANCH flag"
        );
    }

    // ------------------------------------------------------------------
    // CALL rel32  (E8 xx xx xx xx)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_call_rel32() {
        let arch = x64();
        // CALL to self + 5 + (-5) = 0x1000  (i.e. offset = 0xFFFFFFFB = -5)
        let bytes: &[u8] = &[0xe8, 0xfb, 0xff, 0xff, 0xff];
        let base = Address::new(0x1005);
        let instr = arch.disassemble(base, bytes).unwrap();
        assert_eq!(instr.size, 5);
        assert_eq!(instr.bytes, bytes);
        assert!(
            instr.flags.contains(InstrFlags::BRANCH),
            "call must have BRANCH"
        );
        assert!(
            instr.flags.contains(InstrFlags::CALL),
            "call must have CALL"
        );
        assert!(
            !instr.flags.contains(InstrFlags::CONDITIONAL),
            "direct call must not be CONDITIONAL"
        );

        let branches = arch.get_branches(&instr);
        assert_eq!(branches.len(), 1);
        assert_eq!(
            branches[0].target,
            Some(0x1005),
            "branch target should be 0x1005"
        );
        assert_eq!(branches[0].kind, rustre_core::arch::BranchKind::Call);
        assert!(branches[0].is_unconditional());
    }

    // ------------------------------------------------------------------
    // JMP short  (EB xx)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_jmp_short() {
        let arch = x64();
        // JMP +5 (from 0x2000, size=2, target = 0x2000 + 2 + 5 = 0x2007)
        let bytes: &[u8] = &[0xeb, 0x05];
        let base = Address::new(0x2000);
        let instr = arch.disassemble(base, bytes).unwrap();
        assert_eq!(instr.size, 2);
        assert!(instr.flags.contains(InstrFlags::BRANCH));
        assert!(!instr.flags.contains(InstrFlags::CONDITIONAL));
        assert!(!instr.flags.contains(InstrFlags::CALL));

        let branches = arch.get_branches(&instr);
        assert_eq!(branches.len(), 1);
        assert_eq!(branches[0].target, Some(0x2007));
        assert!(branches[0].is_unconditional());
        assert_ne!(branches[0].kind, rustre_core::arch::BranchKind::Call);
    }

    // ------------------------------------------------------------------
    // JZ short  (74 xx)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_jz_short() {
        let arch = x64();
        // JZ +3 (from 0x3000, target = 0x3000 + 2 + 3 = 0x3005)
        let bytes: &[u8] = &[0x74, 0x03];
        let base = Address::new(0x3000);
        let instr = arch.disassemble(base, bytes).unwrap();
        assert_eq!(instr.size, 2);
        assert!(
            instr.flags.contains(InstrFlags::BRANCH),
            "jz must be BRANCH"
        );
        assert!(
            instr.flags.contains(InstrFlags::CONDITIONAL),
            "jz must be CONDITIONAL"
        );
        assert!(!instr.flags.contains(InstrFlags::CALL));

        let branches = arch.get_branches(&instr);
        assert_eq!(branches.len(), 1);
        assert_eq!(branches[0].target, Some(0x3005));
        assert!(!branches[0].is_unconditional());
        assert_ne!(branches[0].kind, rustre_core::arch::BranchKind::Call);
    }

    // ------------------------------------------------------------------
    // JNZ short  (75 xx)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_jnz_short() {
        let arch = x64();
        let bytes: &[u8] = &[0x75, 0x0a];
        let base = Address::new(0x4000);
        let instr = arch.disassemble(base, bytes).unwrap();
        assert!(instr.flags.contains(InstrFlags::BRANCH));
        assert!(instr.flags.contains(InstrFlags::CONDITIONAL));
        let branches = arch.get_branches(&instr);
        assert_eq!(branches.len(), 1);
        assert_eq!(branches[0].target, Some(0x400c));
        assert!(!branches[0].is_unconditional());
    }

    // ------------------------------------------------------------------
    // MOV rax, rbx  (48 89 C3) — actually MOV rbx, rax (AT&T src, dst swap)
    // Standard encoding: REX.W + 89 /r  =>  MOV r/m64, r64
    // 48 89 C3 = MOV rbx, rax  (dst=rbx, src=rax in Intel syntax)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_mov_rax_rbx() {
        let arch = x64();
        // REX.W 89 C3  — MOV rbx, rax (Intel)  /  movq %rax, %rbx (GAS)
        let bytes: &[u8] = &[0x48, 0x89, 0xc3];
        let instr = arch.disassemble(Address::new(0x5000), bytes).unwrap();
        assert_eq!(instr.size, 3);
        // Should not be a branch or return.
        assert!(!instr.flags.contains(InstrFlags::BRANCH));
        assert!(!instr.flags.contains(InstrFlags::RET));
        // Mnemonic should be some variant of "mov".
        assert!(
            instr.mnemonic.contains("mov"),
            "mnemonic '{}' should contain 'mov'",
            instr.mnemonic
        );
    }

    // ------------------------------------------------------------------
    // PUSH RBP  (55) — writes to memory
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_push_rbp() {
        let arch = x64();
        let instr = arch.disassemble(Address::new(0x6000), &[0x55]).unwrap();
        assert_eq!(instr.size, 1);
        assert!(!instr.flags.contains(InstrFlags::BRANCH));
        // push writes to the stack (memory)
        assert!(
            instr.flags.contains(InstrFlags::WRITE_MEM),
            "push must have WRITE_MEM; flags = {:?}",
            instr.flags
        );
    }

    // ------------------------------------------------------------------
    // POP RBP  (5D) — reads from memory
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_pop_rbp() {
        let arch = x64();
        let instr = arch.disassemble(Address::new(0x6001), &[0x5d]).unwrap();
        assert_eq!(instr.size, 1);
        assert!(!instr.flags.contains(InstrFlags::BRANCH));
        assert!(
            instr.flags.contains(InstrFlags::READ_MEM),
            "pop must have READ_MEM; flags = {:?}",
            instr.flags
        );
    }

    // ------------------------------------------------------------------
    // Error on empty input
    // ------------------------------------------------------------------

    #[test]
    fn test_empty_bytes_error() {
        let arch = x64();
        let result = arch.disassemble(Address::new(0x1000), &[]);
        assert!(result.is_err(), "empty bytes should return an error");
    }

    // ------------------------------------------------------------------
    // InstrFlags: BRANCH|CALL vs BRANCH only
    // ------------------------------------------------------------------

    #[test]
    fn test_instrflags_call_vs_jmp() {
        let arch = x64();
        // CALL rel32
        let call_bytes: &[u8] = &[0xe8, 0x00, 0x00, 0x00, 0x00];
        let call_instr = arch.disassemble(Address::new(0x1000), call_bytes).unwrap();
        assert!(
            call_instr
                .flags
                .contains(InstrFlags::BRANCH | InstrFlags::CALL)
        );

        // JMP short
        let jmp_bytes: &[u8] = &[0xeb, 0x00];
        let jmp_instr = arch.disassemble(Address::new(0x1000), jmp_bytes).unwrap();
        assert!(jmp_instr.flags.contains(InstrFlags::BRANCH));
        assert!(!jmp_instr.flags.contains(InstrFlags::CALL));
    }

    // ------------------------------------------------------------------
    // LinearDisassembler
    // ------------------------------------------------------------------

    #[test]
    fn test_linear_disassembler_function_prologue() {
        // Typical x86-64 function prologue:
        //   55           push rbp
        //   48 89 e5     mov rbp, rsp
        //   48 83 ec 20  sub rsp, 0x20
        //   90           nop
        //   c3           ret
        let code: &[u8] = &[0x55, 0x48, 0x89, 0xe5, 0x48, 0x83, 0xec, 0x20, 0x90, 0xc3];
        let arch = x64();
        let base = Address::new(0x1000);
        let instrs: Vec<_> = LinearDisassembler::new(&arch, code, base)
            .collect::<Result<Vec<_>, _>>()
            .expect("all instructions should decode cleanly");

        // We should decode exactly 5 instructions.
        assert_eq!(instrs.len(), 5, "expected 5 instructions in prologue");

        // First: push rbp at 0x1000
        assert_eq!(instrs[0].address.0, 0x1000);
        assert_eq!(instrs[0].size, 1);
        assert!(instrs[0].mnemonic.contains("push"));

        // Second: mov rbp, rsp at 0x1001
        assert_eq!(instrs[1].address.0, 0x1001);
        assert_eq!(instrs[1].size, 3);
        assert!(instrs[1].mnemonic.contains("mov"));

        // Third: sub rsp, 0x20 at 0x1004
        assert_eq!(instrs[2].address.0, 0x1004);
        assert_eq!(instrs[2].size, 4);
        assert!(instrs[2].mnemonic.contains("sub"));

        // Fourth: nop at 0x1008
        assert_eq!(instrs[3].address.0, 0x1008);
        assert_eq!(instrs[3].size, 1);
        assert_eq!(instrs[3].mnemonic, "nop");

        // Fifth: ret at 0x1009
        assert_eq!(instrs[4].address.0, 0x1009);
        assert_eq!(instrs[4].size, 1);
        assert!(instrs[4].flags.contains(InstrFlags::RET));
    }

    #[test]
    fn test_linear_disassembler_offset_tracking() {
        let code: &[u8] = &[0x90, 0x90, 0x90]; // three NOPs
        let arch = x64();
        let base = Address::new(0x2000);
        let mut ld = LinearDisassembler::new(&arch, code, base);

        let i0 = ld.next().unwrap().unwrap();
        assert_eq!(i0.address.0, 0x2000);
        assert_eq!(ld.offset(), 1);

        let i1 = ld.next().unwrap().unwrap();
        assert_eq!(i1.address.0, 0x2001);
        assert_eq!(ld.offset(), 2);

        let i2 = ld.next().unwrap().unwrap();
        assert_eq!(i2.address.0, 0x2002);
        assert_eq!(ld.offset(), 3);

        // Iterator exhausted
        assert!(ld.next().is_none());
        assert!(ld.is_done());
    }

    #[test]
    fn test_linear_disassembler_contains_branches() {
        // call  0x10  (E8 0B 00 00 00 — from 0x1000, target 0x1010)
        // nop         (90)
        // ret         (C3)
        let code: &[u8] = &[0xe8, 0x0b, 0x00, 0x00, 0x00, 0x90, 0xc3];
        let arch = x64();
        let base = Address::new(0x1000);
        let instrs: Vec<_> = LinearDisassembler::new(&arch, code, base)
            .collect::<Result<Vec<_>, _>>()
            .unwrap();

        assert_eq!(instrs.len(), 3);

        // CALL
        let call = &instrs[0];
        assert!(call.flags.contains(InstrFlags::BRANCH | InstrFlags::CALL));
        let branches = arch.get_branches(call);
        assert_eq!(branches.len(), 1);
        assert_eq!(branches[0].target, Some(0x1010));

        // NOP
        assert_eq!(instrs[1].flags, InstrFlags::NONE);

        // RET
        assert!(instrs[2].flags.contains(InstrFlags::RET));
    }

    // ------------------------------------------------------------------
    // 32-bit mode decoding
    // ------------------------------------------------------------------

    #[test]
    fn test_32bit_mode_call() {
        let arch = x32();
        // E8 05 00 00 00  CALL +5 (from 0x1000, target = 0x100A)
        let bytes: &[u8] = &[0xe8, 0x05, 0x00, 0x00, 0x00];
        let instr = arch.disassemble(Address::new(0x1000), bytes).unwrap();
        assert_eq!(instr.size, 5);
        assert!(instr.flags.contains(InstrFlags::BRANCH | InstrFlags::CALL));
        let branches = arch.get_branches(&instr);
        assert_eq!(branches.len(), 1);
        assert_eq!(branches[0].target, Some(0x100a));
    }

    #[test]
    fn test_32bit_pointer_size_and_name() {
        let arch = x32();
        assert_eq!(arch.pointer_size(), 4);
        assert_eq!(arch.name(), "x86_32");
    }

    // ------------------------------------------------------------------
    // Register lists
    // ------------------------------------------------------------------

    #[test]
    fn test_registers_64bit_count() {
        let regs = registers_64bit();
        // Should have well over 100 registers.
        assert!(
            regs.len() > 100,
            "expected >100 registers, got {}",
            regs.len()
        );
    }

    #[test]
    fn test_registers_64bit_has_rax() {
        let regs = registers_64bit();
        assert!(regs.iter().any(|r| r.name == "rax" && r.size == 8));
    }

    #[test]
    fn test_registers_64bit_has_zmm0() {
        let regs = registers_64bit();
        assert!(regs.iter().any(|r| r.name == "zmm0" && r.size == 64));
    }

    #[test]
    fn test_registers_64bit_has_k0() {
        let regs = registers_64bit();
        assert!(regs.iter().any(|r| r.name == "k0"));
    }

    #[test]
    fn test_registers_64bit_unique_ids() {
        let regs = registers_64bit();
        let mut ids: Vec<u32> = regs.iter().map(|r| r.id).collect();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), regs.len(), "register IDs must be unique");
    }

    // ------------------------------------------------------------------
    // Calling conventions
    // ------------------------------------------------------------------

    #[test]
    fn test_calling_conventions_64bit() {
        let arch = x64();
        let ccs = arch.calling_conventions();
        assert!(!ccs.is_empty());
        let sysv = ccs.iter().find(|c| c.name == "sysv_amd64").unwrap();
        assert_eq!(sysv.int_args[0], "rdi");
        assert!(sysv.caller_cleans_stack);

        let ms = ccs.iter().find(|c| c.name == "ms_x64").unwrap();
        assert_eq!(ms.int_args[0], "rcx");
    }

    #[test]
    fn test_calling_conventions_32bit() {
        let arch = x32();
        let ccs = arch.calling_conventions();
        let cdecl = ccs.iter().find(|c| c.name == "cdecl").unwrap();
        assert!(cdecl.caller_cleans_stack);
        let stdcall = ccs.iter().find(|c| c.name == "stdcall").unwrap();
        assert!(!stdcall.caller_cleans_stack);
        let fastcall = ccs.iter().find(|c| c.name == "fastcall").unwrap();
        assert_eq!(fastcall.int_args[0], "ecx");
        assert_eq!(fastcall.int_args[1], "edx");
    }

    // ------------------------------------------------------------------
    // JMP near (E9) — 32-bit operand
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_jmp_near() {
        let arch = x64();
        // E9 05 00 00 00 — JMP +5 from 0x1000 → target 0x100A
        let bytes: &[u8] = &[0xe9, 0x05, 0x00, 0x00, 0x00];
        let instr = arch.disassemble(Address::new(0x1000), bytes).unwrap();
        assert_eq!(instr.size, 5);
        assert!(instr.flags.contains(InstrFlags::BRANCH));
        assert!(!instr.flags.contains(InstrFlags::CONDITIONAL));
        assert!(!instr.flags.contains(InstrFlags::CALL));
        let branches = arch.get_branches(&instr);
        assert_eq!(branches.len(), 1);
        assert_eq!(branches[0].target, Some(0x100a));
    }

    // ------------------------------------------------------------------
    // SYSCALL (0F 05) — iced-x86 classifies this as an indirect call
    // (it transfers control to the kernel at a privilege-determined address).
    // We expect BRANCH | CALL | INDIRECT flags and no static branch target.
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_syscall() {
        let arch = x64();
        let bytes: &[u8] = &[0x0f, 0x05];
        let instr = arch.disassemble(Address::new(0x7000), bytes).unwrap();
        assert_eq!(instr.size, 2);
        // iced-x86 reports syscall as a call-class transfer — CALL must be set.
        assert!(
            instr.flags.contains(InstrFlags::CALL),
            "syscall must have CALL; flags = {:?}",
            instr.flags
        );
        // syscall does not return in the conventional sense.
        assert!(!instr.flags.contains(InstrFlags::RET));
        // No static branch target is available for a syscall.
        let branches = arch.get_branches(&instr);
        assert!(branches.is_empty(), "syscall has no static branch target");
    }

    // ------------------------------------------------------------------
    // MOV with memory — should set READ_MEM / WRITE_MEM
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_mov_mem_write() {
        let arch = x64();
        // 48 89 45 F8  — MOV QWORD PTR [RBP-8], RAX  (write to memory)
        let bytes: &[u8] = &[0x48, 0x89, 0x45, 0xf8];
        let instr = arch.disassemble(Address::new(0x8000), bytes).unwrap();
        assert_eq!(instr.size, 4);
        assert!(
            instr.flags.contains(InstrFlags::WRITE_MEM),
            "mov to memory must have WRITE_MEM; flags = {:?}",
            instr.flags
        );
    }

    #[test]
    fn test_decode_mov_mem_read() {
        let arch = x64();
        // 48 8B 45 F8  — MOV RAX, QWORD PTR [RBP-8]  (read from memory)
        let bytes: &[u8] = &[0x48, 0x8b, 0x45, 0xf8];
        let instr = arch.disassemble(Address::new(0x8000), bytes).unwrap();
        assert_eq!(instr.size, 4);
        assert!(
            instr.flags.contains(InstrFlags::READ_MEM),
            "mov from memory must have READ_MEM; flags = {:?}",
            instr.flags
        );
    }

    // ------------------------------------------------------------------
    // get_branches returns empty for non-branch instructions
    // ------------------------------------------------------------------

    #[test]
    fn test_get_branches_empty_for_nop() {
        let arch = x64();
        let instr = arch.disassemble(Address::new(0x1000), &[0x90]).unwrap();
        let branches = arch.get_branches(&instr);
        assert!(branches.is_empty());
    }

    #[test]
    fn test_get_branches_empty_for_ret() {
        let arch = x64();
        let instr = arch.disassemble(Address::new(0x1000), &[0xc3]).unwrap();
        let branches = arch.get_branches(&instr);
        // RET is RETURN, not a branch with a static target.
        assert!(branches.is_empty());
    }

    // ------------------------------------------------------------------
    // Indirect call:  FF D0  — CALL RAX
    // ------------------------------------------------------------------

    #[test]
    fn test_indirect_call() {
        let arch = x64();
        let bytes: &[u8] = &[0xff, 0xd0]; // CALL rax
        let instr = arch.disassemble(Address::new(0x9000), bytes).unwrap();
        assert_eq!(instr.size, 2);
        assert!(
            instr
                .flags
                .contains(InstrFlags::BRANCH | InstrFlags::CALL | InstrFlags::INDIRECT)
        );
        // No static target available for indirect calls
        let branches = arch.get_branches(&instr);
        assert!(
            branches.is_empty(),
            "indirect call has no static branch target"
        );
    }

    // ------------------------------------------------------------------
    // Indirect jump:  FF E0  — JMP RAX
    // ------------------------------------------------------------------

    #[test]
    fn test_indirect_jmp() {
        let arch = x64();
        let bytes: &[u8] = &[0xff, 0xe0]; // JMP rax
        let instr = arch.disassemble(Address::new(0x9002), bytes).unwrap();
        assert_eq!(instr.size, 2);
        assert!(
            instr
                .flags
                .contains(InstrFlags::BRANCH | InstrFlags::INDIRECT)
        );
        assert!(!instr.flags.contains(InstrFlags::CALL));
    }

    // ------------------------------------------------------------------
    // RETN imm16  (C2 xx xx) — 32-bit return with stack adjustment
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_ret_n() {
        let arch = x64();
        let bytes: &[u8] = &[0xc2, 0x08, 0x00]; // RETN 8
        let instr = arch.disassemble(Address::new(0xa000), bytes).unwrap();
        assert_eq!(instr.size, 3);
        assert!(instr.flags.contains(InstrFlags::RET));
    }

    // ------------------------------------------------------------------
    // XOR rax, rax  (48 31 C0) — common idiom
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_xor_rax_rax() {
        let arch = x64();
        let bytes: &[u8] = &[0x48, 0x31, 0xc0];
        let instr = arch.disassemble(Address::new(0xb000), bytes).unwrap();
        assert_eq!(instr.size, 3);
        assert!(instr.mnemonic.contains("xor"));
        assert!(!instr.flags.contains(InstrFlags::BRANCH));
        assert!(!instr.flags.contains(InstrFlags::RET));
    }

    // ------------------------------------------------------------------
    // INT3  (CC)
    // ------------------------------------------------------------------

    #[test]
    fn test_decode_int3() {
        let arch = x64();
        let instr = arch.disassemble(Address::new(0xc000), &[0xcc]).unwrap();
        assert_eq!(instr.size, 1);
        // 0xCC is INT3 specifically. The old `contains("int3") ||
        // contains("int")` was self-defeating: "int3" CONTAINS "int", so the
        // second alternative subsumes the first and the whole assertion reduced
        // to `contains("int")` — it would have passed for a plain `int 0x80`.
        assert!(
            instr.mnemonic.contains("int3"),
            "0xCC must decode as int3, got {}",
            instr.mnemonic
        );
    }

    // ------------------------------------------------------------------
    // Linear disassembler on 32-bit code
    // ------------------------------------------------------------------

    #[test]
    fn test_linear_disassembler_32bit() {
        // 32-bit prologue: push ebp; mov ebp, esp; ret
        let code: &[u8] = &[0x55, 0x89, 0xe5, 0xc3];
        let arch = x32();
        let base = Address::new(0x1000);
        let instrs: Vec<_> = LinearDisassembler::new(&arch, code, base)
            .collect::<Result<Vec<_>, _>>()
            .unwrap();
        assert_eq!(instrs.len(), 3);
        assert!(instrs[0].mnemonic.contains("push"));
        assert!(instrs[1].mnemonic.contains("mov"));
        assert!(instrs[2].flags.contains(InstrFlags::RET));
    }

    // ──────────────────────────────────────────────────────────────────────
    // Robustness: the decoder/disassembler/lifter must never panic on
    // adversarial input (packed/obfuscated/truncated bytes). Deterministic LCG
    // so any failure reproduces exactly.
    // ──────────────────────────────────────────────────────────────────────

    struct Lcg(u64);
    impl Lcg {
        fn next(&mut self) -> u64 {
            self.0 = self
                .0
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            self.0
        }
    }

    fn fuzz_arch(arch: &X86Arch, bits: u32, seed: u64, iters: usize) {
        let prev = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));
        let mut rng = Lcg(seed);
        let mut first_panic: Option<Vec<u8>> = None;
        for _ in 0..iters {
            let len = 1 + (rng.next() % 16) as usize;
            let mut bytes = Vec::with_capacity(len);
            for _ in 0..len {
                bytes.push((rng.next() >> 24) as u8);
            }
            let bp = bytes.clone();
            let r = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                // Every public entry point that touches raw bytes.
                let _ = crate::length::instr_length(&bytes, bits);
                let _ = crate::branch::classify_branch(&bytes);
                let _ = arch.disassemble(Address(0x1000), &bytes);
                let _ = arch.lift(Address(0x1000), &bytes);
                // Streaming disassembly over the whole buffer (bounded).
                let dis = LinearDisassembler::new(arch, &bytes, Address(0x2000));
                for instr in dis.take(48).flatten() {
                    let _ = arch.get_branches(&instr);
                }
            }));
            if r.is_err() {
                first_panic = Some(bp);
                break;
            }
        }
        std::panic::set_hook(prev);
        assert!(
            first_panic.is_none(),
            "panicked on bytes={:02x?}",
            first_panic
        );
    }

    #[test]
    fn fuzz_decode_disasm_lift_never_panics_64() {
        fuzz_arch(&x64(), 64, 0xdead_beef_0bad_f00d, 40_000);
    }

    #[test]
    fn fuzz_decode_disasm_lift_never_panics_32() {
        fuzz_arch(&x32(), 32, 0x1234_4321_abcd_dcba, 40_000);
    }

    #[test]
    fn fuzz_decode_disasm_lift_never_panics_16() {
        fuzz_arch(&X86Arch::new_16bit(), 16, 0xcafe_d00d_5566_7788, 25_000);
    }

    /// Linear-sweep self-consistency: over a buffer of back-to-back valid
    /// instructions, each decoded length must match the standalone length
    /// scanner, and offsets must advance monotonically without overrun.
    #[test]
    fn linear_sweep_matches_length_scanner() {
        // push rbp; mov rbp,rsp; sub rsp,0x20; xor eax,eax; add rax,1;
        // movzx ecx,al; ret
        let code: &[u8] = &[
            0x55, 0x48, 0x89, 0xE5, 0x48, 0x83, 0xEC, 0x20, 0x31, 0xC0, 0x48, 0x83, 0xC0, 0x01,
            0x0F, 0xB6, 0xC8, 0xC3,
        ];
        let arch = x64();
        let mut off = 0usize;
        let dis = LinearDisassembler::new(&arch, code, Address(0x1000));
        for item in dis {
            let instr = item.expect("valid instruction");
            assert_eq!(
                instr.size,
                crate::length::instr_length(&code[off..], 64).unwrap(),
                "length scanner disagrees with decoder at offset {off}"
            );
            off += instr.size;
            assert!(off <= code.len(), "sweep overran the buffer");
        }
        assert_eq!(off, code.len(), "sweep did not cover the whole buffer");
    }
}
