[package]
license.workspace = true
name = "rustre-crypto-whitebox"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
parking_lot = { workspace = true }
mysql = { workspace = true }
rayon = { workspace = true }

[lints]
workspace = true
