//! `go_demangler` — Demangle Go symbol names from object files and stack traces.
//!
//! Go uses a predictable naming convention: `<import-path>.<SymbolName>`.
//! Closures, method values, interface thunks, and generic instantiations all
//! follow documented patterns.  This module provides a best-effort demangler
//! that decodes these names into human-readable forms.

use std::collections::HashMap;
use std::fmt::Write as _;

use serde::{Deserialize, Serialize};

// ── GoPackage ─────────────────────────────────────────────────────────────────

/// Represents a decoded Go import path and its short name.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct GoPackage {
    /// Full import path, e.g. `github.com/user/repo/pkg`.
    pub import_path: String,
    /// Short (unqualified) package name, e.g. `pkg`.
    pub short_name: String,
    /// Module path prefix (before the package-level segment), if detectable.
    pub module_path: Option<String>,
}

impl GoPackage {
    /// Parse a Go import path into a [`GoPackage`].
    ///
    /// The short name is taken as the last component of the import path,
    /// after stripping any version suffix like `@v1.2.3`.
    #[must_use]
    pub fn from_import_path(import_path: &str) -> Self {
        let clean = import_path.split('@').next().unwrap_or(import_path);
        let short_name = clean.rsplit('/').next().unwrap_or(clean).to_owned();

        // Attempt to split module path (first 3 components of a github-style path).
        let parts: Vec<&str> = clean.splitn(4, '/').collect();
        let module_path = if parts.len() >= 3 {
            Some(parts[..3].join("/"))
        } else {
            None
        };

        Self {
            import_path: import_path.to_owned(),
            short_name,
            module_path,
        }
    }

    /// Return `true` if this package is from the Go standard library.
    #[must_use]
    pub fn is_stdlib(&self) -> bool {
        !self.import_path.contains('.')
    }
}

impl std::fmt::Display for GoPackage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.import_path)
    }
}

// ── GoSymbolKind ──────────────────────────────────────────────────────────────

/// Kind of a decoded Go symbol.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum GoSymbolKind {
    /// Top-level function.
    Function,
    /// Method on a (possibly pointer) receiver.
    Method,
    /// Anonymous function / closure literal.
    Closure,
    /// Interface method wrapper generated by the compiler.
    InterfaceThunk,
    /// Type-assertion or conversion wrapper.
    ///
    /// **Never produced by this crate.** Nothing constructs this variant, so a
    /// consumer matching on it writes a branch that cannot fire — the shape
    /// recorded for `MangleLanguage::Java`, which was unreachable from
    /// `classify` and made `filter_by_language(…, Java)` silently return
    /// nothing.
    ///
    /// Left in place rather than removed because the concept is real: the
    /// corpus contains `errors..typeAssert.2` and the `type:.eq.…` /
    /// `type:.hash.…` families, which today classify as `Function` and
    /// `Unknown`. Deciding which of those are genuinely thunks needs Go
    /// semantics this crate cannot source — Go has no oracle here — so the
    /// variant is documented as unreachable instead of being wired up on a
    /// guess.
    TypeAssertionThunk,
    /// Goroutine-start wrapper.
    GoroutineWrapper,
    /// Generic function instantiation.
    GenericInstance,
    /// Package-level variable initializer.
    PackageInit,
    /// Symbol type could not be determined.
    Unknown,
}

impl GoSymbolKind {
    /// Human-readable name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Function => "function",
            Self::Method => "method",
            Self::Closure => "closure",
            Self::InterfaceThunk => "interface_thunk",
            Self::TypeAssertionThunk => "type_assertion_thunk",
            Self::GoroutineWrapper => "goroutine_wrapper",
            Self::GenericInstance => "generic_instance",
            Self::PackageInit => "package_init",
            Self::Unknown => "unknown",
        }
    }
}

// ── GoSymbol ──────────────────────────────────────────────────────────────────

/// A fully decoded Go symbol.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoSymbol {
    /// The original mangled / raw name.
    pub original: String,
    /// The decoded human-readable name.
    pub demangled: String,
    /// Decoded package.
    pub package: GoPackage,
    /// Receiver type name (for methods), without leading `*`.
    pub receiver: Option<String>,
    /// True if the receiver is a pointer (`*T`).
    pub receiver_is_pointer: bool,
    /// Base function or method name.
    pub function_name: String,
    /// Closure depth (0 = not a closure, 1 = first-level closure, …).
    pub closure_depth: u32,
    /// Index within the parent function for closures (from `funcN` suffix).
    /// Every closure index, outermost first — `Foo.func2.5` gives `[2, 5]`.
    ///
    /// Was a single `Option<u32>` holding only the last `funcN`'s index, which
    /// made `Foo.func2.3` and `Foo.func2.5` indistinguishable.
    pub closure_indices: Vec<u32>,
    /// Generic type arguments, if any.
    pub type_args: Vec<String>,
    /// Kind of this symbol.
    pub kind: GoSymbolKind,
}

impl GoSymbol {
    /// Return a short display string: `pkg.Func` or `pkg.Type.Method`.
    #[must_use]
    pub fn short_name(&self) -> String {
        self.receiver.as_ref().map_or_else(
            || format!("{}.{}", self.package.short_name, self.function_name),
            |recv| {
                let prefix = if self.receiver_is_pointer { "(*" } else { "(" };
                format!(
                    "{}.{}{}{}.{}",
                    self.package.short_name,
                    prefix,
                    recv,
                    ")",
                    self.function_name
                )
            },
        )
    }
}

// ── GoDemangler ───────────────────────────────────────────────────────────────

/// Demangler for Go symbol names.
///
/// Handles:
/// - Standard `pkg.Func` names.
/// - Method names `pkg.(*Type).Method`.
/// - Closures `pkg.Func.func1`, `pkg.Func.func1.1`, …
/// - Interface thunks `pkg.Type.method·ftab`.
/// - Goroutine wrappers `pkg.Func·dwrap`.
/// - Generic instantiations `pkg.Func[.shape.pkg.Type]`.
/// - `go:` prefixed runtime-generated names.
pub struct GoDemangler {
    /// Cache: raw name → decoded symbol.
    cache: HashMap<String, GoSymbol>,
    /// Whether to aggressively strip shape-type decoration from generics.
    pub simplify_generics: bool,
}

impl GoDemangler {
    /// Create a new demangler with default settings.
    #[must_use]
    pub fn new() -> Self {
        Self {
            cache: HashMap::new(),
            simplify_generics: true,
        }
    }

    /// Return `true` if `name` looks like a Go symbol.
    #[must_use]
    pub fn detect(name: &str) -> bool {
        // Go symbols never start with `_Z`, `?`, or `_R`.
        if name.starts_with("_Z")
            || name.starts_with("_R")
            || name.starts_with('?')
            || name.starts_with("_T0")
            || name.starts_with("$s")
        {
            return false;
        }
        // A Go identifier is a letter, digit or underscore, so a package can
        // never begin with `$`. Only the Swift sigil `$s` was excluded above,
        // which let the ARM ELF mapping symbols through: `$d.realdata` and
        // `$t.0` look like a dotted package path and were echoed back as Go
        // decodes. They mark instruction-set transitions and name nothing —
        // see `decline::is_constant_pool`, which classifies them as linker
        // artifacts once nothing claims them.
        if name.starts_with('$') {
            return false;
        }
        // A Go symbol is built from identifiers, import paths, generic argument
        // lists and the compiler's own markers, so its character set is small
        // and closed. Measured over all 2163 Go symbols in the corpora, the only
        // non-alphanumeric characters that occur are
        //
        //     space ( ) * , - . / : [ ] _ { }
        //
        // plus the non-ASCII interface-thunk marker used in `pkg.T.m<dot>ftab`.
        //
        // Without this the detector claimed arbitrary punctuation as long as it
        // held a dot: 8.5% of random printable-ASCII strings "decoded", echoed
        // back verbatim and counted as `Decoded` in the classification metric.
        // A detector looser than what it detects invents symbols — the
        // `_RTC_Initialize` / `_TIFFOpen` lesson, here at scale.
        //
        // Byte-wise, allocation-free, and measured neutral in an interleaved
        // A/B (medians 1.114M vs 1.103M calls/s on an idle machine): `detect`
        // sits on the dispatch hot path, where a per-character scan has already
        // cost throughput once in this crate's history.
        if !name.bytes().all(|b| {
            b.is_ascii_alphanumeric()
                || matches!(
                    b,
                    b' ' | b'(' | b')' | b'*' | b',' | b'-' | b'.' | b'/' | b':' | b'['
                        | b']' | b'_' | b'{' | b'}'
                )
                || b >= 0x80
        }) {
            return false;
        }
        // Go generic instantiations *do* contain spaces — inside their type
        // arguments, e.g. `…Pointer[go.shape.struct { internal/sync.isEntry
        // bool }]` — so whitespace alone cannot be disqualifying. What no Go
        // symbol has is whitespace at bracket depth zero: measured over the
        // corpus, 31 of 2163 Go symbols contain whitespace and **none** of
        // them outside brackets.
        //
        // Without this the detector claimed build strings that live in real
        // symbol tables alongside symbols, echoing `GCC: (GNU) 12.2.0` back as
        // a Go decode.
        //
        // Two stages on purpose: `detect` sits on the dispatch hot path, and a
        // per-character match with depth tracking on *every* symbol measured
        // consistently slower in an interleaved A/B. The cheap byte predicate
        // short-circuits the ~98.6% of symbols with no whitespace at all, so
        // the depth scan runs only for the few that need it.
        if name.as_bytes().iter().any(u8::is_ascii_whitespace) {
            let mut depth = 0i32;
            for c in name.chars() {
                match c {
                    '[' | '(' | '{' | '<' => depth += 1,
                    ']' | ')' | '}' | '>' => depth -= 1,
                    c if c.is_whitespace() && depth <= 0 => return false,
                    _ => {}
                }
            }
        }
        // A trailing dot leaves the final component empty, and no Go symbol
        // ends that way. Without this the detector claimed bare linker-wrapper
        // prefixes such as `__emutls_v.` and echoed them back as decodes.
        //
        // Deliberately narrow: empty *middle* components are legitimate Go and
        // appear in the real corpus — `errors..inittask`,
        // `errors..interfaceSwitch.0`, `errors..typeAssert.2` — so rejecting
        // every empty component would lose real symbols. Only the last one is
        // constrained.
        if name.ends_with('.') {
            return false;
        }
        // Reject GCC function-local statics: `msg.0`, `table.0`, `C.9.0`,
        // `state_mbrtowc.0`. GCC promotes a local `static` to a symbol as
        // `<name>.<counter>` (sometimes nested, `C.9.0`), so every component
        // after the base is a bare integer. These have no demangling — they are
        // undecorated C data — but they are dotted, so the permissive detector
        // claimed them and echoed them back as decodes with `abi: Go`.
        //
        // The discriminator is a grammar property, defined once in
        // `decline::is_gcc_local_static`: a Go symbol always carries at least
        // one non-numeric identifier after the package (a function, type or
        // method name), while a local static never does. This is why it does
        // not disturb the legitimate Go names with numeric *tails* —
        // `errors..interfaceSwitch.0`, `errors..typeAssert.2` — whose earlier
        // components are non-numeric and satisfy the requirement.
        if crate::decline::is_gcc_local_static(name) {
            return false;
        }
        // Must contain at least one dot after a non-empty prefix.
        let dot_pos = name.find('.');
        dot_pos.is_some_and(|p| p > 0)
    }

    /// Attempt to decode `name` into a [`GoSymbol`].
    ///
    /// Returns `None` if the name does not look like a Go symbol.
    pub fn decode(&mut self, name: &str) -> Option<GoSymbol> {
        if let Some(cached) = self.cache.get(name) {
            return Some(cached.clone());
        }
        let sym = decode_go_symbol(name, self.simplify_generics)?;
        self.cache.insert(name.to_owned(), sym.clone());
        Some(sym)
    }

    /// Batch-decode a slice of names.  Names that cannot be decoded are skipped.
    #[must_use]
    pub fn decode_batch(&mut self, names: &[impl AsRef<str>]) -> Vec<GoSymbol> {
        names
            .iter()
            .filter_map(|n| self.decode(n.as_ref()))
            .collect()
    }

    /// Clear the internal decode cache.
    pub fn clear_cache(&mut self) {
        self.cache.clear();
    }

    /// Return cache size.
    #[must_use]
    pub fn cache_size(&self) -> usize {
        self.cache.len()
    }
}

impl Default for GoDemangler {
    fn default() -> Self {
        Self::new()
    }
}

// ── decode_go_symbol (main entry point) ───────────────────────────────────────

/// Decode a raw Go symbol name into a [`GoSymbol`].
///
/// This is the standalone public API — no caching.
#[must_use]
pub fn decode_go_symbol(name: &str, simplify_generics: bool) -> Option<GoSymbol> {
    if !GoDemangler::detect(name) {
        return None;
    }

    let parser = GoParser::new(name, simplify_generics);
    parser.parse()
}

// ── GoParser ──────────────────────────────────────────────────────────────────

struct GoParser<'a> {
    input: &'a str,
    simplify_generics: bool,
}

impl<'a> GoParser<'a> {
    const fn new(input: &'a str, simplify_generics: bool) -> Self {
        Self {
            input,
            simplify_generics,
        }
    }

    fn parse(&self) -> Option<GoSymbol> {
        let raw = self.input;

        // Handle `go:` prefix names like `go:itab.*pkg.T,pkg.I`.
        if let Some(rest) = raw.strip_prefix("go:") {
            return Some(Self::parse_go_colon(rest, raw));
        }

        // Handle `type:` prefix.
        if let Some(rest) = raw.strip_prefix("type:") {
            return Some(Self::parse_type_prefix(rest, raw));
        }

        // Split off generic instantiation suffix `[...]` before further parsing.
        let (base_name, type_args) = split_generic_args(raw, self.simplify_generics);

        // Find the package path / function split.
        // The package path is everything up to (but not including) the last `/`
        // that precedes a `.Identifier`.  Alternatively, find the first dot that
        // is NOT inside parentheses or brackets.
        let (import_path, rest) = split_import_and_rest(&base_name)?;

        let package = GoPackage::from_import_path(&import_path);

        // `rest` is now e.g. `(*Type).Method.func1.1` or `Func.func3`
        let (receiver, receiver_is_pointer, after_recv) = parse_receiver(rest);

        // The remaining part: `Method.func1.1` or `Func.func3`.
        let (function_name, closure_depth, closure_indices) = parse_function_suffix(after_recv);

        // Determine kind.
        let kind = infer_kind(
            raw,
            receiver.as_deref(),
            closure_depth,
            &type_args,
            &function_name,
        );

        // Build the demangled string.
        let demangled = build_demangled(
            &package,
            receiver.as_deref(),
            receiver_is_pointer,
            &function_name,
            closure_depth,
            &closure_indices,
            &type_args,
        );

        Some(GoSymbol {
            original: raw.to_owned(),
            demangled,
            package,
            receiver,
            receiver_is_pointer,
            function_name,
            closure_depth,
            closure_indices,
            type_args,
            kind,
        })
    }

    /// Parse a `go:` prefixed runtime-generated name.
    fn parse_go_colon(rest: &str, raw: &str) -> GoSymbol {
        let kind = if rest.starts_with("itab") {
            GoSymbolKind::InterfaceThunk
        } else {
            GoSymbolKind::Unknown
        };

        GoSymbol {
            original: raw.to_owned(),
            demangled: format!("go:{rest}"),
            // No package: `go:buildid` and `go:itab.*errors.errorString,error`
            // are linker bookkeeping, not code in a Go package. Reporting
            // `runtime` invented an origin the symbol does not have, and it
            // showed up as a namespace absent from the rendered string.
            package: GoPackage::from_import_path(""),
            receiver: None,
            receiver_is_pointer: false,
            function_name: rest.to_owned(),
            closure_depth: 0,
            closure_indices: Vec::new(),
            type_args: Vec::new(),
            kind,
        }
    }

    /// Parse a `type:` prefixed name.
    fn parse_type_prefix(rest: &str, raw: &str) -> GoSymbol {
        GoSymbol {
            original: raw.to_owned(),
            demangled: format!("type descriptor for {rest}"),
            // A type descriptor belongs to the type it describes, which is
            // named inside `rest`; the descriptor itself has no package.
            package: GoPackage::from_import_path(""),
            receiver: None,
            receiver_is_pointer: false,
            function_name: rest.to_owned(),
            closure_depth: 0,
            closure_indices: Vec::new(),
            type_args: Vec::new(),
            kind: GoSymbolKind::Unknown,
        }
    }
}

// ── Parsing helpers ───────────────────────────────────────────────────────────

/// Split `pkg/path.Rest` into `(pkg/path, Rest)`.
///
/// The import path is everything before the first `.` that is NOT inside
/// parentheses (receiver part) and whose preceding character is not `/`.
fn split_import_and_rest(name: &str) -> Option<(String, &str)> {
    let bytes = name.as_bytes();
    let mut paren_depth = 0i32;
    let mut bracket_depth = 0i32;
    // If the name contains a `/`, the package path is everything up to the
    // first `.` AFTER the last `/`. Otherwise it's everything up to the first `.`.
    let last_slash = name.rfind('/');
    let scan_start = last_slash.map_or(0, |i| i + 1);

    for (i, &b) in bytes.iter().enumerate() {
        match b {
            b'(' => paren_depth += 1,
            b')' => paren_depth -= 1,
            b'[' => bracket_depth += 1,
            b']' => bracket_depth -= 1,
            b'.' if paren_depth == 0 && bracket_depth == 0 && i >= scan_start => {
                if i == 0 {
                    continue;
                }
                let prefix = &name[..i];
                let rest = &name[i + 1..];
                return Some((prefix.to_owned(), rest));
            }
            _ => {}
        }
    }
    None
}

/// Parse an optional receiver `(*Type).` or `(Type).` at the start of `s`.
///
/// Returns `(receiver_name, is_pointer, rest_after_receiver)`.
fn parse_receiver(s: &str) -> (Option<String>, bool, &str) {
    if !s.starts_with('(') {
        // Value receiver: `Type.Method[...]` — take the first component as
        // the receiver when a second identifier follows that is not a
        // compiler-generated `funcN` / `gowrapN` closure suffix.
        if let Some(dot) = s.find('.') {
            let (ty, rest) = (&s[..dot], &s[dot + 1..]);
            let next = rest.split('.').next().unwrap_or(rest);
            let is_generated = |p: &str| {
                (p.strip_prefix("func")
                    .or_else(|| p.strip_prefix("gowrap"))
                    .is_some_and(|d| d.chars().all(|c| c.is_ascii_digit())))
                    || p.chars().all(|c| c.is_ascii_digit())
            };
            if !ty.is_empty()
                && !next.is_empty()
                && !is_generated(next)
                && ty.chars().next().is_some_and(char::is_uppercase)
            {
                return (Some(ty.to_owned()), false, rest);
            }
        }
        return (None, false, s);
    }
    if let Some(close) = s.find(')') {
        let inner = &s[1..close];
        let rest = &s[close + 1..];
        let rest = rest.strip_prefix('.').unwrap_or(rest);
        if let Some(stripped) = inner.strip_prefix('*') {
            return (Some(stripped.to_owned()), true, rest);
        }
        return (Some(inner.to_owned()), false, rest);
    }
    (None, false, s)
}

/// Split the function suffix into `(base_name, closure_depth, closure_indices)`.
///
/// Examples:
/// - `"Foo"` → `("Foo", 0, [])`
/// - `"Foo.func1"` → `("Foo", 1, [1])`
/// - `"Foo.func1.1"` → `("Foo", 2, [1, 1])`
/// - `"Foo.func2.5"` → `("Foo", 2, [2, 5])`
fn parse_function_suffix(s: &str) -> (String, u32, Vec<u32>) {
    let parts: Vec<&str> = s.split('.').collect();

    if parts.is_empty() {
        return (s.to_owned(), 0, Vec::new());
    }

    if parts.len() == 1 {
        return (parts[0].to_owned(), 0, Vec::new());
    }

    // The base is every *named* component — everything that is neither a
    // closure marker (`funcN`) nor a nesting index (`1`). Taking `parts[0]`
    // dropped `OnceValue` from `init.OnceValue.func5`, leaving the type
    // arguments attached to `init` (`os.init[bool] {closure-1 #5}`) on 12 of
    // the 28 generic Go symbols in the corpus. Keeping only what precedes the
    // first marker still dropped names that follow one:
    // `traceAdvance.func3.osyield.1` lost `osyield`, a named function nested
    // inside the closure.
    let is_marker = |p: &&str| {
        p.strip_prefix("func")
            .is_some_and(|r| r.parse::<u32>().is_ok())
    };
    let is_index = |p: &&str| !p.is_empty() && p.chars().all(|c| c.is_ascii_digit());
    // A bare `.N` only means "closure nesting" once a `funcN` has been seen.
    // Before that it is part of the name — `runtime.init.6` is the package's
    // sixth init function, exactly as the depth loop below already assumes.
    //
    // Filtering every numeric component regardless of position applied a
    // different rule here than there, and it lost real information:
    // `runtime.init.6.func1` and `runtime.init.func1` both rendered
    // `runtime.init {closure-1 #1}`, so two distinct runtime functions became
    // indistinguishable. Found by a collision sweep over the corpus, which sees
    // what per-symbol completeness checks cannot: `6` is a number, not a name,
    // so nothing required it to reappear in the output.
    let mut seen_marker = false;
    let base = parts
        .iter()
        .filter(|p| {
            if is_marker(p) {
                seen_marker = true;
                return false;
            }
            !(seen_marker && is_index(p))
        })
        .copied()
        .collect::<Vec<_>>()
        .join(".");

    // Count closure levels: each `funcN` adds a level, and RECORD EVERY INDEX.
    //
    // Keeping only the last `funcN`'s index dropped the nesting indices
    // entirely: `main.f.func2.3` and `main.f.func2.5` are two different nested
    // closures in the same binary and BOTH rendered `main.f {closure-2 #2}`,
    // while `main.f.func1.2.3` lost two indices at once. The depth said how
    // deep, but nothing said which one — so distinct functions became
    // indistinguishable.
    let mut depth = 0u32;
    let mut indices: Vec<u32> = Vec::new();

    for part in &parts[1..] {
        if let Some(rest) = part.strip_prefix("func") {
            depth += 1;
            if let Ok(n) = rest.parse::<u32>() {
                indices.push(n);
            }
        } else if depth > 0 && part.parse::<u32>().is_ok() {
            // A bare numeric segment nests a closure inside another one
            // (`Foo.func1.1`), so it counts only once a `funcN` has been seen.
            //
            // On its own, `.N` is not a closure at all: `runtime.init.0` is
            // the package's first init function and `errors..typeAssert.2` is
            // a compiler-internal entry. Treating those as closures produced
            // `runtime.init {closure-1 #?}` — a fabricated construct, with the
            // index reported as unknown even though the real name carries it.
            depth += 1;
            if let Ok(n) = part.parse::<u32>() {
                indices.push(n);
            }
        }
    }

    if depth == 0 {
        // Not a closure pattern — might be a method on a nested type.
        let full = parts.join(".");
        return (full, 0, Vec::new());
    }

    (base, depth, indices)
}

/// Strip the compiler's synthetic shape-package qualifier from a type
/// argument: `go.shape.int` → `int`, `pkg.shape.T` → `T`.
///
/// The shape package name must be removed together with its trailing dot; a
/// bare `.shape.` → `""` substitution would fuse the surrounding segments
/// (`go.shape.int` → `goint`).
fn strip_shape_prefix(arg: &str) -> String {
    // Remove each `<pkg>.shape.` qualifier IN PLACE. Truncating from the front —
    // "everything after the last `.shape.`" — is right only when the qualifier
    // opens the argument. A NESTED generic puts a type name before it, and that
    // name was thrown away along with an unbalanced bracket left behind:
    //
    //   main.A[main.B[go.shape.int]].m  ->  main.A[int]].m
    //
    // `main.B[` lost, `]` orphaned. Removing the qualifier where it occurs
    // keeps everything else, brackets included.
    let mut out = String::with_capacity(arg.len());
    let mut rest = arg;
    while let Some(pos) = rest.find(".shape.") {
        let head = &rest[..pos];
        // Walk back over the package identifier that owns this `.shape.`, and
        // no further: a package path may contain `/` and `.`.
        let start = head
            .rfind(|c: char| !(c.is_alphanumeric() || c == '_' || c == '/' || c == '.'))
            .map_or(0, |i| i + 1);
        out.push_str(&head[..start]);
        rest = &rest[pos + ".shape.".len()..];
    }
    out.push_str(rest);
    out
}

/// Split `name[type_args]suffix` into `(name + suffix, [type_arg_strings])`.
///
/// Any trailing component after the closing bracket (e.g. the `.Get` in
/// `main.Map[...].Get`) belongs to the symbol name and is preserved.
fn split_generic_args(name: &str, simplify: bool) -> (String, Vec<String>) {
    if let Some(bracket) = name.find('[') {
        let (args_str, suffix) = match name.rfind(']') {
            // A `]` before the opening `[` would make the slice range invert
            // and panic — treat that as "no generic args".
            Some(close) if close > bracket => (&name[bracket + 1..close], &name[close + 1..]),
            _ => return (name.to_owned(), Vec::new()),
        };
        let base = format!("{}{}", &name[..bracket], suffix);

        let args: Vec<String> = args_str
            .split(',')
            .map(|a| {
                let a = a.trim();
                if simplify {
                    strip_shape_prefix(a)
                } else {
                    a.to_owned()
                }
            })
            .filter(|a| !a.is_empty())
            .collect();

        (base, args)
    } else {
        (name.to_owned(), Vec::new())
    }
}

/// Infer the [`GoSymbolKind`] from various cues in the decoded components.
fn infer_kind(
    raw: &str,
    receiver: Option<&str>,
    closure_depth: u32,
    type_args: &[String],
    function_name: &str,
) -> GoSymbolKind {
    if raw.contains("·dwrap") || raw.contains(".dwrap") {
        return GoSymbolKind::GoroutineWrapper;
    }
    if raw.contains("·ftab") || raw.contains(".ftab") {
        return GoSymbolKind::InterfaceThunk;
    }
    if closure_depth > 0 {
        return GoSymbolKind::Closure;
    }
    if function_name == "init" || function_name.starts_with("init.") {
        return GoSymbolKind::PackageInit;
    }
    if !type_args.is_empty() {
        return GoSymbolKind::GenericInstance;
    }
    if receiver.is_some() {
        return GoSymbolKind::Method;
    }
    GoSymbolKind::Function
}

/// Build the human-readable demangled form.
fn build_demangled(
    pkg: &GoPackage,
    receiver: Option<&str>,
    receiver_is_pointer: bool,
    function_name: &str,
    closure_depth: u32,
    closure_indices: &[u32],
    type_args: &[String],
) -> String {
    let mut out = String::new();

    out.push_str(&pkg.import_path);
    out.push('.');

    // For a method on a generic type the instantiation belongs to the receiver
    // (`main.Map[int, string].Get`); for a generic free function it belongs to
    // the function itself (`slices.Sort[int]`).
    let args_str = if type_args.is_empty() {
        String::new()
    } else {
        format!("[{}]", type_args.join(", "))
    };

    if let Some(recv) = receiver {
        if receiver_is_pointer {
            write!(out, "(*{recv}{args_str}).").unwrap_or_default();
        } else {
            write!(out, "{recv}{args_str}.").unwrap_or_default();
        }
        out.push_str(function_name);
    } else {
        out.push_str(function_name);
        out.push_str(&args_str);
    }

    if closure_depth > 0 {
        // Join the whole path so nesting stays visible: `#2.5`, not `#2`.
        let idx_str = if closure_indices.is_empty() {
            "?".to_owned()
        } else {
            closure_indices
                .iter()
                .map(u32::to_string)
                .collect::<Vec<_>>()
                .join(".")
        };
        write!(out, " {{closure-{closure_depth} #{idx_str}}}").unwrap_or_default();
    }

    out
}

// ── Well-known Go stdlib patterns ─────────────────────────────────────────────

/// Return a human-readable description for well-known Go runtime symbols.
#[must_use]
pub fn describe_runtime_symbol(name: &str) -> Option<&'static str> {
    match name {
        "runtime.goexit" => Some("goroutine exit trampoline"),
        "runtime.morestack" => Some("stack growth trampoline"),
        "runtime.morestack_noctxt" => Some("stack growth (no context)"),
        "runtime.gcWriteBarrier" => Some("GC write barrier"),
        "runtime.duffzero" => Some("bulk zero (Duff's device)"),
        "runtime.duffcopy" => Some("bulk copy (Duff's device)"),
        "runtime.panicIndex" => Some("panic: index out of range"),
        "runtime.panicSlice" => Some("panic: slice out of bounds"),
        "runtime.panicNilPtr" => Some("panic: nil pointer dereference"),
        "runtime.throw" => Some("fatal runtime error"),
        "runtime.mallocgc" => Some("allocate heap object"),
        "runtime.newobject" => Some("allocate single object"),
        "runtime.makeslice" => Some("make a slice"),
        "runtime.makemap" => Some("make a map"),
        "runtime.chanrecv1" | "runtime.chanrecv2" => Some("channel receive"),
        "runtime.chansend1" => Some("channel send"),
        "runtime.gopanic" => Some("initiate a panic"),
        "runtime.gorecover" => Some("recover from a panic"),
        "runtime.convI2I" => Some("interface to interface conversion"),
        "runtime.convT64" | "runtime.convTstring" => Some("concrete to interface conversion"),
        "runtime.assertI2I" => Some("interface type assertion"),
        "runtime.assertE2T" => Some("empty interface to concrete type assertion"),
        _ => None,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_rejects_itanium() {
        assert!(!GoDemangler::detect("_ZN3foo3barEi"));
        assert!(!GoDemangler::detect("_R..."));
        assert!(!GoDemangler::detect("?foo@@bar"));
    }

    #[test]
    fn detect_accepts_go_style() {
        assert!(GoDemangler::detect("main.main"));
        assert!(GoDemangler::detect("github.com/user/repo.Func"));
        assert!(GoDemangler::detect("fmt.Println"));
    }

    #[test]
    fn decode_simple_function() {
        let sym = decode_go_symbol("main.main", true).unwrap();
        assert_eq!(sym.function_name, "main");
        assert_eq!(sym.package.short_name, "main");
        assert_eq!(sym.kind, GoSymbolKind::Function);
        assert_eq!(sym.closure_depth, 0);
    }

    #[test]
    fn decode_method_with_pointer_receiver() {
        let sym = decode_go_symbol("net/http.(*Server).ListenAndServe", true).unwrap();
        assert_eq!(sym.receiver.as_deref(), Some("Server"));
        assert!(sym.receiver_is_pointer);
        assert_eq!(sym.function_name, "ListenAndServe");
        assert_eq!(sym.kind, GoSymbolKind::Method);
    }

    #[test]
    fn decode_method_with_value_receiver() {
        let sym = decode_go_symbol("bytes.(Buffer).Write", true).unwrap();
        assert_eq!(sym.receiver.as_deref(), Some("Buffer"));
        assert!(!sym.receiver_is_pointer);
        assert_eq!(sym.kind, GoSymbolKind::Method);
    }

    #[test]
    fn decode_closure() {
        let sym = decode_go_symbol("main.init.func1", true).unwrap();
        assert!(sym.closure_depth >= 1);
        assert_eq!(sym.kind, GoSymbolKind::Closure);
    }

    #[test]
    fn decode_nested_closure() {
        let sym = decode_go_symbol("main.processItems.func2.1", true).unwrap();
        assert!(sym.closure_depth >= 2);
    }

    #[test]
    fn decode_package_init() {
        let sym = decode_go_symbol("fmt.init", true).unwrap();
        assert_eq!(sym.kind, GoSymbolKind::PackageInit);
    }

    #[test]
    fn decode_generic_instance() {
        let sym = decode_go_symbol("slices.Sort[int]", true).unwrap();
        assert_eq!(sym.kind, GoSymbolKind::GenericInstance);
        assert!(!sym.type_args.is_empty());
    }

    #[test]
    fn decode_stdlib_path() {
        let sym = decode_go_symbol("encoding/json.Marshal", true).unwrap();
        assert_eq!(sym.package.import_path, "encoding/json");
        assert_eq!(sym.package.short_name, "json");
        assert!(sym.package.is_stdlib());
    }

    #[test]
    fn decode_github_path() {
        let sym = decode_go_symbol("github.com/pkg/errors.New", true).unwrap();
        assert_eq!(sym.function_name, "New");
        assert!(!sym.package.is_stdlib());
        assert!(sym.package.module_path.is_some());
    }

    #[test]
    fn go_package_is_stdlib_true() {
        let p = GoPackage::from_import_path("fmt");
        assert!(p.is_stdlib());
    }

    #[test]
    fn go_package_is_stdlib_false() {
        let p = GoPackage::from_import_path("github.com/spf13/cobra");
        assert!(!p.is_stdlib());
    }

    #[test]
    fn describe_runtime_symbol_known() {
        assert!(describe_runtime_symbol("runtime.mallocgc").is_some());
    }

    #[test]
    fn describe_runtime_symbol_unknown() {
        assert!(describe_runtime_symbol("main.foo").is_none());
    }

    #[test]
    fn caching_works() {
        let mut d = GoDemangler::new();
        d.decode("main.main");
        d.decode("main.main"); // second call hits cache
        assert_eq!(d.cache_size(), 1);
    }

    #[test]
    fn batch_decode() {
        let mut d = GoDemangler::new();
        let names = vec!["main.main", "fmt.Println", "_ZN3foo3barEi"];
        let results = d.decode_batch(&names);
        // The C++ symbol should be rejected.
        assert_eq!(results.len(), 2);
    }

    #[test]
    fn go_colon_prefix_parsed() {
        let sym = decode_go_symbol("go:itab.*net/http.Transport,net.Conn", true).unwrap();
        assert_eq!(sym.kind, GoSymbolKind::InterfaceThunk);
    }

    // ── Runtime-symbol vectors ───────────────────────────────────────────────

    #[test]
    fn go_vec_main_main() {
        let sym = decode_go_symbol("main.main", true).unwrap();
        assert_eq!(sym.short_name(), "main.main");
        assert_eq!(sym.kind, GoSymbolKind::Function);
    }

    #[test]
    fn go_vec_runtime_symbol() {
        let sym = decode_go_symbol("runtime.morestack_noctxt", true).unwrap();
        assert_eq!(sym.short_name(), "runtime.morestack_noctxt");
        assert!(sym.package.is_stdlib());
    }

    #[test]
    fn go_vec_full_import_path_method() {
        let sym = decode_go_symbol("github.com/user/repo/pkg.(*Type).Method", true).unwrap();
        assert_eq!(sym.short_name(), "pkg.(*Type).Method");
        assert_eq!(sym.receiver.as_deref(), Some("Type"));
        assert!(sym.receiver_is_pointer);
        assert_eq!(sym.function_name, "Method");
        assert_eq!(sym.kind, GoSymbolKind::Method);
    }

    #[test]
    fn go_vec_stdlib_pkg_function() {
        let sym = decode_go_symbol("encoding/json.Marshal", true).unwrap();
        assert_eq!(sym.short_name(), "json.Marshal");
        assert_eq!(sym.package.import_path, "encoding/json");
    }

    #[test]
    fn go_vec_closure_on_method() {
        let sym = decode_go_symbol("main.(*Server).handleRequest.func1", true).unwrap();
        assert_eq!(sym.kind, GoSymbolKind::Closure);
        assert!(sym.closure_depth >= 1);
        assert_eq!(sym.function_name, "handleRequest");
    }

    #[test]
    fn go_vec_value_receiver_method() {
        let sym = decode_go_symbol("main.Point.String", true).unwrap();
        assert_eq!(sym.receiver.as_deref(), Some("Point"));
        assert!(!sym.receiver_is_pointer);
    }
}
