[package]
license.workspace = true
name = "rustre-dotnet-edit"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
rustre-dotnet = { path = "../rustre-dotnet" }
rustre-dotnet-metadata = { path = "../rustre-dotnet-metadata" }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
