//! `LibFuzzer` corpus management: load corpus from directory, validate corpus entries,
//! deduplicate by content hash, minimize corpus (remove entries whose coverage is
//! subsumed), track corpus growth over time, export minimized corpus.
//!
//! Types: [`CorpusEntry`], [`CorpusManager`], [`ContentHash`], [`CoverageSubsumption`],
//! [`CorpusStats`].

use std::collections::{HashSet, VecDeque};
use std::fmt;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

// ─── ContentHash ──────────────────────────────────────────────────────────────

/// A 64-bit FNV-1a content hash used for deduplication.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ContentHash(pub u64);

impl ContentHash {
    /// Compute the FNV-1a hash of `data`.
    #[must_use]
    pub fn of(data: &[u8]) -> Self {
        const OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
        const PRIME: u64 = 0x0000_0100_0000_01b3;
        let mut h = OFFSET;
        for &b in data {
            h ^= u64::from(b);
            h = h.wrapping_mul(PRIME);
        }
        Self(h)
    }

    /// Return the raw hash value.
    #[must_use]
    pub const fn value(self) -> u64 {
        self.0
    }
}

impl fmt::Display for ContentHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:016x}", self.0)
    }
}

// ─── CorpusEntry ──────────────────────────────────────────────────────────────

/// A single corpus entry with data and metadata.
#[derive(Debug, Clone)]
pub struct CorpusEntry {
    /// The raw input bytes.
    pub data: Vec<u8>,
    /// FNV-1a hash of the data bytes.
    pub hash: ContentHash,
    /// Synthetic coverage bits derived from the data hash.
    pub coverage_bits: Vec<u8>,
    /// When the entry was added to the corpus.
    pub added_at: SystemTime,
    /// How many times this entry was selected as a mutation parent.
    pub selection_count: u64,
    /// Which file on disk this entry was loaded from, if any.
    pub source_path: Option<PathBuf>,
    /// Whether this entry was generated by minimization.
    pub is_minimized: bool,
    /// Uniqueness score in [0.0, 1.0]: fraction of coverage bits unique to this entry.
    pub uniqueness_score: f64,
}

impl CorpusEntry {
    /// Create a new entry from raw bytes.
    #[must_use]
    pub fn new(data: Vec<u8>) -> Self {
        let hash = ContentHash::of(&data);
        // Derive synthetic 8-byte coverage vector from hash.
        let coverage_bits = hash.0.to_le_bytes().to_vec();
        Self {
            data,
            hash,
            coverage_bits,
            added_at: SystemTime::now(),
            selection_count: 0,
            source_path: None,
            is_minimized: false,
            uniqueness_score: 1.0,
        }
    }

    /// Create an entry with a known source path.
    #[must_use]
    pub fn from_path(data: Vec<u8>, path: PathBuf) -> Self {
        let mut e = Self::new(data);
        e.source_path = Some(path);
        e
    }

    /// Length of the raw data in bytes.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.data.len()
    }

    /// True if the data is empty.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    /// Return the number of set bits in the synthetic coverage vector.
    #[must_use]
    pub fn coverage_popcount(&self) -> u32 {
        self.coverage_bits.iter().map(|b| b.count_ones()).sum()
    }

    /// Return true if this entry's coverage is a subset of `other`'s coverage.
    ///
    /// This is the key predicate for subsumption: if every bit set in `self` is
    /// also set in `other`, then `other` subsumes `self` and `self` can be pruned.
    #[must_use]
    pub fn is_subsumed_by(&self, other: &Self) -> bool {
        let min_len = self.coverage_bits.len().min(other.coverage_bits.len());
        for i in 0..min_len {
            // Any bit in self not in other → not subsumed.
            if self.coverage_bits[i] & !other.coverage_bits[i] != 0 {
                return false;
            }
        }
        // Remaining bits in self (beyond other's length) must be zero.
        for &b in self.coverage_bits.iter().skip(min_len) {
            if b != 0 {
                return false;
            }
        }
        true
    }
}

impl fmt::Display for CorpusEntry {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "CorpusEntry(hash={}, len={}, cov_bits={})",
            self.hash,
            self.data.len(),
            self.coverage_popcount()
        )
    }
}

// ─── CorpusValidationError ────────────────────────────────────────────────────

/// Reason why a corpus entry failed validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CorpusValidationError {
    /// Entry is empty (zero bytes).
    EmptyInput,
    /// Entry exceeds the configured maximum size.
    TooLarge { actual: usize, max: usize },
    /// Entry is below the minimum size.
    TooSmall { actual: usize, min: usize },
    /// Entry is a duplicate of an already-seen hash.
    Duplicate(ContentHash),
    /// Coverage vector has wrong length.
    BadCoverageLength { actual: usize, expected: usize },
}

impl fmt::Display for CorpusValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyInput => write!(f, "empty input"),
            Self::TooLarge { actual, max } => {
                write!(f, "input too large: {actual} > {max}")
            }
            Self::TooSmall { actual, min } => {
                write!(f, "input too small: {actual} < {min}")
            }
            Self::Duplicate(h) => write!(f, "duplicate hash {h}"),
            Self::BadCoverageLength { actual, expected } => {
                write!(f, "coverage length {actual} != {expected}")
            }
        }
    }
}

// ─── CorpusConfig ─────────────────────────────────────────────────────────────

/// Configuration controlling corpus management behaviour.
#[derive(Debug, Clone)]
pub struct CorpusConfig {
    /// Maximum number of entries to retain in the corpus.
    pub max_entries: usize,
    /// Minimum data size in bytes (0 = no minimum).
    pub min_entry_size: usize,
    /// Maximum data size in bytes (0 = unlimited).
    pub max_entry_size: usize,
    /// Whether to automatically deduplicate by content hash on insert.
    pub auto_dedup: bool,
    /// Whether to apply subsumption minimization on every insert.
    pub auto_minimize: bool,
    /// Expected coverage vector length for validation (0 = skip check).
    pub expected_coverage_len: usize,
}

impl Default for CorpusConfig {
    fn default() -> Self {
        Self {
            max_entries: 50_000,
            min_entry_size: 0,
            max_entry_size: 1024 * 1024,
            auto_dedup: true,
            auto_minimize: false,
            expected_coverage_len: 0,
        }
    }
}

// ─── CoverageSubsumption ──────────────────────────────────────────────────────

/// Records a subsumption relationship between two corpus entries.
///
/// When `subsuming_hash` subsumes `subsumed_hash`, the latter can be pruned.
#[derive(Debug, Clone)]
pub struct CoverageSubsumption {
    /// The entry that covers everything `subsumed_hash` covers (and more).
    pub subsuming_hash: ContentHash,
    /// The entry whose coverage is a strict subset of `subsuming_hash`.
    pub subsumed_hash: ContentHash,
    /// Fraction of `subsumed_hash`'s bits covered by `subsuming_hash`.
    pub coverage_fraction: f64,
}

impl CoverageSubsumption {
    /// Create a new subsumption record.
    #[must_use]
    pub const fn new(
        subsuming_hash: ContentHash,
        subsumed_hash: ContentHash,
        coverage_fraction: f64,
    ) -> Self {
        Self {
            subsuming_hash,
            subsumed_hash,
            coverage_fraction,
        }
    }
}

// ─── CorpusGrowthPoint ────────────────────────────────────────────────────────

/// A single data point in the corpus growth timeline.
#[derive(Debug, Clone)]
pub struct CorpusGrowthPoint {
    /// Wall-clock time of this snapshot.
    pub timestamp: SystemTime,
    /// Number of entries in the corpus at this moment.
    pub entry_count: usize,
    /// Total bytes across all entries.
    pub total_bytes: usize,
    /// Cumulative unique coverage bits seen.
    pub cumulative_coverage_bits: u32,
    /// What triggered this growth point.
    pub trigger: GrowthTrigger,
}

/// What caused a corpus growth event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GrowthTrigger {
    /// A new interesting input was added.
    NewInput,
    /// The corpus was loaded from disk.
    Load,
    /// The corpus was minimized (size decreased).
    Minimize,
    /// Duplicate entries were removed.
    Dedup,
}

impl fmt::Display for GrowthTrigger {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NewInput => write!(f, "new_input"),
            Self::Load => write!(f, "load"),
            Self::Minimize => write!(f, "minimize"),
            Self::Dedup => write!(f, "dedup"),
        }
    }
}

// ─── CorpusStats ──────────────────────────────────────────────────────────────

/// Statistics snapshot of a [`CorpusManager`].
#[derive(Debug, Clone, Default)]
pub struct CorpusStats {
    /// Number of entries currently in the corpus.
    pub entry_count: usize,
    /// Total bytes across all entries.
    pub total_bytes: usize,
    /// Minimum entry size in bytes.
    pub min_size: usize,
    /// Maximum entry size in bytes.
    pub max_size: usize,
    /// Average entry size in bytes.
    pub avg_size: f64,
    /// Number of unique content hashes (should equal `entry_count` after dedup).
    pub unique_hashes: usize,
    /// Total unique coverage bits set by the corpus.
    pub total_coverage_bits: u32,
    /// Number of entries pruned by subsumption minimization.
    pub subsumed_count: usize,
    /// Number of duplicate entries removed.
    pub duplicate_count: usize,
    /// Wall-clock time of the oldest entry.
    pub oldest_entry_time: Option<SystemTime>,
    /// Wall-clock time of the newest entry.
    pub newest_entry_time: Option<SystemTime>,
}

impl CorpusStats {
    /// Compute statistics from a slice of entries.
    #[must_use]
    pub fn from_entries(entries: &[CorpusEntry]) -> Self {
        if entries.is_empty() {
            return Self::default();
        }
        let entry_count = entries.len();
        let total_bytes: usize = entries.iter().map(|e| e.data.len()).sum();
        let min_size = entries.iter().map(|e| e.data.len()).min().unwrap_or(0);
        let max_size = entries.iter().map(|e| e.data.len()).max().unwrap_or(0);
        let avg_size = (total_bytes as f64) / (entry_count as f64);

        let unique_hashes: HashSet<ContentHash> = entries.iter().map(|e| e.hash).collect();

        // Union of all coverage bits.
        let mut global_cov = 0u64;
        for e in entries {
            if e.coverage_bits.len() >= 8 {
                let bits = u64::from_le_bytes(e.coverage_bits[..8].try_into().unwrap_or([0u8; 8]));
                global_cov |= bits;
            }
        }
        let total_coverage_bits = global_cov.count_ones();

        let oldest = entries
            .iter()
            .map(|e| e.added_at)
            .min_by(std::cmp::Ord::cmp);
        let newest = entries
            .iter()
            .map(|e| e.added_at)
            .max_by(std::cmp::Ord::cmp);

        Self {
            entry_count,
            total_bytes,
            min_size,
            max_size,
            avg_size,
            unique_hashes: unique_hashes.len(),
            total_coverage_bits,
            subsumed_count: 0,
            duplicate_count: 0,
            oldest_entry_time: oldest,
            newest_entry_time: newest,
        }
    }
}

impl fmt::Display for CorpusStats {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "CorpusStats {{ entries={}, bytes={}, min={}, max={}, avg={:.1}, cov_bits={} }}",
            self.entry_count,
            self.total_bytes,
            self.min_size,
            self.max_size,
            self.avg_size,
            self.total_coverage_bits
        )
    }
}

// ─── CorpusManager ────────────────────────────────────────────────────────────

/// Full corpus manager: load, validate, deduplicate, minimize, and export.
pub struct CorpusManager {
    /// Active corpus entries, ordered by insertion time.
    entries: VecDeque<CorpusEntry>,
    /// Hashes of all entries ever seen (including pruned ones).
    seen_hashes: HashSet<ContentHash>,
    /// Hashes of currently live entries.
    live_hashes: HashSet<ContentHash>,
    /// Configuration.
    pub config: CorpusConfig,
    /// Root directory for disk I/O (logical; does not create files in this impl).
    pub directory: PathBuf,
    /// Growth timeline.
    growth_log: Vec<CorpusGrowthPoint>,
    /// Number of duplicates seen since creation.
    duplicate_count: usize,
    /// Number of entries pruned by subsumption.
    subsumed_count: usize,
    /// Cumulative global coverage union (packed as u64 bitfield).
    global_coverage: u64,
}

impl CorpusManager {
    /// Create a new manager rooted at `dir`.
    #[must_use]
    pub fn new(dir: &Path) -> Self {
        Self {
            entries: VecDeque::new(),
            seen_hashes: HashSet::new(),
            live_hashes: HashSet::new(),
            config: CorpusConfig::default(),
            directory: dir.to_path_buf(),
            growth_log: Vec::new(),
            duplicate_count: 0,
            subsumed_count: 0,
            global_coverage: 0,
        }
    }

    /// Create with a custom configuration.
    #[must_use]
    pub fn with_config(dir: &Path, config: CorpusConfig) -> Self {
        let mut m = Self::new(dir);
        m.config = config;
        m
    }

    // ── Validation ────────────────────────────────────────────────────────────

    /// Validate an entry before insertion. Returns `Ok(())` or a validation error.
    pub fn validate(&self, entry: &CorpusEntry) -> Result<(), CorpusValidationError> {
        if entry.data.is_empty() {
            return Err(CorpusValidationError::EmptyInput);
        }
        let min = self.config.min_entry_size;
        if min > 0 && entry.data.len() < min {
            return Err(CorpusValidationError::TooSmall {
                actual: entry.data.len(),
                min,
            });
        }
        let max = self.config.max_entry_size;
        if max > 0 && entry.data.len() > max {
            return Err(CorpusValidationError::TooLarge {
                actual: entry.data.len(),
                max,
            });
        }
        if self.config.auto_dedup && self.live_hashes.contains(&entry.hash) {
            return Err(CorpusValidationError::Duplicate(entry.hash));
        }
        let exp_len = self.config.expected_coverage_len;
        if exp_len > 0 && entry.coverage_bits.len() != exp_len {
            return Err(CorpusValidationError::BadCoverageLength {
                actual: entry.coverage_bits.len(),
                expected: exp_len,
            });
        }
        Ok(())
    }

    // ── Insert ────────────────────────────────────────────────────────────────

    /// Try to add an entry. Returns `true` if added, `false` if rejected or duplicate.
    pub fn try_add(&mut self, entry: CorpusEntry) -> bool {
        if self.validate(&entry).is_err() {
            if self.seen_hashes.contains(&entry.hash) {
                self.duplicate_count += 1;
            }
            return false;
        }
        self.insert_validated(entry, GrowthTrigger::NewInput);
        true
    }

    /// Add an entry from raw bytes. Returns `true` if added.
    pub fn add_bytes(&mut self, data: Vec<u8>) -> bool {
        let entry = CorpusEntry::new(data);
        self.try_add(entry)
    }

    fn insert_validated(&mut self, entry: CorpusEntry, trigger: GrowthTrigger) {
        // Update coverage union.
        if entry.coverage_bits.len() >= 8 {
            let bits = u64::from_le_bytes(
                entry.coverage_bits[..8].try_into().unwrap_or([0u8; 8]),
            );
            self.global_coverage |= bits;
        }

        self.seen_hashes.insert(entry.hash);
        self.live_hashes.insert(entry.hash);
        self.entries.push_back(entry);

        // Cap corpus size.
        while self.entries.len() > self.config.max_entries {
            if let Some(evicted) = self.entries.pop_front() {
                self.live_hashes.remove(&evicted.hash);
            }
        }

        // Optionally minimize.
        if self.config.auto_minimize {
            self.minimize_inplace();
        }

        self.record_growth(trigger);
    }

    // ── Load ──────────────────────────────────────────────────────────────────

    /// Load corpus entries from a slice of byte vectors (logical load — not disk I/O).
    ///
    /// Returns the number of entries successfully added.
    pub fn load_from_bytes(&mut self, inputs: Vec<Vec<u8>>) -> usize {
        let mut added = 0;
        for data in inputs {
            if self.add_bytes(data) {
                added += 1;
            }
        }
        if added > 0 {
            self.record_growth(GrowthTrigger::Load);
        }
        added
    }

    /// Simulate loading corpus from a directory by accepting entries tagged with paths.
    /// In a real implementation this would read files from `self.directory`.
    pub fn load_from_entries(&mut self, entries: Vec<CorpusEntry>) -> usize {
        let mut added = 0;
        for e in entries {
            if self.try_add(e) {
                added += 1;
            }
        }
        if added > 0 {
            self.record_growth(GrowthTrigger::Load);
        }
        added
    }

    // ── Deduplication ─────────────────────────────────────────────────────────

    /// Remove entries with duplicate content hashes.
    ///
    /// Keeps the first occurrence of each hash. Returns the number removed.
    pub fn dedup(&mut self) -> usize {
        let before = self.entries.len();
        let mut seen: HashSet<ContentHash> = HashSet::new();
        self.entries.retain(|e| seen.insert(e.hash));
        let removed = before - self.entries.len();

        // Rebuild live_hashes.
        self.live_hashes = self.entries.iter().map(|e| e.hash).collect();
        self.duplicate_count += removed;

        if removed > 0 {
            self.record_growth(GrowthTrigger::Dedup);
        }
        removed
    }

    // ── Minimization (subsumption) ────────────────────────────────────────────

    /// Find all subsumption relationships between live entries.
    ///
    /// Returns a vec of [`CoverageSubsumption`] records for every pair (A, B)
    /// where A is subsumed by B.
    #[must_use]
    pub fn find_subsumptions(&self) -> Vec<CoverageSubsumption> {
        let entries: Vec<&CorpusEntry> = self.entries.iter().collect();
        let mut result = Vec::new();

        for (i, candidate) in entries.iter().enumerate() {
            for (j, other) in entries.iter().enumerate() {
                if i == j {
                    continue;
                }
                if candidate.is_subsumed_by(other) {
                    let fraction = f64::from(candidate.coverage_popcount())
                        / f64::from(other.coverage_popcount()).max(1.0);
                    result.push(CoverageSubsumption::new(
                        other.hash,
                        candidate.hash,
                        fraction,
                    ));
                }
            }
        }
        result
    }

    /// Minimize the corpus by removing entries whose coverage is subsumed by others.
    ///
    /// Returns the number of entries removed.
    pub fn minimize(&mut self) -> usize {
        let subsumptions = self.find_subsumptions();
        let to_remove: HashSet<ContentHash> =
            subsumptions.iter().map(|s| s.subsumed_hash).collect();

        if to_remove.is_empty() {
            return 0;
        }

        let before = self.entries.len();
        self.entries.retain(|e| !to_remove.contains(&e.hash));
        let removed = before - self.entries.len();

        // Rebuild live_hashes.
        self.live_hashes = self.entries.iter().map(|e| e.hash).collect();
        self.subsumed_count += removed;

        if removed > 0 {
            self.record_growth(GrowthTrigger::Minimize);
        }
        removed
    }

    fn minimize_inplace(&mut self) {
        self.minimize();
    }

    // ── Export ────────────────────────────────────────────────────────────────

    /// Export the current corpus as a vec of raw byte vectors.
    #[must_use]
    pub fn export(&self) -> Vec<Vec<u8>> {
        self.entries.iter().map(|e| e.data.clone()).collect()
    }

    /// Export only entries that pass the minimum uniqueness threshold.
    #[must_use]
    pub fn export_unique(&self, min_score: f64) -> Vec<Vec<u8>> {
        self.entries
            .iter()
            .filter(|e| e.uniqueness_score >= min_score)
            .map(|e| e.data.clone())
            .collect()
    }

    /// Compute uniqueness scores for all entries and update them in place.
    ///
    /// Score = number of coverage bits unique to this entry / total coverage bits.
    pub fn compute_uniqueness_scores(&mut self) {
        // For each entry, count how many of its bits are not covered by any other entry.
        let n = self.entries.len();
        if n == 0 {
            return;
        }
        let entries: Vec<Vec<u8>> = self.entries.iter().map(|e| e.coverage_bits.clone()).collect();
        let total_bits: u32 = self.global_coverage.count_ones();

        for i in 0..n {
            if entries[i].len() < 8 {
                self.entries[i].uniqueness_score = 0.0;
                continue;
            }
            let self_bits =
                u64::from_le_bytes(entries[i][..8].try_into().unwrap_or([0u8; 8]));
            let mut union_others = 0u64;
            for (j, other) in entries.iter().enumerate() {
                if i == j || other.len() < 8 {
                    continue;
                }
                let ob = u64::from_le_bytes(other[..8].try_into().unwrap_or([0u8; 8]));
                union_others |= ob;
            }
            let unique_bits = (self_bits & !union_others).count_ones();
            let score = if total_bits == 0 {
                0.0
            } else {
                f64::from(unique_bits) / f64::from(total_bits)
            };
            self.entries[i].uniqueness_score = score;
        }
    }

    // ── Statistics ────────────────────────────────────────────────────────────

    /// Return a stats snapshot.
    #[must_use]
    pub fn stats(&self) -> CorpusStats {
        let mut s = CorpusStats::from_entries(&self.entries.iter().cloned().collect::<Vec<_>>());
        s.subsumed_count = self.subsumed_count;
        s.duplicate_count = self.duplicate_count;
        s
    }

    /// Return the number of active entries.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// True if the corpus has no entries.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Return an iterator over active entries.
    pub fn iter(&self) -> impl Iterator<Item = &CorpusEntry> {
        self.entries.iter()
    }

    /// Return the cumulative global coverage bits.
    #[must_use]
    pub const fn global_coverage_bits(&self) -> u32 {
        self.global_coverage.count_ones()
    }

    // ── Growth log ────────────────────────────────────────────────────────────

    fn record_growth(&mut self, trigger: GrowthTrigger) {
        let total_bytes: usize = self.entries.iter().map(|e| e.data.len()).sum();
        self.growth_log.push(CorpusGrowthPoint {
            timestamp: SystemTime::now(),
            entry_count: self.entries.len(),
            total_bytes,
            cumulative_coverage_bits: self.global_coverage.count_ones(),
            trigger,
        });
    }

    /// Return the growth timeline.
    #[must_use]
    pub fn growth_log(&self) -> &[CorpusGrowthPoint] {
        &self.growth_log
    }

    /// Clear the growth log.
    pub fn clear_growth_log(&mut self) {
        self.growth_log.clear();
    }

    // ── Merge ─────────────────────────────────────────────────────────────────

    /// Merge entries from another manager into this one. Returns entries added.
    pub fn merge_from(&mut self, other: &Self) -> usize {
        let mut added = 0;
        for entry in other.iter() {
            if self.try_add(entry.clone()) {
                added += 1;
            }
        }
        added
    }

    // ── Selection ─────────────────────────────────────────────────────────────

    /// Select an entry for mutation based on selection frequency (lowest-count first).
    ///
    /// Returns `None` if the corpus is empty.
    pub fn select_for_mutation(&mut self) -> Option<&CorpusEntry> {
        if self.entries.is_empty() {
            return None;
        }
        // Find the entry with the lowest selection count.
        let idx = self
            .entries
            .iter()
            .enumerate()
            .min_by_key(|(_, e)| e.selection_count)
            .map(|(i, _)| i)?;
        self.entries[idx].selection_count += 1;
        Some(&self.entries[idx])
    }

    // ── Clear ─────────────────────────────────────────────────────────────────

    /// Remove all entries and reset counters.
    pub fn clear(&mut self) {
        self.entries.clear();
        self.live_hashes.clear();
        self.global_coverage = 0;
    }
}

// ─── CorpusExportFormat ───────────────────────────────────────────────────────

/// Supported export formats for corpus serialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CorpusExportFormat {
    /// Raw binary blobs, one per file (logical: returns flat byte vecs).
    RawBinary,
    /// Hex-encoded strings, one per line.
    HexLines,
    /// Base64-encoded strings, one per line.
    Base64Lines,
}

/// Serialize a corpus to a text representation.
///
/// - `RawBinary` returns each entry as a separate item in the outer vec.
/// - `HexLines` / `Base64Lines` return a single item containing all entries as
///   newline-separated encoded strings.
#[must_use]
pub fn export_corpus(entries: &[Vec<u8>], format: CorpusExportFormat) -> Vec<Vec<u8>> {
    match format {
        CorpusExportFormat::RawBinary => entries.to_vec(),
        CorpusExportFormat::HexLines => {
            let mut out = String::new();
            for e in entries {
                for b in e {
                    out.push_str(&format!("{b:02x}"));
                }
                out.push('\n');
            }
            vec![out.into_bytes()]
        }
        CorpusExportFormat::Base64Lines => {
            let mut out = String::new();
            for e in entries {
                out.push_str(&base64_encode(e));
                out.push('\n');
            }
            vec![out.into_bytes()]
        }
    }
}

/// Minimal base-64 encoder (no external crates).
fn base64_encode(data: &[u8]) -> String {
    const TABLE: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(data.len().div_ceil(3) * 4);
    let mut i = 0;
    while i + 2 < data.len() {
        let b0 = data[i];
        let b1 = data[i + 1];
        let b2 = data[i + 2];
        out.push(TABLE[(b0 >> 2) as usize] as char);
        out.push(TABLE[((b0 & 0x03) << 4 | b1 >> 4) as usize] as char);
        out.push(TABLE[((b1 & 0x0f) << 2 | b2 >> 6) as usize] as char);
        out.push(TABLE[(b2 & 0x3f) as usize] as char);
        i += 3;
    }
    if i < data.len() {
        let b0 = data[i];
        out.push(TABLE[(b0 >> 2) as usize] as char);
        if i + 1 < data.len() {
            let b1 = data[i + 1];
            out.push(TABLE[((b0 & 0x03) << 4 | b1 >> 4) as usize] as char);
            out.push(TABLE[((b1 & 0x0f) << 2) as usize] as char);
        } else {
            out.push(TABLE[((b0 & 0x03) << 4) as usize] as char);
            out.push('=');
        }
        out.push('=');
    }
    out
}

// ─── CorpusEntryBuilder ───────────────────────────────────────────────────────

/// Builder for [`CorpusEntry`].
#[derive(Debug, Default)]
pub struct CorpusEntryBuilder {
    data: Vec<u8>,
    source_path: Option<PathBuf>,
    is_minimized: bool,
    custom_coverage: Option<Vec<u8>>,
}

impl CorpusEntryBuilder {
    /// Create a new builder.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the raw data bytes.
    #[must_use]
    pub fn data(mut self, data: Vec<u8>) -> Self {
        self.data = data;
        self
    }

    /// Set the source path.
    #[must_use]
    pub fn source_path(mut self, path: PathBuf) -> Self {
        self.source_path = Some(path);
        self
    }

    /// Mark entry as minimized.
    #[must_use]
    pub const fn minimized(mut self) -> Self {
        self.is_minimized = true;
        self
    }

    /// Override the coverage bits.
    #[must_use]
    pub fn coverage(mut self, bits: Vec<u8>) -> Self {
        self.custom_coverage = Some(bits);
        self
    }

    /// Build the entry.
    #[must_use]
    pub fn build(self) -> CorpusEntry {
        let mut e = CorpusEntry::new(self.data);
        if let Some(path) = self.source_path {
            e.source_path = Some(path);
        }
        e.is_minimized = self.is_minimized;
        if let Some(cov) = self.custom_coverage {
            e.coverage_bits = cov;
        }
        e
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    fn manager() -> CorpusManager {
        CorpusManager::new(Path::new("/tmp/corpus"))
    }

    #[test]
    fn content_hash_deterministic() {
        let h1 = ContentHash::of(b"hello");
        let h2 = ContentHash::of(b"hello");
        assert_eq!(h1, h2);
    }

    #[test]
    fn content_hash_distinct() {
        let h1 = ContentHash::of(b"hello");
        let h2 = ContentHash::of(b"world");
        assert_ne!(h1, h2);
    }

    #[test]
    fn corpus_entry_new() {
        let e = CorpusEntry::new(b"test".to_vec());
        assert_eq!(e.data, b"test");
        assert!(!e.coverage_bits.is_empty());
    }

    #[test]
    fn corpus_entry_len() {
        let e = CorpusEntry::new(vec![1, 2, 3]);
        assert_eq!(e.len(), 3);
        assert!(!e.is_empty());
    }

    #[test]
    fn corpus_entry_coverage_popcount() {
        let e = CorpusEntry::new(b"any".to_vec());
        assert!(e.coverage_popcount() > 0);
    }

    #[test]
    fn validate_empty_rejected() {
        let m = manager();
        let e = CorpusEntry::new(vec![]);
        assert!(matches!(
            m.validate(&e),
            Err(CorpusValidationError::EmptyInput)
        ));
    }

    #[test]
    fn validate_too_large_rejected() {
        let mut m = manager();
        m.config.max_entry_size = 4;
        let e = CorpusEntry::new(vec![0u8; 8]);
        assert!(matches!(
            m.validate(&e),
            Err(CorpusValidationError::TooLarge { .. })
        ));
    }

    #[test]
    fn validate_too_small_rejected() {
        let mut m = manager();
        m.config.min_entry_size = 10;
        let e = CorpusEntry::new(vec![1, 2, 3]);
        assert!(matches!(
            m.validate(&e),
            Err(CorpusValidationError::TooSmall { .. })
        ));
    }

    #[test]
    fn add_bytes_dedup() {
        let mut m = manager();
        assert!(m.add_bytes(b"hello".to_vec()));
        assert!(!m.add_bytes(b"hello".to_vec()));
        assert_eq!(m.len(), 1);
    }

    #[test]
    fn add_bytes_distinct() {
        let mut m = manager();
        m.add_bytes(b"aaa".to_vec());
        m.add_bytes(b"bbb".to_vec());
        assert_eq!(m.len(), 2);
    }

    #[test]
    fn load_from_bytes_counts() {
        let mut m = manager();
        let added = m.load_from_bytes(vec![
            b"a".to_vec(),
            b"b".to_vec(),
            b"a".to_vec(), // duplicate
        ]);
        assert_eq!(added, 2);
        assert_eq!(m.len(), 2);
    }

    #[test]
    fn dedup_removes_duplicates() {
        let mut m = manager();
        // Disable auto_dedup to allow manual insertion of a duplicate.
        m.config.auto_dedup = false;
        let e1 = CorpusEntry::new(b"dup".to_vec());
        let e2 = CorpusEntry::new(b"dup".to_vec());
        m.entries.push_back(e1);
        m.entries.push_back(e2);
        m.live_hashes = m.entries.iter().map(|e| e.hash).collect();
        assert_eq!(m.len(), 2);
        let removed = m.dedup();
        assert_eq!(removed, 1);
        assert_eq!(m.len(), 1);
    }

    #[test]
    fn export_returns_all_data() {
        let mut m = manager();
        m.add_bytes(b"one".to_vec());
        m.add_bytes(b"two".to_vec());
        let exported = m.export();
        assert_eq!(exported.len(), 2);
    }

    #[test]
    fn stats_basic() {
        let mut m = manager();
        m.add_bytes(b"abc".to_vec());
        let s = m.stats();
        assert_eq!(s.entry_count, 1);
        assert_eq!(s.total_bytes, 3);
    }

    #[test]
    fn growth_log_populated() {
        let mut m = manager();
        m.add_bytes(b"entry1".to_vec());
        m.add_bytes(b"entry2".to_vec());
        assert!(!m.growth_log().is_empty());
    }

    #[test]
    fn merge_from_adds_novel() {
        let mut m1 = manager();
        let mut m2 = manager();
        m1.add_bytes(b"aaa".to_vec());
        m2.add_bytes(b"bbb".to_vec());
        m2.add_bytes(b"aaa".to_vec()); // already in m1
        let added = m1.merge_from(&m2);
        assert_eq!(added, 1);
        assert_eq!(m1.len(), 2);
    }

    #[test]
    fn select_for_mutation_increments_count() {
        let mut m = manager();
        m.add_bytes(b"data".to_vec());
        let _sel = m.select_for_mutation();
        assert_eq!(m.entries[0].selection_count, 1);
    }

    #[test]
    fn export_hex_lines() {
        let data = vec![vec![0xAB, 0xCD]];
        let result = export_corpus(&data, CorpusExportFormat::HexLines);
        assert_eq!(result.len(), 1);
        let s = String::from_utf8(result[0].clone()).unwrap();
        assert!(s.contains("abcd"));
    }

    #[test]
    fn corpus_entry_builder() {
        let e = CorpusEntryBuilder::new()
            .data(b"built".to_vec())
            .minimized()
            .build();
        assert_eq!(e.data, b"built");
        assert!(e.is_minimized);
    }

    #[test]
    fn content_hash_display() {
        let h = ContentHash(0x0102_0304_0506_0708);
        assert_eq!(h.to_string(), "0102030405060708");
    }

    #[test]
    fn corpus_stats_empty() {
        let s = CorpusStats::default();
        assert_eq!(s.entry_count, 0);
    }

    #[test]
    fn validation_error_display() {
        let e = CorpusValidationError::EmptyInput;
        assert_eq!(e.to_string(), "empty input");
    }
}
