[package]
license.workspace = true
name = "rustre-agent-prompts"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-agent = { path = "../rustre-agent" }
rustre-agent-llm = { path = "../rustre-agent-llm" }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
parking_lot = { workspace = true }

[lints]
workspace = true
