[package]
license.workspace = true
name = "rustre-arch-ppc"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-core = { path = "../rustre-core" }
ahash = { workspace = true }

[lints]
workspace = true
