[package]
license.workspace = true
name = "rustre-mobile-ipa"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zip = "2"
anyhow = { workspace = true }
flate2 = { workspace = true }
rustre-demangle = { path = "../rustre-demangle" }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
