//! Embeds this crate's own sources so the source guards can run anywhere.
//!
//! Why this exists
//! ---------------
//! A large family of tests in `lib.rs` checks invariants ACROSS the backends by
//! reading the crate's own source — the only lens that covers a platform this
//! workspace cannot execute. They discovered their input with
//! `std::fs::read_dir("src")` at run time, which works only when the test binary
//! runs with the crate root as its working directory.
//!
//! It does not under `xcrun simctl spawn`. The first time this suite was
//! executed for an Apple triple (macos-14 runner, 2026-08-15) five guards failed
//! at once, all with the same cause: the binary runs in the simulator's sandbox,
//! where no repository exists at any path, absolute or relative.
//!
//! `include_str!` alone cannot fix it, because these guards must cover EVERY
//! source file — a hand-written list would go stale the moment a file is added,
//! and a guard that silently stops covering a file is worse than no guard: it
//! reads as coverage. So the list is generated here, from the directory itself,
//! at compile time.
//!
//! The alternative considered and rejected was letting the guards skip when the
//! tree is absent. A test that skips instead of failing when the code is wrong
//! is not a test — a rule this crate already enforces elsewhere.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let src = Path::new(&manifest).join("src");

    let mut files = Vec::new();
    walk(&src, &mut files);
    files.sort();
    assert!(!files.is_empty(), "build.rs found no sources under {}", src.display());

    let mut out = String::from(
        "// Generated by build.rs. Do not edit.\n\
         pub(crate) static EMBEDDED_SOURCES: &[(&str, &str)] = &[\n",
    );
    for f in &files {
        let name = f.file_name().unwrap_or_default().to_string_lossy().to_string();
        // A literal path in `include_str!` must not contain an unescaped
        // backslash: on Windows `Path::display` yields `src\ios\rsp.rs`, and
        // `\i` and `\r` are then read as escapes — `\r` silently becoming a
        // carriage return and the file never being found.
        let path = f.to_string_lossy().replace('\\', "/");
        let _ = writeln!(out, "    ({name:?}, include_str!({path:?})),");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_sources.rs");
    std::fs::write(&dest, out).expect("write embedded_sources.rs");

    // Re-run when a source is added, removed or edited. Watching the DIRECTORY
    // is what catches an addition; watching only the files that exist today
    // would not, which is the staleness this whole file exists to prevent.
    println!("cargo:rerun-if-changed={}", src.display());
    for f in &files {
        println!("cargo:rerun-if-changed={}", f.display());
    }
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            walk(&p, out);
        } else if p.extension().is_some_and(|x| x == "rs") {
            out.push(p);
        }
    }
}
