[package]
license.workspace = true
name = "rustre-analysis-typerecov"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-analysis = { path = "../rustre-analysis" }
rustre-analysis-type = { path = "../rustre-analysis-type" }
thiserror = { workspace = true }
serde = { workspace = true }
iced-x86 = { workspace = true }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
