[package]
license.workspace = true
name = "rustre-ttd-replay"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-ttd = { path = "../rustre-ttd" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
bitflags = { workspace = true }

[lints]
workspace = true
