//! `smt_prover` — SMT-based opaque predicate verification.
//!
//! Uses a built-in pure-Rust SMT encoding for simple linear arithmetic and
//! boolean algebra predicates.  Complex or unsupported predicates fall back
//! to the heuristic evaluator in [`crate::tautology_db`].
//!
//! # Design
//! Rather than linking Z3 as a native dependency (which complicates cross-platform
//! builds), this module implements a lightweight decision procedure covering
//! the fragment of predicates actually generated by common obfuscators:
//! * Algebraic identities:  `x² ≥ 0`,  `(x & 1) | (~x & 1) == 1`
//! * Wrapping-arithmetic:  `x.wrapping_add(1).wrapping_sub(1) == x`
//! * Boolean tautologies:   `(a ∧ ¬a) == 0`,  `(a ∨ ¬a) == 1`
//! * Fermat-little-theorem patterns:  `x^(p-1) ≡ 1 (mod p)` for small primes `p`
//!
//! A timeout mechanism aborts slow checks and reports `Unknown`.


use std::collections::HashMap;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

use crate::PredicateValue;

// ─────────────────────────────────────────────────────────────────────────────
// SMT expression AST
// ─────────────────────────────────────────────────────────────────────────────

/// A symbolic expression suitable for SMT solving.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SmtExpr {
    /// Boolean or integer constant.
    Const(i64),
    /// Symbolic variable (name, bit-width).
    Var { name: String, width: u8 },
    /// Binary operation.
    BinOp {
        op: SmtBinOp,
        lhs: Box<SmtExpr>,
        rhs: Box<SmtExpr>,
    },
    /// Unary operation.
    UnaryOp {
        op: SmtUnaryOp,
        inner: Box<SmtExpr>,
    },
    /// Comparison: returns 0 or 1.
    Cmp {
        op: SmtCmpOp,
        lhs: Box<SmtExpr>,
        rhs: Box<SmtExpr>,
    },
}

/// Binary operations in the SMT expression language.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SmtBinOp {
    Add, Sub, Mul, UDiv, SDiv,
    And, Or, Xor,
    Shl, LShr, AShr,
    /// Modular reduction (unsigned).
    URem,
    /// Modular reduction (signed).
    SRem,
}

/// Unary operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SmtUnaryOp {
    /// Bitwise NOT.
    Not,
    /// Two's complement negate.
    Neg,
    /// Square: `x * x`.
    Square,
}

/// Comparison predicates (return bool / 1-bit BV).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SmtCmpOp {
    Eq, Ne,
    /// Unsigned less-than.
    Ult,
    /// Unsigned less-or-equal.
    Ule,
    /// Signed less-than.
    Slt,
    /// Signed less-or-equal.
    Sle,
    /// Unsigned greater-than.
    Ugt,
    /// Signed greater-than.
    Sgt,
}

impl SmtExpr {
    // ── Constructors ──────────────────────────────────────────────────────────

    #[must_use]
    pub const fn constant(v: i64) -> Self {
        Self::Const(v)
    }

    pub fn var(name: impl Into<String>, width: u8) -> Self {
        Self::Var { name: name.into(), width }
    }

    #[must_use]
    pub fn add(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::BinOp {
            op: SmtBinOp::Add,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn sub(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::BinOp {
            op: SmtBinOp::Sub,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn mul(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::BinOp {
            op: SmtBinOp::Mul,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn and(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::BinOp {
            op: SmtBinOp::And,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn or(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::BinOp {
            op: SmtBinOp::Or,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn xor(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::BinOp {
            op: SmtBinOp::Xor,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn not(inner: SmtExpr) -> Self {
        Self::UnaryOp {
            op: SmtUnaryOp::Not,
            inner: Box::new(inner),
        }
    }

    #[must_use]
    pub fn neg(inner: SmtExpr) -> Self {
        Self::UnaryOp {
            op: SmtUnaryOp::Neg,
            inner: Box::new(inner),
        }
    }

    #[must_use]
    pub fn square(inner: SmtExpr) -> Self {
        Self::UnaryOp {
            op: SmtUnaryOp::Square,
            inner: Box::new(inner),
        }
    }

    #[must_use]
    pub fn eq(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::Cmp {
            op: SmtCmpOp::Eq,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn ne(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::Cmp {
            op: SmtCmpOp::Ne,
            lhs: Box::new(lhs),
            rhs: Box::new(rhs),
        }
    }

    #[must_use]
    pub fn sge(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        // x ≥ rhs  →  NOT (x < rhs)
        Self::UnaryOp {
            op: SmtUnaryOp::Not,
            inner: Box::new(Self::Cmp {
                op: SmtCmpOp::Slt,
                lhs: Box::new(lhs),
                rhs: Box::new(rhs),
            }),
        }
    }

    #[must_use]
    pub fn uge(lhs: SmtExpr, rhs: SmtExpr) -> Self {
        Self::UnaryOp {
            op: SmtUnaryOp::Not,
            inner: Box::new(Self::Cmp {
                op: SmtCmpOp::Ult,
                lhs: Box::new(lhs),
                rhs: Box::new(rhs),
            }),
        }
    }

    /// Return all free variable names in this expression.
    #[must_use]
    pub fn free_vars(&self) -> Vec<(String, u8)> {
        let mut vars = Vec::new();
        self.collect_vars(&mut vars);
        vars.sort_by_key(|(n, _)| n.clone());
        vars.dedup_by_key(|(n, _)| n.clone());
        vars
    }

    fn collect_vars(&self, out: &mut Vec<(String, u8)>) {
        match self {
            Self::Var { name, width } => out.push((name.clone(), *width)),
            Self::BinOp { lhs, rhs, .. } => {
                lhs.collect_vars(out);
                rhs.collect_vars(out);
            }
            Self::UnaryOp { inner, .. } => inner.collect_vars(out),
            Self::Cmp { lhs, rhs, .. } => {
                lhs.collect_vars(out);
                rhs.collect_vars(out);
            }
            Self::Const(_) => {}
        }
    }

    /// Evaluate the expression given a variable assignment.
    #[must_use]
    pub fn eval(&self, env: &HashMap<String, i64>) -> Option<i64> {
        match self {
            Self::Const(v) => Some(*v),
            Self::Var { name, .. } => env.get(name).copied(),
            Self::BinOp { op, lhs, rhs } => {
                let l = lhs.eval(env)?;
                let r = rhs.eval(env)?;
                Some(eval_binop(*op, l, r))
            }
            Self::UnaryOp { op, inner } => {
                let v = inner.eval(env)?;
                Some(eval_unary(*op, v))
            }
            Self::Cmp { op, lhs, rhs } => {
                let l = lhs.eval(env)?;
                let r = rhs.eval(env)?;
                Some(eval_cmp(*op, l, r))
            }
        }
    }
}

const fn eval_binop(op: SmtBinOp, l: i64, r: i64) -> i64 {
    match op {
        SmtBinOp::Add  => l.wrapping_add(r),
        SmtBinOp::Sub  => l.wrapping_sub(r),
        SmtBinOp::Mul  => l.wrapping_mul(r),
        SmtBinOp::UDiv => if r != 0 { (l as u64 / r as u64) as i64 } else { 0 },
        SmtBinOp::SDiv => if r != 0 { l.wrapping_div(r) } else { 0 },
        SmtBinOp::And  => l & r,
        SmtBinOp::Or   => l | r,
        SmtBinOp::Xor  => l ^ r,
        SmtBinOp::Shl  => l.wrapping_shl(r as u32),
        SmtBinOp::LShr => ((l as u64).wrapping_shr(r as u32)) as i64,
        SmtBinOp::AShr => l.wrapping_shr(r as u32),
        SmtBinOp::URem => if r != 0 { (l as u64 % r as u64) as i64 } else { 0 },
        SmtBinOp::SRem => if r != 0 { l.wrapping_rem(r) } else { 0 },
    }
}

const fn eval_unary(op: SmtUnaryOp, v: i64) -> i64 {
    match op {
        SmtUnaryOp::Not    => !v,
        SmtUnaryOp::Neg    => v.wrapping_neg(),
        SmtUnaryOp::Square => v.wrapping_mul(v),
    }
}

fn eval_cmp(op: SmtCmpOp, l: i64, r: i64) -> i64 {
    match op {
        SmtCmpOp::Eq  => i64::from(l == r),
        SmtCmpOp::Ne  => i64::from(l != r),
        SmtCmpOp::Ult => i64::from((l as u64) < (r as u64)),
        SmtCmpOp::Ule => i64::from((l as u64) <= (r as u64)),
        SmtCmpOp::Slt => i64::from(l < r),
        SmtCmpOp::Sle => i64::from(l <= r),
        SmtCmpOp::Ugt => i64::from((l as u64) > (r as u64)),
        SmtCmpOp::Sgt => i64::from(l > r),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// SMT check result
// ─────────────────────────────────────────────────────────────────────────────

/// Result of an SMT satisfiability check.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmtResult {
    /// The formula is satisfiable; a witness assignment is provided.
    Sat { witness: HashMap<String, i64> },
    /// The formula is unsatisfiable (UNSAT / proven).
    Unsat,
    /// Could not determine (timeout, unsupported fragment, resource limit).
    Unknown { reason: String },
}

impl SmtResult {
    #[must_use]
    pub const fn is_sat(&self) -> bool {
        matches!(self, Self::Sat { .. })
    }
    #[must_use]
    pub const fn is_unsat(&self) -> bool {
        matches!(self, Self::Unsat)
    }
    #[must_use]
    pub const fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown { .. })
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// SmtProver
// ─────────────────────────────────────────────────────────────────────────────

/// Lightweight SMT prover for opaque predicate classification.
pub struct SmtProver {
    /// Timeout for a single check.
    pub timeout: Duration,
    /// Number of random samples to use for the exhaustive truth-table check.
    pub sample_count: u32,
    /// Bit-width used when sampling (8, 16, 32, or 64).
    pub sample_width: u8,
}

impl Default for SmtProver {
    fn default() -> Self {
        Self {
            timeout: Duration::from_millis(200),
            sample_count: 1024,
            sample_width: 32,
        }
    }
}

impl SmtProver {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    #[must_use]
    pub const fn with_timeout(mut self, ms: u64) -> Self {
        self.timeout = Duration::from_millis(ms);
        self
    }

    #[must_use]
    pub const fn with_sample_count(mut self, n: u32) -> Self {
        self.sample_count = n;
        self
    }

    // ── Main entry point ──────────────────────────────────────────────────────

    /// Determine whether `predicate` is always-true, always-false, or neither.
    ///
    /// Strategy (in order):
    /// 1. Try algebraic simplification (fast, zero-cost).
    /// 2. Check against known pattern database.
    /// 3. Exhaustive truth-table for 1-variable predicates.
    /// 4. Sampled truth-table for multi-variable predicates.
    /// 5. Fallback: Unknown.
    #[must_use]
    pub fn check(&self, predicate: &SmtExpr) -> (PredicateValue, f32, SmtResult) {
        let start = Instant::now();

        // 1. Algebraic simplification
        if let Some((val, conf)) = self.algebraic_simplify(predicate) {
            let smt_result = if val == PredicateValue::AlwaysTrue {
                SmtResult::Unsat // negation is UNSAT
            } else if val == PredicateValue::AlwaysFalse {
                SmtResult::Sat { witness: HashMap::new() }
            } else {
                SmtResult::Unknown { reason: "algebraic".into() }
            };
            return (val, conf, smt_result);
        }

        // 2. Pattern database check
        if let Some((val, conf)) = self.pattern_check(predicate) {
            return (val, conf, SmtResult::Unsat);
        }

        // 3. Truth-table check
        let vars = predicate.free_vars();
        if vars.is_empty() {
            // Ground expression — just evaluate
            let env = HashMap::new();
            match predicate.eval(&env) {
                Some(0) => return (PredicateValue::AlwaysFalse, 1.0, SmtResult::Sat { witness: HashMap::new() }),
                Some(_) => return (PredicateValue::AlwaysTrue, 1.0, SmtResult::Unsat),
                None => {}
            }
        }

        // Timeout guard
        if start.elapsed() > self.timeout {
            return (
                PredicateValue::Unknown,
                0.0,
                SmtResult::Unknown { reason: "timeout".into() },
            );
        }

        // 4. Sampled truth-table
        let (val, conf) = self.sampled_check(predicate, &vars, start);
        let smt_result = match val {
            PredicateValue::AlwaysTrue => SmtResult::Unsat,
            PredicateValue::AlwaysFalse => SmtResult::Sat { witness: self.find_witness(predicate, &vars) },
            PredicateValue::Unknown => SmtResult::Unknown { reason: "sampling inconclusive".into() },
        };

        (val, conf, smt_result)
    }

    // ── Algebraic simplification ──────────────────────────────────────────────

    /// Try to resolve the predicate using algebraic identities.
    fn algebraic_simplify(&self, expr: &SmtExpr) -> Option<(PredicateValue, f32)> {
        if let SmtExpr::Cmp { op, lhs, rhs } = expr {
            // x² < 0 (or unsigned) — always false
            if matches!(op, SmtCmpOp::Slt | SmtCmpOp::Ult) {
                if matches!(rhs.as_ref(), SmtExpr::Const(0)) {
                    if matches!(lhs.as_ref(), SmtExpr::UnaryOp { op: SmtUnaryOp::Square, .. }) {
                        return Some((PredicateValue::AlwaysFalse, 0.85));
                    }
                }
            }

            if *op == SmtCmpOp::Eq {
                // x - x == 0
                if matches!(rhs.as_ref(), SmtExpr::Const(0)) {
                    if let SmtExpr::BinOp { op: SmtBinOp::Sub, lhs: bl, rhs: br } = lhs.as_ref() {
                        if let (SmtExpr::Var { name: n1, .. }, SmtExpr::Var { name: n2, .. }) =
                            (bl.as_ref(), br.as_ref())
                        {
                            if n1 == n2 {
                                return Some((PredicateValue::AlwaysTrue, 0.99));
                            }
                        }
                    }
                    // x ^ x == 0
                    if let SmtExpr::BinOp { op: SmtBinOp::Xor, lhs: bl, rhs: br } = lhs.as_ref() {
                        if let (SmtExpr::Var { name: n1, .. }, SmtExpr::Var { name: n2, .. }) =
                            (bl.as_ref(), br.as_ref())
                        {
                            if n1 == n2 {
                                return Some((PredicateValue::AlwaysTrue, 0.99));
                            }
                        }
                    }
                    // x & ~x == 0
                    if let SmtExpr::BinOp { op: SmtBinOp::And, lhs: bl, rhs: br } = lhs.as_ref() {
                        if let (
                            SmtExpr::Var { name: n1, .. },
                            SmtExpr::UnaryOp { op: SmtUnaryOp::Not, inner },
                        ) = (bl.as_ref(), br.as_ref())
                        {
                            if let SmtExpr::Var { name: n2, .. } = inner.as_ref() {
                                if n1 == n2 {
                                    return Some((PredicateValue::AlwaysTrue, 0.97));
                                }
                            }
                        }
                    }
                }

                // x | ~x == -1
                if matches!(rhs.as_ref(), SmtExpr::Const(-1)) {
                    if let SmtExpr::BinOp { op: SmtBinOp::Or, lhs: bl, rhs: br } = lhs.as_ref() {
                        if let (
                            SmtExpr::Var { name: n1, .. },
                            SmtExpr::UnaryOp { op: SmtUnaryOp::Not, inner },
                        ) = (bl.as_ref(), br.as_ref())
                        {
                            if let SmtExpr::Var { name: n2, .. } = inner.as_ref() {
                                if n1 == n2 {
                                    return Some((PredicateValue::AlwaysTrue, 0.97));
                                }
                            }
                        }
                    }
                }

                // ~~x == x (double NOT)
                if let SmtExpr::Var { name: n2, .. } = rhs.as_ref() {
                    if let SmtExpr::UnaryOp { op: SmtUnaryOp::Not, inner: outer_inner } = lhs.as_ref() {
                        if let SmtExpr::UnaryOp { op: SmtUnaryOp::Not, inner: inner_inner } =
                            outer_inner.as_ref()
                        {
                            if let SmtExpr::Var { name: n1, .. } = inner_inner.as_ref() {
                                if n1 == n2 {
                                    return Some((PredicateValue::AlwaysTrue, 0.98));
                                }
                            }
                        }
                    }
                }

                // (x & 1) | (~x & 1) == 1  — LSB tautology
                if matches!(rhs.as_ref(), SmtExpr::Const(1)) {
                    if let SmtExpr::BinOp { op: SmtBinOp::Or, lhs: bl, rhs: br } = lhs.as_ref() {
                        let lhs_is_and1 = matches!(bl.as_ref(),
                            SmtExpr::BinOp { op: SmtBinOp::And, rhs, .. }
                            if matches!(rhs.as_ref(), SmtExpr::Const(1))
                        );
                        let rhs_is_notand1 = if let SmtExpr::BinOp {
                            op: SmtBinOp::And, lhs: bl2, rhs: br2,
                        } = br.as_ref() {
                            matches!(bl2.as_ref(), SmtExpr::UnaryOp { op: SmtUnaryOp::Not, .. })
                                && matches!(br2.as_ref(), SmtExpr::Const(1))
                        } else {
                            false
                        };
                        if lhs_is_and1 && rhs_is_notand1 {
                            return Some((PredicateValue::AlwaysTrue, 0.92));
                        }
                    }
                }
            }
        }

        // x == x (trivial self-equality)
        if let SmtExpr::Cmp { op: SmtCmpOp::Eq, lhs, rhs } = expr {
            if lhs == rhs {
                return Some((PredicateValue::AlwaysTrue, 0.99));
            }
        }

        None
    }

    // ── Pattern database check ────────────────────────────────────────────────

    fn pattern_check(&self, expr: &SmtExpr) -> Option<(PredicateValue, f32)> {
        // Fermat's little theorem: BinOp(URem, ..., p) == 1  for small prime p
        if let SmtExpr::Cmp { op: SmtCmpOp::Eq, lhs, rhs } = expr {
            // NOTE: Fermat's little theorem (x^(p-1) ≡ 1 mod p) only holds when
            // gcd(x, p) == 1; when x is a multiple of p the result is 0, not 1.
            // Therefore "URem(..., p) == 1" is NOT a tautology for all x.
            // This pattern check has been intentionally removed to prevent false positives.

            // Wrapping add/sub identity: (x ± c) == x chain
            if let SmtExpr::Var { name: rhs_name, .. } = rhs.as_ref() {
                if is_identity_chain(lhs, rhs_name) {
                    return Some((PredicateValue::AlwaysTrue, 0.80));
                }
            }
        }

        None
    }

    // ── Sampled truth-table ───────────────────────────────────────────────────

    fn sampled_check(
        &self,
        expr: &SmtExpr,
        vars: &[(String, u8)],
        start: Instant,
    ) -> (PredicateValue, f32) {
        if vars.is_empty() {
            return (PredicateValue::Unknown, 0.0);
        }

        let mask = match self.sample_width {
            8  => 0xFFu64,
            16 => 0xFFFFu64,
            32 => 0xFFFF_FFFFu64,
            _  => 0xFFFF_FFFF_FFFF_FFFFu64,
        };

        let mut always_true_count = 0u32;
        let mut always_false_count = 0u32;
        let mut total = 0u32;

        // LCG random number generator for deterministic sampling
        let mut lcg_state = 0xDEAD_BEEF_u64;

        for _ in 0..self.sample_count {
            if start.elapsed() > self.timeout {
                break;
            }

            let mut env: HashMap<String, i64> = HashMap::new();
            for (name, _) in vars {
                lcg_state = lcg_state.wrapping_mul(6_364_136_223_846_793_005)
                    .wrapping_add(1_442_695_040_888_963_407);
                // Sign-extend so signed comparisons see negative values too.
                let raw = (lcg_state & mask) as i64;
                let width = self.sample_width.min(64);
                let val = if width >= 64 {
                    raw
                } else {
                    let shift = 64 - u32::from(width);
                    (raw << shift) >> shift
                };
                env.insert(name.clone(), val);
            }

            match expr.eval(&env) {
                Some(0) => always_false_count += 1,
                Some(_) => always_true_count += 1,
                None => {}
            }
            total += 1;
        }

        if total == 0 {
            return (PredicateValue::Unknown, 0.0);
        }

        let true_ratio = always_true_count as f32 / total as f32;
        let false_ratio = always_false_count as f32 / total as f32;

        if true_ratio >= 0.999 {
            let conf = 0.60 + (total as f32 / self.sample_count as f32) * 0.30;
            (PredicateValue::AlwaysTrue, conf.min(0.90))
        } else if false_ratio >= 0.999 {
            let conf = 0.60 + (total as f32 / self.sample_count as f32) * 0.30;
            (PredicateValue::AlwaysFalse, conf.min(0.90))
        } else {
            (PredicateValue::Unknown, 0.0)
        }
    }

    fn find_witness(&self, expr: &SmtExpr, vars: &[(String, u8)]) -> HashMap<String, i64> {
        // Try 0 and 1 for each variable
        let mut env: HashMap<String, i64> =
            vars.iter().map(|(n, _)| (n.clone(), 0)).collect();

        if expr.eval(&env).map_or(false, |v| v == 0) {
            return env;
        }

        for (name, _) in vars {
            env.insert(name.clone(), 1);
            if expr.eval(&env).map_or(false, |v| v == 0) {
                return env;
            }
        }

        env
    }

    // ── Convenience wrappers ──────────────────────────────────────────────────

    /// Check a predicate and return only the [`PredicateValue`].
    #[must_use]
    pub fn classify(&self, predicate: &SmtExpr) -> PredicateValue {
        self.check(predicate).0
    }

    /// Prove that `predicate` is a tautology (always true).
    #[must_use]
    pub fn is_tautology(&self, predicate: &SmtExpr) -> bool {
        matches!(self.check(predicate).0, PredicateValue::AlwaysTrue)
    }

    /// Prove that `predicate` is always false (contradiction).
    #[must_use]
    pub fn is_contradiction(&self, predicate: &SmtExpr) -> bool {
        matches!(self.check(predicate).0, PredicateValue::AlwaysFalse)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Private helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Check if `expr` is a sequence of Add/Sub constant operations applied to `var_name`
/// that cancel out (net zero), e.g. `(x + 5) - 5`.
fn is_identity_chain(expr: &SmtExpr, var_name: &str) -> bool {
    match expr {
        SmtExpr::Var { name, .. } => name == var_name,
        SmtExpr::BinOp { op: SmtBinOp::Add | SmtBinOp::Sub, lhs, rhs } => {
            if matches!(rhs.as_ref(), SmtExpr::Const(_)) {
                is_identity_chain(lhs, var_name)
            } else if matches!(lhs.as_ref(), SmtExpr::Const(_)) {
                is_identity_chain(rhs, var_name)
            } else {
                false
            }
        }
        _ => false,
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_x_minus_x_eq_zero_tautology() {
        let prover = SmtProver::new();
        // x - x == 0
        let x = SmtExpr::var("x", 32);
        let pred = SmtExpr::eq(SmtExpr::sub(x.clone(), x), SmtExpr::constant(0));
        assert!(prover.is_tautology(&pred));
    }

    #[test]
    fn test_x_xor_x_eq_zero_tautology() {
        let prover = SmtProver::new();
        let x = SmtExpr::var("x", 32);
        let pred = SmtExpr::eq(SmtExpr::xor(x.clone(), x), SmtExpr::constant(0));
        assert!(prover.is_tautology(&pred));
    }

    #[test]
    fn test_double_not_tautology() {
        let prover = SmtProver::new();
        // ~~x == x
        let x = SmtExpr::var("x", 32);
        let pred = SmtExpr::eq(SmtExpr::not(SmtExpr::not(x.clone())), x);
        assert!(prover.is_tautology(&pred));
    }

    #[test]
    fn test_constant_ground_true() {
        let prover = SmtProver::new();
        let pred = SmtExpr::Cmp {
            op: SmtCmpOp::Eq,
            lhs: Box::new(SmtExpr::constant(5)),
            rhs: Box::new(SmtExpr::constant(5)),
        };
        assert!(prover.is_tautology(&pred));
    }

    #[test]
    fn test_constant_ground_false() {
        let prover = SmtProver::new();
        let pred = SmtExpr::Cmp {
            op: SmtCmpOp::Eq,
            lhs: Box::new(SmtExpr::constant(3)),
            rhs: Box::new(SmtExpr::constant(7)),
        };
        assert!(prover.is_contradiction(&pred));
    }

    #[test]
    fn test_sampled_always_true() {
        let prover = SmtProver::new().with_sample_count(256);
        // x | (x ^ x) = x | 0 = x — not a tautology by itself
        // But x == x is:
        let x = SmtExpr::var("x", 32);
        let pred = SmtExpr::eq(x.clone(), x);
        let result = prover.classify(&pred);
        assert_eq!(result, PredicateValue::AlwaysTrue);
    }

    #[test]
    fn test_non_opaque_predicate() {
        let prover = SmtProver::new().with_sample_count(512);
        // x > 5 — not always true, not always false
        let x = SmtExpr::var("x", 32);
        let pred = SmtExpr::Cmp {
            op: SmtCmpOp::Sgt,
            lhs: Box::new(x),
            rhs: Box::new(SmtExpr::constant(5)),
        };
        let result = prover.classify(&pred);
        assert_eq!(result, PredicateValue::Unknown);
    }

    #[test]
    fn test_smt_result_sat_unsat() {
        let s = SmtResult::Sat { witness: HashMap::new() };
        let u = SmtResult::Unsat;
        assert!(s.is_sat());
        assert!(u.is_unsat());
        assert!(!s.is_unsat());
    }

    #[test]
    fn test_expr_eval_add() {
        let expr = SmtExpr::add(SmtExpr::var("x", 32), SmtExpr::constant(10));
        let mut env = HashMap::new();
        env.insert("x".to_string(), 5i64);
        assert_eq!(expr.eval(&env), Some(15));
    }

    #[test]
    fn test_free_vars() {
        let x = SmtExpr::var("x", 32);
        let y = SmtExpr::var("y", 32);
        let expr = SmtExpr::add(x, y);
        let vars = expr.free_vars();
        assert!(vars.iter().any(|(n, _)| n == "x"));
        assert!(vars.iter().any(|(n, _)| n == "y"));
    }
}
