//! `pattern_exporter` — Export/import patterns to external formats.
//!
//! Supports:
//! - Export to 010 Editor template (.bt)
//! - Export to Kaitai Struct (.ksy, YAML)
//! - Export to Wireshark Lua dissector
//! - Import from Kaitai Struct
//! - Import from Synalysis pattern

use std::fmt::Write as FmtWrite;

use serde::{Deserialize, Serialize};

// ─────────────────────────────────────────────────────────────────────────────
// ExportError
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
pub enum ExportError {
    #[error("unsupported type for {format}: {type_name}")]
    UnsupportedType { format: String, type_name: String },
    #[error("parse error: {0}")]
    Parse(String),
    #[error("I/O error: {0}")]
    Io(String),
    #[error("field '{field}': {reason}")]
    Field { field: String, reason: String },
}

// ─────────────────────────────────────────────────────────────────────────────
// Intermediate representation
// ─────────────────────────────────────────────────────────────────────────────

/// Endianness of a field.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum Endian {
    #[default]
    Little,
    Big,
}

impl Endian {
    const fn as_ksy(&self) -> &str {
        match self {
            Endian::Little => "le",
            Endian::Big => "be",
        }
    }
}

/// Primitive field types in the IR.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum IrType {
    U8,
    U16(Endian),
    U32(Endian),
    U64(Endian),
    I8,
    I16(Endian),
    I32(Endian),
    I64(Endian),
    F32(Endian),
    F64(Endian),
    Bytes(usize),
    CString,
    String { encoding: String },
    Struct(String),
    Array { elem_type: Box<IrType>, count: IrArrayCount },
    Union { tag_field: String, variants: Vec<IrUnionVariant> },
    Padding(usize),
}

/// How many elements are in an array.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum IrArrayCount {
    Fixed(usize),
    FieldRef(String),
    NullTerminated,
}

/// A variant in a union type.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IrUnionVariant {
    pub tag_value: String,
    pub type_name: String,
}

/// A single field in an IR struct.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IrField {
    pub name: String,
    pub ty: IrType,
    pub comment: String,
    pub condition: Option<String>,
}

/// An IR struct definition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IrStruct {
    pub name: String,
    pub fields: Vec<IrField>,
    pub comment: String,
    pub version: Option<u32>,
}

/// A full pattern/template in IR form.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct IrPattern {
    pub name: String,
    pub description: String,
    pub file_extensions: Vec<String>,
    pub structs: Vec<IrStruct>,
    pub root_struct: String,
    pub endian: Endian,
}

// ─────────────────────────────────────────────────────────────────────────────
// Export to 010 Editor .bt
// ─────────────────────────────────────────────────────────────────────────────

/// Export an `IrPattern` to a 010 Editor template string.
pub fn export_010_editor(pattern: &IrPattern) -> Result<String, ExportError> {
    let mut out = String::new();

    writeln!(out, "//------------------------------------------------").unwrap();
    writeln!(out, "// 010 Editor Binary Template").unwrap();
    writeln!(out, "// Name: {}", pattern.name).unwrap();
    writeln!(out, "// Description: {}", pattern.description).unwrap();
    writeln!(out, "// Generated by rustre-hex-pattern").unwrap();
    writeln!(out, "//------------------------------------------------").unwrap();
    writeln!(out).unwrap();

    // Set endianness
    match pattern.endian {
        Endian::Little => writeln!(out, "LittleEndian();").unwrap(),
        Endian::Big => writeln!(out, "BigEndian();").unwrap(),
    }
    writeln!(out).unwrap();

    for st in &pattern.structs {
        if !st.comment.is_empty() {
            writeln!(out, "// {}", st.comment).unwrap();
        }
        writeln!(out, "typedef struct {{").unwrap();
        for field in &st.fields {
            let type_str = ir_type_to_010(&field.ty)?;
            if let Some(cond) = &field.condition {
                writeln!(out, "    if ({cond}) {{").unwrap();
                if !field.comment.is_empty() {
                    writeln!(out, "        // {}", field.comment).unwrap();
                }
                writeln!(out, "        {type_str} {};", field.name).unwrap();
                writeln!(out, "    }}").unwrap();
            } else {
                if !field.comment.is_empty() {
                    writeln!(out, "    // {}", field.comment).unwrap();
                }
                writeln!(out, "    {type_str} {};", field.name).unwrap();
            }
        }
        writeln!(out, "}} {};", st.name).unwrap();
        writeln!(out).unwrap();
    }

    // Root instantiation
    writeln!(out, "{} {};", pattern.root_struct, pattern.root_struct.to_lowercase()).unwrap();

    Ok(out)
}

fn ir_type_to_010(ty: &IrType) -> Result<String, ExportError> {
    Ok(match ty {
        IrType::U8 => "uchar".to_string(),
        IrType::U16(_) => "uint16".to_string(),
        IrType::U32(_) => "uint32".to_string(),
        IrType::U64(_) => "uint64".to_string(),
        IrType::I8 => "char".to_string(),
        IrType::I16(_) => "int16".to_string(),
        IrType::I32(_) => "int32".to_string(),
        IrType::I64(_) => "int64".to_string(),
        IrType::F32(_) => "float".to_string(),
        IrType::F64(_) => "double".to_string(),
        IrType::Bytes(n) => format!("uchar[{n}]"),
        IrType::CString => "string".to_string(),
        IrType::String { .. } => "string".to_string(),
        IrType::Struct(name) => name.clone(),
        IrType::Array { elem_type, count } => {
            let elem = ir_type_to_010(elem_type)?;
            match count {
                IrArrayCount::Fixed(n) => format!("{elem}[{n}]"),
                IrArrayCount::FieldRef(f) => format!("{elem}[{f}]"),
                IrArrayCount::NullTerminated => format!("{elem}[]"),
            }
        }
        IrType::Union { .. } => "// union (unsupported in 010 directly)".to_string(),
        IrType::Padding(n) => format!("uchar padding[{n}]"),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Export to Kaitai Struct .ksy
// ─────────────────────────────────────────────────────────────────────────────

/// Export to Kaitai Struct YAML format.
pub fn export_kaitai(pattern: &IrPattern) -> Result<String, ExportError> {
    let mut out = String::new();

    writeln!(out, "meta:").unwrap();
    writeln!(out, "  id: {}", to_snake_case(&pattern.name)).unwrap();
    writeln!(out, "  title: \"{}\"", pattern.name).unwrap();
    if !pattern.file_extensions.is_empty() {
        writeln!(out, "  file-extension:").unwrap();
        for ext in &pattern.file_extensions {
            writeln!(out, "    - {ext}").unwrap();
        }
    }
    writeln!(out, "  endian: {}", pattern.endian.as_ksy()).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "seq:").unwrap();
    // Root struct fields
    if let Some(root) = pattern.structs.iter().find(|s| s.name == pattern.root_struct) {
        for field in &root.fields {
            write_ksy_field(&mut out, field, 2)?;
        }
    }

    if pattern.structs.len() > 1 {
        writeln!(out).unwrap();
        writeln!(out, "types:").unwrap();
        for st in &pattern.structs {
            if st.name == pattern.root_struct {
                continue;
            }
            writeln!(out, "  {}:", to_snake_case(&st.name)).unwrap();
            writeln!(out, "    seq:").unwrap();
            for field in &st.fields {
                write_ksy_field(&mut out, field, 6)?;
            }
        }
    }

    Ok(out)
}

fn write_ksy_field(out: &mut String, field: &IrField, indent: usize) -> Result<(), ExportError> {
    let pad = " ".repeat(indent);
    let name = to_snake_case(&field.name);
    writeln!(out, "{pad}- id: {name}").unwrap();
    let type_str = ir_type_to_ksy(&field.ty)?;
    writeln!(out, "{pad}  type: {type_str}").unwrap();
    if !field.comment.is_empty() {
        writeln!(out, "{pad}  doc: \"{}\"", field.comment).unwrap();
    }
    if let Some(cond) = &field.condition {
        writeln!(out, "{pad}  if: {cond}").unwrap();
    }
    Ok(())
}

fn ir_type_to_ksy(ty: &IrType) -> Result<String, ExportError> {
    Ok(match ty {
        IrType::U8 => "u1".to_string(),
        IrType::U16(e) => if *e == Endian::Little { "u2le".to_string() } else { "u2be".to_string() },
        IrType::U32(e) => if *e == Endian::Little { "u4le".to_string() } else { "u4be".to_string() },
        IrType::U64(e) => if *e == Endian::Little { "u8le".to_string() } else { "u8be".to_string() },
        IrType::I8 => "s1".to_string(),
        IrType::I16(e) => if *e == Endian::Little { "s2le".to_string() } else { "s2be".to_string() },
        IrType::I32(e) => if *e == Endian::Little { "s4le".to_string() } else { "s4be".to_string() },
        IrType::I64(e) => if *e == Endian::Little { "s8le".to_string() } else { "s8be".to_string() },
        IrType::F32(e) => if *e == Endian::Little { "f4le".to_string() } else { "f4be".to_string() },
        IrType::F64(e) => if *e == Endian::Little { "f8le".to_string() } else { "f8be".to_string() },
        IrType::Bytes(n) => format!("bytes[{n}]"),
        IrType::CString => "strz".to_string(),
        IrType::String { encoding } => format!("str (encoding: {encoding})"),
        IrType::Struct(name) => to_snake_case(name),
        IrType::Array { elem_type, count } => {
            let et = ir_type_to_ksy(elem_type)?;
            match count {
                IrArrayCount::Fixed(n) => format!("{et}[{n}]"),
                IrArrayCount::FieldRef(f) => format!("{et}[{f}]"),
                IrArrayCount::NullTerminated => et,
            }
        }
        IrType::Union { .. } => "bytes".to_string(),
        IrType::Padding(n) => format!("bytes[{n}]"),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Export to Wireshark Lua dissector
// ─────────────────────────────────────────────────────────────────────────────

/// Export to a Wireshark Lua dissector.
pub fn export_wireshark_lua(pattern: &IrPattern) -> Result<String, ExportError> {
    let mut out = String::new();
    let proto_name = to_snake_case(&pattern.name);
    let proto_desc = &pattern.description;

    writeln!(out, "-- Wireshark Lua dissector: {}", pattern.name).unwrap();
    writeln!(out, "-- Generated by rustre-hex-pattern").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "local {proto_name}_proto = Proto(\"{proto_name}\", \"{proto_desc}\")").unwrap();
    writeln!(out).unwrap();

    // ProtoField declarations
    writeln!(out, "local f = {{}}").unwrap();
    if let Some(root) = pattern.structs.iter().find(|s| s.name == pattern.root_struct) {
        for field in &root.fields {
            let lua_type = ir_type_to_lua_ftype(&field.ty);
            let field_id = format!("{proto_name}.{}", to_snake_case(&field.name));
            writeln!(
                out,
                "f.{} = ProtoField.{}(\"{field_id}\", \"{}\", base.HEX)",
                to_snake_case(&field.name),
                lua_type,
                field.name
            )
            .unwrap();
        }
    }
    writeln!(out).unwrap();
    writeln!(out, "{proto_name}_proto.fields = f").unwrap();
    writeln!(out).unwrap();

    // Dissector function
    writeln!(out, "function {proto_name}_proto.dissector(buffer, pinfo, tree)").unwrap();
    writeln!(out, "    pinfo.cols.protocol = \"{proto_name}\"").unwrap();
    writeln!(out, "    local subtree = tree:add({proto_name}_proto, buffer())").unwrap();
    writeln!(out, "    local offset = 0").unwrap();

    if let Some(root) = pattern.structs.iter().find(|s| s.name == pattern.root_struct) {
        for field in &root.fields {
            let size = ir_type_lua_size(&field.ty);
            let fn_name = to_snake_case(&field.name);
            writeln!(
                out,
                "    subtree:add(f.{fn_name}, buffer(offset, {size}))"
            )
            .unwrap();
            writeln!(out, "    offset = offset + {size}").unwrap();
        }
    }

    writeln!(out, "end").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "-- Register as heuristic dissector or to a port:").unwrap();
    writeln!(out, "-- DissectorTable.get(\"tcp.port\"):add(12345, {proto_name}_proto)").unwrap();

    Ok(out)
}

const fn ir_type_to_lua_ftype(ty: &IrType) -> &'static str {
    match ty {
        IrType::U8 | IrType::I8 => "uint8",
        IrType::U16(_) | IrType::I16(_) => "uint16",
        IrType::U32(_) | IrType::I32(_) => "uint32",
        IrType::U64(_) | IrType::I64(_) => "uint64",
        IrType::F32(_) => "float",
        IrType::F64(_) => "double",
        _ => "bytes",
    }
}

const fn ir_type_lua_size(ty: &IrType) -> usize {
    match ty {
        IrType::U8 | IrType::I8 => 1,
        IrType::U16(_) | IrType::I16(_) => 2,
        IrType::U32(_) | IrType::I32(_) | IrType::F32(_) => 4,
        IrType::U64(_) | IrType::I64(_) | IrType::F64(_) => 8,
        IrType::Bytes(n) | IrType::Padding(n) => *n,
        _ => 0,
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Import from Kaitai Struct (simplified YAML parser)
// ─────────────────────────────────────────────────────────────────────────────

/// Import an `IrPattern` from a simplified Kaitai Struct YAML.
/// This handles common cases; full YAML parsing would require a dependency.
pub fn import_kaitai(yaml: &str) -> Result<IrPattern, ExportError> {
    let mut pattern = IrPattern {
        endian: Endian::Little,
        ..Default::default()
    };
    let mut root_fields: Vec<IrField> = vec![];
    let mut in_seq = false;
    let mut in_meta = false;
    let mut current_field: Option<(String, IrType)> = None;

    for line in yaml.lines() {
        let trimmed = line.trim();

        // Section detection
        if trimmed == "meta:" {
            in_meta = true;
            in_seq = false;
            continue;
        }
        if trimmed == "seq:" {
            in_seq = true;
            in_meta = false;
            continue;
        }
        if trimmed == "types:" {
            in_seq = false;
            in_meta = false;
            continue;
        }

        if in_meta {
            if let Some(val) = strip_key(trimmed, "id:") {
                pattern.name = val.to_string();
            }
            if let Some(val) = strip_key(trimmed, "title:") {
                pattern.description = val.trim_matches('"').to_string();
            }
            if let Some(val) = strip_key(trimmed, "endian:") {
                pattern.endian = if val == "le" { Endian::Little } else { Endian::Big };
            }
        }

        if in_seq {
            if trimmed.starts_with("- id:") {
                // Flush previous field
                if let Some((name, ty)) = current_field.take() {
                    root_fields.push(IrField {
                        name,
                        ty,
                        comment: String::new(),
                        condition: None,
                    });
                }
                let name = trimmed["- id:".len()..].trim().to_string();
                current_field = Some((name, IrType::Bytes(1)));
            } else if let Some(ref mut f) = current_field {
                if let Some(val) = strip_key(trimmed, "type:") {
                    f.1 = ksy_type_to_ir(val, pattern.endian);
                }
            }
        }
    }

    if let Some((name, ty)) = current_field {
        root_fields.push(IrField {
            name,
            ty,
            comment: String::new(),
            condition: None,
        });
    }

    let root_name = if pattern.name.is_empty() {
        "Root".to_string()
    } else {
        to_pascal_case(&pattern.name)
    };

    pattern.root_struct = root_name.clone();
    pattern.structs.push(IrStruct {
        name: root_name,
        fields: root_fields,
        comment: String::new(),
        version: None,
    });

    Ok(pattern)
}

fn ksy_type_to_ir(s: &str, endian: Endian) -> IrType {
    match s {
        "u1" => IrType::U8,
        "u2le" => IrType::U16(Endian::Little),
        "u2be" => IrType::U16(Endian::Big),
        "u2" => IrType::U16(endian),
        "u4le" => IrType::U32(Endian::Little),
        "u4be" => IrType::U32(Endian::Big),
        "u4" => IrType::U32(endian),
        "u8le" => IrType::U64(Endian::Little),
        "u8be" => IrType::U64(Endian::Big),
        "u8" => IrType::U64(endian),
        "s1" => IrType::I8,
        "s2le" => IrType::I16(Endian::Little),
        "s2be" => IrType::I16(Endian::Big),
        "s2" => IrType::I16(endian),
        "s4le" => IrType::I32(Endian::Little),
        "s4be" => IrType::I32(Endian::Big),
        "s4" => IrType::I32(endian),
        "s8le" => IrType::I64(Endian::Little),
        "s8be" => IrType::I64(Endian::Big),
        "s8" => IrType::I64(endian),
        "f4le" => IrType::F32(Endian::Little),
        "f4be" => IrType::F32(Endian::Big),
        "f4" => IrType::F32(endian),
        "f8le" => IrType::F64(Endian::Little),
        "f8be" => IrType::F64(Endian::Big),
        "f8" => IrType::F64(endian),
        "strz" => IrType::CString,
        _ => IrType::Struct(to_pascal_case(s)),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Import from Synalysis pattern (simplified)
// ─────────────────────────────────────────────────────────────────────────────

/// Import from Synalysis grammar format (simplified XML-like parser).
pub fn import_synalysis(xml: &str) -> Result<IrPattern, ExportError> {
    let mut pattern = IrPattern {
        endian: Endian::Little,
        name: "SynalysisPattern".to_string(),
        ..Default::default()
    };
    let mut fields: Vec<IrField> = vec![];

    // Very simplified parser — extracts <field name="..." type="..." />
    for line in xml.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("<grammar") {
            if let Some(id_start) = trimmed.find("id=\"") {
                let rest = &trimmed[id_start + 4..];
                if let Some(id_end) = rest.find('"') {
                    pattern.name = rest[..id_end].to_string();
                }
            }
        }
        if trimmed.starts_with("<field") || trimmed.starts_with("<structure") {
            let name = extract_xml_attr(trimmed, "name").unwrap_or("field".to_string());
            let type_str = extract_xml_attr(trimmed, "type").unwrap_or("u1".to_string());
            let ty = synalysis_type_to_ir(&type_str, pattern.endian);
            let comment = extract_xml_attr(trimmed, "comment").unwrap_or_default();
            fields.push(IrField {
                name,
                ty,
                comment,
                condition: None,
            });
        }
    }

    let root_name = to_pascal_case(&pattern.name);
    pattern.root_struct = root_name.clone();
    pattern.structs.push(IrStruct {
        name: root_name,
        fields,
        comment: String::new(),
        version: None,
    });

    Ok(pattern)
}

fn synalysis_type_to_ir(s: &str, endian: Endian) -> IrType {
    match s {
        "uint8" | "byte" => IrType::U8,
        "uint16" => IrType::U16(endian),
        "uint32" => IrType::U32(endian),
        "uint64" => IrType::U64(endian),
        "int8" => IrType::I8,
        "int16" => IrType::I16(endian),
        "int32" => IrType::I32(endian),
        "int64" => IrType::I64(endian),
        "float" => IrType::F32(endian),
        "double" => IrType::F64(endian),
        "string" => IrType::CString,
        _ => IrType::Struct(to_pascal_case(s)),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// String helpers
// ─────────────────────────────────────────────────────────────────────────────

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_lowercase().next().unwrap());
    }
    out
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn strip_key<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    if line.starts_with(key) {
        Some(line[key.len()..].trim())
    } else {
        None
    }
}

fn extract_xml_attr(xml: &str, attr: &str) -> Option<String> {
    let search = format!("{attr}=\"");
    let start = xml.find(&search)? + search.len();
    let rest = &xml[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn simple_pattern() -> IrPattern {
        IrPattern {
            name: "TestFormat".to_string(),
            description: "A test format".to_string(),
            file_extensions: vec!["tst".to_string()],
            root_struct: "Header".to_string(),
            endian: Endian::Little,
            structs: vec![IrStruct {
                name: "Header".to_string(),
                comment: "File header".to_string(),
                fields: vec![
                    IrField {
                        name: "magic".to_string(),
                        ty: IrType::U32(Endian::Little),
                        comment: "Magic number".to_string(),
                        condition: None,
                    },
                    IrField {
                        name: "size".to_string(),
                        ty: IrType::U32(Endian::Little),
                        comment: "File size".to_string(),
                        condition: None,
                    },
                ],
                version: None,
            }],
        }
    }

    #[test]
    fn export_010_contains_magic() {
        let p = simple_pattern();
        let bt = export_010_editor(&p).unwrap();
        assert!(bt.contains("010 Editor"), "missing header");
        assert!(bt.contains("uint32 magic"));
        assert!(bt.contains("LittleEndian()"));
    }

    #[test]
    fn export_kaitai_structure() {
        let p = simple_pattern();
        let ksy = export_kaitai(&p).unwrap();
        assert!(ksy.contains("id: test_format"));
        assert!(ksy.contains("endian: le"));
        assert!(ksy.contains("id: magic"));
        assert!(ksy.contains("type: u4le"));
    }

    #[test]
    fn test_export_wireshark_lua() {
        let p = simple_pattern();
        let lua = export_wireshark_lua(&p).unwrap();
        assert!(lua.contains("Proto(\"test_format\""));
        assert!(lua.contains("ProtoField.uint32"));
    }

    #[test]
    fn import_kaitai_roundtrip() {
        let yaml = r#"meta:
  id: my_format
  title: "My Format"
  endian: le
seq:
  - id: magic
    type: u4le
  - id: version
    type: u2le
"#;
        let p = import_kaitai(yaml).unwrap();
        assert_eq!(p.name, "my_format");
        let root = &p.structs[0];
        assert_eq!(root.fields.len(), 2);
        assert_eq!(root.fields[0].name, "magic");
    }

    #[test]
    fn import_synalysis_basic() {
        let xml = r#"<grammar id="simple_format">
  <field name="magic" type="uint32" comment="Magic bytes" />
  <field name="size" type="uint32" />
</grammar>"#;
        let p = import_synalysis(xml).unwrap();
        assert_eq!(p.name, "simple_format");
        assert_eq!(p.structs[0].fields.len(), 2);
    }

    #[test]
    fn snake_case_conversion() {
        assert_eq!(to_snake_case("MyStruct"), "my_struct");
        assert_eq!(to_snake_case("PEHeader"), "p_e_header");
    }
}
