__int64 sub_1400F1D90();
__int64 sub_1400F27F0();
__int64 sub_1400F2808();
__int64 sub_1400A11B0();
__int64 sub_1400F3869();
extern __int64 off_140119F58;
extern __int64 off_1401085B0;
extern __int64 off_1401088B0;
extern __int64 off_1401088C0;
extern __int64 off_14011A370;
extern __int64 off_14011A358;

__int64 __fastcall sub_1400A01D0(size_t a1, int a2, int a3) {
    __int64 rsp;
    int v_28;
    int v_30;
    int v_3070;
    int v_3080;
    int v_3090;
    int v_40;
    int v_48;
    __int64 v_50;
    int v_58;
    __int64 v_68;
    int *v_0;
    int *v_1070;
    int *v_1470;
    int *v_1860;
    int *v_1870;
    int *v_1c6c;
    int *v_1c70;
    int *v_34;
    int *v_38;
    int *v_434;
    int *v_438;
    int *v_46c;
    int *v_470;
    int *v_60;
    int *v_70;
    int *v_834;
    int *v_838;
    int *v_870;
    int *v_c70;
    __int64 result;
    __int64 v5;
    __int64 *src;
    __int64 v2;
    __int64 v6;
    __int64 v7;
    __int64 v4;
    __int64 *src2;
    __int64 *i;
    __int64 i2;
    __int64 i3;
    __int64 i4;
    __m128i xmm6;
    __m128i xmm7;
    __m128i xmm8;
    __m128i xmm0;
    __m128i xmm1;
    __m128i xmm2;
    __m128i xmm3;

    sub_1400F1D90(0x30A8);
    _mm_store_si128((__m128i *)&v_3090, xmm8);
    _mm_store_si128((__m128i *)&v_3080, xmm7);
    _mm_store_si128((__m128i *)&v_3070, xmm6);
    result = a3;
    v_48 = a2;
    v_28 = a1;
    a1 = rsp + 0x870;
    sub_1400F27F0(a1, result, 0x1000);
    v5 = 128;
    a1 = 1;
    src = &off_140119F58;
    v2 = 0x200801C060148461;
    do {
        v6 = v5 + v5;
        v7 = rsp + v5*4;
        v7 += 0x870;
        v4 = 0;
        while (a1 <= 255) {
            src2 = *(src + a1*4);
            ++a1;
            i = v4 + v5;
            i2 = v4;
            result = v5 + i2;
            while (result <= 255) {
                a3 = v_0[i2];
                a3 *= (__int64)src2;
                result = a3;
                result *= v2; /* unsigned; high half in a2 */;
                a2 >>= 20;
                result = a2 * 0x7FE001;
                a3 -= result;
                result = v_870[i2];
                a2 = result + a3;
                i3 = result;
                i3 -= a3;
                i4 = i3 + 0x7FE001;
                if (i4 < 0x7FE001) i3 = i4;
                result += a3;
                result += 0xFF801FFF;
                if (a2 < 0x7FE001) result = a2;
                v_0[i2] = i3;
                v_870[i2] = result;
                ++i2;
                v4 += v6;
                result = v5;
                result >>= 1;
                /* cmp v5 , 2 */;
                v5 = result;
                v5 = 128;
                a1 = 1;
                do {
                    v6 = v5 + v5;
                    v7 = rsp + v5*4;
                    v7 += 0xC70;
                    v4 = 0;
                    while (a1 <= 255) {
                        src2 = *(src + a1*4);
                        ++a1;
                        i = v4 + v5;
                        i2 = v4;
                        result = v5 + i2;
                        while (result <= 255) {
                            a3 = v_0[i2];
                            a3 *= (__int64)src2;
                            result = a3;
                            result *= v2; /* unsigned; high half in a2 */;
                            a2 >>= 20;
                            result = a2 * 0x7FE001;
                            a3 -= result;
                            result = v_c70[i2];
                            a2 = result + a3;
                            i3 = result;
                            i3 -= a3;
                            i4 = i3 + 0x7FE001;
                            if (i4 < 0x7FE001) i3 = i4;
                            result += a3;
                            result += 0xFF801FFF;
                            if (a2 < 0x7FE001) result = a2;
                            v_0[i2] = i3;
                            v_c70[i2] = result;
                            ++i2;
                            v4 += v6;
                            result = v5;
                            result >>= 1;
                            /* cmp v5 , 1 */;
                            v5 = result;
                            v5 = 128;
                            a1 = 1;
                            do {
                                v6 = v5 + v5;
                                v7 = rsp + v5*4;
                                v7 += 0x1070;
                                v4 = 0;
                                while (a1 <= 255) {
                                    src2 = *(src + a1*4);
                                    ++a1;
                                    i = v4 + v5;
                                    i2 = v4;
                                    result = v5 + i2;
                                    while (result <= 255) {
                                        a3 = v_0[i2];
                                        a3 *= (__int64)src2;
                                        result = a3;
                                        result *= v2; /* unsigned; high half in a2 */;
                                        a2 >>= 20;
                                        result = a2 * 0x7FE001;
                                        a3 -= result;
                                        result = v_1070[i2];
                                        a2 = result + a3;
                                        i3 = result;
                                        i3 -= a3;
                                        i4 = i3 + 0x7FE001;
                                        if (i4 < 0x7FE001) i3 = i4;
                                        result += a3;
                                        result += 0xFF801FFF;
                                        if (a2 < 0x7FE001) result = a2;
                                        v_0[i2] = i3;
                                        v_1070[i2] = result;
                                        ++i2;
                                        v4 += v6;
                                        result = v5;
                                        result >>= 1;
                                        /* cmp v5 , 1 */;
                                        v5 = result;
                                        v5 = 128;
                                        a1 = 1;
                                        do {
                                            v6 = v5 + v5;
                                            v7 = rsp + v5*4;
                                            v7 += 0x1470;
                                            v4 = 0;
                                            while (a1 <= 255) {
                                                src2 = *(src + a1*4);
                                                ++a1;
                                                i = v4 + v5;
                                                i2 = v4;
                                                result = v5 + i2;
                                                while (result <= 255) {
                                                    a3 = v_0[i2];
                                                    a3 *= (__int64)src2;
                                                    result = a3;
                                                    result *= v2; /* unsigned; high half in a2 */;
                                                    a2 >>= 20;
                                                    result = a2 * 0x7FE001;
                                                    a3 -= result;
                                                    result = v_1470[i2];
                                                    a2 = result + a3;
                                                    i3 = result;
                                                    i3 -= a3;
                                                    i4 = i3 + 0x7FE001;
                                                    if (i4 < 0x7FE001) i3 = i4;
                                                    result += a3;
                                                    result += 0xFF801FFF;
                                                    if (a2 < 0x7FE001) result = a2;
                                                    v_0[i2] = i3;
                                                    v_1470[i2] = result;
                                                    ++i2;
                                                    v4 += v6;
                                                    result = v5;
                                                    result >>= 1;
                                                    /* cmp v5 , 1 */;
                                                    a1 = rsp + 0x2070;
                                                    sub_1400F2808(a1, 0, 0x1000, result);
                                                    v4 = rsp + 112;
                                                    xmm6 = _mm_load_si128((__m128i *)&off_1401085B0);
                                                    xmm7 = _mm_load_si128((__m128i *)&off_1401088B0);
                                                    xmm8 = _mm_load_si128((__m128i *)&off_1401088C0);
                                                    result = 0;
                                                    a1 = 0;
                                                    do {
                                                        src2 = (__int64 *)a1;
                                                        a1 = rsp + result;
                                                        a1 += 0x2070;
                                                        v_30 = a1;
                                                        result += 0x400;
                                                        v_40 = result;
                                                        result = src2 + 1;
                                                        v_38 = (int *)result;
                                                        sub_1400F2808(v4, 0, 0x400);
                                                        src2 = (__int64 *)((__int64)(__int64)src2 << 12);
                                                        src2 += v_48;
                                                        v_50 = (__int64)src2;
                                                        src2 = rsp + 0x870;
                                                        a2 = 0;
                                                        result = 0;
                                                        do {
                                                            v_68 = (__int64)src2;
                                                            result += 0x400;
                                                            v_60 = (int *)result;
                                                            result = a2 + 1;
                                                            v_58 = result;
                                                            a2 <<= 10;
                                                            a2 += v_50;
                                                            a1 = rsp + 0x470;
                                                            sub_1400F27F0(a1, a2, 0x400);
                                                            v5 = 128;
                                                            a1 = 1;
                                                            do {
                                                                v6 = v5 + v5;
                                                                v7 = rsp + v5*4;
                                                                v7 += 0x470;
                                                                i3 = 0;
                                                                while (a1 <= 255) {
                                                                    i2 = *(src + a1*4);
                                                                    ++a1;
                                                                    src2 = v5 + i3;
                                                                    i = (__int64 *)i3;
                                                                    result = v5 + i;
                                                                    while (result <= 255) {
                                                                        a3 = v_0[(__int64)i];
                                                                        a3 *= i2;
                                                                        result = a3;
                                                                        result *= v2; /* unsigned; high half in a2 */;
                                                                        a2 >>= 20;
                                                                        result = a2 * 0x7FE001;
                                                                        a3 -= result;
                                                                        v4 = v_470[(__int64)i];
                                                                        a2 = v4 + a3;
                                                                        result = v4;
                                                                        result -= a3;
                                                                        i4 = result + 0x7FE001;
                                                                        if (i4 < 0x7FE001) result = i4;
                                                                        a3 += v4;
                                                                        a3 += 0xFF801FFF;
                                                                        if (a2 < 0x7FE001) a3 = a2;
                                                                        v_0[(__int64)i] = result;
                                                                        v_470[(__int64)i] = a3;
                                                                        ++i;
                                                                        i3 += v6;
                                                                        result = v5;
                                                                        result >>= 1;
                                                                        /* cmp v5 , 1 */;
                                                                        v4 = rsp + 0x1C70;
                                                                        sub_1400F2808(v4, 0, 0x400, result);
                                                                        v5 = 1;
                                                                        src2 = (__int64 *)v_68;
                                                                        do {
                                                                            result = v_46c[v5];
                                                                            v6 = v_470[v5];
                                                                            a1 = *(src2 + v5*4 - 4);
                                                                            a1 *= result;
                                                                            result = a1;
                                                                            result *= v2; /* unsigned; high half in a2 */;
                                                                            a2 >>= 20;
                                                                            result = a2 * 0x7FE001;
                                                                            a1 -= result;
                                                                            a3 = v_0[v5];
                                                                            a3 *= v6;
                                                                            result = a3;
                                                                            result *= v2; /* unsigned; high half in a2 */;
                                                                            v_1c6c[v5] = a1;
                                                                            a2 >>= 20;
                                                                            result = a2 * 0x7FE001;
                                                                            a3 -= result;
                                                                            v_1c70[v5] = a3;
                                                                            v5 += 2;
                                                                        } while (v5 != 257);
                                                                        a1 = rsp + 0x1870;
                                                                        sub_1400F27F0(a1, v4, 0x400, v5);
                                                                        result = 4;
                                                                        do {
                                                                            xmm0 = _mm_loadu_si128((__m128i *)&v_60[result]);
                                                                            xmm1 = _mm_loadu_si128((__m128i *)&v_70[result]);
                                                                            xmm2 = _mm_loadu_si128((__m128i *)&v_1860[result]);
                                                                            xmm2 = _mm_add_epi32(xmm2, xmm0);
                                                                            xmm0 = _mm_loadu_si128((__m128i *)&v_1870[result]);
                                                                            xmm0 = _mm_add_epi32(xmm0, xmm1);
                                                                            xmm1 = xmm2;
                                                                            xmm1 = _mm_xor_si128(xmm1, xmm6);
                                                                            xmm1 = _mm_cmpgt_epi32(xmm1, xmm7);
                                                                            xmm3 = xmm0;
                                                                            xmm3 = _mm_xor_si128(xmm3, xmm6);
                                                                            xmm3 = _mm_cmpgt_epi32(xmm3, xmm7);
                                                                            xmm1 = _mm_and_si128(xmm1, xmm8);
                                                                            xmm1 = _mm_add_epi32(xmm1, xmm2);
                                                                            xmm3 = _mm_and_si128(xmm3, xmm8);
                                                                            xmm3 = _mm_add_epi32(xmm3, xmm0);
                                                                            _mm_storeu_si128((__m128i *)&v_60[result], xmm1);
                                                                            _mm_storeu_si128((__m128i *)&v_70[result], xmm3);
                                                                            result += 8;
                                                                        } while (result != 260);
                                                                        src2 += 0x400;
                                                                        result = (__int64)v_60;
                                                                        a2 = v_58;
                                                                        v4 = rsp + 112;
                                                                        sub_1400A11B0(v4, a2);
                                                                        a1 = v_30;
                                                                        sub_1400F27F0(a1, v4, 0x400);
                                                                        result = v_40;
                                                                        a1 = (size_t)v_38;
                                                                        a2 = rsp + 0x2070;
                                                                        a1 = v_28;
                                                                        sub_1400F27F0(a1, a2, 0x1000);
                                                                        xmm6 = _mm_load_si128((__m128i *)&v_3070);
                                                                        xmm7 = _mm_load_si128((__m128i *)&v_3080);
                                                                        xmm8 = _mm_load_si128((__m128i *)&v_3090);
                                                                        return _mm_cvtsi128_si64(xmm8);
                                                                    }
                                                                    a3 = &off_14011A370;
                                                                    sub_1400F3869(result, 256, a3);
                                                                }
                                                                a3 = &off_14011A358;
                                                                sub_1400F3869(a1, 256, a3);
                                                                sub_1400F1D90(0x1038);
                                                                v_30 = a3;
                                                                v_28 = a1;
                                                                a1 = rsp + 0x838;
                                                                sub_1400F27F0(a1, a2, 0x400);
                                                                v5 = 128;
                                                                a1 = 1;
                                                                i = &off_140119F58;
                                                                src2 = 0x200801C060148461;
                                                                do {
                                                                    v6 = v5 + v5;
                                                                    v7 = rsp + v5*4;
                                                                    v7 += 0x838;
                                                                    v2 = 0;
                                                                    do {
                                                                        if (a1 > 255) JUMPOUT(0x1400a119d);
                                                                        i2 = *(i + a1*4);
                                                                        ++a1;
                                                                        i3 = v2 + v5;
                                                                        i4 = v2;
                                                                        do {
                                                                            result = v5 + i4;
                                                                            if (result > 255) JUMPOUT(0x1400a1189);
                                                                            a3 = v_0[i4];
                                                                            a3 *= i2;
                                                                            result = a3;
                                                                            result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                            a2 >>= 20;
                                                                            result = a2 * 0x7FE001;
                                                                            a3 -= result;
                                                                            src = v_838[i4];
                                                                            a2 = src + a3;
                                                                            result = (__int64)src;
                                                                            result -= a3;
                                                                            v4 = result + 0x7FE001;
                                                                            if (v4 < 0x7FE001) result = v4;
                                                                            a3 += (__int64)src;
                                                                            a3 += 0xFF801FFF;
                                                                            if (a2 < 0x7FE001) a3 = a2;
                                                                            v_0[i4] = result;
                                                                            v_838[i4] = a3;
                                                                            ++i4;
                                                                        } while (i4 < i3);
                                                                        v2 += v6;
                                                                    } while (v2 < 256);
                                                                    result = v5;
                                                                    result >>= 1;
                                                                } while ((v5 >= 2));
                                                                a1 = v_28;
                                                                sub_1400F2808(a1, 0, 0x1000, result);
                                                                a1 = rsp + 56;
                                                                a2 = v_30;
                                                                sub_1400F27F0(a1, a2, 0x400);
                                                                v5 = 128;
                                                                a1 = 1;
                                                                do {
                                                                    v6 = v5 + v5;
                                                                    v7 = rsp + v5*4;
                                                                    v7 += 56;
                                                                    v2 = 0;
                                                                    do {
                                                                        if (a1 > 255) JUMPOUT(0x1400a119d);
                                                                        i2 = *(i + a1*4);
                                                                        ++a1;
                                                                        i3 = v2 + v5;
                                                                        i4 = v2;
                                                                        do {
                                                                            result = v5 + i4;
                                                                            if (result > 255) JUMPOUT(0x1400a1189);
                                                                            a3 = v_0[i4];
                                                                            a3 *= i2;
                                                                            result = a3;
                                                                            result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                            a2 >>= 20;
                                                                            result = a2 * 0x7FE001;
                                                                            a3 -= result;
                                                                            result = v_38[i4];
                                                                            a2 = result + a3;
                                                                            src = (__int64 *)result;
                                                                            src -= a3;
                                                                            v4 = src + 0x7FE001;
                                                                            if (v4 < 0x7FE001) src = v4;
                                                                            result += a3;
                                                                            result += 0xFF801FFF;
                                                                            if (a2 < 0x7FE001) result = a2;
                                                                            v_0[i4] = src;
                                                                            v_38[i4] = result;
                                                                            ++i4;
                                                                        } while (i4 < i3);
                                                                        v2 += v6;
                                                                    } while (v2 < 256);
                                                                    result = v5;
                                                                    result >>= 1;
                                                                } while ((v5 >= 2));
                                                                a1 = rsp + 0x438;
                                                                sub_1400F2808(a1, 0, 0x400, result);
                                                                v5 = 1;
                                                                do {
                                                                    result = v_834[v5];
                                                                    v6 = v_838[v5];
                                                                    a3 = v_34[v5];
                                                                    a1 = v_38[v5];
                                                                    a3 *= result;
                                                                    result = a3;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a3 -= result;
                                                                    a1 *= v6;
                                                                    result = a1;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    v_434[v5] = a3;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a1 -= result;
                                                                    v_438[v5] = a1;
                                                                    v5 += 2;
                                                                } while (v5 != 257);
                                                                v2 = rsp + 0xC38;
                                                                a2 = rsp + 0x438;
                                                                sub_1400F27F0(v2, a2, 0x400, v5);
                                                                sub_1400A11B0(v2);
                                                                a1 = v_28;
                                                                sub_1400F27F0(a1, v2, 0x400);
                                                                result = v_30;
                                                                a2 = result + 0x400;
                                                                a1 = rsp + 56;
                                                                sub_1400F27F0(a1, a2, 0x400);
                                                                v5 = 128;
                                                                a1 = 1;
                                                                do {
                                                                    v6 = v5 + v5;
                                                                    v7 = rsp + v5*4;
                                                                    v7 += 56;
                                                                    v2 = 0;
                                                                    do {
                                                                        if (a1 > 255) JUMPOUT(0x1400a119d);
                                                                        i2 = *(i + a1*4);
                                                                        ++a1;
                                                                        i3 = v2 + v5;
                                                                        i4 = v2;
                                                                        do {
                                                                            result = v5 + i4;
                                                                            if (result > 255) JUMPOUT(0x1400a1189);
                                                                            a3 = v_0[i4];
                                                                            a3 *= i2;
                                                                            result = a3;
                                                                            result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                            a2 >>= 20;
                                                                            result = a2 * 0x7FE001;
                                                                            a3 -= result;
                                                                            result = v_38[i4];
                                                                            a2 = result + a3;
                                                                            src = (__int64 *)result;
                                                                            src -= a3;
                                                                            v4 = src + 0x7FE001;
                                                                            if (v4 < 0x7FE001) src = v4;
                                                                            result += a3;
                                                                            result += 0xFF801FFF;
                                                                            if (a2 < 0x7FE001) result = a2;
                                                                            v_0[i4] = src;
                                                                            v_38[i4] = result;
                                                                            ++i4;
                                                                        } while (i4 < i3);
                                                                        v2 += v6;
                                                                    } while (v2 < 256);
                                                                    result = v5;
                                                                    result >>= 1;
                                                                } while ((v5 > 1));
                                                                a1 = rsp + 0x438;
                                                                sub_1400F2808(a1, 0, 0x400, result);
                                                                v5 = 1;
                                                                do {
                                                                    result = v_834[v5];
                                                                    v6 = v_838[v5];
                                                                    a3 = v_34[v5];
                                                                    a1 = v_38[v5];
                                                                    a3 *= result;
                                                                    result = a3;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a3 -= result;
                                                                    a1 *= v6;
                                                                    result = a1;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    v_434[v5] = a3;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a1 -= result;
                                                                    v_438[v5] = a1;
                                                                    v5 += 2;
                                                                } while (v5 != 257);
                                                                v2 = rsp + 0xC38;
                                                                a2 = rsp + 0x438;
                                                                sub_1400F27F0(v2, a2, 0x400, v5);
                                                                sub_1400A11B0(v2);
                                                                result = v_28;
                                                                a1 = result + 0x400;
                                                                sub_1400F27F0(a1, v2, 0x400);
                                                                result = v_30;
                                                                a2 = result + 0x800;
                                                                a1 = rsp + 56;
                                                                sub_1400F27F0(a1, a2, 0x400);
                                                                v5 = 128;
                                                                a1 = 1;
                                                                do {
                                                                    v6 = v5 + v5;
                                                                    v7 = rsp + v5*4;
                                                                    v7 += 56;
                                                                    v2 = 0;
                                                                    do {
                                                                        if (a1 > 255) JUMPOUT(0x1400a119d);
                                                                        i2 = *(i + a1*4);
                                                                        ++a1;
                                                                        i3 = v2 + v5;
                                                                        i4 = v2;
                                                                        do {
                                                                            result = v5 + i4;
                                                                            if (result > 255) JUMPOUT(0x1400a1189);
                                                                            a3 = v_0[i4];
                                                                            a3 *= i2;
                                                                            result = a3;
                                                                            result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                            a2 >>= 20;
                                                                            result = a2 * 0x7FE001;
                                                                            a3 -= result;
                                                                            result = v_38[i4];
                                                                            a2 = result + a3;
                                                                            src = (__int64 *)result;
                                                                            src -= a3;
                                                                            v4 = src + 0x7FE001;
                                                                            if (v4 < 0x7FE001) src = v4;
                                                                            result += a3;
                                                                            result += 0xFF801FFF;
                                                                            if (a2 < 0x7FE001) result = a2;
                                                                            v_0[i4] = src;
                                                                            v_38[i4] = result;
                                                                            ++i4;
                                                                        } while (i4 < i3);
                                                                        v2 += v6;
                                                                    } while (v2 < 256);
                                                                    result = v5;
                                                                    result >>= 1;
                                                                } while ((v5 > 1));
                                                                a1 = rsp + 0x438;
                                                                sub_1400F2808(a1, 0, 0x400, result);
                                                                v5 = 1;
                                                                do {
                                                                    result = v_834[v5];
                                                                    v6 = v_838[v5];
                                                                    a3 = v_34[v5];
                                                                    a1 = v_38[v5];
                                                                    a3 *= result;
                                                                    result = a3;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a3 -= result;
                                                                    a1 *= v6;
                                                                    result = a1;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    v_434[v5] = a3;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a1 -= result;
                                                                    v_438[v5] = a1;
                                                                    v5 += 2;
                                                                } while (v5 != 257);
                                                                v2 = rsp + 0xC38;
                                                                a2 = rsp + 0x438;
                                                                sub_1400F27F0(v2, a2, 0x400, v5);
                                                                sub_1400A11B0(v2);
                                                                result = v_28;
                                                                a1 = result + 0x800;
                                                                sub_1400F27F0(a1, v2, 0x400);
                                                                a2 = v_30;
                                                                a2 += 0xC00;
                                                                a1 = rsp + 56;
                                                                sub_1400F27F0(a1, a2, 0x400);
                                                                v5 = 128;
                                                                a1 = 1;
                                                                do {
                                                                    v6 = v5 + v5;
                                                                    v7 = rsp + v5*4;
                                                                    v7 += 56;
                                                                    v4 = 0;
                                                                    do {
                                                                        if (a1 > 255) JUMPOUT(0x1400a119d);
                                                                        v2 = *(i + a1*4);
                                                                        ++a1;
                                                                        i2 = v4 + v5;
                                                                        i3 = v4;
                                                                        do {
                                                                            result = v5 + i3;
                                                                            if (result > 255) JUMPOUT(0x1400a1189);
                                                                            a3 = v_0[i3];
                                                                            a3 *= v2;
                                                                            result = a3;
                                                                            result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                            a2 >>= 20;
                                                                            result = a2 * 0x7FE001;
                                                                            a3 -= result;
                                                                            result = v_38[i3];
                                                                            a2 = result + a3;
                                                                            src = (__int64 *)result;
                                                                            src -= a3;
                                                                            i4 = src + 0x7FE001;
                                                                            if (i4 < 0x7FE001) src = i4;
                                                                            result += a3;
                                                                            result += 0xFF801FFF;
                                                                            if (a2 < 0x7FE001) result = a2;
                                                                            v_0[i3] = src;
                                                                            v_38[i3] = result;
                                                                            ++i3;
                                                                        } while (i3 < i2);
                                                                        v4 += v6;
                                                                    } while (v4 < 256);
                                                                    result = v5;
                                                                    result >>= 1;
                                                                } while ((v5 > 1));
                                                                a1 = rsp + 0x438;
                                                                sub_1400F2808(a1, 0, 0x400, result);
                                                                v5 = 1;
                                                                do {
                                                                    result = v_834[v5];
                                                                    v6 = v_838[v5];
                                                                    a3 = v_34[v5];
                                                                    a1 = v_38[v5];
                                                                    a3 *= result;
                                                                    result = a3;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a3 -= result;
                                                                    a1 *= v6;
                                                                    result = a1;
                                                                    result *= (__int64)src2; /* unsigned; high half in a2 */;
                                                                    v_434[v5] = a3;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a1 -= result;
                                                                    v_438[v5] = a1;
                                                                    v5 += 2;
                                                                } while (v5 != 257);
                                                                v4 = rsp + 0xC38;
                                                                a2 = rsp + 0x438;
                                                                sub_1400F27F0(v4, a2, 0x400, v5);
                                                                sub_1400A11B0(v4);
                                                                a1 = v_28;
                                                                a1 += 0xC00;
                                                                return sub_1400F27F0(a1, v4, 0x400);
                                                            } while ((0 /* unresolved: flags > */));
                                                            return a1;
                                                        } while (result != 0x1000);
                                                        return a1;
                                                    } while (result != 0x1000);
                                                    return a1;
                                                }
                                                return a1;
                                            }
                                            return a1;
                                        } while ((0 /* unresolved: flags > */));
                                        return a1;
                                    }
                                    return a1;
                                }
                                return a1;
                            } while ((0 /* unresolved: flags > */));
                            return a1;
                        }
                        return a1;
                    }
                    return a1;
                } while ((0 /* unresolved: flags > */));
                return a1;
            }
            return a1;
        }
        return a1;
    } while ((0 /* unresolved: flags >= */));
    return result;
}