// inferred from 4 accesses on `i`
struct Struct_1_t {
    __int64 field_0; // offset 0
    char _pad_0[24];
    __int64 field_20; // offset 32
    __int64 field_28; // offset 40
    __int64 field_30; // offset 48
};

// inferred from 5 accesses on `i2`
struct Struct_2_t {
    __int16 field_0; // offset 0
    char field_2; // offset 2
    char field_3; // offset 3
    __int16 field_4; // offset 4
    char _pad_4[1];
    __int64 field_7; // offset 7
};

// inferred from 3 accesses on `ptr`
struct Struct_3_t {
    __int64 field_0; // offset 0
    __int64 field_8; // offset 8
    __int64 field_10; // offset 16
};

__int64 sub_1400F2D20();
__int64 sub_14002EDF0();
__int64 sub_1400F3340();
__int64 sub_1400F3600();
__int64 sub_1400D4F50();
__int64 sub_1400F27F0();
__int64 sub_1400D9BD0();
__int64 sub_1400DAC20();
__int64 sub_1400DAEC0();
__int64 off_140108030();
__int64 off_140108038();
extern __int64 off_14011D380;

__int64 __fastcall sub_1400DB140(size_t *a1, int *a2, int *a3, int a4) {
    __int64 rsp;
    int arg_1;
    int arg_2;
    int arg_3;
    int v_120;
    int v_20;
    __int64 v_28;
    __int64 v_38;
    int v_40;
    int v_58;
    int v_60;
    __int64 v_68;
    int v_70;
    __int64 v_78;
    int v_80;
    __int64 v_88;
    int v_90;
    int v_a0;
    __int16 *v_30;
    struct Struct_1_t *i;
    struct Struct_3_t *ptr;
    __int64 *i3;
    __int64 v8;
    __int64 *result;
    __int64 v5;
    __int64 *dst;
    struct Struct_2_t *i2;
    __int64 v9;
    __m128i xmm0;
    __m128i xmm1;

    v_58 = a4;
    i = (struct Struct_1_t *)a3;
    ptr = (struct Struct_3_t *)a2;
    i3 = (__int64 *)a1;
    a1 = *a2;
    v8 = a2[2];
    a1 -= v8;
    result = (__int64 *)v8;
    if (a1 <= 6) {
        do {
            v_20 = 1;
            sub_1400F2D20(ptr, v8, 7, 1);
            result = ptr->field_10;
        } while (true);
    }
    a1 = ptr->field_8;
    *(__int64 *)((__int64)a1 + (__int64)result + 3) = 0;
    *(__int64 *)((__int64)a1 + (__int64)result) = 0x3D8D4C;
    result += 7;
    ptr->field_10 = result;
    v5 = i->field_0;
    result = v5 + 1;
    *(__int64 *)i = (__int64)(result);
    sub_14002EDF0(0, 3);
    if (result == 0) {
        sub_1400F3340(1, 3);
        dst += 5;
        a4 = &off_14011D380;
        sub_1400F3600(dst, a2, a3, a4);
        dst += 6;
        a4 = &off_14011D380;
        sub_1400F3600(dst, a2, a3, a4);
        ++i;
        a4 = &off_14011D380;
        sub_1400F3600(i, a2, result, a4);
    }
    i2 = (struct Struct_2_t *)result;
    *result = 0x894D;
    arg_2 = 252;
    result = ptr->field_0;
    a2 = ptr->field_10;
    result = (__int64 *)((__int64)result - (__int64)a2);
    if (result <= 2) {
        v_20 = 1;
        sub_1400F2D20(ptr, a2, 3, 1);
        a2 = ptr->field_10;
    }
    result = ptr->field_8;
    a1 = i2->field_2;
    *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
    a1 = i2->field_0;
    *(__int64 *)((__int64)result + (__int64)a2) = a1;
    a2 += 3;
    ptr->field_10 = a2;
    off_140108030(a1, a2);
    off_140108038(result, 0, i2);
    result = ptr->field_0;
    i2 = ptr->field_10;
    result = (__int64 *)((__int64)result - (__int64)i2);
    a2 = (int *)i2;
    if (result <= 5) {
        v_20 = 1;
        sub_1400F2D20(ptr, i2, 6, 1);
        a2 = ptr->field_10;
    }
    result = ptr->field_8;
    *(__int64 *)((__int64)result + (__int64)a2 + 4) = 0;
    *(__int64 *)((__int64)result + (__int64)a2) = 0xBE41;
    a2 += 6;
    ptr->field_10 = a2;
    result = v5 + 3;
    *(__int64 *)i = (__int64)(result);
    result = ptr->field_0;
    result = (__int64 *)((__int64)result - (__int64)a2);
    if (result <= 1) {
        v_20 = 1;
        sub_1400F2D20(ptr, a2, 2, 1);
        a2 = ptr->field_10;
    }
    result = ptr->field_8;
    *(__int64 *)((__int64)result + (__int64)a2) = 0xB848;
    a2 += 2;
    ptr->field_10 = a2;
    result = ptr->field_0;
    result = (__int64 *)((__int64)result - (__int64)a2);
    if (result <= 7) {
        v_20 = 1;
        sub_1400F2D20(ptr, a2, 8, 1);
        a2 = ptr->field_10;
    }
    result = ptr->field_8;
    a1 = 0x9E3779B97F4A7C15;
    *(__int64 *)((__int64)result + (__int64)a2) = a1;
    a2 += 8;
    ptr->field_10 = a2;
    result = ptr->field_0;
    result = (__int64 *)((__int64)result - (__int64)a2);
    if (result <= 1) {
        v_20 = 1;
        sub_1400F2D20(ptr, a2, 2, 1);
        a2 = ptr->field_10;
    }
    result = ptr->field_8;
    *(__int64 *)((__int64)result + (__int64)a2) = 0xBB48;
    a2 += 2;
    ptr->field_10 = a2;
    result = ptr->field_0;
    result = (__int64 *)((__int64)result - (__int64)a2);
    if (result <= 7) {
        v_20 = 1;
        sub_1400F2D20(ptr, a2, 8, 1);
        a2 = ptr->field_10;
    }
    result = ptr->field_8;
    a1 = 0xA8014F8F497C4A23;
    *(__int64 *)((__int64)result + (__int64)a2) = a1;
    a2 += 8;
    ptr->field_10 = a2;
    result = ptr->field_0;
    result = (__int64 *)((__int64)result - (__int64)a2);
    v_88 = (__int64)i3;
    v_80 = v8;
    v_78 = (__int64)i2;
    if (result <= 2) {
        v_20 = 1;
        sub_1400F2D20(ptr, a2, 3, 1);
        a2 = ptr->field_10;
    }
    result = ptr->field_8;
    *(__int64 *)((__int64)result + (__int64)a2 + 2) = 195;
    *(__int64 *)((__int64)result + (__int64)a2) = 0x3148;
    a2 += 3;
    ptr->field_10 = a2;
    result = v5 + 6;
    v_28 = (__int64)i;
    *(__int64 *)i = (__int64)(result);
    v5 += 9;
    dst = 64;
    v9 = rsp + 48;
    do {
        sub_14002EDF0(0, 8);
        if (result == 0) JUMPOUT(0x1400dd787);
        v_30 = 8;
        v_38 = (__int64)result;
        *result = 0x8B48;
        v_40 = 2;
        sub_1400D4F50(v9, 0, 4, dst);
        i3 = (__int64 *)v_30;
        i2 = (struct Struct_2_t *)v_38;
        v8 = v_40;
        result = ptr->field_0;
        i = ptr->field_10;
        result = (__int64 *)((__int64)result - (__int64)i);
        if (v8 > result) {
            v_20 = 1;
            sub_1400F2D20(ptr, i, v8, 1);
            i = ptr->field_10;
        }
        a1 = ptr->field_8;
        a1 = (size_t *)((__int64)a1 + (__int64)i);
        sub_1400F27F0(a1, i2, v8);
        i += v8;
        ptr->field_10 = i;
        if (i3 == 0) {
            result = ptr->field_0;
            result = (__int64 *)((__int64)result - (__int64)i);
            if (result <= 2) {
                v_20 = 1;
                sub_1400F2D20(ptr, i, 3, 1);
                i = ptr->field_10;
            }
            result = ptr->field_8;
            *(__int64 *)((__int64)result + (__int64)i + 2) = 216;
            *(__int64 *)((__int64)result + (__int64)i) = 0x3148;
            i += 3;
            ptr->field_10 = i;
            result = v5 - 1;
            a1 = (size_t *)v_28;
            *a1 = result;
            sub_14002EDF0(0, 8);
            if (result == 0) JUMPOUT(0x1400dd787);
            a4 = dst + 64;
            v_30 = 8;
            v_38 = (__int64)result;
            *result = 0x8948;
            v_40 = 2;
            sub_1400D4F50(v9, 0, 4, a4);
            i3 = (__int64 *)v_30;
            i2 = (struct Struct_2_t *)v_38;
            i = (struct Struct_1_t *)v_40;
            result = ptr->field_0;
            v8 = ptr->field_10;
            result -= v8;
            if (i > result) {
                v_20 = 1;
                sub_1400F2D20(ptr, v8, i, 1);
                v8 = ptr->field_10;
            }
            a1 = ptr->field_8;
            a1 += v8;
            sub_1400F27F0(a1, i2, i);
            v8 += (__int64)i;
            ptr->field_10 = v8;
            if (i3 == 0) {
                result = (__int64 *)v_28;
                *result = v5;
                dst += 8;
                v5 += 3;
                i3 = (__int64 *)v_28;
                a3 = (int *)v_120;
                sub_1400D9BD0(ptr, i3, a3);
                a3 = (int *)v_58;
                sub_1400DAC20(ptr, i3, a3, 128);
                sub_14002EDF0(0, 3);
                if (result == 0) {
                    return (__int64)a3;
                }
                i2 = (struct Struct_2_t *)result;
                *result = 0x894C;
                arg_2 = 254;
                result = ptr->field_0;
                a2 = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 2) JUMPOUT(0x1400dcf20);
                result = ptr->field_8;
                a1 = i2->field_2;
                *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 3;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                i2 = *i3;
                result = ptr->field_0;
                dst = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 2) JUMPOUT(0x1400dcf46);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 2) = 245;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x8945;
                dst += 3;
                ptr->field_10 = dst;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 3) JUMPOUT(0x1400dcf6f);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x6EDC141;
                dst += 4;
                ptr->field_10 = dst;
                result = i2 + 3;
                a1 = (size_t *)v_28;
                *a1 = result;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 2) JUMPOUT(0x1400dcf98);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 2) = 247;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x8945;
                dst += 3;
                ptr->field_10 = dst;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 3) JUMPOUT(0x1400dcfc1);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x3FE78341;
                dst += 4;
                ptr->field_10 = dst;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 2) JUMPOUT(0x1400dcfea);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 2) = 237;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x8545;
                v9 = dst + 3;
                ptr->field_10 = v9;
                result = ptr->field_0;
                result -= v9;
                i3 = (__int64 *)v9;
                if (result <= 5) JUMPOUT(0x1400dd013);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)i3 + 4) = 0;
                *(__int64 *)((__int64)result + (__int64)i3) = 0x840F;
                i3 += 6;
                ptr->field_10 = i3;
                i2 += 7;
                a2 = (int *)v_28;
                *a2 = i2;
                a3 = (int *)v_58;
                sub_1400DAEC0(ptr, a2, a3);
                sub_14002EDF0(0, 7);
                if (result == 0) JUMPOUT(0x1400dd7dd);
                i2 = (struct Struct_2_t *)result;
                *result = 0x40C48349;
                result = ptr->field_0;
                a2 = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 3) JUMPOUT(0x1400dd03c);
                result = ptr->field_8;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 4;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = (__int64 *)v_28;
                i = *result;
                a1 = ptr->field_0;
                result = ptr->field_10;
                a1 = (size_t *)((__int64)a1 - (__int64)result);
                if (a1 <= 2) JUMPOUT(0x1400dd062);
                a1 = ptr->field_8;
                *(__int64 *)((__int64)a1 + (__int64)result + 2) = 205;
                *(__int64 *)((__int64)a1 + (__int64)result) = 0xFF49;
                a2 = result + 3;
                ptr->field_10 = a2;
                a1 = i + 2;
                a3 = (int *)v_28;
                *a3 = a1;
                result += 9;
                if ((result < 0)) JUMPOUT(0x1400dd7fb);
                i3 = (__int64 *)((__int64)i3 - (__int64)result);
                result = i3;
                if (i3 != i3) JUMPOUT(0x1400dd824);
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 1) JUMPOUT(0x1400dd08b);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)a2) = 0x850F;
                a2 += 2;
                ptr->field_10 = a2;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 3) JUMPOUT(0x1400dd0b1);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)a2) = i3;
                a3 = a2 + 4;
                ptr->field_10 = a3;
                result = i + 3;
                a1 = (size_t *)v_28;
                *a1 = result;
                if (a2 > 0x7FFFFFFB) JUMPOUT(0x1400dd7a5);
                if (dst > 0x7FFFFFF6) JUMPOUT(0x1400dd7a5);
                a2 = dst + 9;
                if (a2 > a3) {
                    return (__int64)a2;
                }
                a3 -= v9;
                a3 += 0xFFFFFFFA;
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 5) = a3;
                sub_14002EDF0(0, 3, a3);
                if (result == 0) {
                    return (__int64)result;
                }
                i2 = (struct Struct_2_t *)result;
                *result = 0x3148;
                arg_2 = 192;
                result = ptr->field_0;
                a2 = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 2) JUMPOUT(0x1400dd0d7);
                i3 = (__int64 *)v_28;
                result = ptr->field_8;
                a1 = i2->field_2;
                *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 3;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = i + 4;
                *i3 = result;
                sub_14002EDF0(0, 8);
                if (result == 0) JUMPOUT(0x1400dd787);
                i2 = (struct Struct_2_t *)result;
                *result = 0x24BC8D48;
                result = ptr->field_0;
                a2 = ptr->field_10;
                i2->field_4 = 192;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 7) JUMPOUT(0x1400dd0fd);
                result = ptr->field_8;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 8;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = i + 5;
                *i3 = result;
                sub_14002EDF0(0, 6);
                if (result == 0) JUMPOUT(0x1400dd7ce);
                i2 = (struct Struct_2_t *)result;
                *result = 185;
                arg_1 = 128;
                result = ptr->field_0;
                a2 = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 4) JUMPOUT(0x1400dd123);
                result = ptr->field_8;
                a1 = i2->field_4;
                *(__int64 *)((__int64)result + (__int64)a2 + 4) = a1;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 5;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = ptr->field_0;
                a2 = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 2) JUMPOUT(0x1400dd149);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)a2 + 2) = 170;
                *(__int64 *)((__int64)result + (__int64)a2) = 0xF3FC;
                a2 += 3;
                ptr->field_10 = a2;
                result = i + 7;
                *i3 = result;
                sub_14002EDF0(0, 8);
                if (result == 0) JUMPOUT(0x1400dd787);
                i2 = (struct Struct_2_t *)result;
                *result = 0x24748948;
                result = ptr->field_0;
                a2 = ptr->field_10;
                i2->field_4 = 24;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 4) JUMPOUT(0x1400dd16f);
                result = ptr->field_8;
                a1 = i2->field_4;
                *(__int64 *)((__int64)result + (__int64)a2 + 4) = a1;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 5;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = i + 8;
                *i3 = result;
                sub_14002EDF0(0, 3);
                if (result == 0) {
                    return (__int64)result;
                }
                i2 = (struct Struct_2_t *)result;
                *result = 0x894C;
                arg_2 = 230;
                result = ptr->field_0;
                a2 = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 2) JUMPOUT(0x1400dd195);
                result = ptr->field_8;
                a1 = i2->field_2;
                *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 3;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = i + 9;
                *i3 = result;
                sub_14002EDF0(0, 8);
                if (result == 0) JUMPOUT(0x1400dd787);
                i2 = (struct Struct_2_t *)result;
                *result = 0x24BC8D48;
                result = ptr->field_0;
                a2 = ptr->field_10;
                i2->field_4 = 192;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 7) JUMPOUT(0x1400dd1bb);
                result = ptr->field_8;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 8;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = ptr->field_0;
                a2 = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 2) JUMPOUT(0x1400dd1e1);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)a2 + 2) = 249;
                *(__int64 *)((__int64)result + (__int64)a2) = 0x8944;
                a2 += 3;
                ptr->field_10 = a2;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 2) JUMPOUT(0x1400dd207);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)a2 + 2) = 164;
                *(__int64 *)((__int64)result + (__int64)a2) = 0xF3FC;
                a2 += 3;
                ptr->field_10 = a2;
                result = i + 12;
                *i3 = result;
                sub_14002EDF0(0, 8);
                if (result == 0) JUMPOUT(0x1400dd787);
                i2 = (struct Struct_2_t *)result;
                *result = 0x24748B48;
                result = ptr->field_0;
                a2 = ptr->field_10;
                i2->field_4 = 24;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 4) JUMPOUT(0x1400dd22d);
                result = ptr->field_8;
                a1 = i2->field_4;
                *(__int64 *)((__int64)result + (__int64)a2 + 4) = a1;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 5;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                result = ptr->field_0;
                dst = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 2) JUMPOUT(0x1400dd253);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 2) = 128;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x7C6;
                dst += 3;
                ptr->field_10 = dst;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 2) JUMPOUT(0x1400dd27c);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 2) = 243;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x894D;
                dst += 3;
                ptr->field_10 = dst;
                result = i + 15;
                a1 = (size_t *)v_28;
                *a1 = result;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 3) JUMPOUT(0x1400dd2a5);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x40C38349;
                dst += 4;
                ptr->field_10 = dst;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 3) JUMPOUT(0x1400dd2ce);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x3E3C149;
                dst += 4;
                ptr->field_10 = dst;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 2) JUMPOUT(0x1400dd2f7);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 2) = 203;
                *(__int64 *)((__int64)result + (__int64)dst) = 0xF49;
                dst += 3;
                ptr->field_10 = dst;
                result = ptr->field_0;
                result = (__int64 *)((__int64)result - (__int64)dst);
                if (result <= 3) JUMPOUT(0x1400dd320);
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst) = 0x37FF8341;
                v9 = dst + 4;
                ptr->field_10 = v9;
                result = i + 19;
                a1 = (size_t *)v_28;
                *a1 = result;
                a1 = ptr->field_0;
                a1 -= v9;
                result = (__int64 *)v9;
                if (a1 <= 5) JUMPOUT(0x1400dd349);
                a1 = ptr->field_8;
                *(__int64 *)((__int64)a1 + (__int64)result + 4) = 0;
                *(__int64 *)((__int64)a1 + (__int64)result) = 0x870F;
                result += 6;
                ptr->field_10 = result;
                sub_14002EDF0(0, 8);
                if (result == 0) JUMPOUT(0x1400dd787);
                i2 = (struct Struct_2_t *)result;
                *result = 0x249C894C;
                result = ptr->field_0;
                a2 = ptr->field_10;
                i2->field_4 = 248;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 7) JUMPOUT(0x1400dd372);
                result = ptr->field_8;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 8;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                i += 21;
                i2 = (struct Struct_2_t *)v_28;
                *(__int64 *)i2 = (__int64)(i);
                a3 = (int *)v_58;
                sub_1400DAC20(ptr, i2, a3, 192);
                result = ptr->field_0;
                i = ptr->field_10;
                result = (__int64 *)((__int64)result - (__int64)i);
                v8 = (__int64)i;
                if (result <= 4) JUMPOUT(0x1400dd398);
                result = ptr->field_8;
                *(result + v8 + 4) = 0;
                *(result + v8) = 233;
                i3 = v8 + 5;
                ptr->field_10 = i3;
                v5 = i2->field_0;
                sub_14002EDF0(0, 8);
                if (result == 0) JUMPOUT(0x1400dd787);
                i2 = (struct Struct_2_t *)result;
                *result = 0x249C894C;
                result = ptr->field_0;
                a2 = ptr->field_10;
                i2->field_4 = 312;
                result = (__int64 *)((__int64)result - (__int64)a2);
                if (result <= 7) JUMPOUT(0x1400dd3c1);
                result = ptr->field_8;
                a1 = i2->field_0;
                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                a2 += 8;
                ptr->field_10 = a2;
                off_140108030(a1, a2);
                off_140108038(result, 0, i2);
                v5 += 2;
                i2 = (struct Struct_2_t *)v_28;
                *(__int64 *)i2 = (__int64)(v5);
                v5 = v_58;
                sub_1400DAC20(ptr, i2, v5, 192);
                sub_1400DAC20(ptr, i2, v5, 256);
                if (v8 > 0x7FFFFFFA) JUMPOUT(0x1400dd7a5);
                if (dst > 0x7FFFFFF5) JUMPOUT(0x1400dd7a5);
                a3 = ptr->field_10;
                a2 = dst + 10;
                if (a2 > a3) {
                    return (__int64)a2;
                }
                i3 -= v9;
                i3 += 0xFFFFFFFA;
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)dst + 6) = i3;
                if (a3 > 0x7FFFFFFF) JUMPOUT(0x1400dd7a5);
                a1 = (size_t *)v_28;
                if (i > 0x7FFFFFFA) JUMPOUT(0x1400dd7a5);
                a2 = i + 5;
                result = ptr->field_10;
                if (a2 > result) {
                    return (__int64)result;
                }
                a3 = (int *)((__int64)a3 - (__int64)i);
                a3 += 0xFFFFFFFB;
                result = ptr->field_8;
                *(__int64 *)((__int64)result + (__int64)i + 1) = a3;
                v5 = *a1;
                dst = 192;
                i3 = 0;
                do {
                    sub_14002EDF0(0, 8, a3);
                    if (result == 0) JUMPOUT(0x1400dd787);
                    a4 = dst - 160;
                    v_30 = 8;
                    v_38 = (__int64)result;
                    *result = 139;
                    v_40 = 1;
                    a1 = rsp + 48;
                    sub_1400D4F50(a1, 0, 4, a4);
                    v9 = (__int64)v_30;
                    i2 = (struct Struct_2_t *)v_38;
                    i = (struct Struct_1_t *)v_40;
                    result = ptr->field_0;
                    v8 = ptr->field_10;
                    result -= v8;
                    if (i > result) {
                        v_20 = 1;
                        sub_1400F2D20(ptr, v8, i, 1);
                        v8 = ptr->field_10;
                    }
                    a1 = ptr->field_8;
                    a1 += v8;
                    sub_1400F27F0(a1, i2, i);
                    v8 += (__int64)i;
                    ptr->field_10 = v8;
                    if (v9 == 0) {
                        result = v5 + i3;
                        ++result;
                        a1 = (size_t *)v_28;
                        *a1 = result;
                        sub_14002EDF0(0, 3);
                        if (result == 0) JUMPOUT(0x1400dd796);
                        i2 = (struct Struct_2_t *)result;
                        *result = 0xC80F;
                        result = ptr->field_0;
                        a2 = ptr->field_10;
                        result = (__int64 *)((__int64)result - (__int64)a2);
                        if (result <= 1) {
                            v_20 = 1;
                            sub_1400F2D20(ptr, a2, 2, 1);
                            a2 = ptr->field_10;
                        }
                        result = ptr->field_8;
                        a1 = i2->field_0;
                        *(__int64 *)((__int64)result + (__int64)a2) = a1;
                        a2 += 2;
                        ptr->field_10 = a2;
                        off_140108030(a1, a2);
                        off_140108038(result, 0, i2);
                        sub_14002EDF0(0, 8);
                        if (result == 0) JUMPOUT(0x1400dd787);
                        v_30 = 8;
                        v_38 = (__int64)result;
                        *result = 137;
                        v_40 = 1;
                        a1 = rsp + 48;
                        sub_1400D4F50(a1, 0, 4, dst);
                        v9 = (__int64)v_30;
                        i2 = (struct Struct_2_t *)v_38;
                        i = (struct Struct_1_t *)v_40;
                        result = ptr->field_0;
                        v8 = ptr->field_10;
                        result -= v8;
                        if (i > result) {
                            v_20 = 1;
                            sub_1400F2D20(ptr, v8, i, 1);
                            v8 = ptr->field_10;
                        }
                        a1 = ptr->field_8;
                        a1 += v8;
                        sub_1400F27F0(a1, i2, i);
                        v8 += (__int64)i;
                        ptr->field_10 = v8;
                        if (v9 == 0) {
                            i2 = v5 + i3;
                            i2 += 3;
                            result = (__int64 *)v_28;
                            *result = i2;
                            i3 += 3;
                            dst += 4;
                            result = ptr->field_0;
                            a2 = ptr->field_10;
                            result = (__int64 *)((__int64)result - (__int64)a2);
                            if (result <= 1) JUMPOUT(0x1400dd3e7);
                            i = (struct Struct_1_t *)v_28;
                            result = ptr->field_8;
                            *(__int64 *)((__int64)result + (__int64)a2) = 0xB848;
                            a2 += 2;
                            ptr->field_10 = a2;
                            result = ptr->field_0;
                            result = (__int64 *)((__int64)result - (__int64)a2);
                            if (result <= 7) JUMPOUT(0x1400dd40d);
                            result = ptr->field_8;
                            a1 = 0xD1B54A327B53C0E1;
                            *(__int64 *)((__int64)result + (__int64)a2) = a1;
                            a2 += 8;
                            ptr->field_10 = a2;
                            result = ptr->field_0;
                            result = (__int64 *)((__int64)result - (__int64)a2);
                            if (result <= 1) JUMPOUT(0x1400dd433);
                            result = ptr->field_8;
                            *(__int64 *)((__int64)result + (__int64)a2) = 0xBB48;
                            a2 += 2;
                            ptr->field_10 = a2;
                            result = ptr->field_0;
                            result = (__int64 *)((__int64)result - (__int64)a2);
                            if (result <= 7) JUMPOUT(0x1400dd459);
                            i2 -= 3;
                            result = ptr->field_8;
                            a1 = 0x8DE9166E270F9CBD;
                            *(__int64 *)((__int64)result + (__int64)a2) = a1;
                            a2 += 8;
                            ptr->field_10 = a2;
                            result = ptr->field_0;
                            result = (__int64 *)((__int64)result - (__int64)a2);
                            if (result <= 2) JUMPOUT(0x1400dd47f);
                            i3 += v5;
                            i3 += 6;
                            result = ptr->field_8;
                            *(__int64 *)((__int64)result + (__int64)a2 + 2) = 195;
                            *(__int64 *)((__int64)result + (__int64)a2) = 0x3148;
                            a2 += 3;
                            ptr->field_10 = a2;
                            i2 += 6;
                            *(__int64 *)i = (__int64)(i2);
                            dst = 64;
                            v9 = rsp + 48;
                            do {
                                sub_14002EDF0(0, 8);
                                if (result == 0) JUMPOUT(0x1400dd787);
                                v_30 = 8;
                                v_38 = (__int64)result;
                                *result = 0x8B48;
                                v_40 = 2;
                                sub_1400D4F50(v9, 0, 4, dst);
                                v5 = (__int64)v_30;
                                i2 = (struct Struct_2_t *)v_38;
                                v8 = v_40;
                                result = ptr->field_0;
                                i = ptr->field_10;
                                result = (__int64 *)((__int64)result - (__int64)i);
                                if (v8 > result) {
                                    v_20 = 1;
                                    sub_1400F2D20(ptr, i, v8, 1);
                                    i = ptr->field_10;
                                }
                                a1 = ptr->field_8;
                                a1 = (size_t *)((__int64)a1 + (__int64)i);
                                sub_1400F27F0(a1, i2, v8);
                                i += v8;
                                ptr->field_10 = i;
                                if (v5 == 0) {
                                    result = ptr->field_0;
                                    result = (__int64 *)((__int64)result - (__int64)i);
                                    if (result <= 2) {
                                        v_20 = 1;
                                        sub_1400F2D20(ptr, i, 3, 1);
                                        i = ptr->field_10;
                                    }
                                    result = ptr->field_8;
                                    *(__int64 *)((__int64)result + (__int64)i + 2) = 216;
                                    *(__int64 *)((__int64)result + (__int64)i) = 0x3148;
                                    i += 3;
                                    ptr->field_10 = i;
                                    result = i3 - 1;
                                    a1 = (size_t *)v_28;
                                    *a1 = result;
                                    sub_14002EDF0(0, 8);
                                    if (result == 0) JUMPOUT(0x1400dd787);
                                    a4 = dst + 64;
                                    v_30 = 8;
                                    v_38 = (__int64)result;
                                    *result = 0x8948;
                                    v_40 = 2;
                                    sub_1400D4F50(v9, 0, 4, a4);
                                    v5 = (__int64)v_30;
                                    i2 = (struct Struct_2_t *)v_38;
                                    i = (struct Struct_1_t *)v_40;
                                    result = ptr->field_0;
                                    v8 = ptr->field_10;
                                    result -= v8;
                                    if (i > result) {
                                        v_20 = 1;
                                        sub_1400F2D20(ptr, v8, i, 1);
                                        v8 = ptr->field_10;
                                    }
                                    a1 = ptr->field_8;
                                    a1 += v8;
                                    sub_1400F27F0(a1, i2, i);
                                    v8 += (__int64)i;
                                    ptr->field_10 = v8;
                                    if (v5 == 0) {
                                        result = (__int64 *)v_28;
                                        *result = i3;
                                        dst += 8;
                                        i3 += 3;
                                        i3 = (__int64 *)v_28;
                                        a3 = (int *)v_120;
                                        sub_1400D9BD0(ptr, i3, a3);
                                        a3 = (int *)v_58;
                                        sub_1400DAC20(ptr, i3, a3, 128);
                                        sub_14002EDF0(0, 3);
                                        if (result == 0) {
                                            return (__int64)a3;
                                        }
                                        i2 = (struct Struct_2_t *)result;
                                        *result = 0x3148;
                                        arg_2 = 192;
                                        result = ptr->field_0;
                                        a2 = ptr->field_10;
                                        result = (__int64 *)((__int64)result - (__int64)a2);
                                        if (result <= 2) JUMPOUT(0x1400dd4a5);
                                        result = ptr->field_8;
                                        a1 = i2->field_2;
                                        *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
                                        a1 = i2->field_0;
                                        *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                        a2 += 3;
                                        ptr->field_10 = a2;
                                        off_140108030(a1, a2);
                                        off_140108038(result, 0, i2);
                                        v5 = *i3;
                                        result = v5 + 1;
                                        *i3 = result;
                                        i = 64;
                                        dst = rsp + 48;
                                        do {
                                            sub_14002EDF0(0, 8);
                                            if (result == 0) JUMPOUT(0x1400dd787);
                                            v_30 = 8;
                                            v_38 = (__int64)result;
                                            *result = 0x8948;
                                            v_40 = 2;
                                            sub_1400D4F50(dst, 0, 4, i);
                                            i3 = (__int64 *)v_30;
                                            i2 = (struct Struct_2_t *)v_38;
                                            v8 = v_40;
                                            result = ptr->field_0;
                                            v9 = ptr->field_10;
                                            result -= v9;
                                            if (v8 > result) {
                                                v_20 = 1;
                                                sub_1400F2D20(ptr, v9, v8, 1);
                                                v9 = ptr->field_10;
                                            }
                                            a1 = ptr->field_8;
                                            a1 += v9;
                                            sub_1400F27F0(a1, i2, v8);
                                            v9 += v8;
                                            ptr->field_10 = v9;
                                            if (i3 == 0) {
                                                i += 8;
                                                sub_14002EDF0(0, 3);
                                                if (result == 0) {
                                                    return (__int64)i;
                                                }
                                                i2 = (struct Struct_2_t *)result;
                                                *result = 0x3148;
                                                arg_2 = 192;
                                                result = ptr->field_0;
                                                a2 = ptr->field_10;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 2) JUMPOUT(0x1400dd4cb);
                                                i3 = (__int64 *)v_28;
                                                result = ptr->field_8;
                                                a1 = i2->field_2;
                                                *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
                                                a1 = i2->field_0;
                                                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                a2 += 3;
                                                ptr->field_10 = a2;
                                                off_140108030(a1, a2);
                                                off_140108038(result, 0, i2);
                                                result = v5 + 10;
                                                *i3 = result;
                                                sub_14002EDF0(0, 8);
                                                if (result == 0) JUMPOUT(0x1400dd787);
                                                i2 = (struct Struct_2_t *)result;
                                                result = 0xE124BC8D48;
                                                *(__int64 *)i2 = (__int64)(result);
                                                result = ptr->field_0;
                                                a2 = ptr->field_10;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 7) JUMPOUT(0x1400dd4f1);
                                                result = ptr->field_8;
                                                a1 = i2->field_0;
                                                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                a2 += 8;
                                                ptr->field_10 = a2;
                                                off_140108030(a1, a2);
                                                off_140108038(result, 0, i2);
                                                sub_14002EDF0(0, 6);
                                                if (result == 0) JUMPOUT(0x1400dd7ce);
                                                i2 = (struct Struct_2_t *)result;
                                                *result = 185;
                                                arg_1 = 23;
                                                result = ptr->field_0;
                                                a2 = ptr->field_10;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 4) JUMPOUT(0x1400dd517);
                                                result = ptr->field_8;
                                                a1 = i2->field_4;
                                                *(__int64 *)((__int64)result + (__int64)a2 + 4) = a1;
                                                a1 = i2->field_0;
                                                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                a2 += 5;
                                                ptr->field_10 = a2;
                                                off_140108030(a1, a2);
                                                off_140108038(result, 0, i2);
                                                result = v5 + 12;
                                                *i3 = result;
                                                result = ptr->field_0;
                                                a2 = ptr->field_10;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 2) JUMPOUT(0x1400dd53d);
                                                result = ptr->field_8;
                                                *(__int64 *)((__int64)result + (__int64)a2 + 2) = 170;
                                                *(__int64 *)((__int64)result + (__int64)a2) = 0xF3FC;
                                                a2 += 3;
                                                ptr->field_10 = a2;
                                                result = ptr->field_0;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 2) JUMPOUT(0x1400dd563);
                                                result = ptr->field_8;
                                                *(__int64 *)((__int64)result + (__int64)a2 + 2) = 36;
                                                *(__int64 *)((__int64)result + (__int64)a2) = 0x84C6;
                                                a2 += 3;
                                                ptr->field_10 = a2;
                                                result = ptr->field_0;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 3) JUMPOUT(0x1400dd589);
                                                result = ptr->field_8;
                                                *(__int64 *)((__int64)result + (__int64)a2) = 224;
                                                a2 += 4;
                                                ptr->field_10 = a2;
                                                if (ptr->field_0 == a2) JUMPOUT(0x1400dd5af);
                                                result = ptr->field_8;
                                                *(__int64 *)((__int64)result + (__int64)a2) = 128;
                                                ++a2;
                                                ptr->field_10 = a2;
                                                result = v5 + 14;
                                                *i3 = result;
                                                sub_14002EDF0(0, 11);
                                                if (result == 0) JUMPOUT(0x1400dd7ec);
                                                i2 = (struct Struct_2_t *)result;
                                                *result = 0x84C7;
                                                arg_2 = 36;
                                                arg_3 = 248;
                                                result = ptr->field_0;
                                                a2 = ptr->field_10;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 10) JUMPOUT(0x1400dd5d5);
                                                result = ptr->field_8;
                                                a1 = i2->field_7;
                                                *(__int64 *)((__int64)result + (__int64)a2 + 7) = a1;
                                                a1 = i2->field_0;
                                                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                a2 += 11;
                                                ptr->field_10 = a2;
                                                off_140108030(a1, a2);
                                                off_140108038(result, 0, i2);
                                                sub_14002EDF0(0, 11);
                                                if (result == 0) JUMPOUT(0x1400dd7ec);
                                                i2 = (struct Struct_2_t *)result;
                                                *result = 0x84C7;
                                                arg_2 = 36;
                                                result = 0x30000000000FC;
                                                i2->field_3 = result;
                                                result = ptr->field_0;
                                                a2 = ptr->field_10;
                                                result = (__int64 *)((__int64)result - (__int64)a2);
                                                if (result <= 10) JUMPOUT(0x1400dd5fb);
                                                result = ptr->field_8;
                                                a1 = i2->field_7;
                                                *(__int64 *)((__int64)result + (__int64)a2 + 7) = a1;
                                                a1 = i2->field_0;
                                                *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                a2 += 11;
                                                ptr->field_10 = a2;
                                                off_140108030(a1, a2);
                                                off_140108038(result, 0, i2);
                                                v5 += 16;
                                                *i3 = v5;
                                                a3 = (int *)v_58;
                                                sub_1400DAC20(ptr, i3, a3, 192);
                                                result = ptr->field_0;
                                                v5 = ptr->field_10;
                                                result -= v5;
                                                if (result <= 1) JUMPOUT(0x1400dd621);
                                                i = ptr->field_8;
                                                *(__int64 *)(i + v5) = (__int64)(0xDB31);
                                                v5 += 2;
                                                ptr->field_10 = v5;
                                                v8 = *i3;
                                                result = v8 + 1;
                                                *i3 = result;
                                                xmm0 = _mm_setzero_si128();
                                                _mm_store_si128((__m128i *)&v_40, xmm0);
                                                _mm_store_si128((__m128i *)&v_30, xmm0);
                                                v9 = 0;
                                                do {
                                                    i3 = (__int64 *)v9;
                                                    sub_14002EDF0(0, 8);
                                                    if (result == 0) JUMPOUT(0x1400dd787);
                                                    v_60 = 8;
                                                    v_68 = (__int64)result;
                                                    *result = 139;
                                                    v_70 = 1;
                                                    a4 = i3 + 32;
                                                    a1 = rsp + 96;
                                                    sub_1400D4F50(a1, 0, 4, a4);
                                                    dst = (__int64 *)v_60;
                                                    v9 = v_68;
                                                    i2 = (struct Struct_2_t *)v_70;
                                                    result = ptr->field_0;
                                                    result -= v5;
                                                    if (i2 > result) {
                                                        v_20 = 1;
                                                        sub_1400F2D20(ptr, v5, i2, 1);
                                                        i = ptr->field_8;
                                                        v5 = ptr->field_10;
                                                    }
                                                    i += v5;
                                                    sub_1400F27F0(i, v9, i2);
                                                    v5 += (__int64)i2;
                                                    ptr->field_10 = v5;
                                                    if (dst == 0) {
                                                        result = v8 + i3;
                                                        result += 2;
                                                        a1 = (size_t *)v_28;
                                                        *a1 = result;
                                                        sub_14002EDF0(0, 3);
                                                        if (result == 0) JUMPOUT(0x1400dd796);
                                                        i2 = (struct Struct_2_t *)result;
                                                        *result = 0xC80F;
                                                        dst = ptr->field_0;
                                                        result = dst;
                                                        result -= v5;
                                                        if (result <= 1) {
                                                            v_20 = 1;
                                                            sub_1400F2D20(ptr, v5, 2, 1);
                                                            dst = ptr->field_0;
                                                            v5 = ptr->field_10;
                                                        }
                                                        i = ptr->field_8;
                                                        result = i2->field_0;
                                                        *(__int64 *)(i + v5) = (__int64)(result);
                                                        v9 = v5 + 2;
                                                        ptr->field_10 = v9;
                                                        off_140108030();
                                                        off_140108038(result, 0, i2);
                                                        result = dst;
                                                        result -= v9;
                                                        if (result <= 5) {
                                                            v_20 = 1;
                                                            sub_1400F2D20(ptr, v9, 6, 1);
                                                            v9 = ptr->field_10;
                                                            dst = ptr->field_0;
                                                            i = ptr->field_8;
                                                        }
                                                        *(__int64 *)(i + v9 + 4) = (__int64)(0);
                                                        *(__int64 *)(i + v9) = (__int64)(0x8633);
                                                        v9 += 6;
                                                        ptr->field_10 = v9;
                                                        v5 += 4;
                                                        v_30[(__int64)i3] = v5;
                                                        dst -= v9;
                                                        if (dst <= 1) {
                                                            v_20 = 1;
                                                            sub_1400F2D20(ptr, v9, 2, 1);
                                                            i = ptr->field_8;
                                                            v9 = ptr->field_10;
                                                        }
                                                        dst = (__int64 *)v_28;
                                                        *(__int64 *)(i + v9) = (__int64)(0xC309);
                                                        v5 = v9;
                                                        v5 += 2;
                                                        ptr->field_10 = v5;
                                                        result = v8 + i3;
                                                        result += 5;
                                                        *dst = result;
                                                        v9 = i3 + 4;
                                                        result = ptr->field_0;
                                                        a1 = (size_t *)result;
                                                        a1 -= v5;
                                                        if (a1 <= 1) JUMPOUT(0x1400dd64a);
                                                        a1 = ptr->field_8;
                                                        *(a1 + v5) = 0xDB85;
                                                        v5 += 2;
                                                        ptr->field_10 = v5;
                                                        result -= v5;
                                                        a2 = (int *)v5;
                                                        if (result <= 5) JUMPOUT(0x1400dd676);
                                                        *(__int64 *)((__int64)a1 + (__int64)a2 + 4) = 0;
                                                        *(__int64 *)((__int64)a1 + (__int64)a2) = 0x850F;
                                                        a2 += 6;
                                                        ptr->field_10 = a2;
                                                        xmm0 = _mm_load_si128((__m128i *)&v_30);
                                                        xmm1 = _mm_load_si128((__m128i *)&v_40);
                                                        _mm_store_si128((__m128i *)&v_a0, xmm1);
                                                        _mm_store_si128((__m128i *)&v_90, xmm0);
                                                        sub_14002EDF0(0, 3);
                                                        if (result == 0) {
                                                            return _mm_cvtsi128_si64(xmm1);
                                                        }
                                                        i2 = (struct Struct_2_t *)result;
                                                        i3 += v8;
                                                        ++i3;
                                                        *result = 0x3148;
                                                        arg_2 = 192;
                                                        result = ptr->field_0;
                                                        a2 = ptr->field_10;
                                                        result = (__int64 *)((__int64)result - (__int64)a2);
                                                        if (result <= 2) JUMPOUT(0x1400dd6a3);
                                                        result = ptr->field_8;
                                                        a1 = i2->field_2;
                                                        *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
                                                        a1 = i2->field_0;
                                                        *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                        a2 += 3;
                                                        ptr->field_10 = a2;
                                                        off_140108030(a1, a2);
                                                        off_140108038(result, 0, i2);
                                                        result = i3 + 7;
                                                        *dst = result;
                                                        sub_14002EDF0(0, 3);
                                                        if (result == 0) {
                                                            return (__int64)result;
                                                        }
                                                        i2 = (struct Struct_2_t *)result;
                                                        *result = 0x8948;
                                                        arg_2 = 231;
                                                        result = ptr->field_0;
                                                        a2 = ptr->field_10;
                                                        result = (__int64 *)((__int64)result - (__int64)a2);
                                                        if (result <= 2) JUMPOUT(0x1400dd6c9);
                                                        result = ptr->field_8;
                                                        a1 = i2->field_2;
                                                        *(__int64 *)((__int64)result + (__int64)a2 + 2) = a1;
                                                        a1 = i2->field_0;
                                                        *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                        a2 += 3;
                                                        ptr->field_10 = a2;
                                                        off_140108030(a1, a2);
                                                        off_140108038(result, 0, i2);
                                                        sub_14002EDF0(0, 6);
                                                        if (result == 0) JUMPOUT(0x1400dd7ce);
                                                        i2 = (struct Struct_2_t *)result;
                                                        *result = 185;
                                                        arg_1 = 320;
                                                        result = ptr->field_0;
                                                        a2 = ptr->field_10;
                                                        result = (__int64 *)((__int64)result - (__int64)a2);
                                                        if (result <= 4) JUMPOUT(0x1400dd6ef);
                                                        result = ptr->field_8;
                                                        a1 = i2->field_4;
                                                        *(__int64 *)((__int64)result + (__int64)a2 + 4) = a1;
                                                        a1 = i2->field_0;
                                                        *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                        a2 += 5;
                                                        ptr->field_10 = a2;
                                                        off_140108030(a1, a2);
                                                        off_140108038(result, 0, i2);
                                                        result = ptr->field_0;
                                                        a2 = ptr->field_10;
                                                        result = (__int64 *)((__int64)result - (__int64)a2);
                                                        if (result <= 2) JUMPOUT(0x1400dd715);
                                                        result = ptr->field_8;
                                                        *(__int64 *)((__int64)result + (__int64)a2 + 2) = 170;
                                                        *(__int64 *)((__int64)result + (__int64)a2) = 0xF3FC;
                                                        a2 += 3;
                                                        ptr->field_10 = a2;
                                                        i3 += 10;
                                                        *dst = i3;
                                                        sub_14002EDF0(0, 7);
                                                        if (result == 0) JUMPOUT(0x1400dd7dd);
                                                        i2 = (struct Struct_2_t *)result;
                                                        *result = 0x8148;
                                                        arg_3 = 320;
                                                        arg_2 = 196;
                                                        result = ptr->field_0;
                                                        a2 = ptr->field_10;
                                                        result = (__int64 *)((__int64)result - (__int64)a2);
                                                        if (result <= 6) JUMPOUT(0x1400dd73b);
                                                        result = ptr->field_8;
                                                        a1 = i2->field_0;
                                                        a3 = i2->field_3;
                                                        *(__int64 *)((__int64)result + (__int64)a2 + 3) = a3;
                                                        *(__int64 *)((__int64)result + (__int64)a2) = a1;
                                                        a2 += 7;
                                                        ptr->field_10 = a2;
                                                        off_140108030(a1, a2, a3);
                                                        off_140108038(result, 0, i2);
                                                        a2 = ptr->field_10;
                                                        if (ptr->field_0 == a2) JUMPOUT(0x1400dd761);
                                                        i2 = v8 + v9;
                                                        i2 += 10;
                                                        result = ptr->field_8;
                                                        *(__int64 *)((__int64)result + (__int64)a2) = 90;
                                                        ++a2;
                                                        ptr->field_10 = a2;
                                                        i3 = 440;
                                                        i = (struct Struct_1_t *)v_88;
                                                        do {
                                                            result = ptr->field_0;
                                                            result = (__int64 *)((__int64)result - (__int64)a2);
                                                            v_20 = 1;
                                                            sub_1400F2D20(ptr, a2, 3, 1);
                                                            a2 = ptr->field_10;
                                                            result = ptr->field_8;
                                                            *(__int64 *)((__int64)result + (__int64)a2 + 2) = 36;
                                                            *(__int64 *)((__int64)result + (__int64)a2) = 0x9C89;
                                                            a2 += 3;
                                                            ptr->field_10 = a2;
                                                            result = ptr->field_0;
                                                            result = (__int64 *)((__int64)result - (__int64)a2);
                                                            if (result <= 3) {
                                                                v_20 = 1;
                                                                sub_1400F2D20(ptr, a2, 4, 1);
                                                                a2 = ptr->field_10;
                                                            }
                                                            result = ptr->field_8;
                                                            *(__int64 *)((__int64)result + (__int64)a2) = i3;
                                                            a2 += 4;
                                                            ptr->field_10 = a2;
                                                            *dst = i2;
                                                            i3 += 4;
                                                            ++i2;
                                                        } while (i3 != 472);
                                                        a1 = (size_t *)v_78;
                                                        a1 += 2;
                                                        result = (__int64 *)v_80;
                                                        i->field_20 = result;
                                                        i->field_28 = a1;
                                                        xmm0 = _mm_load_si128((__m128i *)&v_90);
                                                        xmm1 = _mm_load_si128((__m128i *)&v_a0);
                                                        _mm_storeu_si128((__m128i *)i, xmm0);
                                                        _mm_storeu_si128((__m128i *)(i + 16), xmm1);
                                                        i->field_30 = v5;
                                                        return _mm_cvtsi128_si64(xmm1);
                                                    }
                                                    off_140108030();
                                                    off_140108038(result, 0, v9);
                                                    return _mm_cvtsi128_si64(xmm1);
                                                } while (v9 != 16);
                                                return _mm_cvtsi128_si64(xmm1);
                                            }
                                            off_140108030();
                                            off_140108038(result, 0, i2);
                                            return _mm_cvtsi128_si64(xmm1);
                                        } while (i != 128);
                                        return _mm_cvtsi128_si64(xmm1);
                                    }
                                    off_140108030();
                                    off_140108038(result, 0, i2);
                                    return _mm_cvtsi128_si64(xmm1);
                                }
                                off_140108030();
                                off_140108038(result, 0, i2);
                                i = ptr->field_10;
                                return (__int64)i;
                            } while (dst != 128);
                            return (__int64)i;
                        }
                        off_140108030();
                        off_140108038(result, 0, i2);
                        return (__int64)i;
                    }
                    off_140108030();
                    off_140108038(result, 0, i2);
                    return (__int64)i;
                } while (i3 != 24);
                return (__int64)i;
            }
            off_140108030();
            off_140108038(result, 0, i2);
            return (__int64)i;
        }
        off_140108030();
        off_140108038(result, 0, i2);
        i = ptr->field_10;
        return (__int64)i;
    } while (dst != 128);
    return (__int64)result;
}