__int64 sub_1400F1D90();
__int64 sub_1400F27F0();
__int64 sub_1400F2808();
__int64 sub_1400A11B0();
__int64 sub_1400F3869();
__int64 sub_1400A12E3();
extern __int64 off_140119F58;
extern __int64 off_14011A370;
extern __int64 off_14011A358;

__int64 __fastcall sub_1400A0970(size_t *a1, int a2, size_t a3) {
    __int64 rsp;
    int v_28;
    int v_30;
    int *v_0;
    int *v_34;
    int *v_38;
    int *v_434;
    int *v_438;
    int *v_834;
    int *v_838;
    __int64 v5;
    __int64 *src;
    __int64 v10;
    __int64 v6;
    __int64 v7;
    __int64 v2;
    __int64 v8;
    __int64 i;
    __int64 i2;
    __int64 result;
    __int64 *v3;
    __int64 v4;

    sub_1400F1D90(0x1038);
    v_30 = a3;
    v_28 = (int)a1;
    a1 = rsp + 0x838;
    sub_1400F27F0(a1, a2, 0x400);
    v5 = 128;
    a1 = 1;
    src = &off_140119F58;
    v10 = 0x200801C060148461;
    do {
        v6 = v5 + v5;
        v7 = rsp + v5*4;
        v7 += 0x838;
        v2 = 0;
        while (a1 <= 255) {
            v8 = *(src + (__int64)(__int64)a1*4);
            ++a1;
            i = v2 + v5;
            i2 = v2;
            result = v5 + i2;
            while (result <= 255) {
                a3 = v_0[i2];
                a3 *= v8;
                result = a3;
                result *= v10; /* unsigned; high half in a2 */;
                a2 >>= 20;
                result = a2 * 0x7FE001;
                a3 -= result;
                v3 = v_838[i2];
                a2 = v3 + a3;
                result = (__int64)v3;
                result -= a3;
                v4 = result + 0x7FE001;
                if (v4 < 0x7FE001) result = v4;
                a3 += (__int64)v3;
                a3 += 0xFF801FFF;
                if (a2 < 0x7FE001) a3 = a2;
                v_0[i2] = result;
                v_838[i2] = a3;
                ++i2;
                v2 += v6;
                result = v5;
                result >>= 1;
                /* cmp v5 , 2 */;
                a1 = (size_t *)v_28;
                sub_1400F2808(a1, 0, 0x1000, result);
                a1 = rsp + 56;
                a2 = v_30;
                sub_1400F27F0(a1, a2, 0x400);
                v5 = 128;
                a1 = 1;
                do {
                    v6 = v5 + v5;
                    v7 = rsp + v5*4;
                    v7 += 56;
                    v2 = 0;
                    while (a1 <= 255) {
                        v8 = *(src + (__int64)(__int64)a1*4);
                        ++a1;
                        i = v2 + v5;
                        i2 = v2;
                        result = v5 + i2;
                        while (result <= 255) {
                            a3 = v_0[i2];
                            a3 *= v8;
                            result = a3;
                            result *= v10; /* unsigned; high half in a2 */;
                            a2 >>= 20;
                            result = a2 * 0x7FE001;
                            a3 -= result;
                            result = v_38[i2];
                            a2 = result + a3;
                            v3 = (__int64 *)result;
                            v3 -= a3;
                            v4 = v3 + 0x7FE001;
                            if (v4 < 0x7FE001) v3 = v4;
                            result += a3;
                            result += 0xFF801FFF;
                            if (a2 < 0x7FE001) result = a2;
                            v_0[i2] = v3;
                            v_38[i2] = result;
                            ++i2;
                            v2 += v6;
                            result = v5;
                            result >>= 1;
                            /* cmp v5 , 2 */;
                            a1 = rsp + 0x438;
                            sub_1400F2808(a1, 0, 0x400, result);
                            v5 = 1;
                            do {
                                result = v_834[v5];
                                v6 = v_838[v5];
                                a3 = v_34[v5];
                                a1 = v_38[v5];
                                a3 *= result;
                                result = a3;
                                result *= v10; /* unsigned; high half in a2 */;
                                a2 >>= 20;
                                result = a2 * 0x7FE001;
                                a3 -= result;
                                a1 = (size_t *)((__int64)(__int64)(__int64)a1 * v6);
                                result = (__int64)a1;
                                result *= v10; /* unsigned; high half in a2 */;
                                v_434[v5] = a3;
                                a2 >>= 20;
                                result = a2 * 0x7FE001;
                                a1 -= result;
                                v_438[v5] = a1;
                                v5 += 2;
                            } while (v5 != 257);
                            v2 = rsp + 0xC38;
                            a2 = rsp + 0x438;
                            sub_1400F27F0(v2, a2, 0x400, v5);
                            sub_1400A11B0(v2);
                            a1 = (size_t *)v_28;
                            sub_1400F27F0(a1, v2, 0x400);
                            result = v_30;
                            a2 = result + 0x400;
                            a1 = rsp + 56;
                            sub_1400F27F0(a1, a2, 0x400);
                            v5 = 128;
                            a1 = 1;
                            do {
                                v6 = v5 + v5;
                                v7 = rsp + v5*4;
                                v7 += 56;
                                v2 = 0;
                                while (a1 <= 255) {
                                    v8 = *(src + (__int64)(__int64)a1*4);
                                    ++a1;
                                    i = v2 + v5;
                                    i2 = v2;
                                    result = v5 + i2;
                                    while (result <= 255) {
                                        a3 = v_0[i2];
                                        a3 *= v8;
                                        result = a3;
                                        result *= v10; /* unsigned; high half in a2 */;
                                        a2 >>= 20;
                                        result = a2 * 0x7FE001;
                                        a3 -= result;
                                        result = v_38[i2];
                                        a2 = result + a3;
                                        v3 = (__int64 *)result;
                                        v3 -= a3;
                                        v4 = v3 + 0x7FE001;
                                        if (v4 < 0x7FE001) v3 = v4;
                                        result += a3;
                                        result += 0xFF801FFF;
                                        if (a2 < 0x7FE001) result = a2;
                                        v_0[i2] = v3;
                                        v_38[i2] = result;
                                        ++i2;
                                        v2 += v6;
                                        result = v5;
                                        result >>= 1;
                                        /* cmp v5 , 1 */;
                                        a1 = rsp + 0x438;
                                        sub_1400F2808(a1, 0, 0x400, result);
                                        v5 = 1;
                                        do {
                                            result = v_834[v5];
                                            v6 = v_838[v5];
                                            a3 = v_34[v5];
                                            a1 = v_38[v5];
                                            a3 *= result;
                                            result = a3;
                                            result *= v10; /* unsigned; high half in a2 */;
                                            a2 >>= 20;
                                            result = a2 * 0x7FE001;
                                            a3 -= result;
                                            a1 = (size_t *)((__int64)(__int64)(__int64)a1 * v6);
                                            result = (__int64)a1;
                                            result *= v10; /* unsigned; high half in a2 */;
                                            v_434[v5] = a3;
                                            a2 >>= 20;
                                            result = a2 * 0x7FE001;
                                            a1 -= result;
                                            v_438[v5] = a1;
                                            v5 += 2;
                                        } while (v5 != 257);
                                        v2 = rsp + 0xC38;
                                        a2 = rsp + 0x438;
                                        sub_1400F27F0(v2, a2, 0x400, v5);
                                        sub_1400A11B0(v2);
                                        result = v_28;
                                        a1 = result + 0x400;
                                        sub_1400F27F0(a1, v2, 0x400);
                                        result = v_30;
                                        a2 = result + 0x800;
                                        a1 = rsp + 56;
                                        sub_1400F27F0(a1, a2, 0x400);
                                        v5 = 128;
                                        a1 = 1;
                                        do {
                                            v6 = v5 + v5;
                                            v7 = rsp + v5*4;
                                            v7 += 56;
                                            v2 = 0;
                                            while (a1 <= 255) {
                                                v8 = *(src + (__int64)(__int64)a1*4);
                                                ++a1;
                                                i = v2 + v5;
                                                i2 = v2;
                                                result = v5 + i2;
                                                while (result <= 255) {
                                                    a3 = v_0[i2];
                                                    a3 *= v8;
                                                    result = a3;
                                                    result *= v10; /* unsigned; high half in a2 */;
                                                    a2 >>= 20;
                                                    result = a2 * 0x7FE001;
                                                    a3 -= result;
                                                    result = v_38[i2];
                                                    a2 = result + a3;
                                                    v3 = (__int64 *)result;
                                                    v3 -= a3;
                                                    v4 = v3 + 0x7FE001;
                                                    if (v4 < 0x7FE001) v3 = v4;
                                                    result += a3;
                                                    result += 0xFF801FFF;
                                                    if (a2 < 0x7FE001) result = a2;
                                                    v_0[i2] = v3;
                                                    v_38[i2] = result;
                                                    ++i2;
                                                    v2 += v6;
                                                    result = v5;
                                                    result >>= 1;
                                                    /* cmp v5 , 1 */;
                                                    a1 = rsp + 0x438;
                                                    sub_1400F2808(a1, 0, 0x400, result);
                                                    v5 = 1;
                                                    do {
                                                        result = v_834[v5];
                                                        v6 = v_838[v5];
                                                        a3 = v_34[v5];
                                                        a1 = v_38[v5];
                                                        a3 *= result;
                                                        result = a3;
                                                        result *= v10; /* unsigned; high half in a2 */;
                                                        a2 >>= 20;
                                                        result = a2 * 0x7FE001;
                                                        a3 -= result;
                                                        a1 = (size_t *)((__int64)(__int64)(__int64)a1 * v6);
                                                        result = (__int64)a1;
                                                        result *= v10; /* unsigned; high half in a2 */;
                                                        v_434[v5] = a3;
                                                        a2 >>= 20;
                                                        result = a2 * 0x7FE001;
                                                        a1 -= result;
                                                        v_438[v5] = a1;
                                                        v5 += 2;
                                                    } while (v5 != 257);
                                                    v2 = rsp + 0xC38;
                                                    a2 = rsp + 0x438;
                                                    sub_1400F27F0(v2, a2, 0x400, v5);
                                                    sub_1400A11B0(v2);
                                                    result = v_28;
                                                    a1 = result + 0x800;
                                                    sub_1400F27F0(a1, v2, 0x400);
                                                    a2 = v_30;
                                                    a2 += 0xC00;
                                                    a1 = rsp + 56;
                                                    sub_1400F27F0(a1, a2, 0x400);
                                                    v5 = 128;
                                                    a1 = 1;
                                                    do {
                                                        v6 = v5 + v5;
                                                        v7 = rsp + v5*4;
                                                        v7 += 56;
                                                        v4 = 0;
                                                        while (a1 <= 255) {
                                                            v2 = *(src + (__int64)(__int64)a1*4);
                                                            ++a1;
                                                            v8 = v4 + v5;
                                                            i = v4;
                                                            result = v5 + i;
                                                            while (result <= 255) {
                                                                a3 = v_0[i];
                                                                a3 *= v2;
                                                                result = a3;
                                                                result *= v10; /* unsigned; high half in a2 */;
                                                                a2 >>= 20;
                                                                result = a2 * 0x7FE001;
                                                                a3 -= result;
                                                                result = v_38[i];
                                                                a2 = result + a3;
                                                                v3 = (__int64 *)result;
                                                                v3 -= a3;
                                                                i2 = v3 + 0x7FE001;
                                                                if (i2 < 0x7FE001) v3 = i2;
                                                                result += a3;
                                                                result += 0xFF801FFF;
                                                                if (a2 < 0x7FE001) result = a2;
                                                                v_0[i] = v3;
                                                                v_38[i] = result;
                                                                ++i;
                                                                v4 += v6;
                                                                result = v5;
                                                                result >>= 1;
                                                                /* cmp v5 , 1 */;
                                                                a1 = rsp + 0x438;
                                                                sub_1400F2808(a1, 0, 0x400, result);
                                                                v5 = 1;
                                                                do {
                                                                    result = v_834[v5];
                                                                    v6 = v_838[v5];
                                                                    a3 = v_34[v5];
                                                                    a1 = v_38[v5];
                                                                    a3 *= result;
                                                                    result = a3;
                                                                    result *= v10; /* unsigned; high half in a2 */;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a3 -= result;
                                                                    a1 = (size_t *)((__int64)(__int64)(__int64)a1 * v6);
                                                                    result = (__int64)a1;
                                                                    result *= v10; /* unsigned; high half in a2 */;
                                                                    v_434[v5] = a3;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    a1 -= result;
                                                                    v_438[v5] = a1;
                                                                    v5 += 2;
                                                                } while (v5 != 257);
                                                                v4 = rsp + 0xC38;
                                                                a2 = rsp + 0x438;
                                                                sub_1400F27F0(v4, a2, 0x400, v5);
                                                                sub_1400A11B0(v4);
                                                                a1 = (size_t *)v_28;
                                                                a1 += 0xC00;
                                                                sub_1400F27F0(a1, v4, 0x400);
                                                                return (__int64)a1;
                                                            }
                                                            a3 = &off_14011A370;
                                                            sub_1400F3869(result, 256, a3);
                                                        }
                                                        a3 = &off_14011A358;
                                                        sub_1400F3869(a1, 256, a3);
                                                        a3 = 1;
                                                        v6 = 255;
                                                        v3 = &off_140119F58;
                                                        v7 = 0x200801C060148461;
                                                        do {
                                                            v4 = a3 + a3;
                                                            v2 = a1 + a3*4;
                                                            v10 = 0;
                                                            do {
                                                                if (v6 > 255) JUMPOUT(0x1400a13a8);
                                                                src = 0x7FE001;
                                                                src -= *(v3 + v6*4);
                                                                --v6;
                                                                v8 = v10 + a3;
                                                                i = v10;
                                                                do {
                                                                    if (i == 256) JUMPOUT(0x1400a137e);
                                                                    result = a3 + i;
                                                                    if (result >= 256) JUMPOUT(0x1400a1394);
                                                                    v5 = v_0[i];
                                                                    result = v_0[i];
                                                                    a2 = result + v5;
                                                                    i2 = result + v5 - 0x7FE001;
                                                                    if (a2 < 0x7FE001) i2 = a2;
                                                                    v5 -= result;
                                                                    result = v5 + 0x7FE001;
                                                                    if (result < 0x7FE001) v5 = result;
                                                                    v5 *= (__int64)src;
                                                                    result = v5;
                                                                    result *= v7; /* unsigned; high half in a2 */;
                                                                    v_0[i] = i2;
                                                                    a2 >>= 20;
                                                                    result = a2 * 0x7FE001;
                                                                    v5 -= result;
                                                                    v_0[i] = v5;
                                                                    ++i;
                                                                } while (i < v8);
                                                                v10 += v4;
                                                            } while (v10 < 256);
                                                            a3 = v4;
                                                        } while ((a3 < 128));
                                                        a3 = 1;
                                                        v6 = 0x7FDFFF;
                                                        v5 = 256;
                                                        return sub_1400A12E3();
                                                    } while ((0 /* unresolved: flags > */));
                                                    return v5;
                                                }
                                                return v5;
                                            }
                                            return v5;
                                        } while ((0 /* unresolved: flags > */));
                                        return v5;
                                    }
                                    return v5;
                                }
                                return v5;
                            } while ((0 /* unresolved: flags > */));
                            return v5;
                        }
                        return v5;
                    }
                    return v5;
                } while ((0 /* unresolved: flags >= */));
                return v5;
            }
            return v5;
        }
        return v5;
    } while ((0 /* unresolved: flags >= */));
    return result;
}