[package]
license.workspace = true
name = "rustre-yara-rules"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-yara = { path = "../rustre-yara" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
parking_lot = { workspace = true }
sha2 = { workspace = true }

[lints]
workspace = true
