// GENERATED by tools/gen_runtime_prototypes.py — do not edit by hand.
//
// mingw-w64 / libgcc runtime prototypes, extracted mechanically from the
// installed headers (header:line recorded per entry).
//
// This populates the database the decompiler actually consults: a published
// prototype here wins over inference, so a wrong entry does not merely fail to
// help, it overrides a correct inference. Hence: extracted, never remembered.

use crate::interprocedural::{IpaType, LibrarySignatureDb};

impl LibrarySignatureDb {
    /// Add the mingw-w64 / libgcc runtime prototypes.
    #[allow(clippy::too_many_lines)]
    pub(crate) fn populate_mingw_runtime(&mut self) {
        // unwind.h:120
        self.add("_Unwind_Backtrace", IpaType::Struct("_Unwind_Reason_Code".to_string()), vec![IpaType::Struct("_Unwind_Trace_Fn".to_string()), IpaType::Pointer(Box::new(IpaType::Void))], false);
        // unwind.h:106
        self.add("_Unwind_DeleteException", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string())))], false);
        // unwind.h:183
        self.add("_Unwind_FindEnclosingFunction", IpaType::Pointer(Box::new(IpaType::Void)), vec![IpaType::Pointer(Box::new(IpaType::Struct("void pc".to_string())))], false);
        // unwind.h:102
        self.add("_Unwind_ForcedUnwind", IpaType::Struct("_Unwind_Reason_Code".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string()))), IpaType::Struct("_Unwind_Stop_Fn".to_string()), IpaType::Pointer(Box::new(IpaType::Void))], false);
        // unwind.h:179
        self.add("_Unwind_GetBSP", IpaType::Struct("_Unwind_Word".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string())))], false);
        // unwind.h:133
        self.add("_Unwind_GetCFA", IpaType::Struct("_Unwind_Word".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string())))], false);
        // unwind.h:180
        self.add("_Unwind_GetDataRelBase", IpaType::Struct("_Unwind_Ptr".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string())))], false);
        // unwind.h:125
        self.add("_Unwind_GetGR", IpaType::Struct("_Unwind_Word".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string()))), IpaType::SInt(32)], false);
        // unwind.h:128
        self.add("_Unwind_GetIP", IpaType::Struct("_Unwind_Ptr".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string())))], false);
        // unwind.h:129
        self.add("_Unwind_GetIPInfo", IpaType::Struct("_Unwind_Ptr".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string()))), IpaType::Pointer(Box::new(IpaType::SInt(32)))], false);
        // unwind.h:135
        self.add("_Unwind_GetLanguageSpecificData", IpaType::Pointer(Box::new(IpaType::Void)), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string())))], false);
        // unwind.h:137
        self.add("_Unwind_GetRegionStart", IpaType::Struct("_Unwind_Ptr".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string())))], false);
        // unwind.h:182
        self.add("_Unwind_GetTextRelBase", IpaType::Struct("_Unwind_Ptr".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string())))], false);
        // unwind.h:93
        self.add("_Unwind_RaiseException", IpaType::Struct("_Unwind_Reason_Code".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string())))], false);
        // unwind.h:109
        self.add("_Unwind_Resume", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string())))], false);
        // unwind.h:113
        self.add("_Unwind_Resume_or_Rethrow", IpaType::Struct("_Unwind_Reason_Code".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string())))], false);
        // unwind.h:126
        self.add("_Unwind_SetGR", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string()))), IpaType::SInt(32), IpaType::Struct("_Unwind_Word".to_string())], false);
        // unwind.h:130
        self.add("_Unwind_SetIP", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Context".to_string()))), IpaType::Struct("_Unwind_Ptr".to_string())], false);
        // unwind.h:154
        self.add("_Unwind_SjLj_ForcedUnwind", IpaType::Struct("_Unwind_Reason_Code".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string()))), IpaType::Struct("_Unwind_Stop_Fn".to_string()), IpaType::Pointer(Box::new(IpaType::Void))], false);
        // unwind.h:152
        self.add("_Unwind_SjLj_RaiseException", IpaType::Struct("_Unwind_Reason_Code".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string())))], false);
        // unwind.h:149
        self.add("_Unwind_SjLj_Register", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("SjLj_Function_Context".to_string())))], false);
        // unwind.h:156
        self.add("_Unwind_SjLj_Resume", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string())))], false);
        // unwind.h:158
        self.add("_Unwind_SjLj_Resume_or_Rethrow", IpaType::Struct("_Unwind_Reason_Code".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_Unwind_Exception".to_string())))], false);
        // unwind.h:150
        self.add("_Unwind_SjLj_Unregister", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("SjLj_Function_Context".to_string())))], false);
        // wchar.h:55
        self.add("__acrt_iob_func", IpaType::Pointer(Box::new(IpaType::Struct("FILE".to_string()))), vec![IpaType::UInt(32)], false);
        // math.h:160
        self.add("__mingw_raise_matherr", IpaType::Void, vec![IpaType::SInt(32), IpaType::Pointer(Box::new(IpaType::Struct("char name".to_string()))), IpaType::Float(64), IpaType::Float(64), IpaType::Float(64)], false);
        // assert.h:19
        self.add("_assert", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("char _Message".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("char _File".to_string()))), IpaType::UInt(32)], false);
        // locale.h:83
        self.add("_configthreadlocale", IpaType::SInt(32), vec![IpaType::SInt(32)], false);
        // math.h:278
        self.add("_matherr", IpaType::Struct("define _CRT_MATHERR_DEFINED int".to_string()), vec![IpaType::Pointer(Box::new(IpaType::Struct("_exception".to_string())))], false);
        // pthread.h:206
        self.add("_pthread_cleanup_dest", IpaType::Void, vec![IpaType::Struct("pthread_t".to_string())], false);
        // pthread.h:213
        self.add("_pthread_get_state", IpaType::UInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::UInt(32)], false);
        // pthread.h:210
        self.add("_pthread_invoke_cancel", IpaType::Void, vec![], false);
        // pthread.h:214
        self.add("_pthread_set_state", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::UInt(32), IpaType::UInt(32)], false);
        // pthread.h:353
        self.add("_pthread_tryjoin", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::Pointer(Box::new(IpaType::Pointer(Box::new(IpaType::Struct("void res".to_string())))))], false);
        // wchar.h:1203
        self.add("mbrtowc", IpaType::UInt(64), vec![IpaType::Pointer(Box::new(IpaType::Struct("wchar_t __".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("char __".to_string()))), IpaType::UInt(64), IpaType::Pointer(Box::new(IpaType::Struct("mbstate_t __".to_string())))], false);
        // pthread.h:306
        self.add("pthread_attr_destroy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string())))], false);
        // pthread.h:308
        self.add("pthread_attr_getdetachstate", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int flag".to_string())))], false);
        // pthread.h:310
        self.add("pthread_attr_getinheritsched", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int flag".to_string())))], false);
        // pthread.h:165
        self.add("pthread_attr_getschedparam", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("sched_param param".to_string())))], false);
        // pthread.h:169
        self.add("pthread_attr_getschedpolicy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int pol".to_string())))], false);
        // pthread.h:312
        self.add("pthread_attr_getscope", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int flag".to_string())))], false);
        // pthread.h:313
        self.add("pthread_attr_getstack", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Pointer(Box::new(IpaType::Struct("void stack".to_string()))))), IpaType::Pointer(Box::new(IpaType::Struct("size_t size".to_string())))], false);
        // pthread.h:315
        self.add("pthread_attr_getstackaddr", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Pointer(Box::new(IpaType::Struct("void stack".to_string())))))], false);
        // pthread.h:317
        self.add("pthread_attr_getstacksize", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("size_t size".to_string())))], false);
        // pthread.h:305
        self.add("pthread_attr_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string())))], false);
        // pthread.h:307
        self.add("pthread_attr_setdetachstate", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:309
        self.add("pthread_attr_setinheritsched", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:164
        self.add("pthread_attr_setschedparam", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("sched_param param".to_string())))], false);
        // pthread.h:168
        self.add("pthread_attr_setschedpolicy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:311
        self.add("pthread_attr_setscope", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:314
        self.add("pthread_attr_setstack", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("void stack".to_string()))), IpaType::UInt(64)], false);
        // pthread.h:316
        self.add("pthread_attr_setstackaddr", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("void stack".to_string())))], false);
        // pthread.h:318
        self.add("pthread_attr_setstacksize", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_attr_t attr".to_string()))), IpaType::UInt(64)], false);
        // pthread.h:211
        self.add("pthread_cancel", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string())], false);
        // pthread.h:255
        self.add("pthread_cond_broadcast", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string())))], false);
        // pthread.h:253
        self.add("pthread_cond_destroy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string())))], false);
        // pthread.h:252
        self.add("pthread_cond_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_condattr_t a".to_string())))], false);
        // pthread.h:254
        self.add("pthread_cond_signal", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string())))], false);
        // pthread.h:257
        self.add("pthread_cond_timedwait32", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t external_mutex".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec32 t".to_string())))], false);
        // pthread.h:267
        self.add("pthread_cond_timedwait32_relative_np", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t external_mutex".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec32 t".to_string())))], false);
        // pthread.h:258
        self.add("pthread_cond_timedwait64", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t external_mutex".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec64 t".to_string())))], false);
        // pthread.h:268
        self.add("pthread_cond_timedwait64_relative_np", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t external_mutex".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec64 t".to_string())))], false);
        // pthread.h:256
        self.add("pthread_cond_wait", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_cond_t cv".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t external_mutex".to_string())))], false);
        // pthread.h:333
        self.add("pthread_condattr_destroy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_condattr_t a".to_string())))], false);
        // pthread.h:338
        self.add("pthread_condattr_getclock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_condattr_t attr".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("clockid_t clock_id".to_string())))], false);
        // pthread.h:335
        self.add("pthread_condattr_getpshared", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_condattr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int s".to_string())))], false);
        // pthread.h:334
        self.add("pthread_condattr_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_condattr_t a".to_string())))], false);
        // pthread.h:340
        self.add("pthread_condattr_setclock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_condattr_t attr".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:336
        self.add("pthread_condattr_setpshared", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_condattr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:217
        self.add("pthread_create_wrapper", IpaType::UInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("void args".to_string())))], false);
        // pthread.h:87
        self.add("pthread_delay32_np", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("_timespec32 interval".to_string())))], false);
        // pthread.h:88
        self.add("pthread_delay64_np", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("_timespec64 interval".to_string())))], false);
        // pthread.h:220
        self.add("pthread_detach", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string())], false);
        // pthread.h:204
        self.add("pthread_equal", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::Struct("pthread_t".to_string())], false);
        // pthread.h:209
        self.add("pthread_exit", IpaType::Void, vec![IpaType::Pointer(Box::new(IpaType::Struct("void res".to_string())))], false);
        // pthread.h:207
        self.add("pthread_get_concurrency", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("int val".to_string())))], false);
        // pthread.h:349
        self.add("pthread_getclean", IpaType::Pointer(Box::new(IpaType::Pointer(Box::new(IpaType::Struct("_pthread_cleanup".to_string()))))), vec![], false);
        // pthread.h:330
        self.add("pthread_getconcurrency", IpaType::SInt(32), vec![], false);
        // pthread.h:351
        self.add("pthread_getevent", IpaType::Pointer(Box::new(IpaType::Void)), vec![], false);
        // pthread.h:350
        self.add("pthread_gethandle", IpaType::Pointer(Box::new(IpaType::Void)), vec![IpaType::Struct("pthread_t".to_string())], false);
        // pthread.h:222
        self.add("pthread_getname_np", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::Pointer(Box::new(IpaType::Struct("char name".to_string()))), IpaType::UInt(64)], false);
        // pthread.h:166
        self.add("pthread_getschedparam", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::Pointer(Box::new(IpaType::Struct("int pol".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("sched_param param".to_string())))], false);
        // pthread.h:198
        self.add("pthread_getspecific", IpaType::Pointer(Box::new(IpaType::Void)), vec![IpaType::Struct("pthread_key_t".to_string())], false);
        // pthread.h:219
        self.add("pthread_join", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::Pointer(Box::new(IpaType::Pointer(Box::new(IpaType::Struct("void res".to_string())))))], false);
        // pthread.h:197
        self.add("pthread_key_delete", IpaType::SInt(32), vec![IpaType::Struct("pthread_key_t".to_string())], false);
        // pthread.h:212
        self.add("pthread_kill", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::SInt(32)], false);
        // pthread.h:292
        self.add("pthread_mutex_destroy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t m".to_string())))], false);
        // pthread.h:291
        self.add("pthread_mutex_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t m".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string())))], false);
        // pthread.h:278
        self.add("pthread_mutex_lock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t m".to_string())))], false);
        // pthread.h:279
        self.add("pthread_mutex_timedlock32", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t m".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec32 ts".to_string())))], false);
        // pthread.h:280
        self.add("pthread_mutex_timedlock64", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t m".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec64 ts".to_string())))], false);
        // pthread.h:290
        self.add("pthread_mutex_trylock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t m".to_string())))], false);
        // pthread.h:289
        self.add("pthread_mutex_unlock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutex_t m".to_string())))], false);
        // pthread.h:321
        self.add("pthread_mutexattr_destroy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string())))], false);
        // pthread.h:328
        self.add("pthread_mutexattr_getprioceiling", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::SInt(32)))], false);
        // pthread.h:326
        self.add("pthread_mutexattr_getprotocol", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int type".to_string())))], false);
        // pthread.h:324
        self.add("pthread_mutexattr_getpshared", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int type".to_string())))], false);
        // pthread.h:322
        self.add("pthread_mutexattr_gettype", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int type".to_string())))], false);
        // pthread.h:320
        self.add("pthread_mutexattr_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string())))], false);
        // pthread.h:329
        self.add("pthread_mutexattr_setprioceiling", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:327
        self.add("pthread_mutexattr_setprotocol", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:325
        self.add("pthread_mutexattr_setpshared", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:323
        self.add("pthread_mutexattr_settype", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_mutexattr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:97
        self.add("pthread_num_processors_np", IpaType::SInt(32), vec![], false);
        // pthread.h:250
        self.add("pthread_rwlock_destroy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string())))], false);
        // pthread.h:224
        self.add("pthread_rwlock_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t rwlock_".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlockattr_t attr".to_string())))], false);
        // pthread.h:236
        self.add("pthread_rwlock_rdlock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string())))], false);
        // pthread.h:237
        self.add("pthread_rwlock_timedrdlock32", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec32 ts".to_string())))], false);
        // pthread.h:238
        self.add("pthread_rwlock_timedrdlock64", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec64 ts".to_string())))], false);
        // pthread.h:226
        self.add("pthread_rwlock_timedwrlock32", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t rwlock".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec32 ts".to_string())))], false);
        // pthread.h:227
        self.add("pthread_rwlock_timedwrlock64", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t rwlock".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("_timespec64 ts".to_string())))], false);
        // pthread.h:248
        self.add("pthread_rwlock_tryrdlock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string())))], false);
        // pthread.h:249
        self.add("pthread_rwlock_trywrlock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string())))], false);
        // pthread.h:247
        self.add("pthread_rwlock_unlock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string())))], false);
        // pthread.h:225
        self.add("pthread_rwlock_wrlock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlock_t l".to_string())))], false);
        // pthread.h:354
        self.add("pthread_rwlockattr_destroy", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlockattr_t a".to_string())))], false);
        // pthread.h:355
        self.add("pthread_rwlockattr_getpshared", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlockattr_t a".to_string()))), IpaType::Pointer(Box::new(IpaType::Struct("int s".to_string())))], false);
        // pthread.h:356
        self.add("pthread_rwlockattr_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlockattr_t a".to_string())))], false);
        // pthread.h:357
        self.add("pthread_rwlockattr_setpshared", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_rwlockattr_t a".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:201
        self.add("pthread_self", IpaType::Struct("pthread_t".to_string()), vec![], false);
        // pthread.h:208
        self.add("pthread_set_concurrency", IpaType::SInt(32), vec![IpaType::SInt(32)], false);
        // pthread.h:98
        self.add("pthread_set_num_processors_np", IpaType::SInt(32), vec![IpaType::SInt(32)], false);
        // pthread.h:215
        self.add("pthread_setcancelstate", IpaType::SInt(32), vec![IpaType::SInt(32), IpaType::Pointer(Box::new(IpaType::Struct("int oldstate".to_string())))], false);
        // pthread.h:216
        self.add("pthread_setcanceltype", IpaType::SInt(32), vec![IpaType::SInt(32), IpaType::Pointer(Box::new(IpaType::Struct("int oldtype".to_string())))], false);
        // pthread.h:331
        self.add("pthread_setconcurrency", IpaType::SInt(32), vec![IpaType::SInt(32)], false);
        // pthread.h:221
        self.add("pthread_setname_np", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::Pointer(Box::new(IpaType::Struct("char name".to_string())))], false);
        // pthread.h:167
        self.add("pthread_setschedparam", IpaType::SInt(32), vec![IpaType::Struct("pthread_t".to_string()), IpaType::SInt(32), IpaType::Pointer(Box::new(IpaType::Struct("sched_param param".to_string())))], false);
        // pthread.h:199
        self.add("pthread_setspecific", IpaType::SInt(32), vec![IpaType::Struct("pthread_key_t".to_string()), IpaType::Pointer(Box::new(IpaType::Struct("void value".to_string())))], false);
        // pthread.h:298
        self.add("pthread_spin_init", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_spinlock_t l".to_string()))), IpaType::SInt(32)], false);
        // pthread.h:301
        self.add("pthread_spin_lock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_spinlock_t l".to_string())))], false);
        // pthread.h:302
        self.add("pthread_spin_trylock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_spinlock_t l".to_string())))], false);
        // pthread.h:303
        self.add("pthread_spin_unlock", IpaType::SInt(32), vec![IpaType::Pointer(Box::new(IpaType::Struct("pthread_spinlock_t l".to_string())))], false);
        // pthread.h:203
        self.add("pthread_testcancel", IpaType::Void, vec![], false);
        // pthread.h:205
        self.add("pthread_tls_init", IpaType::Void, vec![], false);
        // sched.h:32
        self.add("sched_get_priority_max", IpaType::SInt(32), vec![IpaType::SInt(32)], false);
        // sched.h:31
        self.add("sched_get_priority_min", IpaType::SInt(32), vec![IpaType::SInt(32)], false);
        // sched.h:33
        self.add("sched_getscheduler", IpaType::SInt(32), vec![IpaType::Struct("pid_t".to_string())], false);
        // sched.h:34
        self.add("sched_setscheduler", IpaType::SInt(32), vec![IpaType::Struct("pid_t".to_string()), IpaType::SInt(32), IpaType::Pointer(Box::new(IpaType::Struct("sched_param param".to_string())))], false);
        // sched.h:28
        self.add("sched_yield", IpaType::SInt(32), vec![], false);
    }
}
