[package]
license.workspace = true
name = "rustre-symb-taint"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
rustre-core = { path = "../rustre-core" }
rustre-symb = { path = "../rustre-symb" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
petgraph = { workspace = true }

[lints]
workspace = true
