//! `memory_model` — **`SymExpr`-level** symbolic memory model.
//!
//! Provides [`SymbolicMemory`]: a memory abstraction that handles both
//! concrete-addressed and symbolic-addressed reads/writes, generates SMT
//! array-theory constraints for symbolic accesses, and supports multi-byte
//! word loads/stores with little-endian and big-endian byte ordering.
//!
//! # Relationship to [`symbolic_memory_model`](crate::symbolic_memory_model)
//!
//! These two modules are **not duplicates** — they operate at different levels
//! of abstraction:
//!
//! | Module | Abstraction level | Value type | Use case |
//! |--------|-------------------|------------|----------|
//! | **`memory_model`** (this file) | [`SymExpr`](crate::SymExpr) trees | `MemoryCell(SymExpr)` | SMT constraint generation; ITE-chain reads for symbolic addresses |
//! | [`symbolic_memory_model`](crate::symbolic_memory_model) | Byte-level with string names | `SymValue` (named symbolic bytes) | Segment tracking, alias analysis cache, write/read logs, `fork`/`merge` |

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{SymExpr, SymType};

// ─── Errors ───────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum MemoryModelError {
    #[error("address {addr:#x} out of mapped range")]
    UnmappedAddress { addr: u64 },
    #[error("symbolic address has no concrete fallback")]
    SymbolicAddressUnresolvable,
    #[error("invalid access size: {size} (must be 1, 2, 4, or 8)")]
    InvalidAccessSize { size: u8 },
    #[error("write to read-only segment at {addr:#x}")]
    WriteToReadOnly { addr: u64 },
    #[error("memory constraint generation error: {0}")]
    ConstraintError(String),
}

// ─── ByteOrder ────────────────────────────────────────────────────────────────

/// Byte order used for multi-byte loads and stores.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub enum ByteOrder {
    #[default]
    LittleEndian,
    BigEndian,
}

// ─── MemoryCell ───────────────────────────────────────────────────────────────

/// A single addressable byte in the symbolic memory model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MemoryCell {
    /// A known concrete byte value.
    Concrete(u8),
    /// A symbolic expression (must have width 8 for a byte cell).
    Symbolic(SymExpr),
    /// Uninitialized — reads produce a fresh symbolic variable.
    Uninit,
}

impl MemoryCell {
    /// Convert to a symbolic expression (width-8 bitvector).
    #[must_use]
    pub fn to_sym_expr(&self, addr: u64) -> SymExpr {
        match self {
            Self::Concrete(b) => SymExpr::bv(u64::from(*b), 8),
            Self::Symbolic(e) => e.clone(),
            Self::Uninit => SymExpr::Var {
                name: format!("mem_{addr:#x}"),
                ty: SymType::BitVec(8),
            },
        }
    }

    /// Return `true` if this cell holds a concrete byte.
    #[must_use]
    pub const fn is_concrete(&self) -> bool {
        matches!(self, Self::Concrete(_))
    }

    /// Return the concrete byte, if available.
    #[must_use]
    pub const fn as_concrete_byte(&self) -> Option<u8> {
        match self {
            Self::Concrete(b) => Some(*b),
            _ => None,
        }
    }
}

// ─── MemoryConstraint ─────────────────────────────────────────────────────────

/// A constraint generated by a symbolic memory access.
///
/// When reading from a symbolic address `addr_expr`, we assert that the
/// symbolic address *must* alias one of the concrete addresses that hold the
/// same value (or we express the disjunction symbolically).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryConstraint {
    /// The symbolic address expression that triggered this constraint.
    pub sym_addr: SymExpr,
    /// The value that was read/written.
    pub value: SymExpr,
    /// Whether this was a read (`true`) or write (`false`).
    pub is_read: bool,
    /// Access size in bytes.
    pub size: u8,
    /// Candidate concrete addresses that `sym_addr` could alias.
    pub candidate_addrs: Vec<u64>,
}

impl MemoryConstraint {
    /// Build the aliasing disjunction: `sym_addr == c1 OR sym_addr == c2 ...`
    #[must_use]
    pub fn aliasing_disjunction(&self) -> SymExpr {
        if self.candidate_addrs.is_empty() {
            return SymExpr::ConstBool(false);
        }
        self.candidate_addrs
            .iter()
            .map(|&c| {
                SymExpr::Eq(
                    Box::new(self.sym_addr.clone()),
                    Box::new(SymExpr::bv(c, 64)),
                )
            })
            .reduce(|acc, e| SymExpr::BoolOr(Box::new(acc), Box::new(e)))
            .unwrap_or(SymExpr::ConstBool(false))
    }

    /// Build an ITE chain that selects the correct value based on `sym_addr`.
    ///
    /// For a read, this yields:
    /// `ITE(addr==c1, val@c1, ITE(addr==c2, val@c2, ...))`
    #[must_use]
    pub fn ite_read_chain(
        &self,
        cells: &HashMap<u64, MemoryCell>,
        byte_order: ByteOrder,
    ) -> SymExpr {
        let default_val = SymExpr::Var {
            name: "mem_unknown".to_string(),
            ty: SymType::BitVec(u32::from(self.size) * 8),
        };
        // Assemble `self.size` consecutive cells at each candidate address.
        //
        // Each branch used to be a single BYTE cell while the default branch
        // was `size * 8` bits wide, so a multi-byte read of a symbolic address
        // came back 8 bits wide and the ITE's own branches disagreed with each
        // other. `SymbolicMemory::read_word_symbolic` — the concrete-address
        // twin of this operation — already assembles the bytes correctly; this
        // mirrors it, which is also why the byte order has to be passed in.
        let value_at = |base: u64| -> SymExpr {
            let bytes: Vec<SymExpr> = (0..u64::from(self.size))
                .map(|i| {
                    let a = base.wrapping_add(i);
                    cells.get(&a).map_or_else(
                        || SymExpr::Var {
                            name: format!("mem_{a:#x}"),
                            ty: SymType::BitVec(8),
                        },
                        |c| c.to_sym_expr(a),
                    )
                })
                .collect();
            let ordered: Box<dyn Iterator<Item = SymExpr>> = match byte_order {
                // byte[0] is least-significant, so it must end up innermost.
                ByteOrder::LittleEndian => Box::new(bytes.into_iter().rev()),
                ByteOrder::BigEndian => Box::new(bytes.into_iter()),
            };
            ordered
                .fold(None, |acc, byte| {
                    Some(match acc {
                        None => byte,
                        Some(higher) => SymExpr::Concat(Box::new(higher), Box::new(byte)),
                    })
                })
                .unwrap_or_else(|| SymExpr::bv(0, 8))
        };

        self.candidate_addrs
            .iter()
            .rev()
            .fold(default_val, |else_, &addr| {
                let then_ = value_at(addr);
                let cond = SymExpr::Eq(
                    Box::new(self.sym_addr.clone()),
                    Box::new(SymExpr::bv(addr, 64)),
                );
                SymExpr::Ite {
                    cond: Box::new(cond),
                    then_: Box::new(then_),
                    else_: Box::new(else_),
                }
            })
    }
}

// ─── MemoryRegion ─────────────────────────────────────────────────────────────

/// An optional descriptor for a mapped memory region.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryRegion {
    pub base: u64,
    pub size: u64,
    pub readable: bool,
    pub writable: bool,
    pub executable: bool,
    pub name: Option<String>,
}

impl MemoryRegion {
    #[must_use]
    pub const fn contains(&self, addr: u64) -> bool {
        addr >= self.base && addr < self.base.saturating_add(self.size)
    }

    #[must_use]
    pub fn new_rw(base: u64, size: u64, name: impl Into<String>) -> Self {
        Self {
            base,
            size,
            readable: true,
            writable: true,
            executable: false,
            name: Some(name.into()),
        }
    }

    #[must_use]
    pub fn new_rx(base: u64, size: u64, name: impl Into<String>) -> Self {
        Self {
            base,
            size,
            readable: true,
            writable: false,
            executable: true,
            name: Some(name.into()),
        }
    }

    #[must_use]
    pub fn new_ro(base: u64, size: u64, name: impl Into<String>) -> Self {
        Self {
            base,
            size,
            readable: true,
            writable: false,
            executable: false,
            name: Some(name.into()),
        }
    }
}

// ─── SymbolicMemory ───────────────────────────────────────────────────────────

/// The full symbolic memory model.
///
/// Maintains a flat byte map (`cells`), a list of known regions, and a
/// log of constraints generated by symbolic-address accesses.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SymbolicMemory {
    /// Byte-level cell map.
    pub cells: HashMap<u64, MemoryCell>,
    /// Memory regions (optional, used for permission checking).
    pub regions: Vec<MemoryRegion>,
    /// Constraints generated by symbolic-address accesses.
    pub constraints: Vec<MemoryConstraint>,
    /// Byte order used for multi-byte accesses.
    pub byte_order: ByteOrder,
    /// Sequence counter for naming fresh symbolic variables.
    var_counter: u64,
}

impl SymbolicMemory {
    // ── Constructors ────────────────────────────────────────────────────────

    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    #[must_use]
    pub fn with_byte_order(byte_order: ByteOrder) -> Self {
        Self {
            byte_order,
            ..Default::default()
        }
    }

    // ── Region management ───────────────────────────────────────────────────

    pub fn add_region(&mut self, region: MemoryRegion) {
        self.regions.push(region);
    }

    /// Return the region that contains `addr`, if any.
    #[must_use]
    pub fn region_at(&self, addr: u64) -> Option<&MemoryRegion> {
        self.regions.iter().find(|r| r.contains(addr))
    }

    /// Return `true` if `addr` is writable.
    #[must_use]
    pub fn is_writable(&self, addr: u64) -> bool {
        self.region_at(addr).is_none_or(|r| r.writable)
    }

    // ── Concrete byte read/write ─────────────────────────────────────────────

    /// Write a concrete byte at `addr`.
    pub fn write_byte(&mut self, addr: u64, val: u8) {
        self.cells.insert(addr, MemoryCell::Concrete(val));
    }

    /// Read a concrete byte from `addr`.
    ///
    /// Returns a fresh symbolic variable if the cell is uninitialized.
    #[must_use]
    pub fn read_byte(&self, addr: u64) -> SymExpr {
        self.cells.get(&addr).map_or_else(
            || SymExpr::Var {
                name: format!("mem_{addr:#x}"),
                ty: SymType::BitVec(8),
            },
            |c| c.to_sym_expr(addr),
        )
    }

    /// Write a `size`-byte concrete value at `addr` (little-endian by default).
    pub fn write_word_concrete(&mut self, addr: u64, val: u64, size: u8) {
        let bytes = val.to_le_bytes();
        let iter: Box<dyn Iterator<Item = (u64, u8)>> = match self.byte_order {
            ByteOrder::LittleEndian => Box::new(
                (0..u64::from(size))
                    .map(move |i| (addr + i, bytes[usize::try_from(i).unwrap_or(0)])),
            ),
            ByteOrder::BigEndian => Box::new((0..u64::from(size)).map(move |i| {
                let idx = size - 1 - u8::try_from(i).unwrap_or(0);
                (addr + i, bytes[usize::from(idx)])
            })),
        };
        for (a, b) in iter {
            self.cells.insert(a, MemoryCell::Concrete(b));
        }
    }

    /// Read a `size`-byte concrete value from `addr` (respecting byte order).
    ///
    /// Returns `None` if any byte is non-concrete.
    #[must_use]
    pub fn read_word_concrete(&self, addr: u64, size: u8) -> Option<u64> {
        let mut result = 0u64;
        for i in 0..u64::from(size) {
            let byte = u64::from(self.cells.get(&(addr + i))?.as_concrete_byte()?);
            match self.byte_order {
                ByteOrder::LittleEndian => result |= byte << (i * 8),
                ByteOrder::BigEndian => result = (result << 8) | byte,
            }
        }
        Some(result)
    }

    // ── Symbolic read ────────────────────────────────────────────────────────

    /// Read `size` bytes from a symbolic address `addr_expr`.
    ///
    /// If `addr_expr` evaluates concretely (is a `ConstBv`), perform a direct
    /// concrete read. Otherwise, build an ITE chain over all known addresses
    /// and record a [`MemoryConstraint`].
    ///
    /// Returns a symbolic expression of width `size * 8`.
    #[must_use]
    pub fn read_symbolic(&mut self, addr_expr: &SymExpr, size: u8) -> SymExpr {
        // Fast path: concrete address.
        if let Some(concrete_addr) = addr_expr.as_const_u64() {
            return self.read_word_symbolic(concrete_addr, size);
        }

        // Symbolic address: build an ITE chain over all known addresses.
        let candidates: Vec<u64> = self.cells.keys().copied().collect();
        let cells_snapshot = self.cells.clone();

        let mc = MemoryConstraint {
            sym_addr: addr_expr.clone(),
            value: SymExpr::Var {
                name: self.fresh_var("symread"),
                ty: SymType::BitVec(u32::from(size) * 8),
            },
            is_read: true,
            size,
            candidate_addrs: candidates,
        };
        let chain = mc.ite_read_chain(&cells_snapshot, self.byte_order);
        self.constraints.push(mc);
        chain
    }

    /// Write `value_expr` to a symbolic address `addr_expr`.
    ///
    /// If `addr_expr` is concrete, performs a direct write. Otherwise records
    /// a write constraint (the memory is havoc'ed at all candidate addresses).
    pub fn write_symbolic(&mut self, addr_expr: &SymExpr, value_expr: &SymExpr, size: u8) {
        if let Some(concrete_addr) = addr_expr.as_const_u64() {
            self.write_word_symbolic(concrete_addr, value_expr, size);
            return;
        }

        // Symbolic write: havoc all candidate addresses.
        let candidates: Vec<u64> = self.cells.keys().copied().collect();
        let fresh_name = self.fresh_var("symwrite_result");
        let mc = MemoryConstraint {
            sym_addr: addr_expr.clone(),
            value: value_expr.clone(),
            is_read: false,
            size,
            candidate_addrs: candidates.clone(),
        };
        self.constraints.push(mc);

        // Havoc: replace each candidate cell with an ITE that selects the
        // written value when the address matches.
        for &addr in &candidates {
            let old_val = self.cells.get(&addr).map_or_else(
                || SymExpr::Var {
                    name: format!("mem_{addr:#x}"),
                    ty: SymType::BitVec(8),
                },
                |c| c.to_sym_expr(addr),
            );
            let cond = SymExpr::Eq(Box::new(addr_expr.clone()), Box::new(SymExpr::bv(addr, 64)));
            let new_val = SymExpr::Ite {
                cond: Box::new(cond),
                then_: Box::new(value_expr.clone()),
                else_: Box::new(old_val),
            };
            self.cells.insert(addr, MemoryCell::Symbolic(new_val));
        }
        let _ = fresh_name; // suppress unused warning
    }

    // ── Multi-byte symbolic read/write (concrete address) ────────────────────

    /// Read `size` bytes from `addr` and return a symbolic expression of width
    /// `size * 8`.
    #[must_use]
    pub fn read_word_symbolic(&self, addr: u64, size: u8) -> SymExpr {
        let bytes: Vec<SymExpr> = (0..u64::from(size))
            .map(|i| self.read_byte(addr + i))
            .collect();

        match self.byte_order {
            ByteOrder::LittleEndian => {
                // byte[0] is least-significant.
                bytes
                    .into_iter()
                    .rev()
                    .fold(None, |acc, byte| {
                        Some(match acc {
                            None => byte,
                            Some(higher) => SymExpr::Concat(Box::new(higher), Box::new(byte)),
                        })
                    })
                    .unwrap_or(SymExpr::bv(0, 8))
            }
            ByteOrder::BigEndian => bytes
                .into_iter()
                .fold(None, |acc, byte| {
                    Some(match acc {
                        None => byte,
                        Some(higher) => SymExpr::Concat(Box::new(higher), Box::new(byte)),
                    })
                })
                .unwrap_or(SymExpr::bv(0, 8)),
        }
    }

    /// Write the symbolic expression `val` as `size` bytes at `addr`.
    ///
    /// The expression is decomposed into bytes via `Extract`.
    pub fn write_word_symbolic(&mut self, addr: u64, val: &SymExpr, size: u8) {
        for i in 0..u32::from(size) {
            let (hi, lo) = match self.byte_order {
                ByteOrder::LittleEndian => (i * 8 + 7, i * 8),
                ByteOrder::BigEndian => {
                    let j = u32::from(size) - 1 - i;
                    (j * 8 + 7, j * 8)
                }
            };
            let byte_expr = SymExpr::Extract {
                expr: Box::new(val.clone()),
                hi,
                lo,
            };
            self.cells
                .insert(addr + u64::from(i), MemoryCell::Symbolic(byte_expr));
        }
    }

    // ── Constraint generation ────────────────────────────────────────────────

    /// Return all accumulated memory constraints.
    #[must_use]
    pub fn memory_constraints(&self) -> &[MemoryConstraint] {
        &self.constraints
    }

    /// Build a conjunction of all aliasing disjunctions from symbolic accesses.
    #[must_use]
    pub fn aliasing_formula(&self) -> SymExpr {
        self.constraints
            .iter()
            .map(MemoryConstraint::aliasing_disjunction)
            .reduce(|acc, e| SymExpr::BoolAnd(Box::new(acc), Box::new(e)))
            .unwrap_or(SymExpr::ConstBool(true))
    }

    // ── Initialisation helpers ───────────────────────────────────────────────

    /// Write a byte slice starting at `base`.
    pub fn load_bytes(&mut self, base: u64, data: &[u8]) {
        for (i, &b) in data.iter().enumerate() {
            self.cells.insert(base.wrapping_add(i as u64), MemoryCell::Concrete(b));
        }
    }

    /// Mark a range of addresses as uninitialized.
    pub fn mark_uninit(&mut self, base: u64, len: usize) {
        for i in 0..len as u64 {
            self.cells.insert(base.wrapping_add(i), MemoryCell::Uninit);
        }
    }

    /// Return the number of mapped cells (concrete + symbolic).
    #[must_use]
    pub fn cell_count(&self) -> usize {
        self.cells.len()
    }

    // ── Internal helpers ─────────────────────────────────────────────────────

    fn fresh_var(&mut self, prefix: &str) -> String {
        let n = self.var_counter;
        self.var_counter += 1;
        format!("{prefix}_{n}")
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_write_read_byte_concrete() {
        let mut mem = SymbolicMemory::new();
        mem.write_byte(0x1000, 0xAB);
        let v = mem.read_byte(0x1000);
        assert_eq!(v.as_const_u64(), Some(0xAB));
    }

    #[test]
    fn test_read_uninit_returns_var() {
        let mem = SymbolicMemory::new();
        let v = mem.read_byte(0xDEAD);
        assert!(matches!(v, SymExpr::Var { .. }));
    }

    #[test]
    fn test_write_read_word_little_endian() {
        let mut mem = SymbolicMemory::with_byte_order(ByteOrder::LittleEndian);
        mem.write_word_concrete(0x2000, 0xDEADBEEF, 4);
        let v = mem.read_word_concrete(0x2000, 4).unwrap();
        assert_eq!(v, 0xDEADBEEF);
    }

    #[test]
    fn test_write_read_word_big_endian() {
        let mut mem = SymbolicMemory::with_byte_order(ByteOrder::BigEndian);
        mem.write_word_concrete(0x3000, 0x12345678, 4);
        let v = mem.read_word_concrete(0x3000, 4).unwrap();
        assert_eq!(v, 0x12345678);
    }

    #[test]
    fn test_load_bytes() {
        let mut mem = SymbolicMemory::new();
        mem.load_bytes(0x4000, &[0x01, 0x02, 0x03]);
        assert_eq!(mem.read_byte(0x4000).as_const_u64(), Some(1));
        assert_eq!(mem.read_byte(0x4001).as_const_u64(), Some(2));
        assert_eq!(mem.read_byte(0x4002).as_const_u64(), Some(3));
    }

    #[test]
    fn test_read_symbolic_concrete_addr() {
        let mut mem = SymbolicMemory::new();
        mem.write_byte(0x1000, 0xCC);
        let addr = SymExpr::bv(0x1000, 64);
        let v = mem.read_symbolic(&addr, 1);
        assert_eq!(v.as_const_u64(), Some(0xCC));
    }

    #[test]
    fn test_read_symbolic_symbolic_addr_produces_ite() {
        let mut mem = SymbolicMemory::new();
        mem.write_byte(0x1000, 0xAA);
        mem.write_byte(0x1001, 0xBB);
        let addr = SymExpr::var("ptr", SymType::BitVec(64));
        let v = mem.read_symbolic(&addr, 1);
        // Result should be an ITE chain.
        assert!(matches!(v, SymExpr::Ite { .. }));
        // A constraint should have been generated.
        assert_eq!(mem.constraints.len(), 1);
    }

    #[test]
    fn test_write_symbolic_concrete_addr() {
        let mut mem = SymbolicMemory::new();
        let addr = SymExpr::bv(0x2000, 64);
        mem.write_symbolic(&addr, &SymExpr::bv(0x42, 8), 1);
        // Should be stored as a symbolic extract expression.
        assert!(mem.cells.contains_key(&0x2000));
    }

    #[test]
    fn test_aliasing_formula_empty() {
        let mem = SymbolicMemory::new();
        assert_eq!(mem.aliasing_formula(), SymExpr::ConstBool(true));
    }

    #[test]
    fn test_memory_region_contains() {
        let region = MemoryRegion::new_rw(0x1000, 0x100, "stack");
        assert!(region.contains(0x1000));
        assert!(region.contains(0x10FF));
        assert!(!region.contains(0x1100));
    }

    #[test]
    fn test_is_writable_no_region() {
        let mem = SymbolicMemory::new();
        assert!(mem.is_writable(0xFFFF)); // no region → writable by default
    }

    #[test]
    fn test_is_writable_ro_region() {
        let mut mem = SymbolicMemory::new();
        mem.add_region(MemoryRegion::new_ro(0x5000, 0x1000, "rodata"));
        assert!(!mem.is_writable(0x5000));
        assert!(!mem.is_writable(0x5FFF));
    }

    #[test]
    fn test_mark_uninit() {
        let mut mem = SymbolicMemory::new();
        mem.mark_uninit(0x6000, 4);
        for i in 0..4u64 {
            assert!(matches!(
                mem.cells.get(&(0x6000 + i)),
                Some(MemoryCell::Uninit)
            ));
        }
    }

    #[test]
    fn test_memory_constraint_aliasing_disjunction_empty() {
        let mc = MemoryConstraint {
            sym_addr: SymExpr::var("p", SymType::Pointer),
            value: SymExpr::bv(0, 8),
            is_read: true,
            size: 1,
            candidate_addrs: Vec::new(),
        };
        assert_eq!(mc.aliasing_disjunction(), SymExpr::ConstBool(false));
    }

    #[test]
    fn test_memory_constraint_aliasing_disjunction_single() {
        let mc = MemoryConstraint {
            sym_addr: SymExpr::var("p", SymType::Pointer),
            value: SymExpr::bv(0, 8),
            is_read: true,
            size: 1,
            candidate_addrs: vec![0x1000],
        };
        let d = mc.aliasing_disjunction();
        assert!(matches!(d, SymExpr::Eq(_, _)));
    }

    #[test]
    fn test_cell_count() {
        let mut mem = SymbolicMemory::new();
        assert_eq!(mem.cell_count(), 0);
        mem.write_byte(0x100, 1);
        mem.write_byte(0x101, 2);
        assert_eq!(mem.cell_count(), 2);
    }

    #[test]
    fn test_read_word_symbolic_le() {
        let mut mem = SymbolicMemory::with_byte_order(ByteOrder::LittleEndian);
        // 0x1234 in little-endian: byte 0 = 0x34, byte 1 = 0x12
        mem.write_byte(0x1000, 0x34);
        mem.write_byte(0x1001, 0x12);
        let v = mem.read_word_symbolic(0x1000, 2);
        // Should be a Concat of two concrete bytes.
        assert!(matches!(v, SymExpr::Concat(_, _)));
    }

    #[test]
    fn test_write_word_symbolic_decomposes() {
        let mut mem = SymbolicMemory::new();
        let val = SymExpr::var("x", SymType::BitVec(16));
        mem.write_word_symbolic(0x2000, &val, 2);
        assert!(mem.cells.contains_key(&0x2000));
        assert!(mem.cells.contains_key(&0x2001));
    }

    #[test]
    fn test_memory_cell_concrete() {
        let c = MemoryCell::Concrete(0xFF);
        assert!(c.is_concrete());
        assert_eq!(c.as_concrete_byte(), Some(0xFF));
        assert_eq!(c.to_sym_expr(0).as_const_u64(), Some(0xFF));
    }

    #[test]
    fn test_memory_cell_uninit_returns_var() {
        let c = MemoryCell::Uninit;
        assert!(!c.is_concrete());
        assert!(c.as_concrete_byte().is_none());
        assert!(matches!(c.to_sym_expr(0x42), SymExpr::Var { .. }));
    }
}
